apiVersion: v1
kind: Service
metadata:
  name: redome-tarefa-svc
  namespace: develop
spec:
  type: NodePort
  selector:
    app: redome-tarefa
    namespace: develop
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redome-tarefa-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redome-tarefa
      namespace: develop
  template:
    metadata:
      labels:
        app: redome-tarefa
        namespace: develop
    spec:
       hostname: redome-tarefa
       subdomain: redome-tarefa-svc          
       containers:
       -  name: redome-tarefa
          image: us.icr.io/dev_modred/redome_tarefa:8-20200828154242
          env:
          -  name: profile
             value: dev
          resources:
            requests:
              cpu: "100m"
              memory: "768Mi"
            limits:
              memory: "1536Mi"
       imagePullSecrets:
       - name: ibmcloudregcred
       nodeSelector:
         name: worker02
             