SET MODE ORACLE;
--REM INSERTING into TIPO_AMOSTRA
--SET DEFINE OFF;
Insert into TIPO_AMOSTRA (TIAM_ID,TIAM_TX_DESCRICAO) values ('1','EDTA');
Insert into TIPO_AMOSTRA (TIAM_ID,TIAM_TX_DESCRICAO) values ('2','ACD');
Insert into TIPO_AMOSTRA (TIAM_ID,TIAM_TX_DESCRICAO) values ('3','Heparina');
Insert into TIPO_AMOSTRA (TIAM_ID,TIAM_TX_DESCRICAO) values ('4','Sem Anticoagolante');
Insert into TIPO_AMOSTRA (TIAM_ID,TIAM_TX_DESCRICAO) values ('5','Anti-HLA');
Insert into TIPO_AMOSTRA (TIAM_ID,TIAM_TX_DESCRICAO) values ('6','Outros');
commit;

--REM INSERTING into CONFIGURACAO
--SET DEFINE OFF;
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('quantidadeMaximaArquivosPrescricao','3',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('tamanhoArquivoPrescricaoEmByte','5242880',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('extensaoArquivoPrescricao','application/pdf,application/wps-office.pdf',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('tamanhoArquivoAutorizacaoPacienteEmByte','5242880',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('extensaoArquivoAutorizacaoPaciente','application/pdf',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('tamanhoArquivoPedidoWorkupEmByte','5242880',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('extensaoArquivoPedidoWorkup','application/pdf,application/wps-office.pdf',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('tamanhoArquivoResultadoWorkupEmByte','5242880',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('extensaoArquivoResultadoWorkup','application/pdf,application/wps-office.pdf',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('tamanhoArquivoPedidoLogisticaEmByte','5242880',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('extensaoArquivoPedidoLogistica','application/pdf,application/wps-office.pdf',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('tamanhoArquivoLaudoEmByte','5242880',null);
Insert into CONFIGURACAO (CONF_ID,CONF_TX_VALOR,CONF_TX_DESCRICAO) values ('extensaoArquivoLaudo','application/pdf,application/wps-office.pdf',null);

commit;

--REM INSERTING into FONTES_CELULAS
--SET DEFINE OFF;
Insert into FONTE_CELULAS (FOCE_ID,FOCE_TX_SIGLA,FOCE_TX_DESCRICAO) values ('1','MO','MEDULA OSSEA');
Insert into FONTE_CELULAS (FOCE_ID,FOCE_TX_SIGLA,FOCE_TX_DESCRICAO) values ('2','SP','SANGUE PERIFERICO');
Insert into FONTE_CELULAS (FOCE_ID,FOCE_TX_SIGLA,FOCE_TX_DESCRICAO) values ('3','DLI','LINFOCITOS');
Insert into FONTE_CELULAS (FOCE_ID,FOCE_TX_SIGLA,FOCE_TX_DESCRICAO) values ('4','CO','CORDAO UMBILICAL');

COMMIT;

--REM INSERTING into STATUS_PEDIDO_LOGISTICA
--SET DEFINE OFF;
INSERT INTO STATUS_PEDIDO_LOGISTICA (STPL_ID, STPL_TX_DESCRICAO) VALUES ('1', 'ABERTO');
INSERT INTO STATUS_PEDIDO_LOGISTICA (STPL_ID, STPL_TX_DESCRICAO) VALUES ('2', 'FECHADO');
INSERT INTO STATUS_PEDIDO_LOGISTICA (STPL_ID, STPL_TX_DESCRICAO) VALUES ('4', 'CANCELADO');

COMMIT;

--REM INSERTING into TIPO_PEDIDO_LOGISTICA
--SET DEFINE OFF;
INSERT INTO TIPO_PEDIDO_LOGISTICA (TIPL_ID, TIPL_TX_DESCRICAO) VALUES ('1', 'DOADOR_WORKUP');
INSERT INTO TIPO_PEDIDO_LOGISTICA (TIPL_ID, TIPL_TX_DESCRICAO) VALUES ('2', 'DOADOR_COLETA');
INSERT INTO TIPO_PEDIDO_LOGISTICA (TIPL_ID, TIPL_TX_DESCRICAO) VALUES ('3', 'MATERIAL_NACIONAL');
INSERT INTO TIPO_PEDIDO_LOGISTICA (TIPL_ID, TIPL_TX_DESCRICAO) VALUES ('4', 'MATERIAL_INTERNACIONAL');

COMMIT;

Insert into USUARIO (USUA_ID,USUA_TX_NOME,USUA_TX_USERNAME,USUA_TX_PASSWORD,USUA_IN_ATIVO,TRAN_ID,LABO_ID,USUA_TX_EMAIL) 
values (9,'ANALISTA_WORKUP','ANALISTA_WORKUP','$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.',1,null,null,'medico_centro_coleta@mail.com');

Insert into USUARIO (USUA_ID,USUA_TX_NOME,USUA_TX_USERNAME,USUA_TX_PASSWORD,USUA_IN_ATIVO,TRAN_ID,LABO_ID,USUA_TX_EMAIL) 
values (12,'ANALISTA_LOGISTICA','ANALISTA_LOGISTICA','$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.',1,null,null,'medico_transplantador@mail.com');

Insert into USUARIO (USUA_ID,USUA_TX_NOME,USUA_TX_USERNAME,USUA_TX_PASSWORD,USUA_IN_ATIVO,TRAN_ID,LABO_ID,USUA_TX_EMAIL) 
values (13,'MEDICO_REDOME','MEDICO_REDOME','$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.',1,null,null,'medico_centro_coleta@mail.com');

Insert into USUARIO (USUA_ID,USUA_TX_NOME,USUA_TX_USERNAME,USUA_TX_PASSWORD,USUA_IN_ATIVO,TRAN_ID,LABO_ID,USUA_TX_EMAIL) 
values (15,'MEDICO_TRANSPLANTADOR','MEDICO_TRANSPLANTADOR','$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.',1,null,null,'medico_transplantador@mail.com');

Insert into USUARIO (USUA_ID,USUA_TX_NOME,USUA_TX_USERNAME,USUA_TX_PASSWORD,USUA_IN_ATIVO,TRAN_ID,LABO_ID,USUA_TX_EMAIL) 
values (20,'ANALISTA_WORKUP_INTERNACIONAL','ANALISTA_WORKUP_INTERNACIONAL','$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.',1,null,null,'analista_workup_internacional@mail.com');

Insert into USUARIO (USUA_ID,USUA_TX_NOME,USUA_TX_USERNAME,USUA_TX_PASSWORD,USUA_IN_ATIVO,TRAN_ID,LABO_ID,USUA_TX_EMAIL) 
values (32,'MEDICO_CENTRO_COLETA','MEDICO_CENTRO_COLETA','$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.',1,null,null,'medico_centro_coleta@mail.com');

COMMIT;