package br.org.cancer.redome.workup.model.domain;

public class Recursos {
	
	public final static String CADASTRAR_PRESCRICAO = "CADASTRAR_PRESCRICAO";
	public final static String AVALIAR_PRESCRICAO = "AVALIAR_PRESCRICAO";	
	public final static String DISTRIBUIR_WORKUP = "DISTRIBUIR_WORKUP";
	public final static String DISTRIBUIR_WORKUP_INTERNACIONAL = "DISTRIBUIR_WORKUP_INTERNACIONAL";
	public final static String TRATAR_PEDIDO_WORKUP = "TRATAR_PEDIDO_WORKUP";
	public final static String CONSULTAR_PEDIDO_WORKUP_NACIONAL = "CONSULTAR_PEDIDO_WORKUP_NACIONAL";
	public final static String TRATAR_PEDIDO_WORKUP_INTERNACIONAL = "TRATAR_PEDIDO_WORKUP_INTERNACIONAL";
	public final static String TRATAR_PEDIDO_WORKUP_CENTRO_COLETA = "TRATAR_PEDIDO_WORKUP_CENTRO_COLETA";
	public final static String INFORMAR_PLANO_WORKUP_NACIONAL = "INFORMAR_PLANO_WORKUP_NACIONAL";
	public final static String INFORMAR_PLANO_WORKUP_INTERNACIONAL = "INFORMAR_PLANO_WORKUP_INTERNACIONAL";
    public final static String APROVAR_PLANO_WORKUP = "APROVAR_PLANO_WORKUP";
    public final static String CADASTRAR_RESULTADO_WORKUP_INTERNACIONAL = "CADASTRAR_RESULTADO_WORKUP_INTERNACIONAL";
    public final static String CADASTRAR_RESULTADO_WORKUP_NACIONAL = "CADASTRAR_RESULTADO_WORKUP_NACIONAL";
    public final static String EFETUAR_LOGISTICA = "EFETUAR_LOGISTICA";
    public final static String SOLICITAR_LOGISTICA_MATERIAL = "SOLICITAR_LOGISTICA_MATERIAL";
    public final static String CADASTRAR_FORMULARIO = "CADASTRAR_FORMULARIO";
    public final static String CONSULTAR_FORMULARIO = "CONSULTAR_FORMULARIO";
    public final static String AVALIAR_RESULTADO_WORKUP_INTERNACIONAL = "AVALIAR_RESULTADO_WORKUP_INTERNACIONAL";
    public final static String AVALIAR_RESULTADO_WORKUP_NACIONAL = "AVALIAR_RESULTADO_WORKUP_NACIONAL";
    public final static String AUTORIZACAO_PACIENTE = "AUTORIZACAO_PACIENTE";
    public final static String CADASTRAR_PEDIDO_ADICIONAL_WORKUP_NACIONAL = "CADASTRAR_PEDIDO_ADICIONAL_WORKUP_NACIONAL";
    public final static String CADASTRAR_PEDIDO_ADICIONAL_WORKUP_INTERNACIONAL = "CADASTRAR_PEDIDO_ADICIONAL_WORKUP_INTERNACIONAL";
    public final static String FINALIZAR_RESULTADO_WORKUP_NACIONAL = "FINALIZAR_RESULTADO_WORKUP_NACIONAL";
    public final static String CADASTRAR_ARQUIVO_PEDIDO_ADICIONAL_WORKUP = "CADASTRAR_ARQUIVO_PEDIDO_ADICIONAL_WORKUP";
    public final static String FINALIZAR_PEDIDO_ADICIONAL_WORKUP = "FINALIZAR_PEDIDO_ADICIONAL_WORKUP";
    public final static String CONSULTAR_PEDIDO_ADICIONAL_WORKUP = "CONSULTAR_PEDIDO_ADICIONAL_WORKUP";
    public final static String AVALIAR_PEDIDO_COLETA = "AVALIAR_PEDIDO_COLETA";
    public final static String CONSULTAR_PEDIDO_COLETA = "CONSULTAR_PEDIDO_COLETA";
    public final static String AGENDAR_PEDIDO_COLETA = "AGENDAR_PEDIDO_COLETA";
	public static final String EFETUAR_LOGISTICA_INTERNACIONAL = "EFETUAR_LOGISTICA_INTERNACIONAL";
	public static final String TRATAR_RECEBIMENTO_COLETA = "TRATAR_RECEBIMENTO_COLETA";
	public static final String AGENDAR_TRANSPORTE_MATERIAL = "AGENDAR_TRANSPORTE_MATERIAL";
	public static final String TRATAR_CONTAGEM_CELULA = "TRATAR_CONTAGEM_CELULA";
	
    public final static String EFETUAR_LOGISTICA_DOADOR_COLETA = "EFETUAR_LOGISTICA_DOADOR_COLETA";
    public final static String FINALIZAR_FORMULARIO_POSCOLETA = "FINALIZAR_FORMULARIO_POSCOLETA";
    
    


}
