server:
  port: 9080
  servlet:
    context-path: /redome
  use-forward-headers: true
resourceId: modred_rest_api
spring:
  mvc:    
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      enabled: true

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh


jpa:
  driver: oracle.jdbc.driver.OracleDriver
  
c3p0:
  initial_pool_size: 5
  min_pool_size: 5
  max_pool_size: 20
  max_idle_time: 1800
hibernate:
  dialect: org.hibernate.dialect.Oracle12cDialect
storage:
  api_key: o93BXIZkOHScnMFcvhLSYBH4xwo80C4RCo6uFyuGjgBv
  service_instance_id: "crn:v1:bluemix:public:cloud-object-storage:global:a/d97c2f72526b4d00bacd785b76777ca2:66ed8cd4-172b-4045-91c2-8fea84f9342e::" 
  endpoint_url: https://s3.sao01.objectstorage.softlayer.net
  IAM_ENDPOINT: https://iam.cloud.ibm.com/identity/token

logging:
  level:
    root: INFO
  file:  
    ize: 5MB
    max-history: 20
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'

