version: "3"
services:
    redome:
        build:
            context: ./redome
            dockerfile: ./.devcontainer/Dockerfile
        ports:
            - "9080:9080"
        volumes:
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"