version: "3"
services:
  discovery:
    build:
      context: ./redome-discovery
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - "9082:9082"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"