version: '3'
services:
    app:
        build:
            context: ./redome-front
            dockerfile: ./.devcontainer/Dockerfile
        #command: npm run dev:watch
        # environment:
        #     NODE_ENV: development
        ports:
            - 4200:4200
        # volumes:
        #     - .:/home/app/library
        #     - /home/app/library/node_modules