version: "3"
services:
    workup:
        build:
            context: ./redome-workup
            dockerfile: ./.devcontainer/Dockerfile
        ports:
            - "9004:9004"
        volumes:
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"