version: "3"
services:
  cloud:
    build:
      context: ./redome-cloud
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - "9081:9081"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"