DELETE FROM MODRED.METODOLOGIA;
INSERT INTO MODRED.METODOLOGIA (METO_ID, METO_TX_SIGLA, METO_TX_DESCRICAO) VALUES ( 1, 'SSP', 'Sequence Specific Primers');
INSERT INTO MODRED.METODOLOGIA (METO_ID, METO_TX_SIGLA, METO_TX_DESCRICAO) VALUES ( 2, 'SSO', 'Sequence Specific Oligonucleotide');
INSERT INTO MODRED.METODOLOGIA (METO_ID, METO_TX_SIGLA, METO_TX_DESCRICAO) VALUES ( 3, 'SBT', 'Sequence Based typing');
INSERT INTO MODRED.METODOLOGIA (METO_ID, METO_TX_SIGLA, METO_TX_DESCRICAO) VALUES ( 4, 'NGS', 'Next Generation Sequencing');
COMMIT;

--Atualização
UPDATE MODRED.METODOLOGIA SET  METO_TX_SIGLA = 'SSP', METO_TX_DESCRICAO = 'Sequence Specific Primers' WHERE METO_ID = 1;
UPDATE MODRED.METODOLOGIA SET  METO_TX_SIGLA = 'SSO', METO_TX_DESCRICAO = 'Sequence Specific Oligonucleotide' WHERE METO_ID = 2;
UPDATE MODRED.METODOLOGIA SET  METO_TX_SIGLA = 'SBT', METO_TX_DESCRICAO = 'Sequence Based typing' WHERE METO_ID = 3;
UPDATE MODRED.METODOLOGIA SET  METO_TX_SIGLA = 'NGS', METO_TX_DESCRICAO = 'Next Generation Sequencing' WHERE METO_ID = 4;
COMMIT;