insert into MODRED.motivo (MOTI_ID,MOTI_TX_DESCRICAO) VALUES (3,'ACOMPANHAMENTO TRIMESTRAL');
insert into MODRED.motivo (MOTI_ID,MOTI_TX_DESCRICAO) VALUES (4,'MUDANÇA DE TRATAMENTO');
insert into MODRED.motivo (MOTI_ID,MOTI_TX_DESCRICAO) VALUES (5,'ALTERAÇÃO DO ESTADO DO PACIENTE');
COMMIT;
