apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: redome-discovery-dev1
build:
  artifacts:
  - image: us.icr.io/dev_modred/redome_discovery
    docker:
      dockerfile: local-Dockerfile
deploy:
  kubectl:
    manifests:
    - local1-deployment.yml
portForward:
  - resourceType: service
    resourceName: redome-discovery-svc1
    port: 9082
    localPort: 9082
