apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: redome-discovery
build:
  artifacts:
  - image: localhost:32000/redome_discovery
    docker:
      dockerfile: local-Dockerfile
deploy:
  kubectl:
    manifests:
    - local-deployment.yml
portForward:
  - resourceType: service
    resourceName: redome-discovery-svc
    port: 9082
    localPort: 9082
