package br.org.cancer.redome.tarefa.helper.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Enum de perfis do sistema.
 * 
 * @author Cintia Oliveira
 *
 */
@AllArgsConstructor
public enum Perfis {
	MEDICO(1L),
	MEDICO_AVALIADOR(2L),
	AVALIADOR_EXAME_HLA(3L),
	ANALISTA_BUSCA(5L),
	ENRIQUECEDOR(6L),
	ANALISTA_CONTATO_FASE2(7L),
	ANALISTA_CONTATO_FASE3(8L),
	ANALISTA_WORKUP(9L),
	ANALISTA_TM_OFFICE(10L),
	CADASTRADOR_RESULTADO_WORKUP(11L),
	ANALISTA_LOGISTICA(12L),
	MEDICO_REDOME(13L),
	CADASTRADOR_RECEBIMENTO_COLETA(14L),
	MEDICO_TRANSPLANTADOR(15L),
	CONTROLADOR_LISTA(16L),
	TRANSPORTADORA(17L), 
	LABORATORIO(18L),
	ADMIN(19L),
	ANALISTA_WORKUP_INTERNACIONAL(20L),
	WEBSERVICE(21L), 
	ANALISTA_LOGISTICA_INTERNACIONAL(22L),
	AVALIADOR_CAMARA_TECNICA(24L),
	AVALIADOR_NOVA_BUSCA(25L),
	CONTATO_SMS(27L),
	TODOS(0L),
	CENTRO_COLETA(29L),
	DISTRIBUIDOR_WORKUP_NACIONAL(30L),
	DISTRIBUIDOR_WORKUP_INTERNACIONAL(31L),
	MEDICO_CENTRO_COLETA(32L);

	@Getter
	private Long id;


}