export const PacienteConstantes = {
  VALIDATOR_DATA : 'validDate',
  VALIDATOR_LOCALIZADO: 'validLocalizado',
  INDIGENA_ID : "5",
  RACA_INDIGENA_COM_ETNIAS : 'INDÍGENA',
  PAIS_BRASIL : 'BRASIL',
  BRASIL_ID: 1,
  MOTIVO_CADASTRO_INICIAL: 1,
  ETAPA_IDENTIFICACAO: 1,
  ETAPA_DADOS_PESSOAIS: 2,
  ETAPA_CONTATO: 3,
  ETAPA_DIAGNOSTICO: 4,
  ETAPA_EVOLUCAO: 5,
  ETAPA_EXAME: 6,
  ETAPA_AVALIACAO: 7,
  USUARIO_LOGADO_FAKE : 1,
  STATUS_TAREFA_FEITA: "FEITA"

};
