version: '3'
services:
    app:
        build: .
        command: npm run dev:watch
        ports:
            - 4200:4200
        volumes:
            - nodemodulos:/src/node_modules

volumes:
    nodemodulos: {}

