SET MODE ORACLE;


Insert into PAIS (PAIS_ID,PAIS_TX_NOME,PAIS_TX_CD_NACIONAL_REDOMEWEB) values (1, 'BRASIL', '10');

Insert into UF (UF_SIGLA,UF_TX_NOME) values ('RJ','RIO DE JANEIRO');

INSERT INTO "MUNICIPIO" (MUNI_ID, UF_SIGLA, MUNI_TX_NOME, MUNI_TX_CODIGO_IBGE, MUNI_TX_CODIGO_DNE)
values (1703,'RJ', 'RIO DE JANEIRO', '3304557', '00007043');

COMMIT;

--REM INSERTING into STATUS_PEDIDO_TRANSPORTE
--SET DEFINE OFF;
Insert into STATUS_PEDIDO_TRANSPORTE (STPT_ID,STPT_TX_DESCRICAO) values ('1','EM ANÁLISE');
Insert into STATUS_PEDIDO_TRANSPORTE (STPT_ID,STPT_TX_DESCRICAO) values ('2','AGUARDANDO DOCUMENTAÇÃO');
Insert into STATUS_PEDIDO_TRANSPORTE (STPT_ID,STPT_TX_DESCRICAO) values ('3','AGUARDANDO CONFIRMAÇÃO');
Insert into STATUS_PEDIDO_TRANSPORTE (STPT_ID,STPT_TX_DESCRICAO) values ('4','AGUARDANDO RETIRADA');
Insert into STATUS_PEDIDO_TRANSPORTE (STPT_ID,STPT_TX_DESCRICAO) values ('5','AGUARDANDO ENTREGA');
Insert into STATUS_PEDIDO_TRANSPORTE (STPT_ID,STPT_TX_DESCRICAO) values ('6','ENTREGUE');
commit;

