apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: redome-workup
build:
  artifacts:
  - image: localhost:32000/redome-workup
    docker:
      dockerfile: local-Dockerfile
deploy:
  kubectl:
    manifests:
    - local-deployment.yml
portForward:
  - resourceType: service
    resourceName: redome-workup-svc
    port: 9004
    localPort: 9004
