GRANT SELECT ON MODRED.STATUS_INVOICE TO RMODRED_READ;
GRANT SELECT ON MODRED.SQ_STIN_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.TIPO_PEDIDO_ITEM_INVOICE TO RMODRED_READ;
GRANT SELECT ON MODRED.SQ_TIPI_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.INVOICE TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.INVOICE TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_INVO_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.ITEM_INVOICE TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.ITEM_INVOICE TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_ITIN_ID TO RMODRED_WRITE;