create or replace procedure proc_criar_qual_match_pre (busca_id in NUMBER, idDoador in NUMBER, fase in VARCHAR2, com_mismatch in BOOLEAN)


IS
matchId NUMBER;


begin

    matchId:=SQ_MAPR_ID.nextval;
    INSERT INTO MODRED.MATCH_PRELIMINAR(MAPR_ID,DOAD_ID,BUPR_ID,MAPR_IN_FASE) 
                values ( matchId, idDoador, busca_id,  fase);

    COMMIT;

    if (fase = '1') then
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'A', 'A', 1, idDoador, '01:01', 5); 
        if(com_mismatch) then
            INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'A', 'M', 2, idDoador, '01:01:01', 5); 
        else
            INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'A', 'P', 2, idDoador, '01:01:01:01', 5); 
        end if;

        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'B', 'L', 1, idDoador, '38:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'B', 'P', 2, idDoador, '18:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'DRB1', 'A', 1, idDoador, '01:01', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'DRB1', 'L', 2, idDoador, '01:01:01', 5); 
        update match_preliminar set MAPR_IN_FASE = 'F1' where MAPR_ID = matchId;
    elsif (fase = '2' OR fase = '3' or fase='D') then
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'A', 'A', 1, idDoador, '01:01:01:02N', 5); 
        if(com_mismatch) then
            INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'A', 'M', 2, idDoador, '01:01:01:03', 5); 
        else
            INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'A', 'P', 2, idDoador, '01:01:01:04', 5); 
        end if;

        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'B', 'L', 1, idDoador, '35:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'B', 'P', 2, idDoador, '46:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'DRB1', 'A', 1, idDoador, '01:01:01G', 3); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'DRB1', 'L', 2, idDoador, '01:01:02', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'C', 'A', 1, idDoador, '01:02', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'C', 'L', 2, idDoador, '01:02:01', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'DRB3', 'A', 1, idDoador, '01:02', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH_PRELIMINAR (QUMP_ID, MAPR_ID, LOCU_ID, QUMP_TX_QUALIFICACAO, QUMP_NR_POSICAO, DOAD_ID, QUMP_TX_GENOTIPO, QUMP_NR_TIPO) VALUES (modred.SQ_QUMP_ID.NEXTVAL, matchId, 'DRB3', 'L', 2, idDoador, '01:01:02:02', 5); 
        if(fase = '2') then
            update match_preliminar set MAPR_IN_FASE = 'F2' where MAPR_ID = matchId;
        else 
            if(fase = '3') then
                update match_preliminar set MAPR_IN_FASE = 'F3' where MAPR_ID = matchId;
            else 
                update match_preliminar set MAPR_IN_FASE = 'D' where MAPR_ID = matchId;
            end if;
        end if;
    end if;
    commit;
end;