CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_AMOSTRA FOR MODRED.TIPO_AMOSTRA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_AMOSTRA_PRESCRICAO FOR MODRED.TIPO_AMOSTRA_PRESCRICAO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_TIAP_ID FOR MODRED.SQ_TIAP_ID;


CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_TRANSPLANTE_EVOLUCAO FOR MODRED.TIPO_TRANSPLANTE_EVOLUCAO;

--#######################################################################################################
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PESQUISA_WMDA FOR MODRED.PESQUISA_WMDA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PESQUISA_WMDA_DOADOR FOR MODRED.PESQUISA_WMDA_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.REGISTRO_ASSOCIADO FOR MODRED.REGISTRO_ASSOCIADO;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PEWM_ID FOR MODRED.SQ_PEWM_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PEWD_ID FOR MODRED.SQ_PEWD_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_REAS_ID FOR MODRED.SQ_REAS_ID;

--#######################################################################################################
--####################3 SPRINT 63 

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.FASE_WORKUP FOR MODRED.FASE_WORKUP;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.MOTIVO_CANCELAMENTO_WORKUP FOR MODRED.MOTIVO_CANCELAMENTO_WORKUP;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_DNA_NMDP FOR MODRED.VALOR_DNA_NMDP;

