CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ITEM_INVOICE FOR MODRED.ITEM_INVOICE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ITIN_ID FOR MODRED.SQ_ITIN_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.INVOICE FOR MODRED.INVOICE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_INVO_ID FOR MODRED.SQ_INVO_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_PEDIDO_ITEM_INVOICE FOR MODRED.TIPO_PEDIDO_ITEM_INVOICE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_TIPI_ID FOR MODRED.SQ_TIPI_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_INVOICE FOR MODRED.STATUS_INVOICE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_STIN_ID FOR MODRED.SQ_STIN_ID;