apiVersion: v1
kind: Service
metadata:
  name: redome-notificacao-svc
  namespace: develop
spec:
  type: NodePort
  selector:
    app: redome-notificacao
    namespace: develop
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redome-notificacao-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redome-notificacao
      namespace: develop
  template:
    metadata:
      labels:
        app: redome-notificacao
        namespace: develop
    spec:
       hostname: redome-notificacao
       subdomain: redome-notificacao-svc          
       containers:
       -  name: redome-notificacao
          image: localhost:32000/redome_notificacao:latest
          env:
          -  name: profile
             value: dev
      