package br.org.cancer.modred.model.domain;

public enum FasesWorkup {
	
	AGUARDANDO_AVALIACAO_PRESCRICAO(1L),
	AGUARDANDO_DISTRIBUICAO_WORKUP(2L),
	AGUARDANDO_FORMULARIO_DOADOR(3L),
	AGUARDANDO_DEFINIR_CENTRO(4L),
	AGUARDANDO_PLANO_WORKUP(5L),
	AGUARDANDO_ACEITE_PLANO(6L),
	AGUARDANDO_AGENDAMENTO_COLETA(7L),
	AGUARDANDO_AVALIACAO_RESULTADO_WORKUP(8L),
	AGUARDANDO_RESULTADO_WORKUP(9L),
	AGUARDANDO_LOGISTICA_DOADOR_WORKUP(10L),
	AGUARDANDO_AUTORIZACAO_PACIENTE(11L),
	AGUARDANDO_AVALIACAO_PEDIDO_COLETA(12L),
	AGUARDANDO_EXAME_ADICIONAL_DOADOR(13L),
	AGUARDANDO_DEFINICAO_LOGISTICA(14L),
	AGUARDANDO_LOGISTICA_COLETA_INTERNACIONAL(15L),
	AGUARDANDO_RECEBIMENTO_COLETA(16L),
	AGUARDANDO_ANALISE_PEDIDO_TRANSPORTE(17L),
	AGUARDANDO_DOCUMENTACAO_PEDIDO_TRANSPORTE_AEREO(18L),
	AGUARDANDO_RETIRADA_MATERIAL(19L);
	
	private Long id;
	
	private FasesWorkup(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}
	
	

}
