apiVersion: v1
kind: Service
metadata:
  name: redome-auth-svc
  namespace: develop
spec:
  type: NodePort
  selector:
    app: redome-auth
    namespace: develop
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redome-auth-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redome-auth
      namespace: develop
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 0                                         
  template:
    metadata:
      labels:
        app: redome-auth
        namespace: develop
    spec:
       hostname: redome-auth
       subdomain: redome-auth-svc          
       containers:
       - name: redome-auth
         image: us.icr.io/dev_modred/redome_auth:8-20200828152043
         env:
         -  name: profile
            value: dev
         resources:
           requests:
             cpu: "100m"
             memory: "768Mi"
           limits:
             memory: "1536Mi"
       imagePullSecrets:
       - name: ibmcloudregcred
       nodeSelector:
         name: worker01
         