GRANT SELECT ON MODRED.DISTRIBUICAO_WORKUP TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.DISTRIBUICAO_WORKUP TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_DIWO_ID TO RMODRED_READ;

GRANT SELECT ON MODRED.DISTRIBUICAO_WORKUP_AUD TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.DISTRIBUICAO_WORKUP_AUD TO RMODRED_WRITE;

GRANT SELECT ON MODRED.ARQUIVO_PEDIDO_WORKUP TO RMODRED_READ;
GRANT INSERT, UPDATE,DELETE ON MODRED.ARQUIVO_PEDIDO_WORKUP TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_ARPW_ID TO RMODRED_READ;


--############################### Sprint 67 #######################################

GRANT SELECT ON MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP TO RMODRED_READ;
GRANT INSERT, UPDATE,DELETE ON MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_APAW_ID TO RMODRED_READ;

//###########################  SPRINT 72 - 5503 ################################

GRANT SELECT ON MODRED.FORMULARIO_POSCOLETA TO RMODRED_READ;
GRANT INSERT, UPDATE,DELETE ON MODRED.FORMULARIO_POSCOLETA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_FOPO_ID TO RMODRED_READ;

--#################################################################################

--################ SPRINT 72 # MODRED-5532 ####################
GRANT SELECT ON MODRED.CONTAGEM_CELULA TO RMODRED_READ;
GRANT INSERT, UPDATE,DELETE ON MODRED.CONTAGEM_CELULA TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_COCE_ID TO RMODRED_READ;
