ALTER TABLE "MODRED"."PRESCRICAO" ADD COLUMNS(
        "PRES_IN_TIPO" NUMBER,
    "PRES_DT_INFUSAO_CORDAO" DATE,
	"PRES_DT_RECEBER_CORDAO_1" DATE, 
	"PRES_DT_RECEBER_CORDAO_2" DATE, 
	"PRES_DT_RECEBER_CORDAO_3" DATE, 
	"PRES_TX_CONTATO_RECEBER" VARCHAR2(30 BYTE), 
	"PRES_IN_ARMAZENA_CORDAO" NUMBER,
	"PRES_TX_CONTATO_URGENTE" VARCHAR2(30),
	"PRES_NR_COD_AREA_URGENTE" NUMBER(2,0), 
	"PRES_NR_TELEFONE_URGENTE" NUMBER(*,0),
        "PRES_IN_FAZER_COLETA" NUMBER);

   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_IN_TIPO"             IS 'Tipo de Prescrição: 0 - Prescrição Medula ou 1 - Prescrição Cordão.';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_DT_INFUSAO_CORDAO"   IS 'Data prevista para infusão do cordão';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_DT_RECEBER_CORDAO_1" IS 'Data 1 desejada para receber o cordão';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_DT_RECEBER_CORDAO_2" IS 'Data 2 desejada para receber o cordão';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_DT_RECEBER_CORDAO_2" IS 'Data 3 desejada para receber o cordão';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_TX_CONTATO_RECEBER"  IS 'Nome do contato para recebimento do material';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_IN_ARMAZENA_CORDAO"  IS 'Informa se centro pode ou não armazenar o cordão';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_TX_CONTATO_URGENTE"  IS 'Nome do contato em caso de urgência.';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_NR_COD_AREA_URGENTE" IS 'Código de área do telefone de urgencia';
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_NR_TELEFONE_URGENTE" IS 'Número do telefone de urgência';	
   COMMENT ON COLUMN "MODRED"."PRESCRICAO"."PRES_IN_FAZER_COLETA"     IS 'Informa se o centro deseja fazer a coleta.';
   
ALTER TABLE "MODRED"."PRESCRICAO" MODIFY(
        "PRES_DT_COLETA_1" DATE NULL ENABLE, 
	"PRES_DT_COLETA_2" DATE NULL ENABLE, 
	"FOCE_ID_OPCAO_1" NUMBER(2,0) NULL ENABLE, 
	"PRES_VL_QUANT_TOTAL_OPCAO_1" NUMBER(6,2) NULL ENABLE, 
	"PRES_VL_QUANT_KG_OPCAO_1" NUMBER(6,2) NULL ENABLE);   
	
ALTER TABLE "MODRED"."PRESCRICAO" MODIFY(
        "PRES_DT_COLETA_1" DATE NULL, 
	"PRES_DT_COLETA_2" DATE NULL, 
	"FOCE_ID_OPCAO_1" NUMBER(2,0) NULL, 
	"PRES_VL_QUANT_TOTAL_OPCAO_1" NUMBER(6,2) NULL, 
	"PRES_VL_QUANT_KG_OPCAO_1" NUMBER(6,2) NULL);  

ALTER TABLE "MODRED"."PRESCRICAO" 
DROP CONSTRAINT FK_PRES_AVPR;

DROP INDEX "MODRED".IN_FK_PRES_AVPR";

ALTER TABLE "MODRED"."PRESCRICAO" 
DROP COLUMN AVPR_ID;




	
DELETE FROM TIPO_SOLICITACAO WHERE TISO_ID IN (3,4);
ALTER TABLE TIPO_SOLICITACAO MODIFY(TISO_TX_DESCRICAO VARCHAR2(50));
INSERT INTO TIPO_SOLICITACAO VALUES (8,'WORKUP DOADOR NACIONAL - PACIENTE NACIONAL');
INSERT INTO TIPO_SOLICITACAO VALUES (9,'WORKUP DOADOR INTERNACIONAL');
INSERT INTO TIPO_SOLICITACAO VALUES (10,'CORDÃO NACIONAL - PACIENTE NACIONAL');
INSERT INTO TIPO_SOLICITACAO VALUES (11,'CORDÃO INTERNACIONAL');
COMMIT;
	


CREATE TABLE MODRED.DISTRIBUICAO_WORKUP 
(
  DIWO_ID NUMBER NOT NULL 
, DIWO_DT_CRIACAO TIMESTAMP NOT NULL 
, DIWO_DT_ATUALIZACAO TIMESTAMP NOT NULL 
, DIWO_IN_TIPO NUMBER NOT NULL 
, USUA_ID_DISTRIBUIU NUMBER 
, USUA_ID_RECEBEU NUMBER 
, SOLI_ID NUMBER NOT NULL 
, CONSTRAINT PK_DIWO PRIMARY KEY 
  (
    DIWO_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MODRED.PK_DIWO_ID ON MODRED.DISTRIBUICAO_WORKUP (DIWO_ID ASC) 
  )
  ENABLE 
);

CREATE INDEX MODRED.IN_FK_DIWO_SOLI ON MODRED.DISTRIBUICAO_WORKUP (SOLI_ID ASC);

CREATE INDEX MODRED.IN_FK_DIWO_USUA_DISTRIBUIU ON MODRED.DISTRIBUICAO_WORKUP (USUA_ID_DISTRIBUIU ASC);

CREATE INDEX MODRED.IN_FK_DIWO_USUA_RECEBEU ON MODRED.DISTRIBUICAO_WORKUP (USUA_ID_RECEBEU ASC);

ALTER TABLE MODRED.DISTRIBUICAO_WORKUP
ADD CONSTRAINT FK_DIWO_SOLI FOREIGN KEY
(
  SOLI_ID 
)
REFERENCES MODRED.SOLICITACAO
(
  SOLI_ID 
)
ENABLE;

ALTER TABLE MODRED.DISTRIBUICAO_WORKUP
ADD CONSTRAINT FK_DIWO_USUA_DISTRIBUIU FOREIGN KEY
(
  USUA_ID_DISTRIBUIU 
)
REFERENCES MODRED.USUARIO
(
  USUA_ID 
)
ENABLE;

ALTER TABLE MODRED.DISTRIBUICAO_WORKUP
ADD CONSTRAINT FK_DIWO_USUA_RECEBEU FOREIGN KEY
(
  USUA_ID_RECEBEU 
)
REFERENCES MODRED.USUARIO
(
  USUA_ID 
)
ENABLE;

COMMENT ON TABLE MODRED.DISTRIBUICAO_WORKUP IS 'Tabela  de distribuição do workup.';
COMMENT ON COLUMN MODRED.DISTRIBUICAO_WORKUP.DIWO_ID IS 'Identificador único da tabela';
COMMENT ON COLUMN MODRED.DISTRIBUICAO_WORKUP.DIWO_DT_CRIACAO IS 'Data de criação.';
COMMENT ON COLUMN MODRED.DISTRIBUICAO_WORKUP.DIWO_DT_ATUALIZACAO IS 'Data de atualizaçlão.';
COMMENT ON COLUMN MODRED.DISTRIBUICAO_WORKUP.DIWO_IN_TIPO IS 'Tipo da distribuição. 0 - Nacional e 1 - Internacional.';
COMMENT ON COLUMN MODRED.DISTRIBUICAO_WORKUP.USUA_ID_DISTRIBUIU IS 'Identificador do usuário que fez a distribuição.';
COMMENT ON COLUMN MODRED.DISTRIBUICAO_WORKUP.USUA_ID_RECEBEU IS 'Identificador do usuário escolhido para receber o pedido de workup.';
COMMENT ON COLUMN MODRED.DISTRIBUICAO_WORKUP.SOLI_ID IS 'Identificador da solicitação';

CREATE SEQUENCE  "MODRED"."SQ_DIWO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 ORDER;


CREATE TABLE MODRED.DISTRIBUICAO_WORKUP_AUD 
(
  DIWO_ID NUMBER NOT NULL
, AUDI_ID NUMBER NOT NULL
, AUDI_TX_TIPO NUMBER NOT NULL
, DIWO_DT_CRIACAO TIMESTAMP NOT NULL 
, DIWO_DT_ATUALIZACAO TIMESTAMP NOT NULL 
, DIWO_IN_TIPO NUMBER NOT NULL 
, USUA_ID_DISTRIBUIU NUMBER 
, USUA_ID_RECEBEU NUMBER 
, SOLI_ID NUMBER NOT NULL 
, CONSTRAINT PK_DWAU PRIMARY KEY 
  (
    DIWO_ID, AUDI_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MODRED.PK_DWAU_ID ON MODRED.DISTRIBUICAO_WORKUP_AUD (DIWO_ID ASC, AUDI_ID ASC) 
  )
  ENABLE 
);

ALTER TABLE MODRED.DISTRIBUICAO_WORKUP_AUD
ADD CONSTRAINT FK_DWAU_AUDI FOREIGN KEY
(
  AUDI_ID 
)
REFERENCES MODRED.AUDITORIA
(
  AUDI_ID 
)
ENABLE;



INSERT INTO MODRED.PERFIL (PERF_ID, PERF_TX_DESCRICAO, SIST_ID) VALUES (30, 'DISTRIBUIDOR_WORKUP_NACIONAL', 1);
INSERT INTO MODRED.PERFIL (PERF_ID, PERF_TX_DESCRICAO, SIST_ID) VALUES (31, 'DISTRIBUIDOR_WORKUP_INTERNACIONAL', 1);
COMMIT;

INSERT INTO TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR)
VALUES (110, 'DISTRIBUIR_WORKUP_NACIONAL', 0, NULL, 0);
INSERT INTO TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR)
VALUES (111, 'DISTRIBUIR_WORKUP_INTERNACIONAL', 0, NULL, 0);
COMMIT;

INSERT INTO MODRED.CATEGORIA_NOTIFICACAO (CANO_ID, CANO_TX_DESCRICAO) VALUES (14, 'Prescrição Internacional');
COMMIT;

UPDATE MODRED.CATEGORIA_NOTIFICACAO SET CANO_TX_DESCRICAO = 'Prescrição Nacional'
WHERE CANO_ID = 3;
COMMIT;


insert into modred.recurso (recu_id, recu_tx_sigla, recu_tx_descricao)
values (218, 'CANCELAR_WORKUP', 'Permite cancelar a solicitação de workup');

insert into modred.permissao (recu_id, perf_id, perm_in_com_restricao) 
values (218, 13, 0);
commit;


INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (219, 'DISTRIBUIR_WORKUP', 'Permite fazer a distribuição das tarefas de workup nacional entre os analistas.');
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (220, 'DISTRIBUIR_WORKUP_INTERNACIONAL', 'Permite fazer a distribuição das tarefas de workup internacional entre os analistas.');
COMMIT;


INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)
VALUES (219, 9, 0);
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)
VALUES (220, 20, 0);
COMMIT;


ALTER TABLE PRESCRICAO 
ADD (PRES_DT_CRIACAO TIMESTAMP );

COMMENT ON COLUMN PRESCRICAO.PRES_DT_CRIACAO IS 'Data de criação do registro.';


MERGE INTO MODRED.PRESCRICAO P
USING MODRED.SOLICITACAO S
ON (P.SOLI_ID = S.SOLI_ID)
WHEN MATCHED THEN UPDATE SET P.PRES_DT_CRIACAO = S.SOLI_DT_CRIACAO;

COMMIT;

ALTER TABLE PRESCRICAO  
MODIFY (PRES_DT_CRIACAO NOT NULL);


INSERT INTO TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR)
VALUES (112, 'CADASTRAR_FORMULARIO_DOADOR', 0, 0, 0);
COMMIT;


INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR)
VALUES (113, 'WORKUP', 0, 0, 1);
COMMIT;


DROP INDEX MODRED.IN_FK_MOCW_PEWO;

DROP INDEX MODRED.IN_FK_STPW_PEWO;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP CONSTRAINT FK_MOCW_PEWO;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP CONSTRAINT FK_STPW_PEWO;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN STPW_ID;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN MOCW_ID;

ALTER TABLE MODRED.PEDIDO_WORKUP 
ADD (PEWO_IN_STATUS NUMBER );

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_IN_STATUS IS 'Status do pedido de workup.';

/* ########################################################################################################*/
INSERT INTO "MODRED"."PERFIL" VALUES (32,'MEDICO_CENTRO_COLETA',1);
COMMIT;
/* ########################################################################################################*/

###################### SPRINT 64 ##################################

INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO)
VALUES (224, 'INFORMAR_PLANO_WORKUP_NACIONAL', 'Permite ao usuario do centro de coleta informar o plano de workup');
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)
VALUES (224, 32, 0);
COMMIT;

INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR)
VALUES (117, 'CONFIRMAR_PLANO_WORKUP', 0, 0, 0);
COMMIT;


ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP CONSTRAINT FK_PEWO_FOCE;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP CONSTRAINT FK_PEWO_USUA;

DROP INDEX MODRED.IN_FK_PEWO_FOCE;

DROP INDEX MODRED.IN_FK_PEWO_USUA;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_DT_LIMITE_WORKUP;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_NR_TENTATIVAS_AGENDAMENTO;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_NR_TIPO_UTILIZADO;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_DT_ULTIMO_STATUS;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN USUA_ID;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_IN_LOGISTICA_DOADOR;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_DT_DISPONIBILIDADE_DOADOR;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_DT_INICIO_WORKUP;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_DT_FINAL_WORKUP;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN PEWO_DT_LIBERACAO_DOADOR;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN FOCE_ID;


ALTER TABLE MODRED.PEDIDO_WORKUP 
ADD (PEWO_DT_EXAME DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP 
ADD (PEWO_DT_RESULTADO DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP 
ADD (PEWO_DT_INTERNACACAO DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP 
ADD (PEWO_DT_CRIACAO_PLANO DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP 
ADD (PEWO_IN_TIPO NUMBER );

ALTER TABLE MODRED.PEDIDO_WORKUP 
ADD (PEWO_TX_OBSERVACAO CLOB );

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_EXAME IS 'Data do exame informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_RESULTADO IS 'Data do resultado informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_INTERNACACAO IS 'Data da internacao informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_CRIACAO_PLANO IS 'Data da criaçao do plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_IN_TIPO IS 'Tipo de workup 0 - nacional e 1 internacional';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_TX_OBSERVACAO IS 'Campo livre de observaçao que podera ser informado no plano de workup.';


UPDATE MODRED.PEDIDO_WORKUP SET pewo_in_tipo = 0;
COMMIT;

ALTER TABLE MODRED.PEDIDO_WORKUP  
MODIFY (PEWO_IN_TIPO NOT NULL);


ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_DT_LIMITE_WORKUP;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_NR_TENTATIVAS_AGENDAMENTO;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_NR_TIPO_UTILIZADO;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_DT_ULTIMO_STATUS;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN USUA_ID;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_IN_LOGISTICA_DOADOR;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_DT_DISPONIBILIDADE_DOADOR;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_DT_INICIO_WORKUP;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_DT_FINAL_WORKUP;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN PEWO_DT_LIBERACAO_DOADOR;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN FOCE_ID;


ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
ADD (PEWO_DT_EXAME DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
ADD (PEWO_DT_RESULTADO DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
ADD (PEWO_DT_INTERNACACAO DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
ADD (PEWO_DT_CRIACAO_PLANO DATE );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
ADD (PEWO_IN_TIPO NUMBER );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
ADD (PEWO_TX_OBSERVACAO CLOB );

--##############################################################################################################################

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_DT_CONDICIONAMENTO DATE );
ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_DT_INFUSAO DATE );
ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_IN_CRIOPRESERVACAO NUMBER );
ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_TX_OBS_APROVA_PLANO CLOB );
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_CONDICIONAMENTO IS 'Data de condicionamento do paciente no plano de workup.';
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_INFUSAO IS 'Data planejada de infusão do plano de workup.';
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_IN_CRIOPRESERVACAO IS 'Criopreservação do produto - não 0 e sim 1.';
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_TX_OBS_APROVA_PLANO IS 'Campo livre de observaçao que podera ser informado aprovação do plano de workup.';


ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_DT_CONDICIONAMENTO DATE );
ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_DT_INFUSAO DATE );
ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_IN_CRIOPRESERVACAO NUMBER );
ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_TX_OBS_APROVA_PLANO CLOB );
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_DT_CONDICIONAMENTO IS 'Data de condicionamento do paciente no plano de workup.';
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_DT_INFUSAO IS 'Data planejada de infusão do plano de workup.';
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_IN_CRIOPRESERVACAO IS 'Criopreservação do produto - não 0 e sim 1.';
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_TX_OBS_APROVA_PLANO IS 'Campo livre de observaçao que podera ser informado aprovação do plano de workup.';


ALTER TABLE MODRED.PRESCRICAO ADD (CETR_ID NUMBER );
ALTER TABLE MODRED.PRESCRICAO ADD CONSTRAINT FK_PRES_CETR FOREIGN KEY (CETR_ID)
REFERENCES MODRED.CENTRO_TRANSPLANTE(CETR_ID) ENABLE;
COMMENT ON COLUMN MODRED.PRESCRICAO.CETR_ID IS 'Centro de transplante responsável pelo workup do doador. ';


ALTER TABLE MODRED.PEDIDO_WORKUP ADD (CETR_ID_COLETA NUMBER );
ALTER TABLE MODRED.PEDIDO_WORKUP RENAME COLUMN CETR_ID TO CETR_ID_TRANSP;
ALTER TABLE MODRED.PEDIDO_WORKUP ADD CONSTRAINT FK_PEWO_CETR_COLETA FOREIGN KEY (CETR_ID_COLETA) 
REFERENCES MODRED.CENTRO_TRANSPLANTE(CETR_ID) ENABLE;

ALTER TABLE MODRED.PEDIDO_WORKUP RENAME CONSTRAINT FK_PEWO_CETR TO FK_PEWO_CETR_TRANSP;
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.CETR_ID_COLETA IS 'Centro de coleta responsável pela coleta no workup do doador.';

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (CETR_ID_COLETA NUMBER(19) );
ALTER TABLE MODRED.PEDIDO_WORKUP_AUD RENAME COLUMN CETR_ID TO CETR_ID_TRANSP;
COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.CETR_ID_COLETA IS 'Centro de coleta responsável pela coleta no workup do doador.';

--##############################################################################################################################

--################################################################

INSERT INTO MODRED.TIPO_TAREFA VALUES (116,'WORKUP_CENTRO',0,0,1);
COMMIT;

INSERT INTO MODRED.RECURSO VALUES (223, 'TRATAR_PEDIDO_WORKUP_CENTRO_COLETA', 'PERMITE VISUALIZAR A LISTAGEM DE TRABALHO PARA O PERFIL CENTRO DE COLETA');
COMMIT;

INSERT INTO MODRED.PERMISSAO VALUES (223,32,0);
INSERT INTO MODRED.PERMISSAO VALUES (219,32,0);
COMMIT;

--################################################################

--##################################################################################

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR) VALUES (119, 'INFORMAR_DETALHE_WORKUP_NACIONAL', 0, 0, 0);
INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR) VALUES (220, 'INFORMAR_RESULTADO_WORKUP_INTERNACIONAL', 0, 0, 0);
COMMIT; 

INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (226, 'APROVAR_PLANO_WORKUP', 'Permite ao centro de transplante aprovar o plano de workup');
COMMIT;

--##################################################################################

INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO, TARE_IN_SOMENTE_AGRUPADOR)
VALUES (118, 'INFORMAR_PLANO_WORKUP_INTERNACIONAL', 0, 0, 0);

UPDATE MODRED.TIPO_TAREFA SET tita_tx_descricao = 'INFORMAR_PLANO_WORKUP_NACIONAL'
WHERE TITA_ID = 115;
COMMIT;

INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO)
VALUES (225, 'INFORMAR_PLANO_WORKUP_INTERNACIONAL', 'Permite ao analista de workup internacional informar o plano de workup');

INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)
VALUES (225, 20, 0);
COMMIT;

INSERT INTO MODRED.CONFIGURACAO (CONF_ID, CONF_TX_VALOR, CONF_TX_DESCRICAO)
VALUES ('extensaoArquivoPedidoWorkup', 'application/pdf', null);

INSERT INTO MODRED.CONFIGURACAO (CONF_ID, CONF_TX_VALOR, CONF_TX_DESCRICAO)
VALUES ('tamanhoArquivoPedidoWorkupEmByte', '5242880', null);
COMMIT;


CREATE TABLE MODRED.ARQUIVO_PEDIDO_WORKUP 
(
  ARPW_ID NUMBER NOT NULL 
, ARPW_TX_CAMINHO VARCHAR2(255) NOT NULL 
, PEWO_ID NUMBER NOT NULL 
);

COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_WORKUP.ARPW_ID IS 'Identificador unico da tabela.';
COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_WORKUP.ARPW_TX_CAMINHO IS 'Nome do arquivo.';
COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_WORKUP.PEWO_ID IS 'Referencia para a tabela de pedido de workup.';
COMMENT ON TABLE MODRED.ARQUIVO_PEDIDO_WORKUP IS 'Arquivos do pedido de workup.';

CREATE INDEX MODRED.IN_FK_ARPW_PEWO ON ARQUIVO_PEDIDO_WORKUP (PEWO_ID ASC);

ALTER TABLE MODRED.ARQUIVO_PEDIDO_WORKUP
ADD CONSTRAINT PK_ARPW PRIMARY KEY 
(
  ARPW_ID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX MODRED.IN_PK_ARPW ON ARQUIVO_PEDIDO_WORKUP (ARPW_ID ASC) 
)
 ENABLE;

ALTER TABLE MODRED.ARQUIVO_PEDIDO_WORKUP
ADD CONSTRAINT FK_ARPW_PEWO FOREIGN KEY
(
  PEWO_ID 
)
REFERENCES MODRED.PEDIDO_WORKUP
(
  PEWO_ID 
)
ENABLE;

CREATE SEQUENCE  "MODRED"."SQ_ARPW_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 ORDER;


--################################### SPRINT 65 ####################################################
DROP TABLE MODRED.ARQUIVO_RESULTADO_WORKUP_AUD;

ALTER TABLE ARQUIVO_RESULTADO_WORKUP 
DROP COLUMN ARRW_IN_EXCLUIDO;

DROP TABLE MODRED.RESULTADO_WORKUP_AUD;

ALTER TABLE RESULTADO_WORKUP 
DROP COLUMN REWO_DT_ATUALIZACAO;

ALTER TABLE RESULTADO_WORKUP 
DROP COLUMN REWO_IN_COLETA_INVIAVEL;

ALTER TABLE RESULTADO_WORKUP 
DROP COLUMN REWO_TX_MOTIVO_INVIABILIDADE;

INSERT INTO MODRED.FASE_WORKUP (FAWO_ID, FAWO_TX_SIGLA)
VALUES (8, 'AGUARDANDO_AVALIACAO_RESULTADO_WORKUP');
COMMIT;

--################################### SPRINT 65 ####################################################

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_DT_EXAME_MEDICO_1 TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_DT_EXAME_MEDICO_2 TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_DT_REPETICAO_BTHCG TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_TX_SETOR_ANDAR VARCHAR2(30) );

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_TX_NOME_PROCURAR VARCHAR2(50) );

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_IN_DOADOR_JEJUM NUMBER );

ALTER TABLE MODRED.PEDIDO_WORKUP ADD (PEWO_HR_JEJUM TIMESTAMP );

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_EXAME_MEDICO_1 IS 'Data do exame medico 1 informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_EXAME_MEDICO_2 IS 'Data do exame medico 2 informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_DT_REPETICAO_BTHCG IS 'Data de repetição BTHCG informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_TX_SETOR_ANDAR IS 'Nome setor e andar informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_TX_NOME_PROCURAR IS 'Nome procurar por informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_IN_DOADOR_JEJUM IS 'Flag doador em jejum informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_HR_JEJUM IS 'Jejum de quantas horas informada no plano de workup.';





ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_DT_EXAME_MEDICO_1 TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_DT_EXAME_MEDICO_2 TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_DT_REPETICAO_BTHCG TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_TX_SETOR_ANDAR VARCHAR2(30) );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_TX_NOME_PROCURAR VARCHAR2(50) );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_IN_DOADOR_JEJUM NUMBER );

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_HR_JEJUM TIMESTAMP );

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_DT_EXAME_MEDICO_1 IS 'Data do exame medico 1 informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_DT_EXAME_MEDICO_2 IS 'Data do exame medico 2 informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_DT_REPETICAO_BTHCG IS 'Data de repetição BTHCG informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_TX_SETOR_ANDAR IS 'Nome setor e andar informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_TX_NOME_PROCURAR IS 'Nome procurar por informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_IN_DOADOR_JEJUM IS 'Flag doador em jejum informada no plano de workup.';

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP_AUD.PEWO_HR_JEJUM IS 'Jejum de quantas horas informada no plano de workup.';

--#########################################################################################################

UPDATE FASE_WORKUP SET FAWO_TX_SIGLA = 'AGUARDANDO_RESULTADO_WORKUP'
WHERE FAWO_ID = 9;
COMMIT;

INSERT INTO PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)
VALUES (223, 15, 0);
COMMIT;


ALTER TABLE PEDIDO_LOGISTICA 
DROP CONSTRAINT FK_PELO_TIPL;

DROP INDEX IN_FK_PELO_TIPL;

ALTER TABLE PEDIDO_LOGISTICA RENAME COLUMN TIPL_ID TO PELO_IN_TIPO;

ALTER TABLE PEDIDO_LOGISTICA  
MODIFY (PELO_IN_TIPO NUMBER(*, 0) );

COMMENT ON COLUMN PEDIDO_LOGISTICA.PELO_IN_TIPO IS 'Tipo de pedido de logistica. 1 - DOADOR_WORKUP, 2 DOADOR_COLETA 3 MATERIAL.';
ALTER TABLE PEDIDO_LOGISTICA 
DROP CONSTRAINT FK_PELO_TIPL;

DROP INDEX IN_FK_PELO_TIPL;

ALTER TABLE PEDIDO_LOGISTICA RENAME COLUMN TIPL_ID TO PELO_IN_TIPO;

ALTER TABLE PEDIDO_LOGISTICA  
MODIFY (PELO_IN_TIPO NUMBER(*, 0) );

COMMENT ON COLUMN PEDIDO_LOGISTICA.PELO_IN_TIPO IS 'Tipo de pedido de logistica. 1 - DOADOR_WORKUP, 2 DOADOR_COLETA 3 MATERIAL.';


ALTER TABLE PEDIDO_LOGISTICA_AUD RENAME COLUMN TIPL_ID TO PELO_IN_TIPO;

ALTER TABLE PEDIDO_LOGISTICA_AUD  
MODIFY (PELO_IN_TIPO NUMBER(*, 0) );


UPDATE MODRED.TIPO_TAREFA SET TITA_TX_DESCRICAO = 'INFORMAR_RESULTADO_WORKUP_NACIONAL'
WHERE TITA_ID = 35;
COMMIT;


ALTER TABLE MODRED.RESULTADO_WORKUP 
ADD (REWO_IN_TIPO NUMBER );

COMMENT ON COLUMN RESULTADO_WORKUP.REWO_IN_TIPO IS 'Tipo resultado: 0 - Nacional ou 1 - Internacional.';

UPDATE MODRED.RESULTADO_WORKUP SET rewo_in_tipo = 1;
COMMIT;

ALTER TABLE RESULTADO_WORKUP  
MODIFY (REWO_IN_TIPO NOT NULL);

--############################### SPRINT 66 ##################################

UPDATE MODRED.RECURSO SET RECU_TX_SIGLA = 'AVALIAR_RESULTADO_WORKUP_INTERNACIONAL',
RECU_TX_DESCRICAO = 'Permite avaliar os resultados de exame de workup internacional'
WHERE RECU_ID = 50;
COMMIT;

INSERT INTO TIPO_TAREFA 
SELECT 223, 'INFORMAR_AUTORIZACAO_PACIENTE', 0, 0, 0 FROM DUAL;
COMMIT;

UPDATE MODRED.TIPO_TAREFA SET TITA_TX_DESCRICAO = 'AGENDAR_COLETA_INTERNACIONAL'
WHERE TITA_ID = 72;
COMMIT;

insert into fase_workup (fawo_id, fawo_tx_sigla)
values (11, 'AGUARDANDO_AUTORIZACAO_PACIENTE');
commit;

--#################################################################################
ALTER TABLE MODRED.RESULTADO_WORKUP ADD (REWO_TX_MOTIVO_COLETA_INVIAVEL CLOB );
ALTER TABLE MODRED.RESULTADO_WORKUP RENAME COLUMN REWO_IN_COLETA_INVIAVEL TO REWO_IN_COLETA_INVIAVEL;
ALTER TABLE MODRED.RESULTADO_WORKUP ADD (REWO_IN_DOADOR_INDISPONIVEL NUMBER );

COMMENT ON COLUMN MODRED.RESULTADO_WORKUP.REWO_IN_COLETA_INVIAVEL IS 'Coleta inviavel pelo registro inernacional ou nacional.';
COMMENT ON COLUMN MODRED.RESULTADO_WORKUP.REWO_TX_MOTIVO_COLETA_INVIAVEL IS 'Motivo da coleta inviavel pelo registro inernacional ou nacional.';
COMMENT ON COLUMN MODRED.RESULTADO_WORKUP.REWO_IN_DOADOR_INDISPONIVEL IS 'Doador Indisponivel para coleta de material.';

--#################################################################################

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES (224, 'AGENDAR_COLETA_NACIONAL', 0, 0);

--#################################################################################

UPDATE "MODRED"."TIPO_TAREFA" SET TITA_TX_DESCRICAO = 'ANALISE_MEDICA_DOADOR_CONTATO' WHERE TITA_ID = 95;
UPDATE "MODRED"."TIPO_TAREFA" SET TITA_TX_DESCRICAO = 'ANALISE_MEDICA_DOADOR_COLETA' WHERE TITA_ID = 38;

INSERT INTO "MODRED"."FASE_WORKUP" (FAWO_ID, FAWO_TX_SIGLA) VALUES (12, 'AGUARDANDO_ANALISE_MEDICA_DOADOR_COLETA');

--#################################################################################

--############################### SPRINT 67 ##############################################

ALTER TABLE AVALIACAO_RESULTADO_WORKUP RENAME COLUMN AVRW_IN_SOLICITA_COLETA TO AVRW_IN_PROSSEGUIR;

COMMENT ON COLUMN AVALIACAO_RESULTADO_WORKUP.AVRW_IN_PROSSEGUIR IS 'Indica se apos a avaliaçao o medico do centro de transplante prosseguiu com a coleta.';

ALTER TABLE AVALIACAO_PEDIDO_COLETA 
DROP CONSTRAINT FK_AVPC_SOLI;

ALTER TABLE AVALIACAO_PEDIDO_COLETA 
DROP COLUMN AVPC_DT_AVALIACAO;

ALTER TABLE AVALIACAO_PEDIDO_COLETA 
DROP COLUMN SOLI_ID;

DROP INDEX IN_FK_AVPC_SOLI;

ALTER TABLE AVALIACAO_PEDIDO_COLETA 
ADD (AVRW_ID NUMBER NOT NULL);

CREATE INDEX IN_FK_AVPC_AVRW ON AVALIACAO_PEDIDO_COLETA (AVRW_ID ASC);

ALTER TABLE AVALIACAO_PEDIDO_COLETA
ADD CONSTRAINT FK_AVPC_AVRW FOREIGN KEY
(
  AVRW_ID 
)
REFERENCES AVALIACAO_RESULTADO_WORKUP
(
  AVRW_ID 
)
ENABLE;

COMMENT ON COLUMN AVALIACAO_PEDIDO_COLETA.AVRW_ID IS 'Identifiador da Avaliaçao do Resultado de Workup.';


UPDATE MODRED.FASE_WORKUP SET FAWO_TX_SIGLA = 'AGUARDANDO_AVALIACAO_PEDIDO_COLETA'
WHERE FAWO_ID = 12;
COMMIT;

--#################################################################################

INSERT INTO "MODRED"."FASE_WORKUP" (FAWO_ID, FAWO_TX_SIGLA) VALUES (13, 'AGUARDANDO_EXAME_ADICIONAL_DOADOR');
INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES (225, 'INFORMAR_EXAME_ADICIONAL_WORKUP_NACIONAL', 0, 0)
INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES (226, 'INFORMAR_EXAME_ADICIONAL_WORKUP_INTERNACIONAL', 0, 0)

INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (230, 'CADASTRAR_PEDIDO_ADICIONAL_WORKUP_NACIONAL', 'Permite cadastrar um novo pedido adicional workup nacional.');
INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (231, 'CADASTRAR_PEDIDO_ADICIONAL_WORKUP_INTERNACIONAL', 'Permite cadastrar um novo pedido adicional workup internacional.');

INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (230, 15, 0);
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (230, 9, 0);
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (231, 15, 0);
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (231, 20, 0);


ALTER TABLE MODRED.ARQUIVO_RESULTADO_WORKUP ADD (PEAW_ID NUMBER );
CREATE INDEX IN_FK_ARRW_PEAW ON MODRED.ARQUIVO_RESULTADO_WORKUP (PEAW_ID ASC);

ALTER TABLE MODRED.ARQUIVO_RESULTADO_WORKUP ADD CONSTRAINT FK_ARRW_PEAW FOREIGN KEY (PEAW_ID)
REFERENCES MODRED.PEDIDO_ADICIONAL_WORKUP (PEAW_ID)
DISABLE;

COMMENT ON COLUMN MODRED.ARQUIVO_RESULTADO_WORKUP.PEAW_ID IS 'Identificador do pedido adicional de workup.';


ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP DROP CONSTRAINT FK_PEAW_AVRW;
ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP DROP COLUMN AVRW_ID;
DROP INDEX IN_FK_PEAW_AVRW;

ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP ADD (REWO_ID NUMBER );
CREATE INDEX IN_FK_PEAW_REWO ON MODRED.PEDIDO_ADICIONAL_WORKUP (REWO_ID ASC);

ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP ADD CONSTRAINT FK_PEAW_REWO FOREIGN KEY (REWO_ID) 
REFERENCES MODRED.RESULTADO_WORKUP (REWO_ID)
DISABLE;

COMMENT ON COLUMN MODRED.PEDIDO_ADICIONAL_WORKUP.REWO_ID IS 'Identificador do resultado de workup.';

--#################################################################################

--############################### Sprint 67 #######################################

CREATE TABLE MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP 
(
  APAW_ID NUMBER NOT NULL 
, APAW_TX_CAMINHO VARCHAR2(225) NOT NULL 
, PEAW_ID NUMBER 
, CONSTRAINT PK_APAW PRIMARY KEY  (APAW_ID)
  ENABLE 
);

CREATE INDEX IN_FK_APAW_PEAW ON MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP (PEAW_ID ASC);

ALTER TABLE MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP ADD CONSTRAINT FK_APAW_PEAW FOREIGN KEY (PEAW_ID)
REFERENCES MODRED.PEDIDO_ADICIONAL_WORKUP (PEAW_ID)
ENABLE;

COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP.APAW_ID IS 'Identificador único da tabela.';

COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP.APAW_TX_CAMINHO IS 'Path do arquivo adicional workup.';

COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP.PEAW_ID IS 'Referência para a tabela de pedido adicional workup.';

CREATE SEQUENCE  MODRED.SQ_APAW_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 ORDER;



ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP DROP CONSTRAINT FK_PEAW_REWO;

ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP RENAME COLUMN REWO_ID TO PEWO_ID;

ALTER INDEX IN_FK_PEAW_REWO RENAME TO IN_FK_PEAW_PEWO;

ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP ADD CONSTRAINT FK_PEAW_PEWO FOREIGN KEY (PEWO_ID)
REFERENCES MODRED.PEDIDO_WORKUP (PEWO_ID)
DISABLE;

COMMENT ON COLUMN MODRED.PEDIDO_ADICIONAL_WORKUP.PEWO_ID IS 'Identificador do pedido de workup.';


--################################# SPRINT 67 ################################################

INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (232, 'CONSULTAR_PEDIDO_WORKUP_NACIONAL', 'Permite consultar pedido de workup nacional.');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (232, 32, 0);
UPDATE "MODRED"."RECURSO" SET RECU_TX_SIGLA = 'FINALIZAR_RESULTADO_WORKUP_NACIONAL', RECU_TX_DESCRICAO = 'Permite finalizar resultado de workup nacional.' WHERE RECU_ID = 227;
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (227, 15, 0);
ALTER TABLE MODRED.PEDIDO_ADICIONAL_WORKUP MODIFY (PEAW_TX_DESCRICAO VARCHAR2(500 BYTE) );

ALTER TABLE MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP ADD (APAW_TX_DESCRICAO VARCHAR2(225) );
COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP.APAW_TX_DESCRICAO IS 'Descrição do arquivo de exama adicional.';

INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (233, 'CADASTRAR_ARQUIVO_PEDIDO_ADICIONAL_WORKUP', 'Permite ao analista de workup de incluir novos arquivos de exame adicional de workup.')
INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (234, 'FINALIZAR_PEDIDO_ADICIONAL_WORKUP', 'Permite ao analista de workup de finalizar o pedido de exame adicional de workup.')
INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (235, 'CONSULTAR_PEDIDO_ADICIONAL_WORKUP', 'Permite consultar o pedido adicional de workup.')

INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (233, 9, 0)
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (234, 9, 0)
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (233, 20, 0)
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (234, 20, 0)
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (235, 9, 0);
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (235, 20, 0);
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (235, 15, 0);
commit;

--#############################################################################################

--################################# SPRINT 68 ################################################

UPDATE "MODRED"."FASE_WORKUP" SET FAWO_TX_SIGLA = 'AGUARDANDO_AGENDAMENTO_COLETA' WHERE FAWO_ID = 7;

ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_IN_PRODUDO NUMBER DEFAULT 0 );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_DT_INICIO_GCSF TIMESTAMP );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_DT_INTERNACAO TIMESTAMP );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_TX_GCSF_SETOR_ANDAR VARCHAR2(30) );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_TX_GCSF_PROCURAR_POR VARCHAR2(50) );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_TX_INTERNACAO_SETOR_ANDAR VARCHAR2(30) );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_TX_INTERNACAO_PROCURAR_POR VARCHAR2(50) );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_IN_JEJUM NUMBER(1,0) );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_NR_HR_JEJUM NUMBER );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_IN_JEJUM_TOTAL NUMBER(1,0) );
ALTER TABLE MODRED.PEDIDO_COLETA ADD (PECL_TX_INFORMACOES_ADICIONAIS CLOB );

COMMENT ON COLUMN MODRED.PEDIDO_COLETA.SOLI_ID IS 'Identificador da soliciotação.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.MOCC_TX_CODIGO IS 'Motivo do cancelamento do pedido de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_IN_PRODUDO IS 'Informar o tipo de produto 0-MO | 1-PBSC | DLI';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_DT_INICIO_GCSF IS 'Data inicío do G-CSF do doador.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_DT_INTERNACAO IS 'Data da internação do doador.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_TX_GCSF_SETOR_ANDAR IS 'Nome setor e andar do G-CSF informado no agendamento do pedido de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_TX_GCSF_PROCURAR_POR IS 'Nome procurar por do G-CSF informado no agendamento do pedido de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_TX_INTERNACAO_SETOR_ANDAR IS 'Nome setor e andar da internação informado no agendamento do pedido de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_TX_INTERNACAO_PROCURAR_POR IS 'Nome procurar por da internação informado no agendamento do pedido de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_IN_JEJUM IS 'Flag doador em jejum informado no agendamento de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_NR_HR_JEJUM IS 'Jejum de quantas horas informado no agendamento de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_IN_JEJUM_TOTAL IS 'Doador em jejum total - sim 1 ou não 0  no agendamento de coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_TX_INFORMACOES_ADICIONAIS IS 'Campo livre de observaçao que sera informado no agendamento de coleta.';

UPDATE MODRED.RECURSO SET RECU_TX_SIGLA = 'AGENDAR_COLETA_DOADOR' WHERE RECU_ID = 51;
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES ('236', 'CONSULTAR_PEDIDO_COLETA', 'Permite consultar o pedido de coleta do doador.')
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (236, 32, 0);
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (237, 'CONSULTAR_CENTRO_TRANSPLANTE', 'Permite consultar centro de transplante.');
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (237, 32, 0);
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES (227, 'DEFINIR_LOGISTICA', 0, 0);
UPDATE MODRED.CATEGORIA_NOTIFICACAO SET CANO_TX_DESCRICAO = 'Agendar Coleta' WHERE CANO_ID = 11;
INSERT INTO MODRED.FASE_WORKUP (FAWO_ID, FAWO_TX_SIGLA) VALUES (14, 'AGUARDANDO_DEFINICAO_LOGISTICA');
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (238, 'AGENDAR_PEDIDO_COLETA', 'Permite fazer o agendamento do pedido de coleta pelo medico do centro de coleta.');
COMMIT;

ALTER TABLE PEDIDO_COLETA MODIFY (PECL_DT_COLETA TIMESTAMP );
COMMENT ON COLUMN PEDIDO_COLETA.PECL_DT_COLETA IS 'Data e hora da coleta replicada do pedido de workup ou da prescrição, Depende se o doador é medula ou cordão.';
COMMENT ON COLUMN PEDIDO_COLETA.PECL_IN_PRODUDO IS 'Informar o tipo de produto 0-MO | 1-PBSC';

--#############################################################################################

UPDATE MODRED.TIPO_TAREFA SET TITA_TX_DESCRICAO = 'INFORMAR_RECEBIMENTO_COLETA' WHERE TITA_ID = 50;
INSERT INTO MODRED.FASE_WORKUP (FAWO_ID, FAWO_TX_SIGLA) VALUES (16, 'AGUARDANDO_RECEBIMENTO_COLETA');
UPDATE MODRED.PERMISSAO SET PERF_ID = 15 WHERE RECU_ID = 74;
UPDATE MODRED.RECURSO SET RECU_TX_SIGLA = 'TRATAR_RECEBIMENTO_COLETA' WHERE RECU_ID = 74; 
COMMIT;

ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_NR_NUMERO_BOLSAS NUMBER );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_NR_VOLUME_PRODUTO NUMBER );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_IN_COLETA_DEACORDO_PRESCRICAO NUMBER );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_TX_MOTIVO_COLETA_INCORRETA CLOB );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_IN_INDENTIFICACAO_DOADOR_CONFERE NUMBER );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_TX_MOTIVO_IDENTIFICACAO_DOADOR_INCORRETO CLOB );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_IN_ACONDICIONADO_CORRETO NUMBER );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_TX_MOTIVO_ACONDICIONADO_INCORRETO CLOB );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_IN_EVENTO_ADVERSO NUMBER );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_TX_DESCREVA_EVENTO_ADVERSO CLOB );
ALTER TABLE MODRED.RECEBIMENTO_COLETA ADD (RECE_TX_COMENTARIO_ADICIONAL CLOB );

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_NR_NUMERO_BOLSAS IS 'Quantidade de bolsas utilizada na coleta do produto.';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_NR_VOLUME_PRODUTO IS 'Volume do produto do recebimento da coleta.';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_IN_COLETA_DEACORDO_PRESCRICAO IS 'Produto coletado esta de acordo com a prescrição?';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_TX_MOTIVO_COLETA_INCORRETA IS 'Motivo do produto coletado não esta de acordo com a prescrição.';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_IN_INDENTIFICACAO_DOADOR_CONFERE IS 'A identificação do doador nas etiquetas confere?';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_TX_MOTIVO_IDENTIFICACAO_DOADOR_INCORRETO IS 'Motivo da identificação do doador nas etiquetas não confererir?';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_IN_ACONDICIONADO_CORRETO IS 'O produto esta acondicionado corretamente?';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_TX_MOTIVO_ACONDICIONADO_INCORRETO IS 'Motivo do produto não esta acondicionado corretamente.';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_IN_EVENTO_ADVERSO IS 'Houve algum evento adverso relacionado com o produto?';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_TX_DESCREVA_EVENTO_ADVERSO IS 'Descreva se houve algum evento adverso relacionado com o produto.';
COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_TX_COMENTARIO_ADICIONAL IS 'Descreve os comentários acicionais sobre a coleta do produto.';
COMMIT;



--#############################################################################################

ALTER TABLE RESULTADO_WORKUP 
ADD (FOCE_ID NUMBER );

ALTER TABLE RESULTADO_WORKUP 
ADD (REWO_DT_COLETA DATE );

ALTER TABLE RESULTADO_WORKUP 
ADD (REWO_DT_GCSF DATE );

ALTER TABLE RESULTADO_WORKUP 
ADD (REWO_IN_ADEGUADO_AFERESE NUMBER );

ALTER TABLE RESULTADO_WORKUP 
ADD (REWO_TX_ACESSO_VENOSO_CENTRAL CLOB );

ALTER TABLE RESULTADO_WORKUP 
ADD (REWO_IN_SANGUE_ANTOLOGO_COLETADO NUMBER );

ALTER TABLE RESULTADO_WORKUP 
ADD (REWO_TX_MOTIVO_SA_NAO_COLETADO CLOB );

CREATE INDEX IN_FK_REWO_FOCE ON RESULTADO_WORKUP (FOCE_ID ASC);

ALTER TABLE RESULTADO_WORKUP
ADD CONSTRAINT FK_REWO_FOCE FOREIGN KEY
(
  FOCE_ID 
)
REFERENCES FONTE_CELULAS
(
  FOCE_ID 
)
ENABLE;

COMMENT ON COLUMN RESULTADO_WORKUP.FOCE_ID IS 'Identificador da fonte de celula.';

COMMENT ON COLUMN RESULTADO_WORKUP.REWO_DT_COLETA IS 'Data prevista da coleta.';

COMMENT ON COLUMN RESULTADO_WORKUP.REWO_DT_GCSF IS 'Data exame GCSF quando fone for sangue periferico..';

COMMENT ON COLUMN RESULTADO_WORKUP.REWO_IN_ADEGUADO_AFERESE IS 'Quando fonte for sangue periferico.';

COMMENT ON COLUMN RESULTADO_WORKUP.REWO_TX_ACESSO_VENOSO_CENTRAL IS '		Quando fonte for sangue periferico.';

COMMENT ON COLUMN RESULTADO_WORKUP.REWO_IN_SANGUE_ANTOLOGO_COLETADO IS '		Quando fonte for medula ossea.';

COMMENT ON COLUMN RESULTADO_WORKUP.REWO_TX_MOTIVO_SA_NAO_COLETADO IS '		Quando fonte for medula ossea.';


//######################################################################################################

ALTER TABLE MODRED.ENDERECO_CONTATO ADD (TRAN_ID NUMBER );

ALTER TABLE MODRED.ENDERECO_CONTATO ADD CONSTRAINT FK_ENCO_TRAN FOREIGN KEY (TRAN_ID) 
REFERENCES MODRED.TRANSPORTADORA (TRAN_ID)
ENABLE;

COMMENT ON COLUMN MODRED.ENDERECO_CONTATO.TRAN_ID IS 'ID de identificação da transportadora associado a este endereço.';

INSERT INTO RECURSO VALUES (227, 'FINALIZAR_RESULTADO_WORKUP_NACIONAL', 'Permite finalizar resultado de workup nacional.');
INSERT INTO PERMISSAO VALUES (227, 32, 0);
COMMIT;

INSERT INTO RECURSO VALUES (228, 'AVALIAR_RESULTADO_WORKUP_NACIONAL', 'Permite avaliar resultado de workup nacional.');
INSERT INTO PERMISSAO VALUES (228, 15, 0);
COMMIT;

//################ SPRINT 70 ####################
ALTER TABLE MODRED.PEDIDO_LOGISTICA ADD (PELO_TX_JUSTIFICA_NAO_PROSSEGUIMENTO CLOB );
COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA.PELO_TX_JUSTIFICA_NAO_PROSSEGUIMENTO IS 'Campo para justificar o motivo do fechamento do pedido de logística.';

ALTER TABLE MODRED.PEDIDO_LOGISTICA_AUD ADD (PELO_TX_JUSTIFICA_NAO_PROSSEGUIMENTO CLOB );
COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA_AUD.PELO_TX_JUSTIFICA_NAO_PROSSEGUIMENTO IS 'Campo para justificar o motivo do fechamento do pedido de logística.';

INSERT INTO MODRED.TIPO_PEDIDO_LOGISTICA (TIPL_ID, TIPL_TX_DESCRICAO) VALUES (4, 'MATERIAL_INTERNACIONAL');
COMMIT;

INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (240, 'EFETUAR_LOGISTICA_DOADOR_COLETA', 'Permite agendar pedido de logistica doador para coleta.');
COMMIT;

INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (240, 9, 0);
COMMIT;

INSERT INTO MODRED.FASE_WORKUP (FAWO_ID, FAWO_TX_SIGLA) VALUES (20, 'AGUARDANDO_RESULTADO_DOADOR_COLETA');
COMMIT;

INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES (229, 'INFORMAR_RESULTADO_DOADOR_COLETA', 0, 0);
COMMIT;

ALTER TABLE MODRED.PEDIDO_LOGISTICA ADD (TRAN_ID NUMBER NULL);
ALTER TABLE MODRED.PEDIDO_LOGISTICA_AUD ADD (TRAN_ID NUMBER NULL);

ALTER TABLE MODRED.PEDIDO_LOGISTICA ADD (PELO_HR_PREVISTA_RETIRADA TIMESTAMP );
ALTER TABLE MODRED.PEDIDO_LOGISTICA_AUD ADD (PELO_HR_PREVISTA_RETIRADA TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_LOGISTICA ADD CONSTRAINT FK_PELO_TRAN FOREIGN KEY (TRAN_ID)
REFERENCES TRANSPORTADORA(TRAN_ID)
ENABLE;

COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA.TRAN_ID IS 'Transportadora responsavel por enviar o courier para retirada do material.';
COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA.PELO_HR_PREVISTA_RETIRADA IS 'Hora prevista para a retirada do material da coleta.';


COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA_AUD.TRAN_ID IS 'Transportadora responsavel por enviar o courier para retirada do material.';
COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA_AUD.PELO_HR_PREVISTA_RETIRADA IS 'Hora prevista para a retirada do material da coleta.';

ALTER TABLE PEDIDO_LOGISTICA 
ADD (PELO_IN_AEREO NUMBER );

COMMENT ON COLUMN PEDIDO_LOGISTICA.PELO_IN_AEREO IS 'Informa se a logistica de material e com aereo.';

ALTER TABLE PEDIDO_LOGISTICA_AUD 
ADD (PELO_IN_AEREO NUMBER );


INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (227, 9, 0);
COMMIT;

--################ SPRINT 71 # MODRED-5446 ####################

INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (241, 'CADASTRAR_COLETA_CONTAGEM_CELULA', 'Permite cadastar contagem de celula para coleta.');

INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (241, 9, 0);

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES (231, 'CADASTRAR_COLETA_CONTAGEM_CELULA',0, 0);


--################ SPRINT 72 # MODRED-5531 ####################

  CREATE TABLE "MODRED"."CONTAGEM_CELULA" 
   (	"COCE_ID" NUMBER NOT NULL ENABLE, 
	"PEWO_ID" NUMBER NOT NULL ENABLE, 
	"COCE_IN_FONTE_CELULA" NUMBER, 
	"COCE_IN_ABO" NUMBER, 
	"COCE_IN_MANIPULACAO_PRODUTO" NUMBER, 
	"COCE_TX_MANIPULACAO" VARCHAR2(20 BYTE), 
	"COCE_DT_COLETA" DATE, 
	"COCE_VL_VOLUME_BOLSA" NUMBER, 
	"COCE_VL_ANTICOAGULANTE" NUMBER, 
	"COCE_NR_TCN" NUMBER, 
	"COCE_NR_TCN_KG" NUMBER, 
	"COCE_DT_AFERISE_0" DATE, 
	"COCE_VL_VOLUME_BOLSA_0" NUMBER, 
	"COCE_NR_CELULA_0" NUMBER, 
	"COCE_NR_CELULA_KG_0" NUMBER, 
	"COCE_DT_AFERISE_1" DATE, 
	"COCE_VL_VOLUME_BOLSA_1" NUMBER, 
	"COCE_NR_CELULA_1" NUMBER, 
	"COCE_NR_CELULA_KG_1" NUMBER, 
	"COCE_DT_AFERISE_2" DATE, 
	"COCE_VL_VOLUME_BOLSA_2" NUMBER, 
	"COCE_NR_CELULA_2" NUMBER, 
	"COCE_NR_CELULA_KG_2" NUMBER, 
	"COCE_DT_ENVIO" DATE, 
	"COCE_HR_ENVIO" TIMESTAMP (6), 
	"COCE_TX_ANTICOAGULANTE" VARCHAR2(20 BYTE), 
	"COCE_IN_INTERCORRENCIA" NUMBER, 
	"COCE_TX_INTERCORRENCIA" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CONTAGEM_CELULA_PK" PRIMARY KEY ("COCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_MODRED_TAB"  ENABLE, 
	 CONSTRAINT "FK_COCE_PEWO" FOREIGN KEY ("PEWO_ID")
	  REFERENCES "MODRED"."PEDIDO_WORKUP" ("PEWO_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_MODRED_TAB" ;

   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_ID" IS 'Identificador da contagem celula.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."PEWO_ID" IS 'Identificador do pedido de workup.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_IN_FONTE_CELULA" IS 'Fonte de Celula: 0-Medula, 1-periferico e 2-linfocito.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_IN_ABO" IS 'ABO: 0-maior, 1-menor e 2-incompativel.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_IN_MANIPULACAO_PRODUTO" IS 'Manipulação do produto: 0-FALSE, 1-TRUE.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_TX_MANIPULACAO" IS 'Qual Manipulação do produto.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_DT_COLETA" IS 'Data da Coleta de Medula.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_VL_VOLUME_BOLSA" IS 'Volume da bolsa ao Coletar Medula.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_VL_ANTICOAGULANTE" IS 'Volume de Anticoagulante na Bolsa.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_TCN" IS 'Quantidade de TCN na Bolsa.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_TCN_KG" IS 'Quantidade de TCN por kg na Bolsa.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_DT_AFERISE_0" IS 'Data da 1ª aferise sangue periferico ou Linfocito.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_VL_VOLUME_BOLSA_0" IS 'Volume da bolsa da 1ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_CELULA_0" IS 'Numero de Celulas da 1ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_CELULA_KG_0" IS 'Numero de Celulas por Kg do paciente da 1ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_DT_AFERISE_1" IS 'Data da 2ª aferise sangue periferico ou Linfocito.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_VL_VOLUME_BOLSA_1" IS 'Volume da bolsa da 2ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_CELULA_1" IS 'Numero de Celulas da 2ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_CELULA_KG_1" IS 'Numero de Celulas por Kg do paciente da 2ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_DT_AFERISE_2" IS 'Data da 3ª aferise sangue periferico ou Linfocito.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_VL_VOLUME_BOLSA_2" IS 'Volume da bolsa da 3ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_CELULA_2" IS 'Numero de Celulas da 3ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_NR_CELULA_KG_2" IS 'Numero de Celulas por Kg do paciente da 3ª aferise.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_DT_ENVIO" IS 'Data do Envio da coleta.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_HR_ENVIO" IS 'Hora do envio da coleta.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_TX_ANTICOAGULANTE" IS 'Anticoagulante Utilizado.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_IN_INTERCORRENCIA" IS 'Houve alguma intercorrência durante ou após a coleta de CTH?: 0-FALSE, 1-TRUE.';
   COMMENT ON COLUMN "MODRED"."CONTAGEM_CELULA"."COCE_TX_INTERCORRENCIA" IS 'Quais intercorrências durante ou após a coleta de CTH.';

--################ SPRINT 72 # MODRED-5533 ####################
CREATE SEQUENCE  "MODRED"."SQ_COCE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 ORDER;

--################ SPRINT 72 # MODRED-5528 ####################
INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (244, 'TRATAR_CONTAGEM_CELULA', 'Permite salvar e finalizar a contagem de celulas.')

INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (244, 32, 0)

INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (236, 9, 0);






################ SPRINT 71 - 5496 ################################

INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (242, 'INFORMAR_FORMULARIO_POSCOLETA', 'Permite ao centro de coleta informar o formulário pos coleta.');
COMMIT;
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (242, 32, 0);
COMMIT;
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES (230, 'INFORMAR_FORMULARIO_POSCOLETA', 0, 0)
COMMIT;

//###########################  SPRINT 72 - 5503 ################################

CREATE TABLE MODRED.FORMULARIO_POSCOLETA
(FOPO_ID NUMBER NOT NULL ENABLE, 
 PEWO_ID NUMBER, 
 USUA_ID NUMBER,
 FOPO_DT_CRIACAO TIMESTAMP (6) NOT NULL ENABLE, 
 FOPO_DT_ATUALIZACAO TIMESTAMP (6)
);
  
 ALTER TABLE MODRED.FORMULARIO_POSCOLETA 
 ADD CONSTRAINT PK_FOPO PRIMARY KEY (FOPO_ID);

 ALTER TABLE MODRED.FORMULARIO_POSCOLETA 
 ADD CONSTRAINT FK_FOPO_PEWO FOREIGN KEY (PEWO_ID)
 REFERENCES MODRED.PEDIDO_WORKUP (PEWO_ID) ENABLE;
 
 ALTER TABLE MODRED.FORMULARIO_POSCOLETA 
 ADD CONSTRAINT FK_FOPO_USUA FOREIGN KEY (USUA_ID) 
 REFERENCES MODRED.USUARIO (USUA_ID);
 
 COMMENT ON COLUMN MODRED.FORMULARIO_POSCOLETA.FOPO_ID IS 'Chave primária que identifica com exclusividade um formulário pós coleta.'; 
 COMMENT ON COLUMN MODRED.FORMULARIO_POSCOLETA.PEWO_ID IS 'Chave estrangeira para pedido de workup';
 COMMENT ON COLUMN MODRED.FORMULARIO_POSCOLETA.USUA_ID IS 'Id do usuário que preencheu o formulário pós coleta';
 COMMENT ON COLUMN MODRED.FORMULARIO_POSCOLETA.FOPO_DT_CRIACAO IS 'Data de criação do fromulário pós coleta.';
 COMMENT ON COLUMN MODRED.FORMULARIO_POSCOLETA.FOPO_DT_ATUALIZACAO IS 'Data de atualização do fromulário pós coleta.';
 
 CREATE SEQUENCE  MODRED.SQ_FOPO_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER;
 
 
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (243, 'FINALIZAR_FORMULARIO_POSCOLETA', 'Permite finalizar formulário pos coleta.');
COMMIT;
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (243, 32, 0);
COMMIT;
 

INSERT INTO "MODRED"."FASE_WORKUP" (FAWO_ID, FAWO_TX_SIGLA) VALUES ('21', 'AGUARDANDO_INFORMACAO_POSCOLETA'); 
COMMIT;

########################## SPRINT 71 # MODRED-5446 #############################

ALTER TABLE MODRED.SOLICITACAO 
ADD (SOLI_IN_POSCOLETA NUMBER);

COMMENT ON COLUMN SOLICITACAO.SOLI_IN_POSCOLETA IS 'Flag que indica se a solciitação tem formulário de pós coleta';    
       
//###############################################################################




