CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DISTRIBUICAO_WORKUP FOR MODRED.DISTRIBUICAO_WORKUP;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_DIWO_ID FOR MODRED.SQ_DIWO_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DISTRIBUICAO_WORKUP_AUD FOR MODRED.DISTRIBUICAO_WORKUP_AUD;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ARQUIVO_PEDIDO_WORKUP FOR MODRED.ARQUIVO_PEDIDO_WORKUP;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ARPW_ID FOR MODRED.SQ_ARPW_ID;

--############################### Sprint 67 #######################################

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ARQUIVO_PEDIDO_ADICIONAL_WORKUP FOR MODRED.ARQUIVO_PEDIDO_ADICIONAL_WORKUP;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_APAW_ID FOR MODRED.SQ_APAW_ID;

//###########################  SPRINT 72 - 5503 ################################

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.FORMULARIO_POSCOLETA FOR MODRED.FORMULARIO_POSCOLETA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_FOPO_ID FOR MODRED.SQ_FOPO_ID;

--#################################################################################

--################ SPRINT 72 # MODRED-5532 ####################
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CONTAGEM_CELULA FOR MODRED.CONTAGEM_CELULA;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_COCE_ID FOR MODRED.SQ_COCE_ID;
