apiVersion: v1
kind: Service
metadata:
  name: redome-courier-svc
  namespace: develop
spec:
  type: NodePort
  selector:
    app: redome-courier
    namespace: develop
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redome-courier-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redome-courier
      namespace: develop
  template:
    metadata:
      labels:
        app: redome-courier
        namespace: develop
    spec:
       hostname: redome-courier
       subdomain: redome-courier-svc          
       containers:
       -  name: redome-courier
          image: us.icr.io/dev_modred/redome_courier:1-20200831142152
          env:
          -  name: profile
             value: dev
          resources:
            requests:
              cpu: "100m"
              memory: "768Mi"
            limits:
              memory: "1536Mi"
       imagePullSecrets:
       - name: ibmcloudregcred
       nodeSelector:
         name: worker03
