apiVersion: v1
kind: Service
metadata:
  name: redome-courier-svc
  namespace: hml
spec:
  type: NodePort
  selector:
    app: redome-courier
    namespace: hml
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redome-courier-deployment
  namespace: hml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redome-courier
      namespace: hml
  template:
    metadata:
      labels:
        app: redome-courier
        namespace: hml
    spec:
       hostname: redome-courier
       subdomain: redome-courier-svc          
       containers:
       -  name: redome-courier
          image: $IMAGE_NAME
          env:
          -  name: profile
             value: hml
          resources:
            requests:
              cpu: "100m"
              memory: "768Mi"
            limits:
              cpu: "100m"
              memory: "1536Mi"
          volumeMounts:
          - mountPath: "/logs"
            name: apilog      
       volumes:
         - name: apilog
           persistentVolumeClaim:
             claimName: inca-pvc
