apiVersion: v1
kind: Service
metadata:
 name: redome-cloud-svc
 namespace: hml
spec:
 type: NodePort
 selector:
   app: redome-cloud
 ports:
  - protocol: TCP
    port: 9081

---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redome-cloud-deployment
  namespace: hml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redome-cloud
      namespace: hml
  template:
    metadata:
      labels:
        app: redome-cloud
        namespace: hml
    spec:
      hostname: redome-cloud
      subdomain: redome-cloud-svc
      containers:
      - name: redome-cloud
        image: sr-vmlxapp26.inca.local:5000/redome-cloud:37_20201028164127
        ports:
        - containerPort: 9081
        env:
          - name: profile
            value: hml
        resources:
          requests:
            cpu: '1m'
            memory: '512Mi'
          limits:
            memory: '768Mi'
        volumeMounts:
          - mountPath: "/logs"
            name: apilog      
      volumes:
        - name: apilog
          persistentVolumeClaim:
            claimName: inca-pvc

