apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: redome-cloud
build:
  artifacts:
  - image: localhost:32000/redome_cloud
    docker:
      dockerfile: local-Dockerfile
deploy:
  kubectl:
    manifests:
    - local-deployment.yml
portForward:
  - resourceType: service
    resourceName: redome-cloud-svc
    port: 9081
    localPort: 9081
  - resourceType: service
    resourceName: redome-cloud-svc
    port: 5000
    localPort: 5000
