UPDATE TIPO_TAREFA SET TITA_TX_DESCRICAO = 'INFORMAR_DOCUMENTACAO_MATERIAL_AEREO'
WHERE TITA_ID = 42;

UPDATE TIPO_TAREFA SET TITA_TX_DESCRICAO = 'INFORMAR_RETIRADA_MATERIAL'
WHERE TITA_ID = 56;

commit;

INSERT INTO FASE_WORKUP VALUES (18, 'AGUARDANDO_DOCUMENTACAO_PEDIDO_TRANSPORTE_AEREO');
INSERT INTO FASE_WORKUP VALUES (19, 'AGUARDANDO_RETIRADA_MATERIAL');

COMMIT;


ALTER TABLE PEDIDO_TRANSPORTE 
ADD (SOLI_ID NUMBER );

CREATE INDEX IN_FK_PETR_SOLI ON PEDIDO_TRANSPORTE (SOLI_ID ASC);

ALTER TABLE PEDIDO_TRANSPORTE
ADD CONSTRAINT FK_PETR_SOLI FOREIGN KEY
(
  SOLI_ID 
)
REFERENCES SOLICITACAO
(
  SOLI_ID 
)
ENABLE;

COMMENT ON COLUMN PEDIDO_TRANSPORTE.SOLI_ID IS 'Identificaçao da solicitaçao de workup.';

ALTER TABLE PEDIDO_TRANSPORTE 
ADD (FOCE_ID NUMBER );

COMMENT ON COLUMN PEDIDO_TRANSPORTE.FOCE_ID IS 'Identificaçao da fonte de celula.';

CREATE INDEX IN_FK_PETR_FOCE ON PEDIDO_TRANSPORTE (FOCE_ID ASC);

ALTER TABLE PEDIDO_TRANSPORTE
ADD CONSTRAINT FK_PETR_FOCE FOREIGN KEY
(
  FOCE_ID 
)
REFERENCES FONTE_CELULAS
(
  FOCE_ID 
)
ENABLE;

