GRANT SELECT ON MODRED.NOTIFICACAO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.NOTIFICACAO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.CATEGORIA_NOTIFICACAO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.CATEGORIA_NOTIFICACAO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.MOTIVO_DESCARTE TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.MOTIVO_DESCARTE TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_NOTI_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.LOCUS_EXAME_AUD TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.LOCUS_EXAME_AUD TO RMODRED_WRITE;
GRANT SELECT ON MODRED.EXAME_AUD TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.EXAME_AUD TO RMODRED_WRITE;
GRANT SELECT ON MODRED.METODOLOGIA_EXAME_AUD TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.METODOLOGIA_EXAME_AUD TO RMODRED_WRITE;
GRANT execute ON MODRED.get_score TO RMODRED_READ;

---JOB---
GRANT INSERT ON MODRED.VALOR_NMDP TO RMODRED_WRITE;
GRANT INSERT, UPDATE, DELETE ON MODRED.VALOR_DNA_NMDP TO RMODRED_WRITE;
GRANT SELECT ON MODRED.TEMP_VALOR_NMDP TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.TEMP_VALOR_NMDP TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SPLIT_VALOR_DNA TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.SPLIT_VALOR_DNA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SPLIT_NMDP TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.SPLIT_NMDP TO RMODRED_WRITE;