GRANT SELECT ON "MODRED"."PROCESSO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PROCESSO" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_PROC_ID" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."TAREFA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."TAREFA" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_TARE_ID" TO RMODRED_WRITE;
GRANT SELECT ON MODRED.IDIOMA TO RMODRED_READ;
GRANT SELECT ON MODRED.CID_IDIOMA TO RMODRED_READ;
GRANT SELECT ON "MODRED"."SQ_PERF_ID" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_CETR_ID" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_USUA_ID" TO RMODRED_WRITE;

---JOB---
GRANT SELECT ON MODRED.TEMP_SPLIT_VALOR_DNA TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.TEMP_SPLIT_VALOR_DNA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.TEMP_VALOR_DNA TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.TEMP_VALOR_DNA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.TEMP_VALOR_DNA_NMDP TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.TEMP_VALOR_DNA_NMDP TO RMODRED_WRITE;
GRANT SELECT ON MODRED.VALOR_DNA_NMDP_VALIDO TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.VALOR_DNA_NMDP_VALIDO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.VALOR_DNA_NMDP TO RMODRED_READ;