DROP SEQUENCE MODRED.SQ_TARE_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_TARE_ID;
DROP SYNONYM MODRED_APLICACAO.TAREFA;
DROP TABLE MODRED.TAREFA CASCADE CONSTRAINTS;

DROP SEQUENCE MODRED.SQ_PROC_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_PROC_ID;
DROP SYNONYM MODRED_APLICACAO.PROCESSO;
DROP TABLE MODRED.PROCESSO CASCADE CONSTRAINTS;

ALTER TABLE MODRED.CID
ADD (CID_TX_DESCRICAO VARCHAR2(300));

COMMENT ON COLUMN "MODRED"."CID"."CID_TX_DESCRICAO" IS 'Descrição do CID';

UPDATE MODRED.CID C SET C. CID_TX_DESCRICAO = (SELECT CI.CIID_TX_DESCRICAO FROM CID_IDIOMA CI WHERE IDIO_ID = 1 AND CI.CID_ID = C.CID_ID);

COMMIT;

ALTER TABLE MODRED.CID  
MODIFY (CID_TX_DESCRICAO NOT NULL);

DROP TABLE MODRED.CID_IDIOMA CASCADE CONSTRAINTS;
DROP TABLE MODRED.IDIOMA CASCADE CONSTRAINTS;
DROP SYNONYM MODRED_APLICACAO.CID_IDIOMA;
DROP SYNONYM MODRED_APLICACAO.IDIOMA;

---JOB---
DROP TABLE MODRED.TEMP_SPLIT_VALOR_DNA;
DROP TABLE MODRED.TEMP_VALOR_DNA;

CREATE TABLE "MODRED"."VALOR_DNA" 
("LOCU_ID" VARCHAR2(4 BYTE) NOT NULL, 
"VADN_TX_VALOR" VARCHAR2(20 BYTE) NOT NULL, 
"VADN_TX_VALOR_G" VARCHAR2(20 BYTE), 
"VADN_TX_VALOR_P" VARCHAR2(20 BYTE)
);

COMMENT ON COLUMN "MODRED"."VALOR_DNA"."LOCU_ID" IS 'CHAVE ESTRANGEIRA RELACIONADA AO LOCUS';
COMMENT ON COLUMN "MODRED"."VALOR_DNA"."VADN_TX_VALOR" IS 'VALOR DNA';
COMMENT ON COLUMN "MODRED"."VALOR_DNA"."VADN_TX_VALOR_G" IS 'VALOR DE AGRUPAMENTO G';
COMMENT ON COLUMN "MODRED"."VALOR_DNA"."VADN_TX_VALOR_P" IS 'VALOR DE AGRUPAMENTO P';
COMMENT ON TABLE "MODRED"."VALOR_DNA"  IS 'TABELA DE VALORES DNA';

CREATE INDEX "MODRED"."IN_FK_VADN_LOCU" ON "MODRED"."VALOR_DNA" ("LOCU_ID");
  
GRANT SELECT ON MODRED.VALOR_DNA TO RMODRED_READ;