GRANT SELECT ON MODRED.GENOTIPO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.GENOTIPO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.TIPO_TAREFA TO RMODRED_READ;
GRANT SELECT ON MODRED.VALOR_SOROLOGICO TO RMODRED_READ;

-- Permissão de deleção na tabela de Genotipo
GRANT DELETE ON MODRED.GENOTIPO TO RMODRED_WRITE;

---JOB---
GRANT SELECT ON MODRED.VALOR_P TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.VALOR_P TO RMODRED_WRITE;
GRANT SELECT ON MODRED.VALOR_G TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.VALOR_G TO RMODRED_WRITE;
GRANT SELECT ON MODRED.TEMP_VALOR_G TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.TEMP_VALOR_G TO RMODRED_WRITE;
GRANT SELECT ON MODRED.TEMP_VALOR_P TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.TEMP_VALOR_P TO RMODRED_WRITE;
GRANT SELECT ON MODRED.VERSAO_ARQUIVO_BAIXADO TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.VERSAO_ARQUIVO_BAIXADO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_VEAB_ID TO RMODRED_WRITE;	 