-- HISTORIA 3 - CRIAÇÃO DA TABELA DE GENÓTIPO
DROP TABLE MODRED.GENOTIPO CASCADE CONSTRAINTS;
DROP SYNONYM MODRED_APLICACAO.GENOTIPO;
DROP INDEX IN_FK_GENO_LOEX;

DROP TABLE MODRED.VALOR_SOROLOGICO CASCADE CONSTRAINTS;
-- HISTORIA 3

-- HISTÓRIA 1
ALTER TABLE MODRED.TAREFA 
DROP COLUMN TARE_NR_RELACAO_ENTIDADE;

DROP INDEX IN_FK_TARE_USUA_ID_RESPONSAVEL;

ALTER TABLE MODRED.TAREFA 
DROP CONSTRAINT FK_TARE_USUA_ID_RESPONSAVEL;

ALTER TABLE MODRED.TAREFA 
ADD (MEDI_ID_RESPONSAVEL NUMBER );

COMMENT ON COLUMN MODRED.TAREFA.MEDI_ID_RESPONSAVEL IS 'Médico para o qual foi conferida esta tarefa, ou seja, trata-se do indivíduo responsável por executar a tarefa.';

ALTER TABLE MODRED.TAREFA ADD CONSTRAINT FK_TARE_MEDI_ID_RESPONSAVEL FOREIGN KEY (MEDI_ID_RESPONSAVEL) REFERENCES MODRED.MEDICO (MEDI_ID) ENABLE;
CREATE INDEX IN_FK_TARE_MEDI_ID_RESPONSAVEL ON MODRED.TAREFA (MEDI_ID_RESPONSAVEL ASC);

UPDATE MODRED.TAREFA T SET T.MEDI_ID_RESPONSAVEL = (SELECT M.MEDI_ID FROM MODRED.MEDICO M WHERE T.USUA_ID_RESPONSAVEL = M.USUA_ID);
COMMIT;

ALTER TABLE MODRED.TAREFA 
DROP COLUMN USUA_ID_RESPONSAVEL;


DROP INDEX IN_FK_TARE_TITA;

ALTER TABLE MODRED.TAREFA 
DROP CONSTRAINT FK_TARE_TITA;

ALTER TABLE MODRED.TAREFA RENAME COLUMN TITA_ID TO TARE_NR_TIPO;

COMMENT ON COLUMN MODRED.TAREFA.TARE_NR_TIPO IS 'Identificação do tipo de tarefa a ser executada no processo de negócio.';

DROP TABLE MODRED.TIPO_TAREFA;

-- HISTÓRIA 1

---JOB---
DROP TABLE MODRED.VALOR_G;
DROP TABLE TEMP_VALOR_G;
DROP TABLE MODRED.VALOR_P;
DROP TABLE TEMP_VALOR_P;

ALTER TABLE MODRED.VALOR_DNA_NMDP_VALIDO 
DROP COLUMN VADN_TX_NOME_GRUPO;