CREATE OR REPLACE SYNONYM MODRED_APLICACAO.GENOTIPO FOR MODRED.GENOTIPO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_TAREFA FOR MODRED.TIPO_TAREFA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_SOROLOGICO FOR MODRED.VALOR_SOROLOGICO;

---JOB---
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."VALOR_G" FOR "MODRED"."VALOR_G";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."VALOR_NMDP" FOR "MODRED"."VALOR_NMDP";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."VALOR_P" FOR "MODRED"."VALOR_P";
