GRANT SELECT ON "MODRED"."STATUS_BUSCA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."STATUS_BUSCA" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."BUSCA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."BUSCA" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_BUSC_ID" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."BUSCA_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."BUSCA_AUD" TO RMODRED_WRITE;

--Cancelamento de busca


GRANT SELECT ON "MODRED"."CANCELAMENTO_BUSCA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."CANCELAMENTO_BUSCA" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."MOTIVO_CANCELAMENTO_BUSCA" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."SQ_CABU_ID" TO RMODRED_READ;

-- Endereço contato
GRANT DELETE ON MODRED.CONTATO_TELEFONICO TO RMODRED_WRITE;