drop table MODRED.BUSCA;
drop table MODRED.STATUS_BUSCA;
drop sequence MODRED.SQ_BUSC_ID;

DELETE FROM "MODRED"."PERFIL" WHERE PERF_ID = 5;
DELETE FROM "MODRED"."USUARIO" WHERE USUA_ID = 5;
DELETE FROM "USUARIO_PERFIL" WHERE USUA_ID = AND  PERF_ID = 5;
COMMIT;


drop SYNONYM "MODRED_APLICACAO"."CANCELAMENTO_BUSCA";
drop sequence MODRED.SQ_CABU_ID;
drop table MODRED.CANCELAMENTO_BUSCA;
drop table MODRED.MOTIVO_CANCELAMENTO_BUSCA;
drop SYNONYM "MODRED_APLICACAO"."MOTIVO_CANCELAMENTO_BUSCA";

-- AVALIAÇÃO
ALTER TABLE MODRED.AVALIACAO DROP COLUMN AVAL_TX_MOTIVO_CANCELAMENTO;
-- e na tabela de auditoria
ALTER TABLE MODRED.AVALIACAO_AUD DROP COLUMN AVAL_TX_MOTIVO_CANCELAMENTO;
