CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."STATUS_BUSCA" FOR "MODRED"."STATUS_BUSCA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."BUSCA" FOR "MODRED"."BUSCA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_BUSC_ID" FOR "MODRED"."SQ_BUSC_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."BUSCA_AUD" FOR "MODRED"."BUSCA_AUD";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."CANCELAMENTO_BUSCA" FOR "MODRED"."CANCELAMENTO_BUSCA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_CABU_ID" FOR "MODRED"."SQ_CABU_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."MOTIVO_CANCELAMENTO_BUSCA" FOR "MODRED"."MOTIVO_CANCELAMENTO_BUSCA";
