-- PEDIDO CONTATO, TENTATIVA E RESPOSTA CONTATO
GRANT SELECT ON MODRED.SQ_RETC_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_TECD_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PECO_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.RESPOSTA_TENTATIVA_CONTATO TO RMODRED_READ;
GRANT SELECT ON MODRED.TENTATIVA_CONTATO_DOADOR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.TENTATIVA_CONTATO_DOADOR TO RMODRED_WRITE;

GRANT SELECT ON MODRED.PEDIDO_CONTATO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PEDIDO_CONTATO TO RMODRED_WRITE;


-- TABELA DE PEDIDO_CONTATO
GRANT SELECT ON "MODRED"."DOADOR" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."DOADOR" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."DOADOR_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."DOADOR_AUD" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_DOAD_NR_DMR" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."EMAIL_CONTATO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."EMAIL_CONTATO" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."EMAIL_CONTATO_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."EMAIL_CONTATO_AUD" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_EMCO_ID" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."STATUS_DOADOR" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."STATUS_DOADOR" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."MOTIVO_STATUS_DOADOR" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."MOTIVO_STATUS_DOADOR" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" TO RMODRED_READ;

GRANT SELECT ON "MODRED"."TIPO_SOLICITACAO" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."SOLICITACAO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."SOLICITACAO" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_SOLI_ID" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."PEDIDO_ENRIQUECIMENTO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PEDIDO_ENRIQUECIMENTO" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_PEEN_ID" TO RMODRED_WRITE;


GRANT SELECT ON MODRED.PEDIDO_EXAME TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PEDIDO_EXAME TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PEEX_ID TO RMODRED_WRITE;