alter table MODRED.tarefa 
drop column TARE_DT_INICIO,
drop column TARE_DT_FIM,
drop column  TARE_DT_HORA_INICIO, 
drop column  TARE_DT_HORA_FIM,
drop column  TARE_NR_INCLUSIVO_EXCLUSIVO;


DROP TABLE MODRED.TENTATIVA_CONTATO_DOADOR CASCADE CONSTRAINTS;
DROP SEQUENCE MODRED.SQ_TECD_ID;
DROP TABLE MODRED.RESPOSTA_TENTATIVA_CONTATO CASCADE CONSTRAINTS;
DROP SEQUENCE MODRED.SQ_RETC_ID;
DROP TABLE MODRED.PEDIDO_CONTATO CASCADE CONSTRAINTS;
DROP SEQUENCE MODRED.SQ_PECO_ID;


DROP TABLE MODRED.DOADOR_AUD;
DROP TABLE MODRED.EMAIL_CONTATO;
DROP TABLE MODRED.EMAIL_CONTATO_AUD;

DROP SEQUENCE MODRED.SQ_DOAD_NR_DMR;
DROP SEQUENCE MODRED.SQ_EMCO_ID;

DROP TABLE MODRED.MOTIVO_STATUS_DOADOR_RECURSO;
DROP SEQUENCE MODRED.SQ_SOLI_ID;
DROP TABLE MODRED.PEDIDO_ENRIQUECIMENTO;
DROP SEQUENCE MODRED.SQ_PEEN_ID;
DROP TABLE MODRED.SOLICITACAO;
DROP TABLE MODRED.TIPO_SOLICITACAO;

ALTER TABLE MODRED.CONTATO_TELEFONICO
    DROP CONSTRAINT FK_COTE_DOAD;
ALTER TABLE MODRED.CONTATO_TELEFONICO
    DROP COLUMN DOAD_NR_DMR; 
ALTER TABLE MODRED.CONTATO_TELEFONICO_AUD
drop column DOAD_NR_DMR;

ALTER TABLE MODRED.ENDERECO_CONTATO
    DROP CONSTRAINT FK_ENCO_DOAD;
ALTER TABLE MODRED.ENDERECO_CONTATO
    DROP COLUMN DOAD_NR_DMR;    

DROP TABLE MODRED.DOADOR;
DROP TABLE MODRED.MOTIVO_STATUS_DOADOR;
DROP TABLE MODRED.STATUS_DOADOR;

ALTER TABLE MODRED.PACIENTE
ADD (ENCO_ID NUMBER );

UPDATE MODRED.PACIENTE SET ENCO_ID = (SELECT E.ENCO_ID FROM MODRED.ENDERECO_CONTATO E WHERE E.PACI_NR_RMR = PACI_NR_RMR);
COMMIT;

ALTER TABLE MODRED.PACIENTE_AUD
ADD (ENCO_ID NUMBER );

UPDATE MODRED.PACIENTE_AUD SET ENCO_ID = (SELECT E.ENCO_ID FROM MODRED.ENDERECO_CONTATO E WHERE E.PACI_NR_RMR = PACI_NR_RMR);
COMMIT;

ALTER TABLE MODRED.ENDERECO_CONTATO
    DROP CONSTRAINT FK_ENCO_PACI;
    
ALTER TABLE MODRED.ENDERECO_CONTATO
    DROP COLUMN PACI_NR_RMR;    
    
ALTER TABLE MODRED.ENDERECO_CONTATO_AUD
    DROP COLUMN PACI_NR_RMR;    

ALTER TABLE MODRED.ENDERECO_CONTATO
DROP COLUMN ENCO_FL_EXCLUIDO;

ALTER TABLE MODRED.ENDERECO_CONTATO_AUD
DROP COLUMN ENCO_FL_EXCLUIDO;
    
ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_ENCO FOREIGN KEY
(
  ENCO_ID 
)
REFERENCES MODRED.ENDERECO_CONTATO
(
  ENCO_ID
)
ENABLE;
    
ALTER TABLE MODRED.CONTATO_TELEFONICO
DROP COLUMN COTE_FL_EXCLUIDO;
    
ALTER TABLE MODRED.CONTATO_TELEFONICO_AUD
DROP COLUMN COTE_FL_EXCLUIDO;

ALTER TABLE MODRED.CONTATO_TELEFONICO  
MODIFY (PACI_NR_RMR NOT NULL);

DROP TABLE MODRED.PEDIDO_EXAME CASCADE CONSTRAINTS;
DROP SEQUENCE MODRED.SQ_PEEX_ID;
