-- TENTATIVA E RESPOSTA CONTATO
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_TECD_ID FOR MODRED.SQ_TECD_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TENTATIVA_CONTATO_DOADOR FOR MODRED.TENTATIVA_CONTATO_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_RETC_ID FOR MODRED.SQ_RETC_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESPOSTA_TENTATIVA_CONTATO FOR MODRED.RESPOSTA_TENTATIVA_CONTATO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PECO_ID FOR MODRED.SQ_PECO_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_CONTATO FOR MODRED.PEDIDO_CONTATO;

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."DOADOR" FOR "MODRED"."DOADOR";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."DOADOR_AUD" FOR "MODRED"."DOADOR_AUD";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_DOAD_NR_DMR" FOR "MODRED"."SQ_DOAD_NR_DMR";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."EMAIL_CONTATO" FOR "MODRED"."EMAIL_CONTATO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_EMCO_ID" FOR "MODRED"."SQ_EMCO_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."EMAIL_CONTATO_AUD" FOR "MODRED"."EMAIL_CONTATO_AUD";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."STATUS_DOADOR" FOR "MODRED"."STATUS_DOADOR";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."MOTIVO_STATUS_DOADOR" FOR "MODRED"."MOTIVO_STATUS_DOADOR";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."MOTIVO_STATUS_DOADOR_RECURSO" FOR "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."TIPO_SOLICITACAO" FOR "MODRED"."TIPO_SOLICITACAO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SOLICITACAO" FOR "MODRED"."SOLICITACAO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_SOLI_ID" FOR "MODRED"."SQ_SOLI_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."PEDIDO_ENRIQUECIMENTO" FOR "MODRED"."PEDIDO_ENRIQUECIMENTO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_PEEN_ID" FOR "MODRED"."SQ_PEEN_ID";
