GRANT SELECT ON MODRED.RESSALVA_DOADOR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.RESSALVA_DOADOR TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_REDO_ID TO RMODRED_WRITE;

/* formulário */
GRANT SELECT ON MODRED.SQ_FORM_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_FODO_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_REFD_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.RESPOSTA_FORMULARIO_DOADOR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.RESPOSTA_FORMULARIO_DOADOR TO RMODRED_WRITE;

GRANT SELECT ON MODRED.FORMULARIO_DOADOR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.FORMULARIO_DOADOR TO RMODRED_WRITE;

GRANT SELECT ON MODRED.FORMULARIO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.FORMULARIO TO RMODRED_WRITE;

GRANT SELECT ON MODRED.TIPO_FORMULARIO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.TIPO_FORMULARIO TO RMODRED_WRITE;
/* fim formulário*/
GRANT SELECT ON MODRED.TURNO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.TURNO TO RMODRED_WRITE;

GRANT SELECT ON MODRED.RESSALVA_DOADOR_AUD TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.RESSALVA_DOADOR_AUD TO RMODRED_WRITE;
GRANT DELETE ON MODRED.RESSALVA_DOADOR TO RMODRED_READ;
