CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_REDO_ID FOR MODRED.SQ_REDO_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESSALVA_DOADOR FOR MODRED.RESSALVA_DOADOR;

/* formulário */
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_FORM_ID FOR MODRED.SQ_FORM_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_FODO_ID FOR MODRED.SQ_FODO_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_REFD_ID FOR MODRED.SQ_REFD_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESPOSTA_FORMULARIO_DOADOR FOR MODRED.RESPOSTA_FORMULARIO_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.FORMULARIO_DOADOR FOR MODRED.FORMULARIO_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.FORMULARIO FOR MODRED.FORMULARIO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_FORMULARIO FOR MODRED.TIPO_FORMULARIO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TURNO FOR MODRED.TURNO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESSALVA_DOADOR_AUD FOR MODRED.RESSALVA_DOADOR_AUD;

/* fim formulário */
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PEEX_ID FOR MODRED.SQ_PEEX_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_EXAME FOR MODRED.PEDIDO_EXAME;
