-- HISTORIA 2
DROP TABLE MODRED.HEMO_ENTIDADE CASCADE CONSTRAINTS;
DROP SEQUENCE MODRED.SQ_HEEN_ID;
COMMIT;
DROP SYNONYM MODRED_APLICACAO.PRESCRICAO;
DROP SYNONYM MODRED_APLICACAO.PEDIDO_WORKUP;

DROP TABLE MODRED.PRESCRICAO;
DROP SYNONYM MODRED.PEDIDO_WORKUP;

DROP SEQUENCE SQ_PEWO_ID;COMMIT;

-- DROPANDO A COLUNA ASSOCIATIVA ENTRE PEDIDO DE CONTATO E HEMO ENTIDADE.
ALTER TABLE MODRED.PEDIDO_CONTATO
DROP COLUMN HEEN_ID CASCADE CONSTRAINTS;
COMMIT;

ALTER TABLE MODRED.PEDIDO_CONTATO_AUD
DROP COLUMN HEEN_ID CASCADE CONSTRAINTS;
COMMIT;


-- HISTORIA 2 - ASSOCIAÇÃO ENTRE HEMOENTIDADE E ENDERECO_CONTATO
ALTER TABLE MODRED.HEMO_ENTIDADE
DROP COLUMN ENCO_ID CASCADE CONSTRAINTS;
COMMIT;

ALTER TABLE MODRED.ENDERECO_CONTATO
DROP COLUMN HEEN_ID CASCADE CONSTRAINTS;
COMMIT;

ALTER TABLE MODRED.PEDIDO_WORKUP
DROP COLUMN STPW_ID CASCADE CONSTRAINTS;

ALTER TABLE MODRED.PEDIDO_WORKUP
DROP COLUMN MOCW_ID CASCADE CONSTRAINTS;
--Inicio scripts -Queiroz 21/12/2017 12:00
drop table modred.DISPONIBILIDADE;
drop table modred.STATUS_PEDIDO_WORKUP;
drop table modred.MOTIVO_CANCELAMENTO_WORKUP;
drop table modred.INFO_PREVIA;

drop sequence MODRED.SQ_DISP_ID;
drop sequence MODRED.SQ_INPR_ID;

DROP SYNONYM MODRED_APLICACAO.SQ_DISP_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_INPR_ID;
DROP SYNONYM MODRED_APLICACAO.DISPONIBILIDADE;
DROP SYNONYM MODRED_APLICACAO.STATUS_PEDIDO_WORKUP;
DROP SYNONYM MODRED_APLICACAO.MOTIVO_CANCELAMENTO_WORKUP;
DROP SYNONYM MODRED_APLICACAO.INFO_PREVIA;
COMMIT;
--Fim scripts -Queiroz 21/12/2017 12:00

-- HISTORIA 2 - USUARIO DE CONTATO FASE 3
DELETE FROM MODRED.USUARIO_PERFIL
WHERE USUA_ID = 8 AND PERF_ID = 8;
DELETE FROM MODRED.USUARIO
WHERE USUA_ID = 8;
COMMIT;

-- INSERINDO AS PERMISSÕES PARA O ANALISTA DE CONTATO FASE 3.
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 31 AND PERF_ID = 8;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 23 AND PERF_ID = 8;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 34 AND PERF_ID = 8;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 27 AND PERF_ID = 8;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 8 AND PERF_ID = 8;--Fim scripts -Queiroz 21/12/2017 12:00


--Funções do centro de transplante Queiroz 21/12/2017 10:19
drop table MODRED.FUNCAO_CENTRO_TRANSPLANTE ;
drop table MODRED.FUNCAO_TRANSPLANTE;
DROP SYNONYM MODRED_APLICACAO.FUNCAO_TRANSPLANTE;
DROP SYNONYM MODRED_APLICACAO.FUNCAO_CENTRO_TRANSPLANTE;
--Fim scripts -Queiroz 21/12/2017 10:19

--Script de tipo de tarefa para follow up de workup Queiroz 26/12/2017
DELETE FROM MODRED.TAREFA WHERE TITA_ID = 31;
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 31;
COMMIT;
--Fim Script de tipo de tarefa para follow up de workup Queiroz 26/12/2017

-- REMOVENDO QUESTIONÁRIO DE FASE 3.
DELETE FROM MODRED.RESPOSTA_FORMULARIO_DOADOR WHERE FODO_ID IN (SELECT FODO_ID FROM FORMULARIO_DOADOR WHERE FORM_ID = 2);
DELETE FROM MODRED.FORMULARIO_DOADOR WHERE FORM_ID = 2;
DELETE FROM MODRED.FORMULARIO WHERE FORM_ID = 2;
COMMIT;