-- HISTORIA 2
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_HEEN_ID FOR MODRED.SQ_HEEN_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.HEMO_ENTIDADE FOR MODRED.HEMO_ENTIDADE;
COMMIT;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PRESCRICAO FOR MODRED.PRESCRICAO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_WORKUP FOR MODRED.PEDIDO_WORKUP;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PEWO_ID FOR MODRED.SQ_PEWO_ID;

--Inicio scripts -Queiroz 21/12/2017 12:00
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_DISP_ID FOR MODRED.SQ_DISP_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_INPR_ID FOR MODRED.SQ_INPR_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DISPONIBILIDADE FOR MODRED.DISPONIBILIDADE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_PEDIDO_WORKUP FOR MODRED.STATUS_PEDIDO_WORKUP;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.MOTIVO_CANCELAMENTO_WORKUP FOR MODRED.MOTIVO_CANCELAMENTO_WORKUP;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.INFO_PREVIA FOR MODRED.INFO_PREVIA;
COMMIT;
--Fim scripts -Queiroz 21/12/2017 12:00

--Alterando tabela de centro_transplante para ser um centro generico com diversos papeis Queiroz 21/12/2017 14:30
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.FUNCAO_TRANSPLANTE FOR MODRED.FUNCAO_TRANSPLANTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.FUNCAO_CENTRO_TRANSPLANTE FOR MODRED.FUNCAO_CENTRO_TRANSPLANTE;
--Fim scripts -Queiroz 21/12/2017 14:30