--Ajustes nos scripts da sprint passada Cintia 03/01
GRANT SELECT ON MODRED.SQ_DICC_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."DISPONIBILIDADE_CENTRO_COLETA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."DISPONIBILIDADE_CENTRO_COLETA" TO RMODRED_WRITE;

--Adicionando auditoria nas tabelas DISPONIBILIDADE e PEDIDO_WORKUP Cintia 05/01
GRANT SELECT ON "MODRED"."DISPONIBILIDADE_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."DISPONIBILIDADE_AUD" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."PEDIDO_WORKUP_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PEDIDO_WORKUP_AUD" TO RMODRED_WRITE;