--Ajustes nos scripts da sprint passada Cintia 03/01
DROP SYNONYM MODRED_APLICACAO.SQ_INPR_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_DICC_ID FOR MODRED.SQ_DICC_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DISPONIBILIDADE_CENTRO_COLETA FOR MODRED.DISPONIBILIDADE_CENTRO_COLETA;

--Adicionando auditoria nas tabelas DISPONIBILIDADE e PEDIDO_WORKUP Cintia 05/01
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DISPONIBILIDADE_AUD FOR MODRED.DISPONIBILIDADE_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_WORKUP_AUD FOR MODRED.PEDIDO_WORKUP_AUD;