--Script para armazenar o resultado de workup CINTIA 16/01
GRANT SELECT ON MODRED.SQ_REWO_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."RESULTADO_WORKUP" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."RESULTADO_WORKUP" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."RESULTADO_WORKUP_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."RESULTADO_WORKUP_AUD" TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_ARRW_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."ARQUIVO_RESULTADO_WORKUP" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."ARQUIVO_RESULTADO_WORKUP" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."ARQUIVO_RESULTADO_WORKUP_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."ARQUIVO_RESULTADO_WORKUP_AUD" TO RMODRED_WRITE;
--FIM

--Script para a funcionalidade de cadastrar resultado de workup Cintia 16/01
GRANT SELECT ON "MODRED"."USUARIO_CENTRO_TRANSPLANTE" TO RMODRED_READ;
GRANT INSERT ON "MODRED"."USUARIO_CENTRO_TRANSPLANTE" TO RMODRED_WRITE;
--FIM

--Script para armazenar os pedidos de logistica do pedido de workup Cintia 17/01
GRANT SELECT ON MODRED.SQ_PELO_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_TRTE_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."TIPO_PEDIDO_LOGISTICA" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."STATUS_PEDIDO_LOGISTICA" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."PEDIDO_LOGISTICA" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."ARQUIVO_VOUCHER_LOGISTICA" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."TRANSPORTE_TERRESTRE" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PEDIDO_LOGISTICA" TO RMODRED_WRITE;
GRANT INSERT, UPDATE ON "MODRED"."ARQUIVO_VOUCHER_LOGISTICA" TO RMODRED_WRITE;
GRANT INSERT, UPDATE ON "MODRED"."TRANSPORTE_TERRESTRE" TO RMODRED_WRITE;
--FIM

--Auditoria para pedido de logistica
-- PEDIDO_LOGISTICA_AUDITORIA
GRANT SELECT ON "MODRED"."PEDIDO_LOGISTICA_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PEDIDO_LOGISTICA_AUD" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."ARQUIVO_VOUCHER_LOGISTICA_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."ARQUIVO_VOUCHER_LOGISTICA_AUD" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."TRANSPORTE_TERRESTRE_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."TRANSPORTE_TERRESTRE_AUD" TO RMODRED_WRITE;
--FIM

-- Script para avaliação de resultado de workup Cintia 23/01
GRANT SELECT ON "MODRED"."AVALIACAO_RESULTADO_WORKUP" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."AVALIACAO_RESULTADO_WORKUP" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."PEDIDO_ADICIONAL_WORKUP" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PEDIDO_ADICIONAL_WORKUP" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."RESPOSTA_PEDIDO_ADICIONAL" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."RESPOSTA_PEDIDO_ADICIONAL" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."PEDIDO_COLETA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PEDIDO_COLETA" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."STATUS_PEDIDO_COLETA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."STATUS_PEDIDO_COLETA" TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_AVRW_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PEAW_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_REPA_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PECL_ID TO RMODRED_WRITE;

--FIM

GRANT SELECT ON MODRED.SQ_ARVL_ID TO RMODRED_WRITE;
