--Script para armazenar o resultado de workup CINTIA 16/01
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_REWO_ID" FOR "MODRED"."SQ_REWO_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."RESULTADO_WORKUP" FOR "MODRED"."RESULTADO_WORKUP";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."RESULTADO_WORKUP_AUD" FOR "MODRED"."RESULTADO_WORKUP_AUD";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_ARRW_ID" FOR "MODRED"."SQ_ARRW_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."ARQUIVO_RESULTADO_WORKUP" FOR "MODRED"."ARQUIVO_RESULTADO_WORKUP";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."ARQUIVO_RESULTADO_WORKUP_AUD" FOR "MODRED"."ARQUIVO_RESULTADO_WORKUP_AUD";
--FIM

--Script para a funcionalidade de cadastrar resultado de workup Cintia 16/01
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."USUARIO_CENTRO_TRANSPLANTE" FOR "MODRED"."USUARIO_CENTRO_TRANSPLANTE";
--FIM

--Script para armazenar os pedidos de logistica do pedido de workup Cintia 17/01
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_PELO_ID" FOR "MODRED"."SQ_PELO_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_TRTE_ID" FOR "MODRED"."SQ_TRTE_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."TIPO_PEDIDO_LOGISTICA" FOR "MODRED"."TIPO_PEDIDO_LOGISTICA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."STATUS_PEDIDO_LOGISTICA" FOR "MODRED"."STATUS_PEDIDO_LOGISTICA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."PEDIDO_LOGISTICA" FOR "MODRED"."PEDIDO_LOGISTICA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."ARQUIVO_VOUCHER_LOGISTICA" FOR "MODRED"."ARQUIVO_VOUCHER_LOGISTICA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."TRANSPORTE_TERRESTRE" FOR "MODRED"."TRANSPORTE_TERRESTRE";
--FIM

--Auditoria para pedido de logistica
--PEDIDO_LOGISTICA_AUDITORIA
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."PEDIDO_LOGISTICA_AUD" FOR "MODRED"."PEDIDO_LOGISTICA_AUD";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."ARQUIVO_VOUCHER_LOGISTICA_AUD" FOR "MODRED"."ARQUIVO_VOUCHER_LOGISTICA_AUD";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."TRANSPORTE_TERRESTRE_AUD" FOR "MODRED"."TRANSPORTE_TERRESTRE_AUD";
--FIM

-- Script para avaliação de resultado de workup Cintia 23/01
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."AVALIACAO_RESULTADO_WORKUP" FOR "MODRED"."AVALIACAO_RESULTADO_WORKUP";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."PEDIDO_ADICIONAL_WORKUP" FOR "MODRED"."PEDIDO_ADICIONAL_WORKUP";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."RESPOSTA_PEDIDO_ADICIONAL" FOR "MODRED"."RESPOSTA_PEDIDO_ADICIONAL";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."PEDIDO_COLETA" FOR "MODRED"."PEDIDO_COLETA";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."STATUS_PEDIDO_COLETA" FOR "MODRED"."STATUS_PEDIDO_COLETA";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_AVRW_ID" FOR "MODRED"."SQ_AVRW_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_PEAW_ID" FOR "MODRED"."SQ_PEAW_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_REPA_ID" FOR "MODRED"."SQ_REPA_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_PECL_ID" FOR "MODRED"."SQ_PECL_ID";
--FIM

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_ARVL_ID" FOR "MODRED"."SQ_ARVL_ID";
