--Scripts para agendamento de pedido de coleta Cintia 30/01
GRANT SELECT ON "MODRED"."FONTE_CELULAS" TO RMODRED_READ;
--FIM

--Script para armazenar a avaliação ao pedido de coleta CINTIA 06/02
GRANT SELECT ON MODRED.SQ_AVPC_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."AVALIACAO_PEDIDO_COLETA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."AVALIACAO_PEDIDO_COLETA" TO RMODRED_WRITE;
--FIM