--Scripts para agendamento de pedido de coleta Cintia 30/01
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.FONTE_CELULAS FOR MODRED.FONTE_CELULAS;
--FIM

--Script para armazenar a avaliação ao pedido de coleta CINTIA 06/02
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_AVPC_ID" FOR "MODRED"."SQ_AVPC_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."AVALIACAO_PEDIDO_COLETA" FOR "MODRED"."AVALIACAO_PEDIDO_COLETA";
--FIM