--Alteração na tabela de RESSALVA_DOADOR
DROP INDEX IN_FK_REDO_USUA;

ALTER TABLE MODRED.RESSALVA_DOADOR 
DROP COLUMN REDO_DT_CRIACAO;

ALTER TABLE MODRED.RESSALVA_DOADOR 
DROP COLUMN USUA_ID_CRIACAO CASCADE CONSTRAINTS;

ALTER TABLE MODRED.RESSALVA_DOADOR 
DROP COLUMN REDO_IN_EXCLUIDO;

ALTER TABLE MODRED.RESSALVA_DOADOR_AUD 
DROP COLUMN REDO_DT_CRIACAO;

ALTER TABLE MODRED.RESSALVA_DOADOR_AUD 
DROP COLUMN USUA_ID_CRIACAO;

ALTER TABLE MODRED.RESSALVA_DOADOR_AUD 
DROP COLUMN REDO_IN_EXCLUIDO;
--FIM

--Script para armazenar a avaliação de workup do doador
drop table "MODRED"."AVALIACAO_WORKUP_DOADOR" cascade constraints PURGE;
DROP SYNONYM MODRED_APLICACAO.AVALIACAO_WORKUP_DOADOR;

DELETE FROM MODRED.PERMISSAO WHERE RECU_ID=53;
DELETE FROM MODRED.RECURSO WHERE RECU_ID=53;
DELETE FROM MODRED.MOTIVO_STATUS_DOADOR_RECURSO WHERE RECU_ID=53;

DELETE FROM MODRED.MOTIVO_STATUS_DOADOR WHERE MOSD_ID=7;
DELETE FROM MODRED.MOTIVO_STATUS_DOADOR WHERE MOSD_ID=8;
COMMIT;
--FIM

--criação de recursos para adicionar e remover ressalvas
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID=54 OR RECU_ID=55;
DELETE FROM MODRED.RECURSO WHERE RECU_ID=54 OR RECU_ID=55;
COMMIT;
--FIM