--Alteração na tabela de RESSALVA_DOADOR
ALTER TABLE MODRED.RESSALVA_DOADOR 
ADD (REDO_DT_CRIACAO DATE );

ALTER TABLE MODRED.RESSALVA_DOADOR 
ADD (USUA_ID_CRIACAO NUMBER);

ALTER TABLE MODRED.RESSALVA_DOADOR 
ADD (REDO_IN_EXCLUIDO NUMBER(1) DEFAULT 0 NOT NULL);

ALTER TABLE MODRED.RESSALVA_DOADOR_AUD 
ADD (REDO_DT_CRIACAO DATE );

ALTER TABLE MODRED.RESSALVA_DOADOR_AUD 
ADD (USUA_ID_CRIACAO NUMBER);

ALTER TABLE MODRED.RESSALVA_DOADOR_AUD 
ADD (REDO_IN_EXCLUIDO NUMBER(1));

COMMENT ON COLUMN MODRED.RESSALVA_DOADOR.REDO_DT_CRIACAO IS 'Data em que a ressalva foi criada.';
COMMENT ON COLUMN MODRED.RESSALVA_DOADOR.USUA_ID_CRIACAO IS 'Usuário responsável pela adição da ressalva.';
COMMENT ON COLUMN MODRED.RESSALVA_DOADOR.REDO_IN_EXCLUIDO IS 'Indicador que a ressalva foi excluída. 1-Sim, 0-Não.';

UPDATE MODRED.RESSALVA_DOADOR SET REDO_DT_CRIACAO=SYSDATE, USUA_ID_CRIACAO=13;
UPDATE MODRED.RESSALVA_DOADOR_AUD SET REDO_DT_CRIACAO=SYSDATE, USUA_ID_CRIACAO=13;
COMMIT;

ALTER TABLE MODRED.RESSALVA_DOADOR 
MODIFY (REDO_DT_CRIACAO DATE NOT NULL);

ALTER TABLE MODRED.RESSALVA_DOADOR 
MODIFY (USUA_ID_CRIACAO NUMBER NOT NULL);

CREATE INDEX IN_FK_REDO_USUA ON MODRED.RESSALVA_DOADOR (USUA_ID_CRIACAO ASC);

ALTER TABLE MODRED.RESSALVA_DOADOR
ADD CONSTRAINT FK_REDO_USUA FOREIGN KEY
(
  USUA_ID_CRIACAO 
)
REFERENCES MODRED.USUARIO
(
  USUA_ID 
)
ENABLE;

DROP INDEX IN_FK_REDO_DOAD;

CREATE INDEX IN_FK_REDO_DOAD ON MODRED.RESSALVA_DOADOR (DOAD_NR_DMR ASC);
--FIM

--CRIANDO TABELA AVALIACAO_WORKUP_DOADOR
CREATE TABLE MODRED.AVALIACAO_WORKUP_DOADOR 
(
  AVWD_ID NUMBER NOT NULL 
, REWO_ID NUMBER NOT NULL 
, AVWD_DT_CRIACAO TIMESTAMP NOT NULL 
, AVWD_DT_CONCLUSAO TIMESTAMP 
, USUA_ID_RESPONSAVEL NUMBER 
, AVWD_NR_RESULTADO NUMBER(1) 
, CONSTRAINT PK_AVWD PRIMARY KEY 
  (
    AVWD_ID 
  )
  ENABLE 
);

CREATE INDEX IN_FK_AVWD_USUA ON MODRED.AVALIACAO_WORKUP_DOADOR (USUA_ID_RESPONSAVEL ASC);
CREATE INDEX IN_FK_AVWD_REWO ON MODRED.AVALIACAO_WORKUP_DOADOR (REWO_ID ASC);

ALTER TABLE MODRED.AVALIACAO_WORKUP_DOADOR
ADD CONSTRAINT FK_AVWD_USUA FOREIGN KEY
(
  USUA_ID_RESPONSAVEL 
)
REFERENCES MODRED.USUARIO
(
  USUA_ID 
)
ENABLE;

ALTER TABLE MODRED.AVALIACAO_WORKUP_DOADOR
ADD CONSTRAINT FK_AVWD_REWO FOREIGN KEY
(
  REWO_ID 
)
REFERENCES MODRED.RESULTADO_WORKUP
(
  REWO_ID 
)
ENABLE;

COMMENT ON TABLE MODRED.AVALIACAO_WORKUP_DOADOR IS 'Tabela responsável por armazenar as avaliações de workup dos doadores.';

COMMENT ON COLUMN MODRED.AVALIACAO_WORKUP_DOADOR.AVWD_ID IS 'Identificador da avaliação de workup do doador.';

COMMENT ON COLUMN MODRED.AVALIACAO_WORKUP_DOADOR.REWO_ID IS 'Identificador do resultado de workup do doador.';

COMMENT ON COLUMN MODRED.AVALIACAO_WORKUP_DOADOR.AVWD_DT_CRIACAO IS 'Data de criação da avaliação.';

COMMENT ON COLUMN MODRED.AVALIACAO_WORKUP_DOADOR.AVWD_DT_CONCLUSAO IS 'Data de conclusao.';

COMMENT ON COLUMN MODRED.AVALIACAO_WORKUP_DOADOR.USUA_ID_RESPONSAVEL IS 'Usuário responsável que efetuou a avaliação.';

COMMENT ON COLUMN MODRED.AVALIACAO_WORKUP_DOADOR.AVWD_NR_RESULTADO IS 'Indica o resultado da avaliação. 0-Nada, 1-Inativou doador, 2-Alterou ressalvas.';

--sequence
CREATE SEQUENCE MODRED.SQ_AVWD_ID INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

--criação de recurso
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (53,'AVALIAR_WORKUP_DOADOR','Permite avaliar o workup de um doador.');
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (53,13,0);

INSERT INTO MODRED.MOTIVO_STATUS_DOADOR VALUES (7, 'Doente - Impedido Permanentemente', 4);
INSERT INTO MODRED.MOTIVO_STATUS_DOADOR VALUES (8, 'Doente - Impedido Temporariamente', 3);

INSERT INTO "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" (MOSD_ID, RECU_ID) VALUES ('3', '53');
INSERT INTO "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" (MOSD_ID, RECU_ID) VALUES ('7', '53');
INSERT INTO "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" (MOSD_ID, RECU_ID) VALUES ('8', '53');
commit;
--FIM

--criação de recursos para adicionar e remover ressalvas
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (54,'ADICIONAR_RESSALVA_DOADOR','Permite adicionar ressalva para um doador.');
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (55,'EXCLUIR_RESSALVA_DOADOR','Permite excluir ressalva de um doador.');
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (54,13,0);
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (55,13,0);
commit;
--FIM

--Acesso ao cabeçalho de doador para o medico_redome
insert into modred.permissao (recu_id, perf_id, perm_in_com_restricao) values (44,13,0);
commit;
--Fim

--PERMISSÃO PARA MEDICO REDOME VISUALIZAR A IDENTIFICAÇÃO DO PACIENTE
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID) VALUES ('8', '13');
commit;
--Fim


--Alterando recurso de inativar
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (56,'INATIVAR_DOADOR_AVALIACAO_WORKUP','Permite inativar o doador na avaliação.');
INSERT INTO "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" (MOSD_ID, RECU_ID) VALUES ('3', '56');
INSERT INTO "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" (MOSD_ID, RECU_ID) VALUES ('7', '56');
INSERT INTO "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" (MOSD_ID, RECU_ID) VALUES ('8', '56');

delete from "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" where MOSD_ID = 3 and RECU_ID = 53;
delete from "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" where MOSD_ID = 7 and RECU_ID = 53;
delete from "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" where MOSD_ID = 8 and RECU_ID = 53;
insert into "MODRED"."PERMISSAO" (PERF_ID,PERM_IN_COM_RESTRICAO,RECU_ID) VALUES (13,0,56);
commit;
--FIM

--Adicionando tempo de execução nos tipos de tarefas 
UPDATE "MODRED"."TIPO_TAREFA" SET TITA_NR_TEMPO_EXECUCAO = '3600' WHERE tita_id=37;
UPDATE "MODRED"."TIPO_TAREFA" SET TITA_NR_TEMPO_EXECUCAO = '3600' WHERE tita_id=38;
commit;
--FIM

--Removendo coluna da tabela AVALIACAO_WORKUP_DOADOR
ALTER TABLE MODRED.AVALIACAO_WORKUP_DOADOR 
DROP COLUMN AVWD_NR_RESULTADO;
--FIM