--Script para armazenar a avaliação de workup do doador
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_AVWD_ID" FOR "MODRED"."SQ_AVWD_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."AVALIACAO_WORKUP_DOADOR" FOR "MODRED"."AVALIACAO_WORKUP_DOADOR";
--FIM