--Grants
GRANT SELECT ON MODRED.SQ_MATC_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."MATCH" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."MATCH" TO RMODRED_WRITE;


GRANT SELECT ON MODRED.SQ_EVBU_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."EVOLUCAO_BUSCA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."EVOLUCAO_BUSCA" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."LABORATORIO" TO RMODRED_READ;


GRANT SELECT ON MODRED.SQ_COMA_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."COMENTARIO_MATCH" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."COMENTARIO_MATCH" TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_QUMA_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."QUALIFICACAO_MATCH" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."QUALIFICACAO_MATCH" TO RMODRED_WRITE;
COMMIT;


--valor genotipo
GRANT SELECT ON MODRED.SQ_VAGE_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."VALOR_GENOTIPO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."VALOR_GENOTIPO" TO RMODRED_WRITE;


--GENOTIPO
GRANT SELECT ON MODRED.SQ_GENO_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."GENOTIPO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."GENOTIPO" TO RMODRED_WRITE;

--GENOTIPO BUSCA

GRANT SELECT ON MODRED.SQ_VAGB_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."VALOR_GENOTIPO_BUSCA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."VALOR_GENOTIPO_BUSCA" TO RMODRED_WRITE;

--GENOTIPO EXPANDIDO 

GRANT SELECT ON MODRED.SQ_VGEE_ID TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."VALOR_GENOTIPO_EXPANDIDO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."VALOR_GENOTIPO_EXPANDIDO" TO RMODRED_WRITE;

--BUG#2474
GRANT INSERT, UPDATE, DELETE ON MODRED.LOCUS_EXAME TO RMODRED_WRITE;