
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_MATC_ID" FOR "MODRED"."SQ_MATC_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."MATCH" FOR "MODRED"."MATCH";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_EVBU_ID" FOR "MODRED"."SQ_EVBU_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."EVOLUCAO_BUSCA" FOR "MODRED"."EVOLUCAO_BUSCA";


CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_COMA_ID" FOR "MODRED"."SQ_COMA_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."COMENTARIO_MATCH" FOR "MODRED"."COMENTARIO_MATCH";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_QUMA_ID" FOR "MODRED"."SQ_QUMA_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."QUALIFICACAO_MATCH" FOR "MODRED"."QUALIFICACAO_MATCH";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."LABORATORIO" FOR "MODRED"."LABORATORIO";



COMMIT;



CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_VAGE_ID" FOR "MODRED"."SQ_VAGE_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."VALOR_GENOTIPO" FOR "MODRED"."VALOR_GENOTIPO";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_GENO_ID" FOR "MODRED"."SQ_GENO_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."GENOTIPO" FOR "MODRED"."GENOTIPO";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_VAGB_ID" FOR "MODRED"."SQ_VAGB_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."VALOR_GENOTIPO_BUSCA" FOR "MODRED"."VALOR_GENOTIPO_BUSCA";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_VGEE_ID" FOR "MODRED"."SQ_VGEE_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."VALOR_GENOTIPO_EXPANDIDO" FOR "MODRED"."VALOR_GENOTIPO_EXPANDIDO";


CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."LABORATORIO" FOR "MODRED"."LABORATORIO";