
--ESTÓRIA 5

GRANT SELECT ON MODRED.SQ_PRES_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_ARPR_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.ARQUIVO_PRESCRICAO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.ARQUIVO_PRESCRICAO TO RMODRED_WRITE;
