ALTER TABLE MODRED.QUALIFICACAO_MATCH 
DROP CONSTRAINT FK_QUMA_DOAD;
DROP SEQUENCE MODRED.SQ_ARPR_ID;
DROP INDEX MODRED.IN_FK_ARPR_PRES;
DROP TABLE MODRED.ARQUIVO_PRESCRICAO;

ALTER TABLE MODRED.QUALIFICACAO_MATCH 
DROP COLUMN DOAD_NR_DMR;

ALTER TABLE MODRED.QUALIFICACAO_MATCH 
DROP COLUMN QUMA_TX_GENOTIPO;
ALTER TABLE MODRED.PRESCRICAO 
DROP CONSTRAINT PK_PRES;

DELETE FROM "MODRED"."CONFIGURACAO" WHERE CONF_ID = 'quantidadeFavoritosAvaliacaoMatch';

DROP INDEX MODRED.IN_FK_PRES_SOLI;

ALTER TABLE MODRED.GENOTIPO 
DROP COLUMN GENO_IN_EXCLUIDO;

COMMIT;
ALTER TABLE MODRED.PRESCRICAO
ADD CONSTRAINT PK_PRES PRIMARY KEY 
(
  SOLI_ID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX MODRED.PK_PRES ON PRESCRICAO (SOLI_ID ASC) 
)
 ENABLE;
 
DROP SEQUENCE MODRED.SQ_PRES_ID;
 
ALTER TABLE MODRED.PRESCRICAO 
DROP COLUMN PRES_VL_QUANTIDADE_TCN_CD34;

ALTER TABLE MODRED.PRESCRICAO 
DROP COLUMN PRES_ID;

ALTER TABLE MODRED.PRESCRICAO  
MODIFY (SOLI_ID NOT NULL);

DELETE FROM MODRED.CONFIGURACAO WHERE CONF_ID = 'quantidadeMaximaArquivosPrescricao';
DELETE FROM MODRED.CONFIGURACAO WHERE CONF_ID = 'tamanhoArquivoPrescricaoEmByte';
DELETE FROM MODRED.CONFIGURACAO WHERE CONF_ID = 'extensaoArquivoPrescricao';
COMMIT;

DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 60 AND PERF_ID = 1;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 71 AND PERF_ID = 1;

DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 63 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 64 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 65 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 66 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 67 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 68 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 69 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 70 AND PERF_ID = 5;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 72 AND PERF_ID = 5;

DELETE FROM MODRED.RECURSO WHERE RECU_ID = 63;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 64;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 65;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 66;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 67;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 68;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 69;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 70;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 71;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 72;

UPDATE MODRED.RECURSO SET RECU_TX_SIGLA = 'AVALIAR_DOADOR_MATCH' WHERE RECU_ID = 58;
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (58, 5, 0);
COMMIT;

