CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PRES_ID FOR MODRED.SQ_PRES_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ARPR_ID FOR MODRED.SQ_ARPR_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ARQUIVO_PRESCRICAO FOR MODRED.ARQUIVO_PRESCRICAO;