DROP TABLE MODRED.AVALIACAO_PRESCRICAO;
DROP SEQUENCE SQ_AVPR_ID;

DROP SYNONYM MODRED_APLICACAO.SQ_AVPR_ID;
DROP SYNONYM MODRED_APLICACAO.AVALIACAO_PRESCRICAO;

delete from modred.permissao where RECU_ID = 73;
delete from modred.recurso where RECU_ID = 73;

-- início Estória 1
DROP INDEX MODRED.IN_FK_PRES_FOCE_OPCAO_2;

ALTER TABLE MODRED.PRESCRICAO 
DROP CONSTRAINT FK_PRES_FOCE_OP_2;

ALTER TABLE MODRED.PRESCRICAO 
DROP COLUMN FOCE_ID_OPCAO_2;

ALTER TABLE MODRED.PRESCRICAO 
DROP COLUMN PRES_VL_QUANT_KG_OPCAO_1;

ALTER TABLE MODRED.PRESCRICAO 
DROP COLUMN PRES_VL_QUANT_TOTAL_OPCAO_2;

ALTER TABLE MODRED.PRESCRICAO 
DROP COLUMN PRES_VL_QUANT_KG_OPCAO_2;

ALTER TABLE MODRED.PRESCRICAO RENAME COLUMN FOCE_ID_OPCAO_1 TO FOCE_ID;

ALTER TABLE MODRED.PRESCRICAO RENAME COLUMN PRES_VL_QUANT_TOTAL_OPCAO_1 TO PRES_VL_QUANTIDADE_TCN_CD34;

ALTER TABLE MODRED.PRESCRICAO  
MODIFY (PRES_VL_QUANTIDADE_TCN_CD34 NULL);

ALTER INDEX MODRED.IN_FK_PRES_FOCE_OPCAO_1 
RENAME TO IN_FK_PRES_FOCE;

ALTER TABLE MODRED.PRESCRICAO 
RENAME CONSTRAINT FK_PRES_FOCE_OP_1 TO FK_PRES_FOCE;

ALTER TABLE MODRED.ARQUIVO_PRESCRICAO 
DROP COLUMN ARPR_IN_JUSTIFICATIVA;

DELETE FROM MODRED.CONFIGURACAO WHERE CONF_ID = 'tempoMinimoInclusaoEvolucaoEmSegundos';
COMMIT;

DROP INDEX MODRED.IN_FK_PEWO_FOCE;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP CONSTRAINT FK_PEWO_FOCE;

ALTER TABLE MODRED.PEDIDO_WORKUP 
DROP COLUMN FOCE_ID;

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD 
DROP COLUMN FOCE_ID;

DROP INDEX MODRED.IN_FK_PRES_AVPR;

ALTER TABLE MODRED.PRESCRICAO 
DROP CONSTRAINT FK_PRES_AVPR;

ALTER TABLE MODRED.PRESCRICAO 
DROP COLUMN AVPR_ID;

select * from resultado_workup;



-- RELACIONAMENTO PACIENTE E GENOTIPO
ALTER TABLE MODRED.PACIENTE
ADD GENO_ID NUMBER;

MERGE INTO MODRED.PACIENTE PAC
USING (
    SELECT GENO_ID, PACI_NR_RMR
    FROM MODRED.GENOTIPO
    ) GEN
ON (GEN.PACI_NR_RMR = PAC.PACI_NR_RMR)
WHEN MATCHED THEN UPDATE
SET PAC.GENO_ID = GEN.GENO_ID;
COMMIT;

ALTER TABLE MODRED.GENOTIPO
DROP COLUMN PACI_NR_RMR;-- Final Estória 1
