CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PRES_ID FOR MODRED.SQ_PRES_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ARPR_ID FOR MODRED.SQ_ARPR_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ARQUIVO_PRESCRICAO FOR MODRED.ARQUIVO_PRESCRICAO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_AVPR_ID FOR MODRED.SQ_AVPR_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.AVALIACAO_PRESCRICAO FOR MODRED.AVALIACAO_PRESCRICAO;

-- SINONIMOS 2698
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_LOEV_ID FOR MODRED.SQ_LOEV_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.LOG_EVOLUCAO FOR MODRED.LOG_EVOLUCAO;

