--FILIPE PAES (ESTORIA 2696)
GRANT SELECT ON MODRED.DESTINO_COLETA TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.DESTINO_COLETA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.RECEBIMENTO_COLETA TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.RECEBIMENTO_COLETA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_RECO_ID TO RMODRED_READ;
--FILIPE PAES (ESTÓRIA 2699)
GRANT SELECT ON MODRED.DIALOGO_BUSCA  TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.DIALOGO_BUSCA  TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_DIBU_ID TO RMODRED_WRITE;

--2697 Queiroz--
GRANT SELECT ON MODRED.CLASSIFICACAO_ABO TO RMODRED_READ;
commit;
--2697 Queiroz--