--FILIPE PAES (ESTORIA 2696)
DROP TABLE MODRED.DESTINO_COLETA;
DROP TABLE MODRED.RECEBIMENTO_COLETA;
DROP SEQUENCE  "MODRED"."SQ_RECO_ID";

DELETE FROM "MODRED"."PERMISSAO" WHERE RECU_ID=74 AND PERF_ID=14;
DELETE FROM "MODRED"."PERFIL" WHERE PERF_ID=14;
DELETE FROM "MODRED"."RECURSO" WHERE RECU_ID=74;
DELETE FROM  "MODRED"."TIPO_TAREFA" where tita_id=50;
DELETE FROM  "MODRED"."USUARIO" where usua_id=14;
DELETE FROM "MODRED"."USUARIO_PERFIL" WHERE USUA_ID = 14 AND PERF_ID = 14;
DELETE FROM "MODRED"."USUARIO_CENTRO_TRANSPLANTE" WHERE USUA_ID = 14 AND  CETR_ID = 2;
DELETE FROM "MODRED"."DESTINO_COLETA";
DELETE FROM "MODRED"."PERMISSAO" WHERE  RECU_ID = 8 AND PERF_ID = 14;
DELETE FROM  "MODRED"."TIPO_TAREFA" WHERE TITA_ID = 54;
COMMIT;


--FILIPE PAES (ESTÓRIA 2699)
DROP TABLE MODRED.DIALOGO_BUSCA;
DROP SEQUENCE MODRED.SQ_DIBU_ID;

DELETE FROM "MODRED"."PERMISSAO" WHERE RECU_ID = 78 AND  PERF_ID = 1;
DELETE FROM "MODRED"."PERMISSAO"  WHERE RECU_ID = 78 AND  PERF_ID = 5;
DELETE FROM "MODRED"."RECURSO" WHERE RECU_ID = 78;
COMMIT;

-- INÍCIO ESTÓRIA 2771
ALTER TABLE MODRED.QUALIFICACAO_MATCH 
DROP COLUMN QUMA_NR_TIPO;

-- RODAR O SCRIPT DA PROCEDURE SEPARADAMENTE
create or replace procedure proc_criar_qualificacoes_match (rmr in NUMBER, dmr in NUMBER, fase in VARCHAR2, com_mismatch in BOOLEAN)


IS
matchId NUMBER;


begin
    select m.matc_id into matchId from MODRED.paciente paci inner join MODRED.busca b on paci.paci_nr_rmr = b.paci_nr_rmr inner join match m on m.busc_id = b.busc_id where paci.PACI_NR_RMR = rmr and m.doad_nr_dmr = dmr;


    if (fase = '1') then
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'A', 1, dmr, '01:01'); 
        if(com_mismatch) then
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'M', 2, dmr, '01:01:01'); 
        else
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'P', 2, dmr, '01:01:01:01'); 
        end if;

        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'L', 1, dmr, '38:NOVO'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'P', 2, dmr, '18:NOVO'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'A', 1, dmr, '01:01'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'L', 2, dmr, '01:01:01'); 
        update match set MATC_TX_SITUACAO = 'F1' where matc_id = matchId;
    elsif (fase = '2' OR fase = '3' or fase='D') then
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'A', 1, dmr, '01:01:01:02N'); 
        if(com_mismatch) then
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'M', 2, dmr, '01:01:01:03'); 
        else
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'P', 2, dmr, '01:01:01:04'); 
        end if;

        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'L', 1, dmr, '35:NOVO'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'P', 2, dmr, '46:NOVO'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'A', 1, dmr, '01:01:01G'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'L', 2, dmr, '01:01:02'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'C', 'A', 1, dmr, '01:02'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'C', 'L', 2, dmr, '01:02:01'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB3', 'A', 1, dmr, '01:02'); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB3', 'L', 2, dmr, '01:01:02:02'); 
        if(fase = '2') then
            update match set MATC_TX_SITUACAO = 'F2' where matc_id = matchId;
        else 
            if(fase = '3') then
                update match set MATC_TX_SITUACAO = 'F3' where matc_id = matchId;
            else 
                update match set MATC_TX_SITUACAO = 'D' where matc_id = matchId;
            end if;
        end if;
    end if;
    commit;

end;

-- FIM ESTÓRIA 2771 


--2697 Queiroz--

drop table MODRED.CLASSIFICACAO_ABO;

commit;
--2697 Queiroz--

--INICIO ESTÓRIA 2773
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (1, 71, 0);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (1, 39, 0);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (1, 42, 0);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (1, 43, 0);
DELETE FROM MODRED.PERMISSAO WHERE PERF_ID = 15 AND RECU_ID in (71, 39, 42, 43);
DELETE FROM MODRED.USUARIO_PERFIL WHERE USUA_ID = 15 AND PERF_ID = 1;
COMMIT;

ALTER TABLE MODRED.AUDITORIA  
MODIFY (AUDI_TX_USUARIO VARCHAR2(20 BYTE) );
--FIM ESTÓRIA 2773


-- SPRINT 25
-- ESTORIA 2772 / PIZAO
-- ROLLBACK / 2772

-- PERFIL CONTROLADOR_LISTA CRIADO
DELETE FROM MODRED.PERFIL WHERE PERF_ID = 14;
COMMIT;

-- TIPO TAREFA CADASTRAR_PRESCRICAO CRIADO
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 52;
COMMIT;

-- TIPO TAREFA ENCONTRAR_CENTRO_TRANSPLANTE
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 53;
COMMIT;

-- CRIANDO ASSOCIAÇÃO ENTRE BUSCA E CENTRO TRANPLANTE
ALTER TABLE MODRED.BUSCA
DROP COLUMN CETR_ID_CENTRO_TRANSPLANTE;

ALTER TABLE MODRED.BUSCA
RENAME COLUMN CETR_ID_CENTRO_COLETA TO CETR_ID_TRANSPLANTADOR;

DROP INDEX IN_FK_BUSC_CETR_COLETA;

CREATE INDEX IN_FK_BUSC_CETR ON MODRED.BUSCA (CETR_ID_TRANSPLANTADOR ASC);


-- CRIANDO STATUS DA BUSCA FINALIZADA, INDICANDO QUANDO A BUSCA NÃO PODERÁ MAIS RECEBER NOVOS EXAMES.
DELETE FROM MODRED.STATUS_BUSCA WHERE STBU_ID = 5;
COMMIT;

-- CRIANDO RECURSO CRIAR_PRESCRICAO.
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 74;
COMMIT;

-- ASSOCIANDO PERFIL AO USUARIO (MEDICO_TRANSPLANTADOR)
DELETE FROM MODRED.USUARIO_PERFIL WHERE USUA_ID = 14 AND PERF_ID = 15;
COMMIT;

-- CRIANDO PERFIL MEDICO_TRANSPLANTADOR.
DELETE FROM MODRED.PERFIL WHERE PERF_ID = 15;
COMMIT;

-- CRIANDO USUARIO MEDICO_TRANSPLANTADOR.
DELETE FROM MODRED.USUARIO WHERE USUA_ID = 14;
COMMIT;


-- CRIANDO RECURSO CRIAR_PRESCRICAO.
DELETE FROM MODRED.USUARIO_CENTRO_TRANSPLANTE WHERE USUA_ID = 14 AND CETR_ID = 3;
COMMIT;

