--FILIPE PAES/INICIO (ESTORIA 2696)
CREATE TABLE MODRED.DESTINO_COLETA 
(
  DECO_ID NUMBER NOT NULL 
, DECO_TX_DESCRICAO VARCHAR2(60 BYTE) NOT NULL 
, CONSTRAINT PK_DECO PRIMARY KEY 
  (
    DECO_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_DECO ON DESTINO_COLETA (DECO_ID ASC) 
  )ENABLE 
) ;

COMMENT ON TABLE DESTINO_COLETA IS 'DESTINOS DADOS A COLETA RETIRADA DO DOADOR';

COMMENT ON COLUMN DESTINO_COLETA.DECO_ID IS 'ID DO DESTINO DE COLETA';

COMMENT ON COLUMN DESTINO_COLETA.DECO_TX_DESCRICAO IS 'NOME DO DESTINO DADO A COLETA';


CREATE TABLE MODRED.RECEBIMENTO_COLETA 
(
  RECE_ID NUMBER NOT NULL 
, PECL_ID NUMBER NOT NULL 
, FOCE_ID NUMBER NOT NULL 
, DECO_ID NUMBER NOT NULL 
, RECI_DT_INFUSAO DATE 
, RECI_DT_DESCARTE DATE 
, RECI_DT_PREVISTA_INFUSAO DATE 
, RECI_NR_TOTAL_TCN NUMBER 
, RECI_NR_TOTAL_CD34 NUMBER 
, RECI_TX_JUST_CONGELAMENTO VARCHAR2(500 BYTE) 
, RECI_TX_JUST_DESCARTE VARCHAR2(500 BYTE) 
, RECI_IN_RECEBEU NUMBER 
, CONSTRAINT PK_RECI_ID PRIMARY KEY 
  (
    RECE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_RECO ON RECEBIMENTO_COLETA (RECE_ID ASC)
  )
  ENABLE 
) ;

CREATE INDEX IN_FK_RECO_DECO ON MODRED.RECEBIMENTO_COLETA (DECO_ID ASC) ;

CREATE INDEX IN_FK_RECO_FOCE ON MODRED.RECEBIMENTO_COLETA (FOCE_ID ASC);

CREATE INDEX IN_FK_RECO_PECL ON MODRED.RECEBIMENTO_COLETA (PECL_ID ASC);

ALTER TABLE MODRED.RECEBIMENTO_COLETA
ADD CONSTRAINT FK_RECI_DECO FOREIGN KEY
(
  DECO_ID 
)
REFERENCES DESTINO_COLETA
(
  DECO_ID 
)
ENABLE;

ALTER TABLE MODRED.RECEBIMENTO_COLETA
ADD CONSTRAINT FK_RECI_FOCE FOREIGN KEY
(
  FOCE_ID 
)
REFERENCES FONTE_CELULAS
(
  FOCE_ID 
)
ENABLE;

ALTER TABLE MODRED.RECEBIMENTO_COLETA
ADD CONSTRAINT FK_RECI_PECL FOREIGN KEY
(
  PECL_ID 
)
REFERENCES PEDIDO_COLETA
(
  PECL_ID 
)
ENABLE;

COMMENT ON TABLE MODRED.RECEBIMENTO_COLETA IS 'REGISTRO DE RECEBIMENTO E DESTINO DADO PARA A COLETA FEITA DO DOADOR.';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECE_ID IS 'ID DE RECEBIMENTO DE COLETA';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.PECL_ID IS 'REFERENCIA DE PEDIDO DE COLETA';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.FOCE_ID IS 'REFERENICA PARA A FONTE DA AMOSTRA';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.DECO_ID IS 'REFERENCIA PARA O TIPO DE DESTINO QUE FOI DADO A AMOSTRA';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_DT_INFUSAO IS 'DATA DA INSUSÃO CASO A COLETA TENHA SIDO INFUDIDA ';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_DT_DESCARTE IS 'DATA DO DESCARTE CASO A COLETA TENHA SIDO DESCARTADA';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_DT_PREVISTA_INFUSAO IS 'DATA PREVISTA PARA INFUSÃO CASO A COLETA TENHA SIDO CONGELADA ';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_NR_TOTAL_TCN IS 'TOTAL DE CELULAS NUCLEADAS CASO A FONTE SEJA TCN';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_NR_TOTAL_CD34 IS 'TOTAL DE CD34 CASO A FONTE SEJA CD34';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_TX_JUST_CONGELAMENTO IS 'JUSTIFICATIVA PARA CASO A AMOSTRA TENHA SIDO CONGELADA';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_TX_JUST_DESCARTE IS 'JUSTIFICATIVA DE DESCARTE CASO A AMOSTRA TENHA SIDO DESCARTADA';

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_IN_RECEBEU IS '1 SE RECEBEU A COLETA E 0 SE NÃO RECEBEU';


CREATE SEQUENCE  "MODRED"."SQ_RECO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--recurso


INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES ('74', 'CADASTRAR_RECEBIMENTO_COLETA', 'Permite o cadastro de recebimento de coleta');
INSERT INTO "MODRED"."PERFIL" (PERF_ID, PERF_TX_DESCRICAO, PERF_NR_ENTITY_STATUS) VALUES ('14', 'CADASTRADOR_RECEBIMENTO_COLETA', '1');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID) VALUES ('74', '14');
COMMIT;


ALTER TABLE MODRED.RECEBIMENTO_COLETA 
ADD (RECI_DT_RECEBIMENTO DATE NOT NULL);

COMMENT ON COLUMN MODRED.RECEBIMENTO_COLETA.RECI_DT_RECEBIMENTO IS 'DATA DO RECEBIMENTO DA COLETA NO CENTRO DE TRANSPLANTE';

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO) VALUES ('50', 'CADASTRAR_RECEBIMENTO_COLETA', '1', '3600');
COMMIT;


INSERT INTO "MODRED"."USUARIO" (USUA_ID, USUA_TX_NOME, USUA_TX_USERNAME, USUA_TX_PASSWORD, USUA_IN_ATIVO, USUA_NR_ENTITY_STATUS) VALUES ('14', 'CADASTRADOR RECEBIMENTO COLETA', 'CADASTRADOR_RECEBIMENTO_COLETA', '$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.', '1', '1');
COMMIT;

INSERT INTO "MODRED"."USUARIO_PERFIL" (USUA_ID, PERF_ID) VALUES ('14', '14');
INSERT INTO "MODRED"."USUARIO_CENTRO_TRANSPLANTE" (USUA_ID, CETR_ID) VALUES ('14', '2');

COMMIT;



INSERT INTO "MODRED"."DESTINO_COLETA" (DECO_ID, DECO_TX_DESCRICAO) VALUES ('1', 'INFUSÃO');
INSERT INTO "MODRED"."DESTINO_COLETA" (DECO_ID, DECO_TX_DESCRICAO) VALUES ('2', 'CONGELAMENTO');
INSERT INTO "MODRED"."DESTINO_COLETA" (DECO_ID, DECO_TX_DESCRICAO) VALUES ('3', 'DESCARTE');
COMMIT;


INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID) VALUES ('8', '14');
COMMIT;

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA) VALUES ('54', 'NOTIFICACAO_NAO_RECEBIMENTO_COLETA', '0');
COMMIT;
--FILIPE PAES/ FIM


--FILIPE PAES - ESTÓRIA 2699 - INÍCIO


CREATE TABLE MODRED.DIALOGO_BUSCA 
(
  DIBU_ID NUMBER NOT NULL 
, BUSC_ID NUMBER NOT NULL 
, USUA_ID NUMBER NOT NULL 
, DIBU_TX_MENSAGEM VARCHAR2(255 BYTE) NOT NULL 
, DIBU_DT_MOMENTO_MENSAGEM TIMESTAMP(6) NOT NULL 
, CONSTRAINT PK_DIBU_ID PRIMARY KEY 
  (
    DIBU_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_DIBU_ID ON DIALOGO_BUSCA (DIBU_ID ASC) 
  )
  ENABLE 
) ;

CREATE INDEX IN_FK_DIBU_BUSC ON MODRED.DIALOGO_BUSCA (BUSC_ID ASC) ;

CREATE INDEX IN_FK_DIBU_USUA ON MODRED.DIALOGO_BUSCA (USUA_ID ASC) ;

ALTER TABLE MODRED.DIALOGO_BUSCA
ADD CONSTRAINT FK_DIBU_BUSC FOREIGN KEY
(
  BUSC_ID 
)
REFERENCES BUSCA
(
  BUSC_ID 
)
ENABLE;

ALTER TABLE MODRED.DIALOGO_BUSCA
ADD CONSTRAINT FK_DIBU_USUA FOREIGN KEY
(
  USUA_ID 
)
REFERENCES USUARIO
(
  USUA_ID 
)
ENABLE;

COMMENT ON TABLE MODRED.DIALOGO_BUSCA IS 'ARMAZENAMENTO DA CONVERSA ENTRE O MÉDICO DO PACIENTE E O ANALISTA DE BUSCA SOBRE A BUSCA EM QUESTÃO';

COMMENT ON COLUMN MODRED.DIALOGO_BUSCA.DIBU_ID IS 'IDENTIFICAÇÃO DO DIALOGO DE BUSCA';

COMMENT ON COLUMN MODRED.DIALOGO_BUSCA.BUSC_ID IS 'REFERENCIA DE BUSCA';

COMMENT ON COLUMN MODRED.DIALOGO_BUSCA.USUA_ID IS 'USUARIO QUE ESTÁ ENVIANDO A MENSAGEM';

COMMENT ON COLUMN MODRED.DIALOGO_BUSCA.DIBU_TX_MENSAGEM IS 'MENSAGEM ENVIADA';

COMMENT ON COLUMN MODRED.DIALOGO_BUSCA.DIBU_DT_MOMENTO_MENSAGEM IS 'MOMENTO DA MENSAGEM';



CREATE SEQUENCE  "MODRED"."SQ_DIBU_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES ('75', 'DIALOGO_BUSCA', 'Permite o diálogo entre médico e o analista de busca ');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('75', '1', '0');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('75', '5', '0');
commit;
--FIM ESTÓRIA 2699

--ESTÓRIA 2771
ALTER TABLE MODRED.QUALIFICACAO_MATCH 
ADD (QUMA_NR_TIPO NUMBER );

COMMENT ON COLUMN MODRED.QUALIFICACAO_MATCH.QUMA_NR_TIPO IS '0- para sorologia, 1- para antígeno, 2- NMDP, 3- Grupo G, 4-  Grupo P e 5 Alelo';


--RODAR O SCRIPT DA PROCEDURE SEPARADAMENTE 
create or replace procedure proc_criar_qualificacoes_match (rmr in NUMBER, dmr in NUMBER, fase in VARCHAR2, com_mismatch in BOOLEAN)


IS
matchId NUMBER;


begin
    select m.matc_id into matchId from MODRED.paciente paci inner join MODRED.busca b on paci.paci_nr_rmr = b.paci_nr_rmr inner join match m on m.busc_id = b.busc_id where paci.PACI_NR_RMR = rmr and m.doad_nr_dmr = dmr;


    if (fase = '1') then
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'A', 1, dmr, '01:01', 5); 
        if(com_mismatch) then
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'M', 2, dmr, '01:01:01', 5); 
        else
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'P', 2, dmr, '01:01:01:01', 5); 
        end if;

        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'L', 1, dmr, '38:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'P', 2, dmr, '18:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'A', 1, dmr, '01:01', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'L', 2, dmr, '01:01:01', 5); 
        update match set MATC_TX_SITUACAO = 'F1' where matc_id = matchId;
    elsif (fase = '2' OR fase = '3' or fase='D') then
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'A', 1, dmr, '01:01:01:02N', 5); 
        if(com_mismatch) then
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'M', 2, dmr, '01:01:01:03', 5); 
        else
            INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'A', 'P', 2, dmr, '01:01:01:04', 5); 
        end if;

        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'L', 1, dmr, '35:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'B', 'P', 2, dmr, '46:NOVO', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'A', 1, dmr, '01:01:01G', 3); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB1', 'L', 2, dmr, '01:01:02', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'C', 'A', 1, dmr, '01:02', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'C', 'L', 2, dmr, '01:02:01', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB3', 'A', 1, dmr, '01:02', 5); 
        INSERT INTO MODRED.QUALIFICACAO_MATCH (QUMA_ID, MATC_ID, LOCU_ID, QUMA_TX_QUALIFICACAO, QUMA_NR_POSICAO, DOAD_NR_DMR, QUMA_TX_GENOTIPO, QUMA_NR_TIPO) VALUES (modred.SQ_QUMA_ID.NEXTVAL, matchId, 'DRB3', 'L', 2, dmr, '01:01:02:02', 5); 
        if(fase = '2') then
            update match set MATC_TX_SITUACAO = 'F2' where matc_id = matchId;
        else 
            if(fase = '3') then
                update match set MATC_TX_SITUACAO = 'F3' where matc_id = matchId;
            else 
                update match set MATC_TX_SITUACAO = 'D' where matc_id = matchId;
            end if;
        end if;
    end if;
    commit;
end;
--FIM ESTÓRIA 2771


--2697 Queiroz--


CREATE TABLE MODRED.CLASSIFICACAO_ABO 
(
  CLAB_TX_ABO VARCHAR2(20) NOT NULL 
, CLAB_VL_PRIORIDADE NUMBER NOT NULL 
, CLAB_TX_ABO_RELACAO VARCHAR2(20) NOT NULL 
, CONSTRAINT PK_CLAB PRIMARY KEY 
  (
    CLAB_TX_ABO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_CLAB ON MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO ASC) 
  )
  ENABLE 
);

COMMENT ON TABLE MODRED.CLASSIFICACAO_ABO IS 'Tabela para priorizar ordenação de ABO.';

COMMENT ON COLUMN MODRED.CLASSIFICACAO_ABO.CLAB_TX_ABO IS 'Chave primária da tabela de classificação abo.';

COMMENT ON COLUMN MODRED.CLASSIFICACAO_ABO.CLAB_VL_PRIORIDADE IS 'Ordenação do ABO';

COMMENT ON COLUMN MODRED.CLASSIFICACAO_ABO.CLAB_TX_ABO_RELACAO IS 'Relação do abo atual com outro ABO.';


ALTER TABLE MODRED.CLASSIFICACAO_ABO 
DROP CONSTRAINT PK_CLAB;

ALTER TABLE MODRED.CLASSIFICACAO_ABO
ADD CONSTRAINT PK_CLAB PRIMARY KEY 
(
  CLAB_TX_ABO 
, CLAB_TX_ABO_RELACAO 
)
ENABLE;

commit;



Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','1','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','1','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','2','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','2','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','1','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','1','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','2','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A+','2','O-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','1','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','1','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','2','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','2','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','1','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','1','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','2','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('A-','2','O-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','2','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','2','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','1','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','1','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','1','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','1','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','2','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B+','2','O-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','2','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','2','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','1','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','1','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','1','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','1','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','2','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('B-','2','O-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','2','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','2','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','2','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','2','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','1','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','1','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','2','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB+','2','O-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','1','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','1','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','1','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','1','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','2','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','2','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','2','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('AB-','2','O-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O+','1','O-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','A+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','A-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','B+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','B-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','AB+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','AB-');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','O+');
Insert into MODRED.CLASSIFICACAO_ABO (CLAB_TX_ABO,CLAB_VL_PRIORIDADE,CLAB_TX_ABO_RELACAO) values ('O-','1','O-');
--2697 Queiroz----2697 Queiroz--

--INÍCIO ESTÓRIA 2773
DELETE FROM MODRED.PERMISSAO WHERE PERF_ID = 1 AND RECU_ID in (71, 39, 42, 43);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (15, 71, 0);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (15, 39, 0);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (15, 42, 0);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES (15, 43, 0);
INSERT INTO MODRED.USUARIO_PERFIL (USUA_ID, PERF_ID) VALUES (15, 1);
COMMIT;

ALTER TABLE MODRED.AUDITORIA  
MODIFY (AUDI_TX_USUARIO VARCHAR2(150 BYTE) );
--FIM ESTÓRIA 2773


-- ESTORIA 2772 / PIZAO
-- SCRIPT / 2772
-- PERFIL CONTROLADOR_LISTA CRIADO
INSERT INTO MODRED.PERFIL (PERF_ID, PERF_TX_DESCRICAO, PERF_NR_ENTITY_STATUS) 
VALUES (16, 'CONTROLADOR_LISTA', 1);
COMMIT;

-- TIPO TAREFA CADASTRAR_PRESCRICAO CRIADO
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA) 
VALUES (52, 'CADASTRAR_PRESCRICAO', 0);
COMMIT;

-- TIPO TAREFA ENCONTRAR_CENTRO_TRANSPLANTE
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA) 
VALUES (53, 'ENCONTRAR_CENTRO_TRANSPLANTE', 0);
COMMIT;

-- CRIANDO ASSOCIAÇÃO ENTRE BUSCA E CENTRO TRANPLANTE
ALTER TABLE MODRED.BUSCA
RENAME COLUMN CETR_ID_TRANSPLANTADOR TO CETR_ID_CENTRO_COLETA;
COMMENT ON COLUMN MODRED.BUSCA.CETR_ID_CENTRO_COLETA IS 'Centro de coleta selecionado para a busca do paciente (FK).';

ALTER TABLE MODRED.BUSCA_AUD
RENAME COLUMN CETR_ID_TRANSPLANTADOR TO CETR_ID_CENTRO_COLETA;

DROP INDEX IN_FK_BUSC_CETR;
CREATE INDEX IN_FK_BUSC_CETR_COLETA ON MODRED.BUSCA (CETR_ID_CENTRO_COLETA ASC);

ALTER TABLE MODRED.BUSCA
ADD CETR_ID_CENTRO_TRANSPLANTE NUMBER;
COMMENT ON COLUMN MODRED.BUSCA.CETR_ID_CENTRO_TRANSPLANTE IS 'Centro de transplante confirmado para o paciente (FK).';

ALTER TABLE MODRED.BUSCA_AUD
ADD CETR_ID_CENTRO_TRANSPLANTE NUMBER;

ALTER TABLE MODRED.BUSCA
ADD CONSTRAINT FK_BUSC_CETR_TRANSPLANTE FOREIGN KEY(CETR_ID_CENTRO_TRANSPLANTE)
REFERENCES MODRED.CENTRO_TRANSPLANTE(CETR_ID)
ENABLE;

CREATE INDEX IN_FK_BUSC_CETR_TRANSPLANTE ON MODRED.BUSCA (CETR_ID_CENTRO_TRANSPLANTE ASC);

-- CRIANDO STATUS DA BUSCA FINALIZADA, INDICANDO QUANDO A BUSCA NÃO PODERÁ MAIS RECEBER NOVOS EXAMES.
INSERT INTO MODRED.STATUS_BUSCA (STBU_ID, STBU_TX_DESCRICAO, STBU_IN_BUSCA_ATIVA) 
VALUES (5, 'MATCH_SELECIONADO', 1);
COMMIT;

-- CRIANDO RECURSO CRIAR_PRESCRICAO.
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (75, 'CRIAR_PRESCRICAO', 'Permite ao medico do centro transplantador criar uma nova prescrição.');
COMMIT;

-- CRIANDO PERFIL MEDICO_TRANSPLANTADOR.
INSERT INTO MODRED.PERFIL (PERF_ID, PERF_TX_DESCRICAO, PERF_NR_ENTITY_STATUS) 
VALUES (15, 'MEDICO_TRANSPLANTADOR', '1');
COMMIT;

-- CRIANDO USUARIO MEDICO_TRANSPLANTADOR.
INSERT INTO MODRED.USUARIO (USUA_ID, USUA_TX_NOME, USUA_TX_USERNAME, USUA_TX_PASSWORD, USUA_IN_ATIVO, USUA_NR_ENTITY_STATUS) 
VALUES (15, 'MEDICO_TRANSPLANTADOR', 'MEDICO_TRANSPLANTADOR', '$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.', 1, 1);
COMMIT;

-- ASSOCIANDO PERFIL AO USUARIO (MEDICO_TRANSPLANTADOR)
INSERT INTO MODRED.USUARIO_PERFIL (USUA_ID, PERF_ID) VALUES (15, 15);
COMMIT;

-- CRIANDO RECURSO CRIAR_PRESCRICAO.
INSERT INTO MODRED.USUARIO_CENTRO_TRANSPLANTE (USUA_ID, CETR_ID) VALUES (15, 3);
COMMIT;

-- RECURSO PARA CONFIRMAR CENTRO TRANSPLANTADOR
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (76, 'CONFIRMAR_CENTRO_TRANSPLANTADOR', 'Permite ao analista de busca confirmar o centro transplantador que irá realizado o procedimento.');
COMMIT;

-- PERMISSÃO PARA O ANALISTA DE BUSCA CONFIRMAR O CENTRO TRANSPLANTADOR
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (76, 5, 0);
COMMIT;

-- RECURSO PARA CONCLUIR A BUSCA
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (77, 'CONCLUIR_BUSCA', 'Permite ao analista de busca concluir a seleção dos doadores em match com o paciente.');
COMMIT;

-- PERMISSÃO PARA O ANALISTA DE BUSCA CONCLUIR A BUSCA
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (77, 5, 0);
COMMIT;

-- REMOVENDO A COLUNA CENTRO COLETA DA BUSCA.
ALTER TABLE MODRED.BUSCA
DROP COLUMN CETR_ID_CENTRO_COLETA CASCADE CONSTRAINTS;


-- SPRINT 25
-- ESTORIA 2774 / PIZAO

-- CRIANDO RECURSO CRIAR_PRESCRICAO.
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (79, 'ENCONTRAR_CENTRO_TRANSPLANTADOR', 'Permite ao controlador de lista selecionar centro transplantador para paciente sem centro definido.');
COMMIT;

-- PERMISSÃO PARA O ANALISTA DE BUSCA CONFIRMAR O CENTRO TRANSPLANTADOR
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (79, 16, 0);
COMMIT;

-- CRIANDO USUARIO CONTROLADOR DE LISTA.
INSERT INTO MODRED.USUARIO (USUA_ID, USUA_TX_NOME, USUA_TX_USERNAME, USUA_TX_PASSWORD, USUA_IN_ATIVO, USUA_NR_ENTITY_STATUS) 
VALUES (16, 'CONTROLADOR_LISTA', 'CONTROLADOR_LISTA', '$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.', 1, 1);
COMMIT;

-- ASSOCIANDO PERFIL AO USUARIO (CONTROLADOR DE LISTA)
INSERT INTO MODRED.USUARIO_PERFIL (USUA_ID, PERF_ID) VALUES (16, 16);
COMMIT;



INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('78', '15', '0');
COMMIT;