--FILIPE PAES - ESTÓRIA 2696
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DESTINO_COLETA FOR MODRED.DESTINO_COLETA ;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RECEBIMENTO_COLETA FOR MODRED.RECEBIMENTO_COLETA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_RECO_ID FOR "MODRED"."SQ_RECO_ID";
--FILIPE PAES - ESTÓRIA 2699
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_DIBU_ID FOR MODRED.SQ_DIBU_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DIALOGO_BUSCA FOR MODRED.DIALOGO_BUSCA;

--2697 Queiroz--
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CLASSIFICACAO_ABO FOR MODRED.CLASSIFICACAO_ABO;
commit;
--2697 Queiroz--