-- ESTORIA 1 / 2864 (PIZAO)

GRANT SELECT ON MODRED.PEDIDO_TRANSPORTE TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PEDIDO_TRANSPORTE TO RMODRED_WRITE;

GRANT SELECT ON MODRED.TRANSPORTADORA TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.TRANSPORTADORA TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_TRAN_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PETR_ID TO RMODRED_WRITE;

-- ESTORIA 1 / 2864 (PIZAO)
-- ESTORIA 3/ 2879 (FILIPE PAES)

GRANT SELECT ON MODRED.ARQUIVO_PEDIDO_TRANSPORTE TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.ARQUIVO_PEDIDO_TRANSPORTE TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_ARPT_ID TO RMODRED_WRITE;

-- ESTORIA 3/ 2879 (FILIPE PAES)
-- ESTORIA 1 / 2864 (PIZAO)


GRANT SELECT ON MODRED.STATUS_PEDIDO_TRANSPORTE TO RMODRED_READ;
-- ESTORIA 1 / 2864 (PIZAO)
