-- ESTORIA 1 / 2864 (PIZAO)
ALTER TABLE MODRED.TAREFA 
ADD (CETR_ID_RESPONSAVEL NUMBER );

COMMENT ON COLUMN MODRED.TAREFA.CETR_ID_RESPONSAVEL IS 'Centro de transplante para o qual foi conferida esta tarefa, ou seja, trata-se da organização responsável por executar a tarefa.';

UPDATE MODRED.TAREFA SET CETR_ID_RESPONSAVEL = TARE_NR_PARCEIRO;
COMMIT;

ALTER TABLE MODRED.TAREFA
ADD CONSTRAINT FK_TARE_CETR_ID_RESPONSAVEL FOREIGN KEY
(
  CETR_ID_RESPONSAVEL 
)
REFERENCES CENTRO_TRANSPLANTE
(
  CETR_ID 
)
ENABLE;

CREATE INDEX IN_FK_CETR_ID_RESPONSAVEL ON MODRED.TAREFA (CETR_ID_RESPONSAVEL);

DROP INDEX MODRED.IN_TARE_NR_PARCEIRO;

ALTER TABLE MODRED.TAREFA 
DROP COLUMN TARE_NR_PARCEIRO;

-- Criar tabela de pedido de transporte com coluna de usuario;
DROP TABLE MODRED.PEDIDO_TRANSPORTE CASCADE CONSTRAINTS;

-- Criar Transportadora; 
DROP TABLE MODRED.TRANSPORTADORA CASCADE CONSTRAINTS;

-- Criar tipo de tarefa PEDIDO_TRANSPORTE com a entidade Pedido_Transporte.
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 55;

DROP SEQUENCE MODRED.SQ_TRAN_ID;
DROP SEQUENCE MODRED.SQ_PETR_ID;


DROP TABLE STATUS_PEDIDO_TRANSPORTE;
-- ESTORIA 3/ 2879 (FILIPE PAES)

DROP TABLE MODRED.ARQUIVO_PEDIDO_TRANSPORTE CASCADE CONSTRAINTS;
DROP SEQUENCE MODRED.SQ_ARPT_ID;


DELETE FROM MODRED.CONFIGURACAO WHERE CONF_ID = 'quantidadeMaximaArquivosPedidoTransporte';
DELETE FROM MODRED.CONFIGURACAO WHERE CONF_ID = 'tamanhoArquivoPedidoTransporteEmByte';
DELETE FROM MODRED.CONFIGURACAO WHERE CONF_ID = 'extensaoArquivoPedidoTransporte';
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 81;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 81 AND PERF_ID = 12;
commit;

-- ESTORIA 3/ 2879 (FILIPE PAES)

-- ESTORIA 4 
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 57;
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 58;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 82 AND PERF_ID = 17;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 83 AND PERF_ID = 17;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 82;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 83;
COMMIT;

-- FIM ESTORIA 4
