-- ESTORIA 1 / 2864 (PIZAO)

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_TRANSPORTE FOR MODRED.PEDIDO_TRANSPORTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TRANSPORTADORA FOR MODRED.TRANSPORTADORA;

-- ESTORIA 1 / 2864 (PIZAO)


CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_PEDIDO_TRANSPORTE FOR MODRED.STATUS_PEDIDO_TRANSPORTE;
-- ESTORIA 1 / 2864 (PIZAO)

-- ESTORIA 3/ 2879 (FILIPE PAES)

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ARQUIVO_PEDIDO_TRANSPORTE FOR MODRED.ARQUIVO_PEDIDO_TRANSPORTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ARPT_ID FOR MODRED.SQ_ARPT_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PETR_ID FOR MODRED.SQ_PETR_ID;

-- ESTORIA 3/ 2879 (FILIPE PAES)
