--Queiroz Usuario com perfil transportadora, login COURIER--
INSERT INTO "MODRED"."USUARIO" (USUA_ID, USUA_TX_NOME, USUA_TX_USERNAME, USUA_TX_PASSWORD, USUA_IN_ATIVO, USUA_NR_ENTITY_STATUS, TRANS_ID) VALUES ('51', 'COURIER', 'COURIER', '$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.', '1', '1', '1');
INSERT INTO "MODRED"."PERFIL" (PERF_ID, PERF_TX_DESCRICAO, PERF_NR_ENTITY_STATUS) VALUES ('17', 'TRANSPORTADORA', '1');
INSERT INTO "MODRED"."USUARIO_PERFIL" (USUA_ID, PERF_ID) VALUES ('51', '17');
INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES ('80', 'AGENDAR_TRANSPORTE_MATERIAL', 'Permite o usuario de uma transportadora agendar um transporte de material.');
--Fim Queiroz--

INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('80', '17', '0');
--Fim Queiroz--


-- ESTORIA 1 / 2864 (PIZAO)

-- Criar Transportadora; 
CREATE TABLE MODRED.TRANSPORTADORA
(
  TRAN_ID NUMBER NOT NULL 
, TRAN_NOME NUMBER NOT NULL 
, CONSTRAINT PK_TRAN_ID PRIMARY KEY (TRAN_ID) 
  USING INDEX (CREATE UNIQUE INDEX IN_PK_TRAN ON TRANSPORTADORA (TRAN_ID ASC)) ENABLE
);

COMMENT ON TABLE MODRED.TRANSPORTADORA IS 'Entidade que representa a transportadora que ir� realizar o transporte do material coletado (empresa terceirizada de courier).';
COMMENT ON COLUMN MODRED.TRANSPORTADORA.TRAN_ID IS 'Identifica��o da tabela.';
COMMENT ON COLUMN MODRED.TRANSPORTADORA.TRAN_NOME IS 'Nome da transportadora.';

CREATE SEQUENCE MODRED.SQ_TRAN_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;


-- Criar tabela de pedido de transporte com coluna de usuario;
CREATE TABLE MODRED.PEDIDO_TRANSPORTE
(
  PETR_ID NUMBER NOT NULL 
, PETR_DT_ATUALIZACAO TIMESTAMP NOT NULL 
, USUA_ID_RESPONSAVEL NUMBER
, PETR_HR_PREVISTA_RETIRADA TIMESTAMP NOT NULL 
, TRAN_ID NUMBER NOT NULL
, CONSTRAINT PK_PETR_ID PRIMARY KEY (PETR_ID) 
  USING INDEX (CREATE UNIQUE INDEX IN_PK_PETR ON PEDIDO_TRANSPORTE (PETR_ID ASC)) ENABLE
);

COMMENT ON TABLE MODRED.PEDIDO_TRANSPORTE IS 'Entidade que representa a transportadora que ir� realizar o transporte do material coletado (empresa terceirizada de courier).';
COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_ID IS 'Identifica��o da tabela.';
COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_DT_ATUALIZACAO IS 'Data de �ltima atualiza��o da tabela.';
COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.USUA_ID_RESPONSAVEL IS 'Usu�rio respons�vel por realizar (finalizar) o pedido.';
COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_HR_PREVISTA_RETIRADA IS 'Hora prevista para a retirada do material da coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.TRAN_ID IS 'Transportadora respons�vel por enviar o courier para retirada do material.';

CREATE SEQUENCE MODRED.SQ_PETR_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;


ALTER TABLE MODRED.PEDIDO_TRANSPORTE
ADD CONSTRAINT FK_PETR_USUA FOREIGN KEY(USUA_ID_RESPONSAVEL)
REFERENCES MODRED.USUARIO(USUA_ID)
ENABLE;

ALTER TABLE MODRED.PEDIDO_TRANSPORTE
ADD CONSTRAINT FK_PETR_TRAN FOREIGN KEY(TRAN_ID)
REFERENCES MODRED.USUARIO(USUA_ID)
ENABLE;

-- Criar tipo de tarefa PEDIDO_TRANSPORTE com a entidade Pedido_Transporte. 
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA)
VALUES (55, 'PEDIDO_TRANSPORTE', 0);
COMMIT;

-- ESTORIA 1 / 2864 (PIZAO)
-- CORRIGINDO CONSTRAINT DE FK CRIADA ERRADO PARA TRANSPORTE
ALTER TABLE MODRED.PEDIDO_TRANSPORTE
DROP CONSTRAINT FK_PETR_TRAN;

ALTER TABLE MODRED.PEDIDO_TRANSPORTE
ADD CONSTRAINT FK_PETR_TRAN FOREIGN KEY(TRAN_ID)
REFERENCES MODRED.TRANSPORTADORA(TRAN_ID)
ENABLE;

ALTER TABLE MODRED.TAREFA 
ADD (TARE_NR_PARCEIRO NUMBER );

COMMENT ON COLUMN MODRED.TAREFA.TARE_NR_PARCEIRO IS 'Parceiro para o qual foi conferida esta tarefa, ou seja, trata-se da organização responsável por executar a tarefa.';

UPDATE MODRED.TAREFA SET TARE_NR_PARCEIRO = CETR_ID_RESPONSAVEL;
COMMIT;

ALTER TABLE MODRED.TAREFA 
DROP CONSTRAINT FK_TARE_CETR_ID_RESPONSAVEL;

DROP INDEX MODRED.IN_FK_CETR_ID_RESPONSAVEL;

ALTER TABLE MODRED.TAREFA 
DROP COLUMN CETR_ID_RESPONSAVEL;



-- ESTORIA 1 / 2864 (PIZAO)

--Queiroz Corrigindo tabela transportadora
ALTER TABLE MODRED.TRANSPORTADORA  MODIFY (TRAN_NOME VARCHAR2(55) );
insert into transportadora values (sq_tran_id.nextval,'TRANSPORTADORA CARGO X');



ALTER TABLE MODRED.PEDIDO_LOGISTICA 
ADD (PETR_ID NUMBER );

CREATE INDEX IN_FK_PELO_PETR ON MODRED.PEDIDO_LOGISTICA (PELO_DT_CRIACAO);

ALTER TABLE MODRED.PEDIDO_LOGISTICA
ADD CONSTRAINT FK_PELO_PETR FOREIGN KEY
(
  PETR_ID 
)
REFERENCES MODRED.PEDIDO_TRANSPORTE
(
  PETR_ID 
)
ENABLE;

COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA.PETR_ID IS 'Identificador da tabela de pedido de transporte';

ALTER TABLE MODRED.PEDIDO_TRANSPORTE 
ADD (PETR_IN_STATUS NUMBER DEFAULT 0 NOT NULL);

COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_IN_STATUS IS '0 - ANALISE, 1 - AGUARDANDO DOCUMENTACAO, 2 - AGUARDANDO CONFIRMACAO, 3 - AGUARDANDO RETIRADA, 4 - AGUARDANDO ENTREGA';
commit;
--Fim Queiroz

--Inicio Status Pedido Transporte Queiroz
ALTER TABLE MODRED.PEDIDO_TRANSPORTE RENAME COLUMN PETR_IN_STATUS TO STPT_ID;


-- ADICIONANDO COLUNA NO PEDIDO LOGISTICA AUDITORIA
ALTER TABLE MODRED.PEDIDO_LOGISTICA_AUD
ADD (PETR_ID NUMBER);

-- AJUSTANDO A BASE, PARA OS CASOS DE TIPO 52 (CADASTRAR PRESCRIÇÃO) SEM INFORMAR O CT.
UPDATE MODRED.TAREFA
SET CETR_ID_RESPONSAVEL = 3
WHERE CETR_ID_RESPONSAVEL IS NULL
AND TITA_ID = 52;

-- INCLUSÃO DA COLUNA QUE DEFINE O TIPO DE TRAREFA COMO AGRUPADORA.
ALTER TABLE MODRED.TIPO_TAREFA
ADD TARE_IN_SOMENTE_AGRUPADOR NUMBER;

UPDATE MODRED.TIPO_TAREFA
SET TARE_IN_SOMENTE_AGRUPADOR = 0;

ALTER TABLE MODRED.TIPO_TAREFA
MODIFY TARE_IN_SOMENTE_AGRUPADOR NOT NULL;

-- INCLUSÃO DO NOVO TIPO DE TAREFA: LOGISTICA (AGRUPA TODOS OS ITENS DE LOGISTICA).
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) 
VALUES (59, 'LOGISTICA', 0, 1);

ALTER TABLE MODRED.PEDIDO_TRANSPORTE  
MODIFY (STPT_ID DEFAULT 1 );



CREATE TABLE MODRED.STATUS_PEDIDO_TRANSPORTE 
(
  STPT_ID NUMBER NOT NULL 
, STPT_TX_DESCRICAO VARCHAR2(30) 
, CONSTRAINT PK_STPT PRIMARY KEY 
  (
    STPT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_STPT ON MODRED.STATUS_PEDIDO_TRANSPORTE (STPT_ID ASC) 
  )
  ENABLE 
);

COMMENT ON COLUMN MODRED.STATUS_PEDIDO_TRANSPORTE.STPT_ID IS 'Chave primária da tabela';

COMMENT ON COLUMN MODRED.STATUS_PEDIDO_TRANSPORTE.STPT_TX_DESCRICAO IS 'Descrição do status';

INSERT INTO "MODRED"."STATUS_PEDIDO_TRANSPORTE" (STPT_ID, STPT_TX_DESCRICAO) VALUES ('1', 'EM ANÁLISE');
INSERT INTO "MODRED"."STATUS_PEDIDO_TRANSPORTE" (STPT_ID, STPT_TX_DESCRICAO) VALUES ('2', 'AGUARDANDO DOCUMENTAÇÃO');
INSERT INTO "MODRED"."STATUS_PEDIDO_TRANSPORTE" (STPT_ID, STPT_TX_DESCRICAO) VALUES ('3', 'AGUARDANDO CONFIRMAÇÃO');
INSERT INTO "MODRED"."STATUS_PEDIDO_TRANSPORTE" (STPT_ID, STPT_TX_DESCRICAO) VALUES ('4', 'AGUARDANDO RETIRADA');
INSERT INTO "MODRED"."STATUS_PEDIDO_TRANSPORTE" (STPT_ID, STPT_TX_DESCRICAO) VALUES ('5', 'AGUARDANDO ENTREGA');


ALTER TABLE MODRED.PEDIDO_TRANSPORTE
ADD CONSTRAINT FK_PETR_STPT FOREIGN KEY
(
  STPT_ID 
)
REFERENCES MODRED.STATUS_PEDIDO_TRANSPORTE
(
  STPT_ID 
)
ENABLE;

COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.STPT_ID IS 'Identificado da tabela de status do pedido de transporte';
--Fim Status pedido transporte Queiroz



-- Inicio Queiroz Serviço para confirmar agendamentode pedido de transporte
INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA,TARE_IN_SOMENTE_AGRUPADOR) VALUES ('56', 'PEDIDO_TRANSPORTE_RETIRADA', '0', 0); 
INSERT INTO "MODRED"."TIPO_PEDIDO_LOGISTICA" (TIPL_ID, TIPL_TX_DESCRICAO) VALUES ('3', 'MATERIAL COM AÉREO');
COMMIT;



ALTER TABLE MODRED.PEDIDO_TRANSPORTE 
ADD (PETR_DADOS_VOO VARCHAR2(255) );

ALTER TABLE MODRED.PEDIDO_TRANSPORTE 
ADD (PETR_DADOS_COURIER VARCHAR2(255) );

COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_DADOS_VOO IS 'Dados do voo inseridos pela transportadora.';

COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_DADOS_COURIER IS 'Dados do Courier inseridos pela transportadora.';
COMMIT;

-- Fim Queiroz Serviço para confirmar agendamentode pedido de transporte
--Fim Status pedido transporte Queiroz-- ESTORIA 1 / 2864 (PIZAO)

-- ESTORIA 3/ 2879 (FILIPE PAES)
CREATE TABLE MODRED.ARQUIVO_PEDIDO_TRANSPORTE 
(
  ARPT_ID NUMBER NOT NULL 
, ARPT_TX_CAMINHO VARCHAR2(255 BYTE) NOT NULL 
, PETR_ID NUMBER 
, CONSTRAINT PK_ARPT_ID PRIMARY KEY 
  (
    ARPT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_ARPT_ID ON MODRED.ARQUIVO_PEDIDO_TRANSPORTE (ARPT_ID ASC)
  )
  ENABLE 
);

CREATE INDEX IN_FK_ARPT_PETR ON ARQUIVO_PEDIDO_TRANSPORTE (PETR_ID ASC) ;

ALTER TABLE ARQUIVO_PEDIDO_TRANSPORTE
ADD CONSTRAINT FK_ARPT_PETR FOREIGN KEY
(
  PETR_ID 
)
REFERENCES PEDIDO_TRANSPORTE
(
  PETR_ID 
)
ENABLE;


COMMENT ON TABLE MODRED.ARQUIVO_PEDIDO_TRANSPORTE IS 'Armazenamento de referência de arquivos de pedido de transporte. No momento em que as passagens são emitidas pela C.N.T é necessário que seja gerado um arquivo para que fique com o Courier. Este arquivo será armazenado nesta tabela.';

COMMENT ON TABLE MODRED.ARQUIVO_PEDIDO_TRANSPORTE IS 'Armazenamento de referência de arquivos de pedido de transporte. No momento em que as passagens são emitidas pela C.N.T é necessário que seja gerado um arquivo para que fique com o Courier. Este arquivo será armazenado nesta tabela.';

COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_TRANSPORTE.ARPT_ID IS 'Identificação do arquivo de pedido de transporte';

COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_TRANSPORTE.ARPT_TX_CAMINHO IS 'Caminho do arquivo no storage ';

COMMENT ON COLUMN MODRED.ARQUIVO_PEDIDO_TRANSPORTE.PETR_ID IS 'Referencia para o pedido de transporte';


CREATE SEQUENCE  "MODRED"."SQ_ARPT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;



INSERT INTO "MODRED"."CONFIGURACAO" (CONF_ID, CONF_TX_VALOR) VALUES ('quantidadeMaximaArquivosPedidoTransporte', '1');
INSERT INTO "MODRED"."CONFIGURACAO" (CONF_ID, CONF_TX_VALOR) VALUES ('tamanhoArquivoPedidoTransporteEmByte', '5242880');
INSERT INTO "MODRED"."CONFIGURACAO" (CONF_ID, CONF_TX_VALOR) VALUES ('extensaoArquivoPedidoTransporte', 'application/pdf');
commit;


INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES ('81', 'SOLICITAR_LOGISTICA_MATERIAL', 'Permite ao analista de logistica solicitar a uma transportadora uma logística de material');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID) VALUES ('81', '12');
commit;

-- ESTORIA 3/ 2879 (FILIPE PAES)

-- ESTORIA 4
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO) VALUES (57, 'PEDIDO_TRANSPORTE_ENTREGA', '0', null);
INSERT INTO MODRED.TIPO_TAREFA (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TITA_NR_TEMPO_EXECUCAO) VALUES (58, 'PEDIDO_TRANSPORTE_RETIRADA_ENTREGA', '0', null);
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (82, 'RETIRAR_TRANSPORTE_MATERIAL', 'Permite o usuario de uma transportadora retirar um  material.');
INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES (83, 'ENTREGAR_TRANSPORTE_MATERIAL', 'Permite o usuario de uma transportadora entregar um  material que foi retirado.');
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (82, 17, 0);
INSERT INTO MODRED.PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES (83, 17, 0);
COMMIT;

ALTER TABLE MODRED.PEDIDO_TRANSPORTE 
ADD (PETR_DT_RETIRADA TIMESTAMP );

ALTER TABLE MODRED.PEDIDO_TRANSPORTE 
ADD (PETR_DT_ENTREGA TIMESTAMP );

COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_DT_RETIRADA IS 'Data da retirada do material da coleta.';
COMMENT ON COLUMN MODRED.PEDIDO_TRANSPORTE.PETR_DT_ENTREGA IS 'Data da entregado material da coleta.';
-- FIM ESTORIA 4

--Queiroz Ligação de usuario com transportadora



ALTER TABLE MODRED.USUARIO 
ADD (TRAN_ID NUMBER );

CREATE INDEX IN_FK_USUA_TRAN ON MODRED.USUARIO (TRAN_ID);

ALTER TABLE MODRED.USUARIO
ADD CONSTRAINT FK_USUA_TRAN FOREIGN KEY
(
  TRAN_ID 
)
REFERENCES MODRED.TRANSPORTADORA
(
  TRAN_ID 
)
ENABLE;

COMMENT ON COLUMN MODRED.USUARIO.TRAN_ID IS 'Transportadora a qual o usuário está associado.';


commit;



--Fim Queiroz

-- CRIANDO NOVO STATUS DO PEDIDO DE TRANSPORTE (FINALIZAÇÃO / ENTREGUE)
INSERT INTO MODRED.STATUS_PEDIDO_TRANSPORTE (STPT_ID, STPT_TX_DESCRICAO) VALUES (6, 'ENTREGUE');
COMMIT;

-- MODIFICANDO A COLUNA DATA RECEBIMENTO NO RECEBIMENTO DA COLETA.
ALTER TABLE MODRED.RECEBIMENTO_COLETA
MODIFY RECI_DT_RECEBIMENTO TIMESTAMP;