--Estoria 2890
DROP INDEX MODRED.IN_FK_CETR_LABO;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE 
DROP CONSTRAINT FK_CETR_LABO; 

ALTER TABLE MODRED.CENTRO_TRANSPLANTE 
DROP COLUMN LABO_ID;

DELETE FROM MODRED.ENDERECO_CONTATO_AUD
WHERE LABO_ID IS NOT NULL;

ALTER TABLE MODRED.ENDERECO_CONTATO_AUD 
DROP COLUMN LABO_ID;

DELETE FROM MODRED.ENDERECO_CONTATO
WHERE LABO_ID IS NOT NULL;

ALTER TABLE MODRED.ENDERECO_CONTATO 
DROP COLUMN LABO_ID;

DELETE FROM PERMISSAO WHERE RECU_ID = 86 AND PERF_ID = 5;
DELETE FROM RECURSO WHERE RECU_ID = 86;

DROP SEQUENCE SQ_INCO_ID; 

DROP INDEX MODRED.IN_FK_INCO_LABO;

ALTER TABLE MODRED.INSTRUCAO_COLETA
DROP CONSTRAINT FK_INCO_LABO;

DROP TABLE MODRED.INSTRUCAO_COLETA;

ALTER TABLE MODRED.EXAME_AUD 
DROP COLUMN LABO_ID;

ALTER TABLE MODRED.EXAME_AUD 
DROP COLUMN EXAM_DT_COLETA_AMOSTRA;

ALTER TABLE MODRED.EXAME_AUD 
DROP COLUMN EXAM_IN_LABORATORIO_PARTICULAR;

DROP INDEX MODRED.IN_FK_EXAM_LABO;

ALTER TABLE MODRED.EXAME
DROP CONSTRAINT FK_EXAM_LABO;

ALTER TABLE MODRED.EXAME 
DROP COLUMN LABO_ID;

ALTER TABLE MODRED.EXAME 
DROP COLUMN EXAM_DT_COLETA_AMOSTRA;

ALTER TABLE MODRED.EXAME 
DROP COLUMN EXAM_IN_LABORATORIO_PARTICULAR;

ALTER TABLE MODRED.LABORATORIO 
DROP COLUMN LABO_IN_FAZ_CT;

ALTER TABLE MODRED.LABORATORIO 
RENAME COLUMN LABO_TX_NOME TO LABO_NOME;

DELETE FROM MODRED.PEDIDO_EXAME;
COMMIT;

ALTER TABLE MODRED.PEDIDO_EXAME 
ADD (PEEX_NR_STATUS NUMBER NOT NULL);

ALTER TABLE MODRED.PEDIDO_EXAME 
DROP COLUMN LABO_ID;

ALTER TABLE MODRED.PEDIDO_EXAME 
DROP COLUMN STPX_ID;

ALTER TABLE MODRED.PEDIDO_EXAME 
DROP COLUMN PEEX_DT_COLETA_AMOSTRA;

ALTER TABLE MODRED.PEDIDO_EXAME 
DROP COLUMN PEEX_DT_RECEBIMENTO_AMOSTRA;

DROP INDEX MODRED.IN_FK_PEEX_LABO;

DROP INDEX IN_FK_PEEX_STPX;

ALTER TABLE MODRED.PEDIDO_EXAME
DROP CONSTRAINT FK_PEEX_LABO;

ALTER TABLE MODRED.PEDIDO_EXAME
DROP CONSTRAINT FK_PEEX_STPX;

DROP TABLE MODRED.STATUS_PEDIDO_EXAME; 

ALTER TABLE MODRED.TIPO_EXAME_LOCUS 
DROP CONSTRAINT FK_TIEL_LOCU;

ALTER TABLE MODRED.TIPO_EXAME_LOCUS 
DROP CONSTRAINT FK_TIEL_TIEX;

DROP TABLE MODRED.TIPO_EXAME_LOCUS;
DROP TABLE MODRED.TIPO_EXAME;
--Fim Estoria 2890

--ESTORIA 2874

DELETE FROM  "MODRED"."PERMISSAO" WHERE RECU_ID =84 AND  PERF_ID = 18;
DELETE FROM  "MODRED"."RECURSO" WHERE RECU_ID = '84';
DELETE FROM  "MODRED"."PERFIL" WHERE PERF_ID = 18;
DELETE FROM  "MODRED"."USUARIO_PERFIL" WHERE USUA_ID=18 AND  PERF_ID=18;
DELETE FROM  "MODRED"."USUARIO" WHERE USUA_ID=18;
DELETE FRON "MODRED"."TIPO_TAREFA" WHERE TITA_ID=60;
COMMIT;

ALTER TABLE MODRED.USUARIO 
DROP COLUMN LABO_ID;

DELETE FRON "MODRED"."TIPO_TAREFA" WHERE TITA_ID=61;
commit;

ALTER TABLE PEDIDO_EXAME 
DROP COLUMN EXAM_ID;

ALTER TABLE PEDIDO_EXAME 
DROP COLUMN TIEX_ID;


DROP INDEX MODRED.IN_FK_DOAD_REGI_ORIGEM;

ALTER TABLE MODRED.DOADOR
DROP CONSTRAINT FK_DOAD_REGI_ORIGEM;

DROP INDEX MODRED.IN_FK_DOAD_REGI_PAGAMENTO;

ALTER TABLE MODRED.DOADOR
DROP CONSTRAINT FK_DOAD_REGI_PAGAMENTO;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_NR_IDADE;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN DOAD_NR_IDADE;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_NR_GRID;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN DOAD_NR_GRID;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN REGI_ID_ORIGEM;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN REGI_ID_ORIGEM;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN REGI_ID_PAGAMENTO;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN REGI_ID_PAGAMENTO;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_IN_TIPO;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN DOAD_IN_TIPO;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_TX_ID_REGISTRO;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN DOAD_TX_ID_REGISTRO;

ALTER TABLE MODRED.DOADOR  
MODIFY (DOAD_TX_NOME NOT NULL);

ALTER TABLE MODRED.DOADOR  
MODIFY (DOAD_TX_NOME_MAE NOT NULL);

ALTER TABLE MODRED.DOADOR  
MODIFY (DOAD_TX_ABO NULL);

ALTER TABLE MODRED.DOADOR  
MODIFY (DOAD_VL_PESO NULL);

ALTER TABLE MODRED.DOADOR  
MODIFY (LABO_ID NOT NULL);

DROP INDEX MODRED.IN_FK_REGI_PAIS;

ALTER TABLE MODRED.REGISTRO
DROP CONSTRAINT FK_REGI_PAIS;

DROP TABLE MODRED.REGISTRO;


