CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_RELA_ID FOR MODRED.SQ_RELA_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RELATORIO FOR MODRED.RELATORIO;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_HIBU_ID FOR MODRED.SQ_HIBU_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.HISTORICO_BUSCA FOR MODRED.HISTORICO_BUSCA;

--Estoria 2890
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_PEDIDO_EXAME FOR MODRED.STATUS_PEDIDO_EXAME;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_EXAME FOR MODRED.TIPO_EXAME;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_EXAME_LOCUS FOR MODRED.TIPO_EXAME_LOCUS;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.INSTRUCAO_COLETA FOR MODRED.INSTRUCAO_COLETA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_INCO_ID FOR MODRED.SQ_INCO_ID;
--fim Estoria 2890

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_DOAD_ID FOR MODRED.SQ_DOAD_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.REGISTRO FOR MODRED.REGISTRO;


-- SINONIMOS DA TABELA DE RESERVA DOADOR INTERNACIONAL
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_REDI_ID FOR MODRED.SQ_REDI_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESERVA_DOADOR_INTERNACIONAL FOR MODRED.RESERVA_DOADOR_INTERNACIONAL;
