CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_GEDO_ID" FOR "MODRED"."SQ_GEDO_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_VGBD_ID" FOR "MODRED"."SQ_VGBD_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_VGED_ID" FOR "MODRED"."SQ_VGED_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_GEPA_ID" FOR "MODRED"."SQ_GEPA_ID";

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.GENOTIPO_PACIENTE FOR MODRED.GENOTIPO_PACIENTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_GENOTIPO_PACIENTE FOR MODRED.VALOR_GENOTIPO_PACIENTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_GENOTIPO_EXPAND_PACIENTE FOR MODRED.VALOR_GENOTIPO_EXPAND_PACIENTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_GENOTIPO_BUSCA_PACIENTE FOR MODRED.VALOR_GENOTIPO_BUSCA_PACIENTE;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.GENOTIPO_DOADOR FOR MODRED.GENOTIPO_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_GENOTIPO_DOADOR FOR MODRED.VALOR_GENOTIPO_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_GENOTIPO_EXPAND_DOADOR FOR MODRED.VALOR_GENOTIPO_EXPAND_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.VALOR_GENOTIPO_BUSCA_DOADOR FOR MODRED.VALOR_GENOTIPO_BUSCA_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.proc_criar_match_fake FOR MODRED.proc_criar_match_fake;
commit;

-- GRANTS ENVOLVENDO A TABELA LOCUS_PEDIDO_EXAME
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.LOCUS_PEDIDO_EXAME FOR MODRED.LOCUS_PEDIDO_EXAME;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_LOPE_ID FOR MODRED.SQ_LOPE_ID;


CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_EXAME_AUD FOR MODRED.PEDIDO_EXAME_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.LOCUS_PEDIDO_EXAME_AUD FOR MODRED.LOCUS_PEDIDO_EXAME_AUD;