/*
* Roolback das tabelas de negócio
*
* Autor: Bruno Sousa
*
*/
DROP TABLE USUARIO_PERFIL;

DROP SEQUENCE MODRED.SQ_PERF_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_PERF_ID;
DROP TABLE PERFIL CASCADE CONSTRAINTS;
DROP SYNONYM MODRED_APLICACAO.PERFIL;

DROP SEQUENCE MODRED.SQ_USUA_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_USUA_ID;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP SYNONYM MODRED_APLICACAO.USUARIO;

DROP SEQUENCE MODRED.SQ_PACI_NR_RMR;
DROP SYNONYM MODRED_APLICACAO.SQ_PACI_NR_RMR;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP SYNONYM MODRED_APLICACAO.PACIENTE;

DROP TABLE ETNIA;
DROP SYNONYM MODRED_APLICACAO.ETNIA;

DROP TABLE RACA;
DROP SYNONYM MODRED_APLICACAO.RACA;

DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP SYNONYM MODRED_APLICACAO.PAIS; 

DROP TABLE UF;
DROP SYNONYM MODRED_APLICACAO.UF;

DROP SEQUENCE MODRED.SQ_COEN_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_COEN_ID;
DROP TABLE CONTATO_ENDERECO;
DROP SYNONYM MODRED_APLICACAO.CONTATO_ENDERECO; 

DROP SEQUENCE SQ_RESP_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_RESP_ID;
DROP TABLE RESPONSAVEL;
DROP SYNONYM MODRED_APLICACAO.RESPONSAVEL; 

DROP SEQUENCE MODRED.SQ_COTE_ID;
DROP SYNONYM MODRED_APLICACAO.SQ_COTE_ID ;
DROP TABLE CONTATO_TELEFONICO;
DROP SYNONYM MODRED_APLICACAO.CONTATO_TELEFONICO; 

/*
* Roolback das tabelas que ser�o usadas pelo servi�o de busca por cep
*
* Autor: Bruno Sousa
*
*/
  drop SYNONYM "MODRED_APLICACAO"."TIPO_LOGRADOURO_CORREIO";
  drop SYNONYM "MODRED_APLICACAO"."PAIS_CORREIO";
  drop SYNONYM "MODRED_APLICACAO"."UNIDADE_FEDERATIVA_CORREIO";
  drop SYNONYM "MODRED_APLICACAO"."LOCALIDADE_CORREIO";
  drop SYNONYM "MODRED_APLICACAO"."BAIRRO_CORREIO";
  drop SYNONYM "MODRED_APLICACAO"."LOGRADOURO_CORREIO";
  
  DROP TABLE LOGRADOURO_CORREIO;
  DROP TABLE BAIRRO_CORREIO;
  DROP TABLE LOCALIDADE_CORREIO;
  DROP TABLE UNIDADE_FEDERATIVA_CORREIO;
  DROP TABLE PAIS_CORREIO;
  DROP TABLE TIPO_LOGRADOURO_CORREIO;
  
/* Fim */
