/* *
 * Script de login 
 * 
 * Autor: Bruno Sousa
 * 
 * */

/* *
 * Script para as tabelas de DOMÍNIO
 * 07/06/2017
 * */
 /* INÍCIO DO SCRIPT DE DOMÍNIO */

 -- ETNIA -- 
-- TABELA
CREATE TABLE "MODRED"."ETNIA" 
("ETNI_ID" NUMBER NOT NULL ENABLE, 
"ETNI_TX_NOME" VARCHAR2(50 BYTE) NOT NULL, 
CONSTRAINT "PK_ETNI" PRIMARY KEY ("ETNI_ID") ENABLE
) ;
COMMENT ON COLUMN "MODRED"."ETNIA"."ETNI_ID" IS 'Identificador da etnia';
COMMENT ON COLUMN "MODRED"."ETNIA"."ETNI_TX_NOME" IS 'Nome da etnia ';
COMMENT ON TABLE "MODRED"."ETNIA"  IS 'Etnias indígenas';   

-- RACA --
-- TABELA
CREATE TABLE "MODRED"."RACA" 
("RACA_ID" NUMBER NOT NULL ENABLE, 
"RACA_TX_NOME" VARCHAR2(50 BYTE) NOT NULL,
CONSTRAINT "PK_RACA" PRIMARY KEY ("RACA_ID") ENABLE
);
COMMENT ON COLUMN "MODRED"."RACA"."RACA_ID" IS 'Identifiador da raca';
COMMENT ON COLUMN "MODRED"."RACA"."RACA_TX_NOME" IS 'Nome da raca';
COMMENT ON TABLE "MODRED"."RACA"  IS 'Raças';

-- PAIS -- 
-- TABELA
CREATE TABLE "MODRED"."PAIS" 
("PAIS_ID" NUMBER NOT NULL ENABLE, 
"PAIS_TX_NOME" VARCHAR2(100 BYTE) NOT NULL,
CONSTRAINT "PK_PAIS" PRIMARY KEY ("PAIS_ID") ENABLE
);
COMMENT ON COLUMN "MODRED"."PAIS"."PAIS_ID" IS 'Identificador do País';
COMMENT ON COLUMN "MODRED"."PAIS"."PAIS_TX_NOME" IS 'Nome do País ';
COMMENT ON TABLE "MODRED"."PAIS"  IS 'Paises';

-- UF -- 
-- TABELA
CREATE TABLE "MODRED"."UF" 
("UF_SIGLA" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
"UF_TX_NOME" VARCHAR2(80 BYTE), 
CONSTRAINT "PK_UF" PRIMARY KEY ("UF_SIGLA")  ENABLE
) ;
COMMENT ON COLUMN "MODRED"."UF"."UF_SIGLA" IS 'Identificador de UF';
COMMENT ON COLUMN "MODRED"."UF"."UF_TX_NOME" IS 'Nome da UF';
COMMENT ON TABLE "MODRED"."UF"  IS 'Unidades Federativas do Brasil';

/* FIM DO SCRIPT DE DOMÍNIO */
 
-- USUÁRIO --
-- TABELA
CREATE TABLE "MODRED"."USUARIO" 
 (	"USUA_ID" NUMBER NOT NULL ENABLE, 
"USUA_TX_NOME" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
"USUA_TX_USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"USUA_TX_PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "PK_USUA" PRIMARY KEY ("USUA_ID") ENABLE
 );
COMMENT ON COLUMN "MODRED"."USUARIO"."USUA_ID" IS 'Identificador do usuário';
COMMENT ON COLUMN "MODRED"."USUARIO"."USUA_TX_NOME" IS 'Nome do usuário';
COMMENT ON COLUMN "MODRED"."USUARIO"."USUA_TX_USERNAME" IS 'Username do usuário';
COMMENT ON COLUMN "MODRED"."USUARIO"."USUA_TX_PASSWORD" IS 'Password do usuário criptografada';
COMMENT ON TABLE "MODRED"."USUARIO"  IS 'Usuários do sistema';

-- SEQUENCE
CREATE SEQUENCE "MODRED"."SQ_USUA_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;


-- PERFIL --
-- TABELA
CREATE TABLE "MODRED"."PERFIL" 
 (	"PERF_ID" NUMBER NOT NULL ENABLE, 
"PERF_TX_DESCRICAO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "PK_PERF" PRIMARY KEY ("PERF_ID") ENABLE
 );
COMMENT ON COLUMN "MODRED"."PERFIL"."PERF_ID" IS 'Identificador do perfil';
COMMENT ON COLUMN "MODRED"."PERFIL"."PERF_TX_DESCRICAO" IS 'Descrição do perfil';
COMMENT ON TABLE "MODRED"."PERFIL"  IS 'Quadro de perfis do sistema';

-- SEQUENCE
CREATE SEQUENCE "MODRED"."SQ_PERF_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;


-- USUARIO_PERFIL -- 
-- TABELA
CREATE TABLE "MODRED"."USUARIO_PERFIL" 
 (	"USUA_ID" NUMBER NOT NULL ENABLE, 
	"PERF_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_USPE" PRIMARY KEY ("USUA_ID", "PERF_ID") ENABLE, 
	 CONSTRAINT "FK_USPE_USUA" FOREIGN KEY ("USUA_ID")
	  REFERENCES "MODRED"."USUARIO" ("USUA_ID") ENABLE, 
	 CONSTRAINT "FK_USPE_PERF" FOREIGN KEY ("PERF_ID")
	  REFERENCES "MODRED"."PERFIL" ("PERF_ID") ENABLE
  );
COMMENT ON COLUMN "MODRED"."USUARIO_PERFIL"."USUA_ID" IS 'Identificador do usuário';
COMMENT ON COLUMN "MODRED"."USUARIO_PERFIL"."PERF_ID" IS 'Identificador do Perfil';
COMMENT ON TABLE "MODRED"."USUARIO_PERFIL"  IS 'Perfis dos usuários';

-- INDEX
CREATE INDEX "MODRED"."IN_FK_USPE_PERF" ON "MODRED"."USUARIO_PERFIL" ("PERF_ID");
CREATE INDEX "MODRED"."IN_FK_USPE_USUA" ON "MODRED"."USUARIO_PERFIL" ("USUA_ID");


-- CONTATO_ENDERECO --
-- TABELA
CREATE TABLE CONTATO_ENDERECO 
(
  COEN_ID NUMBER NOT NULL 
, COEN_ID_PAIS NUMBER NOT NULL
, COEN_CEP VARCHAR2(9 BYTE) 
, COEN_TX_TIPO_LOGRADOURO VARCHAR2(100 BYTE) 
, COEN_TX_NOME VARCHAR2(255 BYTE) -- alterar para COEN_TX_NOME_LOGRADOURO
, COEN_NR_NUMERO NUMBER 
, COEN_TX_COMPLEMENTO VARCHAR2(50 BYTE) 
, COEN_TX_BAIRRO VARCHAR2(255 BYTE) 
, COEN_TX_MUNICIPIO VARCHAR2(255 BYTE) 
, COEN_TX_SIGLA_UF VARCHAR2(2 BYTE) 
, COEN_TX_ENDERECO_ESTRANGEIRO VARCHAR2(255 BYTE) 
, CONSTRAINT PK_COEN PRIMARY KEY (COEN_ID) ENABLE 
);
ALTER TABLE CONTATO_ENDERECO
ADD CONSTRAINT FK_COEN_PAIS FOREIGN KEY (COEN_ID_PAIS) REFERENCES PAIS (PAIS_ID) ENABLE;

COMMENT ON TABLE CONTATO_ENDERECO IS 'Dados de endereço do Paciente';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_ID IS 'Identificador do Contato';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_ID_PAIS IS 'Campo de referencia de pais';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_CEP IS 'CEP do contato';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_TX_TIPO_LOGRADOURO IS 'Tipo do Logradouro';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_TX_NOME IS 'Nome do Logradouro';-- alterar para COEN_TX_NOME_LOGRADOURO
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_NR_NUMERO IS 'Número do logradouro';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_TX_COMPLEMENTO IS 'Complemento do logradouro';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_TX_BAIRRO IS 'Bairro do logradouro';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_TX_MUNICIPIO IS 'Municipio do logradouro';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_TX_SIGLA_UF IS 'Sigla da UF';
COMMENT ON COLUMN CONTATO_ENDERECO.COEN_TX_ENDERECO_ESTRANGEIRO IS 'Endereço completo quando for estrangeiro';

-- SEQUENCE
CREATE SEQUENCE "MODRED"."SQ_COEN_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;


-- RESPONSÁVEL --
-- TABELA
CREATE TABLE MODRED.RESPONSAVEL 
(
  RESP_ID NUMBER NOT NULL 
, RESP_TX_CPF VARCHAR2(11) 
, RESP_TX_NOME VARCHAR2(255) 
, RESP_TX_PARENTESCO VARCHAR2(20) 
, CONSTRAINT PK_RESP PRIMARY KEY (RESP_ID) ENABLE 
);
COMMENT ON TABLE MODRED.RESPONSAVEL IS 'Responsável do paciente';
COMMENT ON COLUMN MODRED.RESPONSAVEL.RESP_ID IS 'Identificador do responsável';
COMMENT ON COLUMN MODRED.RESPONSAVEL.RESP_TX_CPF IS 'CPF do Responsável';
COMMENT ON COLUMN MODRED.RESPONSAVEL.RESP_TX_NOME IS 'Nome do Responsável';
COMMENT ON COLUMN MODRED.RESPONSAVEL.RESP_TX_PARENTESCO IS 'Parentesco com o paciente';

-- SEQUENCE
CREATE SEQUENCE "MODRED"."SQ_RESP_ID" MINVALUE 1  MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;


-- PACIENTE --
-- TABELA
CREATE TABLE MODRED.PACIENTE 
(
  PACI_NR_RMR NUMBER NOT NULL --ALTERAR PARA PACI_ID_RMR
, PACI_TX_CPF VARCHAR2(11 BYTE) 
, PACI_TX_CNS VARCHAR2(15 BYTE) 
, PACI_TX_NOME VARCHAR2(255 BYTE) NOT NULL
, PACI_TX_NOME_MAE VARCHAR2(255 BYTE) 
, PACI_IN_SEXO VARCHAR2(1 BYTE)  NOT NULL
, RACA_ID NUMBER  NOT NULL
, ETNI_ID NUMBER 
, PACI_TX_ABO VARCHAR2(3 BYTE)  NOT NULL-- ALTERAR PARA PACI_IN_ABO
, PAIS_ID NUMBER  NOT NULL
, UF_SIGLA VARCHAR2(2 BYTE) 
, PACI_TX_EMAIL VARCHAR2(100 BYTE) 
, USUA_ID NUMBER  NOT NULL
, PACI_DT_CADASTRO DATE  NOT NULL
, COEN_ID NUMBER  NOT NULL
, PACI_DT_NASCIMENTO DATE NOT NULL
, RESP_ID NUMBER
, CONSTRAINT PACIENTE_PK PRIMARY KEY (PACI_NR_RMR) ENABLE 
);

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_COEN FOREIGN KEY (COEN_ID) REFERENCES MODRED.CONTATO_ENDERECO (COEN_ID) ENABLE;

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAIS (PAIS_ID) ENABLE;

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_ETNI FOREIGN KEY (ETNI_ID) REFERENCES ETNIA (ETNI_ID) ENABLE;

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_RACA FOREIGN KEY (RACA_ID) REFERENCES RACA (RACA_ID) ENABLE;

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_UF FOREIGN KEY (UF_SIGLA) REFERENCES UF (UF_SIGLA) ENABLE;

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_RESP FOREIGN KEY (RESP_ID) REFERENCES RESPONSAVEL (RESP_ID) ENABLE;

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_USUA FOREIGN KEY (USUA_ID) REFERENCES USUARIO (USUA_ID) ENABLE;

COMMENT ON TABLE MODRED.PACIENTE IS 'Pacientes';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_NR_RMR IS 'Identificador do Paciente';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_TX_CPF IS 'Cpf do paciente';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_TX_CNS IS 'Cartão nacional de saúde do paciente';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_TX_NOME IS 'Nome do paciente';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_TX_NOME_MAE IS 'Nome da Mãe do Paciente';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_IN_SEXO IS 'Sexo do paciente (M - masculinho, F- Feminino)';
COMMENT ON COLUMN MODRED.PACIENTE.RACA_ID IS 'Referencia para tabela raça ';
COMMENT ON COLUMN MODRED.PACIENTE.ETNI_ID IS 'Referencia para a tabela etnia ';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_TX_ABO IS 'Tipo sanguíneo (A+,B+,A-,B-,AB+,AB-,O+,O-)';--ALTERAR PARA PACI_IN_ABO
COMMENT ON COLUMN MODRED.PACIENTE.PAIS_ID IS 'Id do país da nacionalidade';
COMMENT ON COLUMN MODRED.PACIENTE.UF_SIGLA IS 'Id do estado da naturadlidade';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_TX_EMAIL IS 'Email do paciente';
COMMENT ON COLUMN MODRED.PACIENTE.USUA_ID IS 'Referencia do usuario que cadastrou';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_DT_CADASTRO IS 'Data do cadastro ';
COMMENT ON COLUMN MODRED.PACIENTE.COEN_ID IS 'Referencia do endereco do paciente';
COMMENT ON COLUMN MODRED.PACIENTE.PACI_DT_NASCIMENTO IS 'Data de nascimento do Paciente';

-- SEQUENCE
CREATE SEQUENCE  "MODRED"."SQ_PACI_NR_RMR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;


-- CONTATO TELEFONICO
-- TABELA
CREATE TABLE MODRED.CONTATO_TELEFONICO 
(
  COTE_ID NUMBER NOT NULL 
, COTE_IN_PRINCIPAL NUMBER NOT NULL -- ADICIONAR DEFAULT 0
, COTE_TX_NOME VARCHAR2(100 BYTE) NOT NULL
, COTE_IN_TIPO NUMBER NOT NULL
, COTE_NR_COD_INTER NUMBER(5, 0) NOT NULL
, COTE_NR_COD_AREA NUMBER(5, 0) NOT NULL
, COTE_NR_NUMERO NUMBER NOT NULL
, COTE_TX_COMPLEMENTO VARCHAR2(20 BYTE) 
, PACI_NR_RMR NUMBER NOT NULL
, CONSTRAINT PK_COTE PRIMARY KEY (COTE_ID) ENABLE 
);

ALTER TABLE MODRED.CONTATO_TELEFONICO
ADD CONSTRAINT FK_COTE_PACI FOREIGN KEY (PACI_NR_RMR) REFERENCES PACIENTE (PACI_NR_RMR) ENABLE;

COMMENT ON TABLE MODRED.CONTATO_TELEFONICO IS 'Contatos Telefonicos dos Pacientes';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_ID IS 'Identificador do Contato Telefônico';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_IN_PRINCIPAL IS 'Flag para definir se o telefone será o principal ou não (1- principal, 0-não principal)';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_TX_NOME IS 'Nome do Contato';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_IN_TIPO IS 'Tipo do contato (1 - fixo, 2- celular)';-- ALTERAR AS OPCOES PARA F-FIXO E C-CELULAR
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_NR_COD_INTER IS 'Código Internacional';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_NR_COD_AREA IS 'Código de área';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_NR_NUMERO IS 'Número do Telefone';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.COTE_TX_COMPLEMENTO IS 'Complemento do Telefone';
COMMENT ON COLUMN MODRED.CONTATO_TELEFONICO.PACI_NR_RMR IS 'Referencia do paciente que possui os telefones';

-- SEQUENCE
CREATE SEQUENCE  "MODRED"."SQ_COTE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

--- Fim ---

/* *
 * Inserts dados básicos 
 * 
 * Autor: Cintia Oliveira
 * 
 * */

-- PERFIL
INSERT INTO MODRED.PERFIL (PERF_ID, PERF_TX_DESCRICAO) VALUES (1, 'MÉDICO');

-- USUARIO
INSERT INTO MODRED.USUARIO VALUES (SQ_USUA_ID.NEXTVAL, 'MEDICO GENERICO', 'MEDICO', '123456');

--USUARIO_PERFIL
INSERT INTO USUARIO_PERFIL VALUES (SQ_USUA_ID.CURRVAL, 1);

-- RAÇAS
INSERT INTO MODRED.RACA (RACA_ID, RACA_TX_NOME) VALUES (1, 'BRANCA');
INSERT INTO MODRED.RACA (RACA_ID, RACA_TX_NOME) VALUES (2, 'PRETA');
INSERT INTO MODRED.RACA (RACA_ID, RACA_TX_NOME) VALUES (3, 'AMARELA');
INSERT INTO MODRED.RACA (RACA_ID, RACA_TX_NOME) VALUES (4, 'PARDA');
INSERT INTO MODRED.RACA (RACA_ID, RACA_TX_NOME) VALUES (5, 'INDÍGENA');

-- ETNIAS
INSERT INTO MODRED.ETNIA VALUES(1,'ACONÃ');
INSERT INTO MODRED.ETNIA VALUES(2,'AIKANÁ');
INSERT INTO MODRED.ETNIA VALUES(3,'AIMORE');
INSERT INTO MODRED.ETNIA VALUES(4,'AJURU');
INSERT INTO MODRED.ETNIA VALUES(5,'AKUNTSÚ');
INSERT INTO MODRED.ETNIA VALUES(6,'ALAKETESU');
INSERT INTO MODRED.ETNIA VALUES(7,'ALANTESU');
INSERT INTO MODRED.ETNIA VALUES(8,'AMANAYÉ');
INSERT INTO MODRED.ETNIA VALUES(9,'AMONDÁWA');
INSERT INTO MODRED.ETNIA VALUES(10,'ANACÉ');
INSERT INTO MODRED.ETNIA VALUES(11,'ANAMBÉ');
INSERT INTO MODRED.ETNIA VALUES(12,'APALAÍ');
INSERT INTO MODRED.ETNIA VALUES(13,'APIAKÁ');
INSERT INTO MODRED.ETNIA VALUES(14,'APINAYÉ');
INSERT INTO MODRED.ETNIA VALUES(15,'APOLIMA - ARARA');
INSERT INTO MODRED.ETNIA VALUES(16,'APURINÃ');
INSERT INTO MODRED.ETNIA VALUES(17,'ARANÃ');
INSERT INTO MODRED.ETNIA VALUES(18,'ARAPÁSO');
INSERT INTO MODRED.ETNIA VALUES(19,'ARAPIUN');
INSERT INTO MODRED.ETNIA VALUES(20,'ARARA DE RONDÔNIA');
INSERT INTO MODRED.ETNIA VALUES(21,'ARARA DO ACRE');
INSERT INTO MODRED.ETNIA VALUES(22,'ARARA DO ARIPUANÃ');
INSERT INTO MODRED.ETNIA VALUES(23,'ARARA DO PARÁ');
INSERT INTO MODRED.ETNIA VALUES(24,'ARAWETÉ');
INSERT INTO MODRED.ETNIA VALUES(25,'ARIKAPÚ');
INSERT INTO MODRED.ETNIA VALUES(26,'ARIKÉN');
INSERT INTO MODRED.ETNIA VALUES(27,'ARIKOSÉ');
INSERT INTO MODRED.ETNIA VALUES(28,'ARUÁ');
INSERT INTO MODRED.ETNIA VALUES(29,'ASHANINKA');
INSERT INTO MODRED.ETNIA VALUES(30,'ASURINI DO TOCANTINS');
INSERT INTO MODRED.ETNIA VALUES(31,'ASURINI DO XINGU');
INSERT INTO MODRED.ETNIA VALUES(32,'ATIKUM');
INSERT INTO MODRED.ETNIA VALUES(33,'AVA-CANOEIRO');
INSERT INTO MODRED.ETNIA VALUES(34,'AWETI');
INSERT INTO MODRED.ETNIA VALUES(35,'BAENÃ');
INSERT INTO MODRED.ETNIA VALUES(36,'BAKAIRÍ');
INSERT INTO MODRED.ETNIA VALUES(37,'BANAWA');
INSERT INTO MODRED.ETNIA VALUES(38,'BANIWA');
INSERT INTO MODRED.ETNIA VALUES(39,'BARÁ');
INSERT INTO MODRED.ETNIA VALUES(40,'BARASÁNA');
INSERT INTO MODRED.ETNIA VALUES(41,'BARÉ');
INSERT INTO MODRED.ETNIA VALUES(42,'BÓRA');
INSERT INTO MODRED.ETNIA VALUES(43,'BORARI');
INSERT INTO MODRED.ETNIA VALUES(44,'BORORO');
INSERT INTO MODRED.ETNIA VALUES(45,'BOTOCUDO');
INSERT INTO MODRED.ETNIA VALUES(46,'CATOKIN');
INSERT INTO MODRED.ETNIA VALUES(47,'CHAMAKÓKO');
INSERT INTO MODRED.ETNIA VALUES(48,'CHARRUA');
INSERT INTO MODRED.ETNIA VALUES(49,'CHIQUITÁNO');
INSERT INTO MODRED.ETNIA VALUES(50,'CINTA LARGA');
INSERT INTO MODRED.ETNIA VALUES(51,'DÂW');
INSERT INTO MODRED.ETNIA VALUES(52,'DENÍ');
INSERT INTO MODRED.ETNIA VALUES(53,'DESÁNA');
INSERT INTO MODRED.ETNIA VALUES(54,'DIAHÓI');
INSERT INTO MODRED.ETNIA VALUES(55,'DJEOROMITXÍ - JABUTÍ');
INSERT INTO MODRED.ETNIA VALUES(56,'ENAWENÊ-NAWÊ');
INSERT INTO MODRED.ETNIA VALUES(57,'FULNI-Ô');
INSERT INTO MODRED.ETNIA VALUES(58,'GALIBI DO OIAPOQUE');
INSERT INTO MODRED.ETNIA VALUES(59,'GALIBÍ MARWÓRNO');
INSERT INTO MODRED.ETNIA VALUES(60,'GAVIÃO DE RONDÔNIA');
INSERT INTO MODRED.ETNIA VALUES(61,'GAVIÃO KRIKATEJÊ');
INSERT INTO MODRED.ETNIA VALUES(62,'GAVIÃO PARKATEJÊ');
INSERT INTO MODRED.ETNIA VALUES(63,'GAVIÃO PUKOBIÊ');
INSERT INTO MODRED.ETNIA VALUES(64,'GUAIKURÚ');
INSERT INTO MODRED.ETNIA VALUES(65,'GUAJÁ');
INSERT INTO MODRED.ETNIA VALUES(66,'GUARANÍ');
INSERT INTO MODRED.ETNIA VALUES(67,'GUARANI KAIOWÁ');
INSERT INTO MODRED.ETNIA VALUES(68,'GUARANI MBYA');
INSERT INTO MODRED.ETNIA VALUES(69,'GUARANI NHANDEVA');
INSERT INTO MODRED.ETNIA VALUES(70,'GUATÓ');
INSERT INTO MODRED.ETNIA VALUES(71,'HAHAINTESU');
INSERT INTO MODRED.ETNIA VALUES(72,'HALOTESU');
INSERT INTO MODRED.ETNIA VALUES(73,'HIXKARYÁNA');
INSERT INTO MODRED.ETNIA VALUES(74,'HUPDA');
INSERT INTO MODRED.ETNIA VALUES(75,'IKPENG');
INSERT INTO MODRED.ETNIA VALUES(76,'INGARIKÓ');
INSERT INTO MODRED.ETNIA VALUES(77,'IRÁNTXE');
INSERT INTO MODRED.ETNIA VALUES(78,'ISSÉ');
INSERT INTO MODRED.ETNIA VALUES(79,'JAMAMADÍ');
INSERT INTO MODRED.ETNIA VALUES(80,'JARAWÁRA');
INSERT INTO MODRED.ETNIA VALUES(81,'JARICUNA');
INSERT INTO MODRED.ETNIA VALUES(82,'JAVAÉ');
INSERT INTO MODRED.ETNIA VALUES(83,'JERIPANCÓ');
INSERT INTO MODRED.ETNIA VALUES(84,'JUMA');
INSERT INTO MODRED.ETNIA VALUES(85,'KA''APOR');
INSERT INTO MODRED.ETNIA VALUES(86,'KADIWÉU');
INSERT INTO MODRED.ETNIA VALUES(87,'KAETÉ');
INSERT INTO MODRED.ETNIA VALUES(88,'KAHYANA');
INSERT INTO MODRED.ETNIA VALUES(89,'KAIABI');
INSERT INTO MODRED.ETNIA VALUES(90,'KAIMBÉ');
INSERT INTO MODRED.ETNIA VALUES(91,'KAINGANG');
INSERT INTO MODRED.ETNIA VALUES(92,'KAIXANA');
INSERT INTO MODRED.ETNIA VALUES(93,'KALABAÇA');
INSERT INTO MODRED.ETNIA VALUES(94,'KALANKÓ');
INSERT INTO MODRED.ETNIA VALUES(95,'KALAPALO');
INSERT INTO MODRED.ETNIA VALUES(96,'KAMAKÃ');
INSERT INTO MODRED.ETNIA VALUES(97,'KAMAYURÁ');
INSERT INTO MODRED.ETNIA VALUES(98,'KAMBA');
INSERT INTO MODRED.ETNIA VALUES(99,'KAMBÉBA');
INSERT INTO MODRED.ETNIA VALUES(100,'KAMBIWÁ');
INSERT INTO MODRED.ETNIA VALUES(101,'KAMBIWÁ-PIPIPÃ');
INSERT INTO MODRED.ETNIA VALUES(102,'KAMPÉ');
INSERT INTO MODRED.ETNIA VALUES(103,'KANAMANTI');
INSERT INTO MODRED.ETNIA VALUES(104,'KANAMARÍ');
INSERT INTO MODRED.ETNIA VALUES(105,'KANELA');
INSERT INTO MODRED.ETNIA VALUES(106,'KANELA APANIEKRA');
INSERT INTO MODRED.ETNIA VALUES(107,'KANELA RANKOCAMEKRA');
INSERT INTO MODRED.ETNIA VALUES(108,'KANINDÉ');
INSERT INTO MODRED.ETNIA VALUES(109,'KANOÉ');
INSERT INTO MODRED.ETNIA VALUES(110,'KANTARURÉ');
INSERT INTO MODRED.ETNIA VALUES(111,'KAPINAWÁ');
INSERT INTO MODRED.ETNIA VALUES(112,'KAPON PATAMÓNA');
INSERT INTO MODRED.ETNIA VALUES(113,'KARAFAWYANA');
INSERT INTO MODRED.ETNIA VALUES(114,'KARAJÁ');
INSERT INTO MODRED.ETNIA VALUES(115,'KARAPANÃ');
INSERT INTO MODRED.ETNIA VALUES(116,'KARAPOTÓ');
INSERT INTO MODRED.ETNIA VALUES(117,'KARIJÓ');
INSERT INTO MODRED.ETNIA VALUES(118,'KARIPUNA');
INSERT INTO MODRED.ETNIA VALUES(119,'KARIPÚNA DO AMAPÁ');
INSERT INTO MODRED.ETNIA VALUES(120,'KARIRI');
INSERT INTO MODRED.ETNIA VALUES(121,'KARIRI - XOCÓ');
INSERT INTO MODRED.ETNIA VALUES(122,'KARITIANA');
INSERT INTO MODRED.ETNIA VALUES(123,'KATAWIXÍ');
INSERT INTO MODRED.ETNIA VALUES(124,'KATUENA');
INSERT INTO MODRED.ETNIA VALUES(125,'KATUKINA DO ACRE');
INSERT INTO MODRED.ETNIA VALUES(126,'KAWAHÍB');
INSERT INTO MODRED.ETNIA VALUES(127,'KAXARARI');
INSERT INTO MODRED.ETNIA VALUES(128,'KAXINAWÁ');
INSERT INTO MODRED.ETNIA VALUES(129,'KAXIXÓ');
INSERT INTO MODRED.ETNIA VALUES(130,'KAXUYANA');
INSERT INTO MODRED.ETNIA VALUES(131,'KAYAPÓ');
INSERT INTO MODRED.ETNIA VALUES(132,'KAYUISIANA');
INSERT INTO MODRED.ETNIA VALUES(133,'KINIKINAU');
INSERT INTO MODRED.ETNIA VALUES(134,'KIRIRI');
INSERT INTO MODRED.ETNIA VALUES(135,'KISÊDJÊ');
INSERT INTO MODRED.ETNIA VALUES(136,'KITHAULU');
INSERT INTO MODRED.ETNIA VALUES(137,'KOIUPANKÁ');
INSERT INTO MODRED.ETNIA VALUES(138,'KOKAMA');
INSERT INTO MODRED.ETNIA VALUES(139,'KOKUIREGATEJÊ');
INSERT INTO MODRED.ETNIA VALUES(140,'KONTANAWÁ');
INSERT INTO MODRED.ETNIA VALUES(141,'KORÚBO');
INSERT INTO MODRED.ETNIA VALUES(142,'KRAHÔ');
INSERT INTO MODRED.ETNIA VALUES(143,'KRAHÔ-KANELA');
INSERT INTO MODRED.ETNIA VALUES(144,'KRENÁK');
INSERT INTO MODRED.ETNIA VALUES(145,'KRENYÊ');
INSERT INTO MODRED.ETNIA VALUES(146,'KRIKATI');
INSERT INTO MODRED.ETNIA VALUES(147,'KUBEO');
INSERT INTO MODRED.ETNIA VALUES(148,'KUIKURO');
INSERT INTO MODRED.ETNIA VALUES(149,'KUJUBIM');
INSERT INTO MODRED.ETNIA VALUES(150,'KULINA MADIJÁ');
INSERT INTO MODRED.ETNIA VALUES(151,'KULINA PÁNO');
INSERT INTO MODRED.ETNIA VALUES(152,'KURIPAKO');
INSERT INTO MODRED.ETNIA VALUES(153,'KURUÁYA');
INSERT INTO MODRED.ETNIA VALUES(154,'KWAZÁ');
INSERT INTO MODRED.ETNIA VALUES(155,'LAIANA');
INSERT INTO MODRED.ETNIA VALUES(156,'LAKONDÊ');
INSERT INTO MODRED.ETNIA VALUES(157,'LATUNDÊ');
INSERT INTO MODRED.ETNIA VALUES(158,'MAKÚ');
INSERT INTO MODRED.ETNIA VALUES(159,'MAKÚNA');
INSERT INTO MODRED.ETNIA VALUES(160,'MAKURÁP');
INSERT INTO MODRED.ETNIA VALUES(161,'MAKUXÍ');
INSERT INTO MODRED.ETNIA VALUES(162,'MAMAINDÊ');
INSERT INTO MODRED.ETNIA VALUES(163,'MANAO');
INSERT INTO MODRED.ETNIA VALUES(164,'MANCHINERI');
INSERT INTO MODRED.ETNIA VALUES(165,'MANDUKA');
INSERT INTO MODRED.ETNIA VALUES(166,'MARAGUA');
INSERT INTO MODRED.ETNIA VALUES(167,'MARIMÃ');
INSERT INTO MODRED.ETNIA VALUES(168,'MARÚBO');
INSERT INTO MODRED.ETNIA VALUES(169,'MATIPÚ');
INSERT INTO MODRED.ETNIA VALUES(170,'MATÍS');
INSERT INTO MODRED.ETNIA VALUES(171,'MATSÉS');
INSERT INTO MODRED.ETNIA VALUES(172,'MAWAYÁNA');
INSERT INTO MODRED.ETNIA VALUES(173,'MAXAKALI');
INSERT INTO MODRED.ETNIA VALUES(174,'MAYA');
INSERT INTO MODRED.ETNIA VALUES(175,'MAYTAPU');
INSERT INTO MODRED.ETNIA VALUES(176,'MEHINÁKU');
INSERT INTO MODRED.ETNIA VALUES(177,'MIGUELÉNO');
INSERT INTO MODRED.ETNIA VALUES(178,'MIRÁNHA');
INSERT INTO MODRED.ETNIA VALUES(179,'MIRITITAPUIA');
INSERT INTO MODRED.ETNIA VALUES(180,'MUCURIM');
INSERT INTO MODRED.ETNIA VALUES(181,'MUNDURUKÚ');
INSERT INTO MODRED.ETNIA VALUES(182,'MÚRA');
INSERT INTO MODRED.ETNIA VALUES(183,'MYNKY');
INSERT INTO MODRED.ETNIA VALUES(184,'NADËB');
INSERT INTO MODRED.ETNIA VALUES(185,'NAHUKUÁ');
INSERT INTO MODRED.ETNIA VALUES(186,'NAMBIKWÁRA');
INSERT INTO MODRED.ETNIA VALUES(187,'NARAVUTE');
INSERT INTO MODRED.ETNIA VALUES(188,'NAWA');
INSERT INTO MODRED.ETNIA VALUES(189,'NEGAROTÊ');
INSERT INTO MODRED.ETNIA VALUES(190,'NINÁM');
INSERT INTO MODRED.ETNIA VALUES(191,'NUKINÍ');
INSERT INTO MODRED.ETNIA VALUES(192,'OFAYÉ');
INSERT INTO MODRED.ETNIA VALUES(193,'ORO WIN');
INSERT INTO MODRED.ETNIA VALUES(194,'PAIAKU');
INSERT INTO MODRED.ETNIA VALUES(195,'PAKAA NOVA');
INSERT INTO MODRED.ETNIA VALUES(196,'PALIKUR');
INSERT INTO MODRED.ETNIA VALUES(197,'PANARÁ');
INSERT INTO MODRED.ETNIA VALUES(198,'PANKARÁ');
INSERT INTO MODRED.ETNIA VALUES(199,'PANKARARÉ');
INSERT INTO MODRED.ETNIA VALUES(200,'PANKARARÚ');
INSERT INTO MODRED.ETNIA VALUES(201,'PANKARARÚ - KARUAZU');
INSERT INTO MODRED.ETNIA VALUES(202,'PANKARU');
INSERT INTO MODRED.ETNIA VALUES(203,'PAPAVÓ');
INSERT INTO MODRED.ETNIA VALUES(204,'PARAKANÃ');
INSERT INTO MODRED.ETNIA VALUES(205,'PARESÍ');
INSERT INTO MODRED.ETNIA VALUES(206,'PARINTINTIM');
INSERT INTO MODRED.ETNIA VALUES(207,'PATAXÓ');
INSERT INTO MODRED.ETNIA VALUES(208,'PATAXO HÁ-HÁ-HÁ');
INSERT INTO MODRED.ETNIA VALUES(209,'PAUMARÍ');
INSERT INTO MODRED.ETNIA VALUES(210,'PAUMELENHO');
INSERT INTO MODRED.ETNIA VALUES(211,'PIRAHÃ');
INSERT INTO MODRED.ETNIA VALUES(212,'PIRATAPUYA');
INSERT INTO MODRED.ETNIA VALUES(213,'PIRI-PIRI');
INSERT INTO MODRED.ETNIA VALUES(214,'PITAGUARI');
INSERT INTO MODRED.ETNIA VALUES(215,'POTIGUARA');
INSERT INTO MODRED.ETNIA VALUES(216,'POYANÁWA');
INSERT INTO MODRED.ETNIA VALUES(217,'PURI');
INSERT INTO MODRED.ETNIA VALUES(218,'PUROBORÁ');
INSERT INTO MODRED.ETNIA VALUES(219,'RIKBAKTSA');
INSERT INTO MODRED.ETNIA VALUES(220,'SABANÊ');
INSERT INTO MODRED.ETNIA VALUES(221,'SAKURABIAT');
INSERT INTO MODRED.ETNIA VALUES(222,'SALAMÃY');
INSERT INTO MODRED.ETNIA VALUES(223,'SANUMÁ');
INSERT INTO MODRED.ETNIA VALUES(224,'SAPARÁ');
INSERT INTO MODRED.ETNIA VALUES(225,'SARARE');
INSERT INTO MODRED.ETNIA VALUES(226,'SATERÉ-MAWÉ');
INSERT INTO MODRED.ETNIA VALUES(227,'SAWENTESU');
INSERT INTO MODRED.ETNIA VALUES(228,'SHANENÁWA');
INSERT INTO MODRED.ETNIA VALUES(229,'SIRIANO');
INSERT INTO MODRED.ETNIA VALUES(230,'SURUÍ DE RONDÔNIA');
INSERT INTO MODRED.ETNIA VALUES(231,'SURUÍ DO PARÁ');
INSERT INTO MODRED.ETNIA VALUES(232,'TABAJARA');
INSERT INTO MODRED.ETNIA VALUES(233,'TAMOIO');
INSERT INTO MODRED.ETNIA VALUES(234,'TAPAJÓS');
INSERT INTO MODRED.ETNIA VALUES(235,'TAPAYUNA');
INSERT INTO MODRED.ETNIA VALUES(236,'TAPEBA');
INSERT INTO MODRED.ETNIA VALUES(237,'TAPIRAPÉ');
INSERT INTO MODRED.ETNIA VALUES(238,'TAPIUNS');
INSERT INTO MODRED.ETNIA VALUES(239,'TAPUIA');
INSERT INTO MODRED.ETNIA VALUES(240,'TARIANA');
INSERT INTO MODRED.ETNIA VALUES(241,'TAULIPÁNG');
INSERT INTO MODRED.ETNIA VALUES(242,'TAWANDÊ');
INSERT INTO MODRED.ETNIA VALUES(243,'TEMBÉ');
INSERT INTO MODRED.ETNIA VALUES(244,'TENETEHARA');
INSERT INTO MODRED.ETNIA VALUES(245,'TENHARIM');
INSERT INTO MODRED.ETNIA VALUES(246,'TERENA');
INSERT INTO MODRED.ETNIA VALUES(247,'TIKÚNA');
INSERT INTO MODRED.ETNIA VALUES(248,'TIMBIRA');
INSERT INTO MODRED.ETNIA VALUES(249,'TINGUI-BOTÓ');
INSERT INTO MODRED.ETNIA VALUES(250,'TIRIYÓ');
INSERT INTO MODRED.ETNIA VALUES(251,'TORÁ');
INSERT INTO MODRED.ETNIA VALUES(252,'TREMEMBÉ');
INSERT INTO MODRED.ETNIA VALUES(253,'TRUKÁ');
INSERT INTO MODRED.ETNIA VALUES(254,'TRUMÁI');
INSERT INTO MODRED.ETNIA VALUES(255,'TUKANO');
INSERT INTO MODRED.ETNIA VALUES(256,'TUMBALALÁ');
INSERT INTO MODRED.ETNIA VALUES(257,'TUNAYANA');
INSERT INTO MODRED.ETNIA VALUES(258,'TUPAIU');
INSERT INTO MODRED.ETNIA VALUES(259,'TUPARÍ');
INSERT INTO MODRED.ETNIA VALUES(260,'TUPINAMBÁ');
INSERT INTO MODRED.ETNIA VALUES(261,'TUPINAMBARANÁ');
INSERT INTO MODRED.ETNIA VALUES(262,'TUPINIQUIM');
INSERT INTO MODRED.ETNIA VALUES(263,'TURIWÁRA');
INSERT INTO MODRED.ETNIA VALUES(264,'TUXÁ');
INSERT INTO MODRED.ETNIA VALUES(265,'TUYÚCA');
INSERT INTO MODRED.ETNIA VALUES(266,'UMUTINA');
INSERT INTO MODRED.ETNIA VALUES(267,'URUCÚ');
INSERT INTO MODRED.ETNIA VALUES(268,'URU-EU-WAU-WAU');
INSERT INTO MODRED.ETNIA VALUES(269,'WAI WAI');
INSERT INTO MODRED.ETNIA VALUES(270,'WAIÃPY');
INSERT INTO MODRED.ETNIA VALUES(271,'WAIKISU');
INSERT INTO MODRED.ETNIA VALUES(272,'WAIMIRI ATROARI');
INSERT INTO MODRED.ETNIA VALUES(273,'WAKALITESU');
INSERT INTO MODRED.ETNIA VALUES(274,'WANANA');
INSERT INTO MODRED.ETNIA VALUES(275,'WAPIXANA');
INSERT INTO MODRED.ETNIA VALUES(276,'WAREKENA');
INSERT INTO MODRED.ETNIA VALUES(277,'WASSÚ');
INSERT INTO MODRED.ETNIA VALUES(278,'WASUSU');
INSERT INTO MODRED.ETNIA VALUES(279,'WAUJA');
INSERT INTO MODRED.ETNIA VALUES(280,'WAYANA');
INSERT INTO MODRED.ETNIA VALUES(281,'WITÓTO');
INSERT INTO MODRED.ETNIA VALUES(282,'XACRIABÁ');
INSERT INTO MODRED.ETNIA VALUES(283,'XAMBIOÁ');
INSERT INTO MODRED.ETNIA VALUES(284,'XAVANTE');
INSERT INTO MODRED.ETNIA VALUES(285,'XERENTE');
INSERT INTO MODRED.ETNIA VALUES(286,'XEREU');
INSERT INTO MODRED.ETNIA VALUES(287,'XETÁ');
INSERT INTO MODRED.ETNIA VALUES(288,'XIPÁYA');
INSERT INTO MODRED.ETNIA VALUES(289,'XOCÓ');
INSERT INTO MODRED.ETNIA VALUES(290,'XOKLÉNG');
INSERT INTO MODRED.ETNIA VALUES(291,'XUCURU');
INSERT INTO MODRED.ETNIA VALUES(292,'XUCURU - KARIRI');
INSERT INTO MODRED.ETNIA VALUES(293,'YAIPIYANA');
INSERT INTO MODRED.ETNIA VALUES(294,'YAMINÁWA');
INSERT INTO MODRED.ETNIA VALUES(295,'YANOMÁMI');
INSERT INTO MODRED.ETNIA VALUES(296,'YANOMÁN');
INSERT INTO MODRED.ETNIA VALUES(297,'YAWALAPITÍ');
INSERT INTO MODRED.ETNIA VALUES(298,'YAWANAWÁ');
INSERT INTO MODRED.ETNIA VALUES(299,'YE''KUANA');
INSERT INTO MODRED.ETNIA VALUES(300,'YUDJÁ');
INSERT INTO MODRED.ETNIA VALUES(301,'YURUTÍ');
INSERT INTO MODRED.ETNIA VALUES(302,'ZO''É');
INSERT INTO MODRED.ETNIA VALUES(303,'ZORÓ');
INSERT INTO MODRED.ETNIA VALUES(304,'ZURUAHÃ');

COMMIT;

-- UFS
INSERT INTO MODRED.UF VALUES('AC','RIO BRANCO');
INSERT INTO MODRED.UF VALUES('AL','ALAGOAS');
INSERT INTO MODRED.UF VALUES('AP','AMAPÁ');
INSERT INTO MODRED.UF VALUES('AM','AMAZONAS');
INSERT INTO MODRED.UF VALUES('BA','BAHIA');
INSERT INTO MODRED.UF VALUES('CE','CEARÁ');
INSERT INTO MODRED.UF VALUES('DF','DISTRITO FEDERAL');
INSERT INTO MODRED.UF VALUES('ES','ESPÍRITO SANTO');
INSERT INTO MODRED.UF VALUES('GO','GOIÁS');
INSERT INTO MODRED.UF VALUES('MA','MARANHÃO');
INSERT INTO MODRED.UF VALUES('MT','MATO GROSSO');
INSERT INTO MODRED.UF VALUES('MS','MATO GROSSO DO SUL');
INSERT INTO MODRED.UF VALUES('MG','MINAS GERAIS');
INSERT INTO MODRED.UF VALUES('PA','PARÁ');
INSERT INTO MODRED.UF VALUES('PB','PARAÍBA');
INSERT INTO MODRED.UF VALUES('PR','PARANÁ');
INSERT INTO MODRED.UF VALUES('PE','PERNAMBUCO');
INSERT INTO MODRED.UF VALUES('PI','PIAUÍ');
INSERT INTO MODRED.UF VALUES('RJ','RIO DE JANEIRO');
INSERT INTO MODRED.UF VALUES('RN','RIO GRANDE DO NORTE');
INSERT INTO MODRED.UF VALUES('RS','RIO GRANDE DO SUL');
INSERT INTO MODRED.UF VALUES('RO','RONDÔNIA');
INSERT INTO MODRED.UF VALUES('RR','RORAIMA');
INSERT INTO MODRED.UF VALUES('SC','SANTA CATARINA');
INSERT INTO MODRED.UF VALUES('SP','SÃO PAULO');
INSERT INTO MODRED.UF VALUES('SE','SERGIPE');
INSERT INTO MODRED.UF VALUES('TO','TOCANTINS');

-- PAISES
INSERT INTO MODRED.PAIS VALUES(1,'AFEGANISTAO');
INSERT INTO MODRED.PAIS VALUES(2,'AFRICA DO SUL');
INSERT INTO MODRED.PAIS VALUES(3,'ALBANIA');
INSERT INTO MODRED.PAIS VALUES(4,'ALEMANHA');
INSERT INTO MODRED.PAIS VALUES(5,'ANDORRA');
INSERT INTO MODRED.PAIS VALUES(6,'ANGOLA');
INSERT INTO MODRED.PAIS VALUES(7,'ANGUILLA');
INSERT INTO MODRED.PAIS VALUES(8,'ANTARCTICA');
INSERT INTO MODRED.PAIS VALUES(9,'ANTIGUA E BARBUDA');
INSERT INTO MODRED.PAIS VALUES(10,'ANTILHAS HOLANDESAS');
INSERT INTO MODRED.PAIS VALUES(11,'ARABIA SAUDITA');
INSERT INTO MODRED.PAIS VALUES(12,'ARGELIA');
INSERT INTO MODRED.PAIS VALUES(13,'ARGENTINA');
INSERT INTO MODRED.PAIS VALUES(14,'ARMENIA');
INSERT INTO MODRED.PAIS VALUES(15,'ARUBA');
INSERT INTO MODRED.PAIS VALUES(16,'AUSTRALIA');
INSERT INTO MODRED.PAIS VALUES(17,'AUSTRIA');
INSERT INTO MODRED.PAIS VALUES(18,'AZERBAIDJAO');
INSERT INTO MODRED.PAIS VALUES(19,'BAHAMAS');
INSERT INTO MODRED.PAIS VALUES(20,'BANGLADESH');
INSERT INTO MODRED.PAIS VALUES(21,'BARBADOS');
INSERT INTO MODRED.PAIS VALUES(22,'BAREIN');
INSERT INTO MODRED.PAIS VALUES(23,'BELARUS');
INSERT INTO MODRED.PAIS VALUES(24,'BELGICA');
INSERT INTO MODRED.PAIS VALUES(25,'BELIZE');
INSERT INTO MODRED.PAIS VALUES(26,'BENIN');
INSERT INTO MODRED.PAIS VALUES(27,'BERMUDA');
INSERT INTO MODRED.PAIS VALUES(28,'BOLIVIA');
INSERT INTO MODRED.PAIS VALUES(29,'BOSNIA-HERZEGOVINA');
INSERT INTO MODRED.PAIS VALUES(30,'BOTSWANA');
INSERT INTO MODRED.PAIS VALUES(31,'BRASIL');
INSERT INTO MODRED.PAIS VALUES(32,'BRUNEI');
INSERT INTO MODRED.PAIS VALUES(33,'BULGARIA');
INSERT INTO MODRED.PAIS VALUES(34,'BURKINA FASSO');
INSERT INTO MODRED.PAIS VALUES(35,'BURUNDI');
INSERT INTO MODRED.PAIS VALUES(36,'BUTAO');
INSERT INTO MODRED.PAIS VALUES(37,'CABO VERDE');
INSERT INTO MODRED.PAIS VALUES(38,'CAMAROES');
INSERT INTO MODRED.PAIS VALUES(39,'CAMBOJA');
INSERT INTO MODRED.PAIS VALUES(40,'CANADA');
INSERT INTO MODRED.PAIS VALUES(41,'CATAR');
INSERT INTO MODRED.PAIS VALUES(42,'CAZAQUISTAO');
INSERT INTO MODRED.PAIS VALUES(43,'CHADE');
INSERT INTO MODRED.PAIS VALUES(44,'CHILE');
INSERT INTO MODRED.PAIS VALUES(45,'CHINA');
INSERT INTO MODRED.PAIS VALUES(46,'CHIPRE');
INSERT INTO MODRED.PAIS VALUES(47,'CINGAPURA');
INSERT INTO MODRED.PAIS VALUES(48,'COLOMBIA');
INSERT INTO MODRED.PAIS VALUES(49,'COMORES');
INSERT INTO MODRED.PAIS VALUES(50,'CONGO');
INSERT INTO MODRED.PAIS VALUES(51,'COREIA DO NORTE');
INSERT INTO MODRED.PAIS VALUES(52,'COREIA DO SUL');
INSERT INTO MODRED.PAIS VALUES(53,'COSTA DO MARFIM');
INSERT INTO MODRED.PAIS VALUES(54,'COSTA RICA');
INSERT INTO MODRED.PAIS VALUES(55,'CROACIA');
INSERT INTO MODRED.PAIS VALUES(56,'CUBA');
INSERT INTO MODRED.PAIS VALUES(57,'DINAMARCA');
INSERT INTO MODRED.PAIS VALUES(58,'DJIBUTI');
INSERT INTO MODRED.PAIS VALUES(59,'DOMINICA');
INSERT INTO MODRED.PAIS VALUES(60,'EGITO');
INSERT INTO MODRED.PAIS VALUES(61,'EL SALVADOR');
INSERT INTO MODRED.PAIS VALUES(62,'EMIRADOS ARABES UNIDOS');
INSERT INTO MODRED.PAIS VALUES(63,'EQUADOR');
INSERT INTO MODRED.PAIS VALUES(64,'ERITREIA');
INSERT INTO MODRED.PAIS VALUES(65,'ESLOVAQUIA');
INSERT INTO MODRED.PAIS VALUES(66,'ESLOVENIA');
INSERT INTO MODRED.PAIS VALUES(67,'ESPANHA');
INSERT INTO MODRED.PAIS VALUES(68,'ESTADOS UNIDOS DA AMERICA');
INSERT INTO MODRED.PAIS VALUES(69,'ESTONIA');
INSERT INTO MODRED.PAIS VALUES(70,'ETIOPIA');
INSERT INTO MODRED.PAIS VALUES(71,'FEDERACAO RUSSA');
INSERT INTO MODRED.PAIS VALUES(72,'FIJI');
INSERT INTO MODRED.PAIS VALUES(73,'FILIPINAS');
INSERT INTO MODRED.PAIS VALUES(74,'FINLANDIA');
INSERT INTO MODRED.PAIS VALUES(75,'FRANCA');
INSERT INTO MODRED.PAIS VALUES(76,'FRANCA METROPOLITANA');
INSERT INTO MODRED.PAIS VALUES(77,'GABAO');
INSERT INTO MODRED.PAIS VALUES(78,'GAMBIA');
INSERT INTO MODRED.PAIS VALUES(79,'GANA');
INSERT INTO MODRED.PAIS VALUES(80,'GEORGIA');
INSERT INTO MODRED.PAIS VALUES(81,'GIBRALTAR');
INSERT INTO MODRED.PAIS VALUES(82,'GRA-BRETANHA');
INSERT INTO MODRED.PAIS VALUES(83,'GRANADA');
INSERT INTO MODRED.PAIS VALUES(84,'GRECIA');
INSERT INTO MODRED.PAIS VALUES(85,'GROENLANDIA');
INSERT INTO MODRED.PAIS VALUES(86,'GUADALUPE');
INSERT INTO MODRED.PAIS VALUES(87,'GUAM');
INSERT INTO MODRED.PAIS VALUES(88,'GUATEMALA');
INSERT INTO MODRED.PAIS VALUES(89,'GUIANA');
INSERT INTO MODRED.PAIS VALUES(90,'GUIANA FRANCESA');
INSERT INTO MODRED.PAIS VALUES(91,'GUINE');
INSERT INTO MODRED.PAIS VALUES(92,'GUINE EQUATORIAL');
INSERT INTO MODRED.PAIS VALUES(93,'GUINE-BISSAU');
INSERT INTO MODRED.PAIS VALUES(94,'HAITI');
INSERT INTO MODRED.PAIS VALUES(95,'HOLANDA');
INSERT INTO MODRED.PAIS VALUES(96,'HONDURAS');
INSERT INTO MODRED.PAIS VALUES(97,'HONG KONG');
INSERT INTO MODRED.PAIS VALUES(98,'HUNGRIA');
INSERT INTO MODRED.PAIS VALUES(99,'IEMEN');
INSERT INTO MODRED.PAIS VALUES(100,'ILHA BOUVET');
INSERT INTO MODRED.PAIS VALUES(101,'ILHA CHRISTMAS');
INSERT INTO MODRED.PAIS VALUES(102,'ILHA NORFOLK');
INSERT INTO MODRED.PAIS VALUES(103,'ILHAS CAYMAN');
INSERT INTO MODRED.PAIS VALUES(104,'ILHAS COCOS');
INSERT INTO MODRED.PAIS VALUES(105,'ILHAS COOK');
INSERT INTO MODRED.PAIS VALUES(106,'ILHAS DE GUERNSEY');
INSERT INTO MODRED.PAIS VALUES(107,'ILHAS DE JERSEY');
INSERT INTO MODRED.PAIS VALUES(108,'ILHAS FAROE');
INSERT INTO MODRED.PAIS VALUES(109,'ILHAS GEORGIA DO SUL E ILHAS SANDWICH DO SUL');
INSERT INTO MODRED.PAIS VALUES(110,'ILHAS HEARD E MAC DONALD');
INSERT INTO MODRED.PAIS VALUES(111,'ILHAS MALVINAS');
INSERT INTO MODRED.PAIS VALUES(112,'ILHAS MARIANA');
INSERT INTO MODRED.PAIS VALUES(113,'ILHAS MARSHALL');
INSERT INTO MODRED.PAIS VALUES(114,'ILHAS PITCAIRN');
INSERT INTO MODRED.PAIS VALUES(115,'ILHAS REUNIAO');
INSERT INTO MODRED.PAIS VALUES(116,'ILHAS SALOMAO');
INSERT INTO MODRED.PAIS VALUES(117,'ILHAS SANTA HELENA');
INSERT INTO MODRED.PAIS VALUES(118,'ILHAS SVALBARD E JAN MAYEN');
INSERT INTO MODRED.PAIS VALUES(119,'ILHAS TOKELAU');
INSERT INTO MODRED.PAIS VALUES(120,'ILHAS TURKS E CAICOS');
INSERT INTO MODRED.PAIS VALUES(121,'ILHAS VIRGENS');
INSERT INTO MODRED.PAIS VALUES(122,'ILHAS VIRGENS BRITANICAS');
INSERT INTO MODRED.PAIS VALUES(123,'ILHAS WALLIS E FUTUNA');
INSERT INTO MODRED.PAIS VALUES(124,'INDIA');
INSERT INTO MODRED.PAIS VALUES(125,'INDONESIA');
INSERT INTO MODRED.PAIS VALUES(126,'IRA');
INSERT INTO MODRED.PAIS VALUES(127,'IRAQUE');
INSERT INTO MODRED.PAIS VALUES(128,'IRLANDA');
INSERT INTO MODRED.PAIS VALUES(129,'ISLANDIA');
INSERT INTO MODRED.PAIS VALUES(130,'ISRAEL');
INSERT INTO MODRED.PAIS VALUES(131,'ITALIA');
INSERT INTO MODRED.PAIS VALUES(132,'IUGOSLAVIA');
INSERT INTO MODRED.PAIS VALUES(133,'JAMAICA');
INSERT INTO MODRED.PAIS VALUES(134,'JAPAO');
INSERT INTO MODRED.PAIS VALUES(135,'JORDANIA');
INSERT INTO MODRED.PAIS VALUES(136,'KIRIBATI');
INSERT INTO MODRED.PAIS VALUES(137,'KUWEIT');
INSERT INTO MODRED.PAIS VALUES(138,'LAOS');
INSERT INTO MODRED.PAIS VALUES(139,'LESOTO');
INSERT INTO MODRED.PAIS VALUES(140,'LETONIA');
INSERT INTO MODRED.PAIS VALUES(141,'LIBANO');
INSERT INTO MODRED.PAIS VALUES(142,'LIBERIA');
INSERT INTO MODRED.PAIS VALUES(143,'LIBIA');
INSERT INTO MODRED.PAIS VALUES(144,'LIECHTENSTEIN');
INSERT INTO MODRED.PAIS VALUES(145,'LITUANIA');
INSERT INTO MODRED.PAIS VALUES(146,'LUXEMBURGO');
INSERT INTO MODRED.PAIS VALUES(147,'MACAU');
INSERT INTO MODRED.PAIS VALUES(148,'MACEDONIA');
INSERT INTO MODRED.PAIS VALUES(149,'MADAGASCAR');
INSERT INTO MODRED.PAIS VALUES(150,'MALASIA');
INSERT INTO MODRED.PAIS VALUES(151,'MALAUI');
INSERT INTO MODRED.PAIS VALUES(152,'MALDIVAS');
INSERT INTO MODRED.PAIS VALUES(153,'MALI');
INSERT INTO MODRED.PAIS VALUES(154,'MALTA');
INSERT INTO MODRED.PAIS VALUES(155,'MARROCOS');
INSERT INTO MODRED.PAIS VALUES(156,'MARTINICA');
INSERT INTO MODRED.PAIS VALUES(157,'MAURICIO');
INSERT INTO MODRED.PAIS VALUES(158,'MAURITANIA');
INSERT INTO MODRED.PAIS VALUES(159,'MAYOTTE');
INSERT INTO MODRED.PAIS VALUES(160,'MEXICO');
INSERT INTO MODRED.PAIS VALUES(161,'MIANMAR');
INSERT INTO MODRED.PAIS VALUES(162,'MICRONESIA');
INSERT INTO MODRED.PAIS VALUES(163,'MOCAMBIQUE');
INSERT INTO MODRED.PAIS VALUES(164,'MOLDAVIA');
INSERT INTO MODRED.PAIS VALUES(165,'MONACO');
INSERT INTO MODRED.PAIS VALUES(166,'MONGOLIA');
INSERT INTO MODRED.PAIS VALUES(167,'MONTSERRAT');
INSERT INTO MODRED.PAIS VALUES(168,'NAMIBIA');
INSERT INTO MODRED.PAIS VALUES(169,'NAURU');
INSERT INTO MODRED.PAIS VALUES(170,'NEPAL');
INSERT INTO MODRED.PAIS VALUES(171,'NICARAGUA');
INSERT INTO MODRED.PAIS VALUES(172,'NIGER');
INSERT INTO MODRED.PAIS VALUES(173,'NIGERIA');
INSERT INTO MODRED.PAIS VALUES(174,'NIUE');
INSERT INTO MODRED.PAIS VALUES(175,'NORUEGA');
INSERT INTO MODRED.PAIS VALUES(176,'NOVA CALEDONIA');
INSERT INTO MODRED.PAIS VALUES(177,'NOVA ZELANDIA');
INSERT INTO MODRED.PAIS VALUES(178,'OMA');
INSERT INTO MODRED.PAIS VALUES(179,'PALAU');
INSERT INTO MODRED.PAIS VALUES(180,'PANAMA');
INSERT INTO MODRED.PAIS VALUES(181,'PAPUA NOVA GUINE');
INSERT INTO MODRED.PAIS VALUES(182,'PAQUISTAO');
INSERT INTO MODRED.PAIS VALUES(183,'PARAGUAI');
INSERT INTO MODRED.PAIS VALUES(184,'PERU');
INSERT INTO MODRED.PAIS VALUES(185,'POLINESIA FRANCESA');
INSERT INTO MODRED.PAIS VALUES(186,'POLONIA');
INSERT INTO MODRED.PAIS VALUES(187,'PORTO RICO');
INSERT INTO MODRED.PAIS VALUES(188,'PORTUGAL');
INSERT INTO MODRED.PAIS VALUES(189,'QUENIA');
INSERT INTO MODRED.PAIS VALUES(190,'QUIRGUIZIA');
INSERT INTO MODRED.PAIS VALUES(191,'REPUBLICA CENTRO-AFRICANA');
INSERT INTO MODRED.PAIS VALUES(192,'REPUBLICA DOMINICANA');
INSERT INTO MODRED.PAIS VALUES(193,'REPUBLICA TCHECA');
INSERT INTO MODRED.PAIS VALUES(194,'ROMENIA');
INSERT INTO MODRED.PAIS VALUES(195,'RUANDA');
INSERT INTO MODRED.PAIS VALUES(196,'SAHARA OCIDENTAL');
INSERT INTO MODRED.PAIS VALUES(197,'SAMOA AMERICANA');
INSERT INTO MODRED.PAIS VALUES(198,'SAMOA OCIDENTAL');
INSERT INTO MODRED.PAIS VALUES(199,'SAN MARINO');
INSERT INTO MODRED.PAIS VALUES(200,'SANTA LUCIA');
INSERT INTO MODRED.PAIS VALUES(201,'SAO CRISTOVAO E NEVIS');
INSERT INTO MODRED.PAIS VALUES(202,'SAO PIERRE E MIQUELON');
INSERT INTO MODRED.PAIS VALUES(203,'SAO TOME E PRINCIPE');
INSERT INTO MODRED.PAIS VALUES(204,'SAO VICENTE E GRANADINAS');
INSERT INTO MODRED.PAIS VALUES(205,'SEICHELES');
INSERT INTO MODRED.PAIS VALUES(206,'SENEGAL');
INSERT INTO MODRED.PAIS VALUES(207,'SERRA LEOA');
INSERT INTO MODRED.PAIS VALUES(208,'SIRIA');
INSERT INTO MODRED.PAIS VALUES(209,'SOMALIA');
INSERT INTO MODRED.PAIS VALUES(210,'SRI LANKA');
INSERT INTO MODRED.PAIS VALUES(211,'SUAZILANDIA');
INSERT INTO MODRED.PAIS VALUES(212,'SUDAO');
INSERT INTO MODRED.PAIS VALUES(213,'SUECIA');
INSERT INTO MODRED.PAIS VALUES(214,'SUICA');
INSERT INTO MODRED.PAIS VALUES(215,'SURINAME');
INSERT INTO MODRED.PAIS VALUES(216,'TADJIQUISTAO');
INSERT INTO MODRED.PAIS VALUES(217,'TAILANDIA');
INSERT INTO MODRED.PAIS VALUES(218,'TAIWAN');
INSERT INTO MODRED.PAIS VALUES(219,'TANZANIA');
INSERT INTO MODRED.PAIS VALUES(220,'TERRITORIOS FRANCESES MERIDIONAIS');
INSERT INTO MODRED.PAIS VALUES(221,'TIMOR LESTE');
INSERT INTO MODRED.PAIS VALUES(222,'TOGO');
INSERT INTO MODRED.PAIS VALUES(223,'TONGA');
INSERT INTO MODRED.PAIS VALUES(224,'TRINIDAD E TOBAGO');
INSERT INTO MODRED.PAIS VALUES(225,'TUNISIA');
INSERT INTO MODRED.PAIS VALUES(226,'TURCOMENIA');
INSERT INTO MODRED.PAIS VALUES(227,'TURQUIA');
INSERT INTO MODRED.PAIS VALUES(228,'TUVALU');
INSERT INTO MODRED.PAIS VALUES(229,'UCRANIA');
INSERT INTO MODRED.PAIS VALUES(230,'UGANDA');
INSERT INTO MODRED.PAIS VALUES(231,'URUGUAI');
INSERT INTO MODRED.PAIS VALUES(232,'UZBEQUISTAO');
INSERT INTO MODRED.PAIS VALUES(233,'VANUATU');
INSERT INTO MODRED.PAIS VALUES(234,'VATICANO');
INSERT INTO MODRED.PAIS VALUES(235,'VENEZUELA');
INSERT INTO MODRED.PAIS VALUES(236,'VIETNA');
INSERT INTO MODRED.PAIS VALUES(237,'ZAMBIA');
INSERT INTO MODRED.PAIS VALUES(238,'ZIMBABUE');

COMMIT;

--- Fim ---

/*
* Criação das tabelas que serão usadas pelo serviço de busca por cep
*
* Autor: Bruno Sousa
*
*/

  CREATE TABLE "MODRED"."TIPO_LOGRADOURO_CORREIO" 
   (	"TILC_ID" NUMBER NOT NULL ENABLE, 
	"TILC_TX_NOME" VARCHAR2(72 BYTE) NOT NULL ENABLE, 
	"TILC_TX_NOME_ABREVIADO" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TILC" PRIMARY KEY ("TILC_ID") ENABLE
   );

   COMMENT ON COLUMN "MODRED"."TIPO_LOGRADOURO_CORREIO"."TILC_ID" IS 'Chave do Tipo de Logradouro no DNE';
   COMMENT ON COLUMN "MODRED"."TIPO_LOGRADOURO_CORREIO"."TILC_TX_NOME" IS 'Nome Oficial do Tipo de Logradouro';
   COMMENT ON COLUMN "MODRED"."TIPO_LOGRADOURO_CORREIO"."TILC_TX_NOME_ABREVIADO" IS 'Abreviatura do Tipo de logradouro';
   COMMENT ON TABLE "MODRED"."TIPO_LOGRADOURO_CORREIO"  IS 'Tipos de Logradouros';
   
   
  CREATE TABLE "MODRED"."PAIS_CORREIO" 
   (	"PACO_ID" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"PACO_TX_NOME" VARCHAR2(72 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PACO" PRIMARY KEY ("PACO_ID") ENABLE
   );

   COMMENT ON COLUMN "MODRED"."PAIS_CORREIO"."PACO_ID" IS 'Sigla do País';
   COMMENT ON COLUMN "MODRED"."PAIS_CORREIO"."PACO_TX_NOME" IS 'Nome do País';
   COMMENT ON TABLE "MODRED"."PAIS_CORREIO"  IS 'Tabela de País';
   
   

  CREATE TABLE "MODRED"."UNIDADE_FEDERATIVA_CORREIO" 
   (	"UNFC_ID" NUMBER NOT NULL ENABLE, 
	"UNFC_TX_SIGLA" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"UNFC_TX_NOME" VARCHAR2(72 BYTE) NOT NULL ENABLE, 
	"PACO_ID" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_UNFC" PRIMARY KEY ("UNFC_ID") ENABLE, 
	 CONSTRAINT "FK_UNFC_PACO" FOREIGN KEY ("PACO_ID")
	  REFERENCES "MODRED"."PAIS_CORREIO" ("PACO_ID") ENABLE
   );

   COMMENT ON COLUMN "MODRED"."UNIDADE_FEDERATIVA_CORREIO"."UNFC_ID" IS 'Chave da UF no DNE';
   COMMENT ON COLUMN "MODRED"."UNIDADE_FEDERATIVA_CORREIO"."UNFC_TX_SIGLA" IS 'Sigla da Unidade da Federação';
   COMMENT ON COLUMN "MODRED"."UNIDADE_FEDERATIVA_CORREIO"."UNFC_TX_NOME" IS 'Nome da Unidade da Federação';
   COMMENT ON COLUMN "MODRED"."UNIDADE_FEDERATIVA_CORREIO"."PACO_ID" IS 'id da tabela país';
   COMMENT ON TABLE "MODRED"."UNIDADE_FEDERATIVA_CORREIO"  IS 'Unidade Federativa';
   
  CREATE INDEX "MODRED"."IN_FK_UNFC_PACO" ON "MODRED"."UNIDADE_FEDERATIVA_CORREIO" ("PACO_ID");
  

  CREATE TABLE "MODRED"."LOCALIDADE_CORREIO" 
   ("LOCC_ID" NUMBER NOT NULL ENABLE, 
	"LOCC_TX_NOME" VARCHAR2(72 BYTE) NOT NULL ENABLE, 
	"LOCC_TX_CEP" VARCHAR2(8 BYTE), 
	"LOCC_NR_CODIGO_IBGE" NUMBER, 
	"LOCC_IN_TIPO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"LOCC_ID_SUBORDINACAO" NUMBER, 
	"UNFC_ID" NUMBER, 
	 CONSTRAINT "PK_LOCO" PRIMARY KEY ("LOCC_ID") ENABLE, 
	 CONSTRAINT "FK_LOCC_UNFC" FOREIGN KEY ("UNFC_ID") 
         REFERENCES "MODRED"."UNIDADE_FEDERATIVA_CORREIO" ("UNFC_ID") ENABLE,
	 CONSTRAINT "CK_TP_LOCC" CHECK (LOCC_IN_TIPO in ('D', 'M', 'P', 'R')) 
   );

   COMMENT ON COLUMN "MODRED"."LOCALIDADE_CORREIO"."LOCC_ID" IS 'Chave da Localidade no DNE';
   COMMENT ON COLUMN "MODRED"."LOCALIDADE_CORREIO"."LOCC_TX_NOME" IS 'Nome Oficial da Localidade';
   COMMENT ON COLUMN "MODRED"."LOCALIDADE_CORREIO"."LOCC_TX_CEP" IS 'CEP da Localidade';
   COMMENT ON COLUMN "MODRED"."LOCALIDADE_CORREIO"."LOCC_NR_CODIGO_IBGE" IS 'Código IBGE da Localidade';
   COMMENT ON COLUMN "MODRED"."LOCALIDADE_CORREIO"."LOCC_IN_TIPO" IS 'Tipo da Localidade (D->Distrito, M->Município, P->Povoado, R->Região Administrativa)';
   COMMENT ON COLUMN "MODRED"."LOCALIDADE_CORREIO"."LOCC_ID_SUBORDINACAO" IS 'Chave que permite localizar os dados do município ao qual o distrito/povoado pertence.';
   COMMENT ON COLUMN "MODRED"."LOCALIDADE_CORREIO"."UNFC_ID" IS 'ID da tabela Unidade Federativa';
   COMMENT ON TABLE "MODRED"."LOCALIDADE_CORREIO"  IS 'Tabela de Localidades(Municípios)';

   CREATE INDEX "MODRED"."IN_FK_LOCC_UNFC" ON "MODRED"."LOCALIDADE_CORREIO" ("UNFC_ID");
   
  
  CREATE TABLE "MODRED"."BAIRRO_CORREIO" 
   (	"BACO_ID" NUMBER NOT NULL ENABLE, 
	"BACO_TX_NOME" VARCHAR2(72 BYTE) NOT NULL ENABLE, 
	"LOCC_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_BACO" PRIMARY KEY ("BACO_ID") ENABLE, 
	 CONSTRAINT "FK_BACO_LOCC" FOREIGN KEY ("LOCC_ID")
	  REFERENCES "MODRED"."LOCALIDADE_CORREIO" ("LOCC_ID") ENABLE
   );

   COMMENT ON COLUMN "MODRED"."BAIRRO_CORREIO"."BACO_ID" IS 'Chave do Bairro no DNE';
   COMMENT ON COLUMN "MODRED"."BAIRRO_CORREIO"."BACO_TX_NOME" IS 'Nome Oficial do Bairro';
   COMMENT ON COLUMN "MODRED"."BAIRRO_CORREIO"."LOCC_ID" IS 'ID da Tabela da Localidade';
   COMMENT ON TABLE "MODRED"."BAIRRO_CORREIO"  IS 'Bairro por Localidade';

   CREATE INDEX "MODRED"."IN_FK_BACO_LOCC" ON "MODRED"."BAIRRO_CORREIO" ("LOCC_ID");
   

  CREATE TABLE "MODRED"."LOGRADOURO_CORREIO" 
   ("LOGC_ID" NUMBER NOT NULL ENABLE, 
	"LOGC_TX_NOME" VARCHAR2(72 BYTE) NOT NULL ENABLE, 
	"LOGC_TX_CEP" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"TILC_ID" NUMBER NOT NULL ENABLE, 
	"BACO_ID_INICIAL" NUMBER NOT NULL ENABLE, 
	"BACO_ID_FINAL" NUMBER,
	"LOGC_NR_CHAVE_DNE" NUMBER,
	 CONSTRAINT "PK_LOGC" PRIMARY KEY ("LOGC_ID") ENABLE, 
	 CONSTRAINT "FK_LOGC_BACO_INICIAL" FOREIGN KEY ("BACO_ID_FINAL")
	  REFERENCES "MODRED"."BAIRRO_CORREIO" ("BACO_ID") ENABLE, 
	 CONSTRAINT "FK_LOGC_BACO_FINAL" FOREIGN KEY ("BACO_ID_INICIAL")
	  REFERENCES "MODRED"."BAIRRO_CORREIO" ("BACO_ID") ENABLE, 
	 CONSTRAINT "FK_LOGC_TILC" FOREIGN KEY ("TILC_ID")
	  REFERENCES "MODRED"."TIPO_LOGRADOURO_CORREIO" ("TILC_ID") ENABLE
   );

   COMMENT ON COLUMN "MODRED"."LOGRADOURO_CORREIO"."LOGC_ID" IS 'Número sequencial';
   COMMENT ON COLUMN "MODRED"."LOGRADOURO_CORREIO"."LOGC_TX_NOME" IS 'Nome Oficial do LOGRADOURO_CORREIO';
   COMMENT ON COLUMN "MODRED"."LOGRADOURO_CORREIO"."LOGC_TX_CEP" IS 'CEP do LOGRADOURO_CORREIO';
   COMMENT ON COLUMN "MODRED"."LOGRADOURO_CORREIO"."TILC_ID" IS 'ID do Tipo LOGRADOURO_CORREIO';
   COMMENT ON COLUMN "MODRED"."LOGRADOURO_CORREIO"."BACO_ID_INICIAL" IS 'ID do BAIRRO_CORREIO Inicial';
   COMMENT ON COLUMN "MODRED"."LOGRADOURO_CORREIO"."BACO_ID_FINAL" IS 'ID do BAIRRO_CORREIO final';
   COMMENT ON COLUMN "MODRED"."LOGRADOURO_CORREIO"."LOGC_NR_CHAVE_DNE" IS 'Chave do logradouro no DNE';
   COMMENT ON TABLE "MODRED"."LOGRADOURO_CORREIO"  IS 'Tabela de LOGRADOURO_CORREIOS';

  CREATE INDEX "MODRED"."IN_FK_LOGC_BACO_FINAL" ON "MODRED"."LOGRADOURO_CORREIO" ("BACO_ID_FINAL") ;

  CREATE INDEX "MODRED"."IN_FK_LOGC_BACO_INICIAL" ON "MODRED"."LOGRADOURO_CORREIO" ("BACO_ID_INICIAL");

  CREATE INDEX "MODRED"."IN_FK_LOGC_TILC" ON "MODRED"."LOGRADOURO_CORREIO" ("TILC_ID");
  
  COMMIT;
  
  -- Fim --
