CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ETNIA FOR MODRED.ETNIA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RACA FOR MODRED.RACA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PAIS FOR MODRED.PAIS;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.UF FOR MODRED.UF;
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."USUARIO" FOR "MODRED"."USUARIO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_USUA_ID" FOR "MODRED"."SQ_USUA_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."PERFIL" FOR "MODRED"."PERFIL";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_PERF_ID" FOR "MODRED"."SQ_PERF_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."USUARIO_PERFIL" FOR "MODRED"."USUARIO_PERFIL";
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CONTATO_ENDERECO FOR MODRED.CONTATO_ENDERECO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESPONSAVEL FOR MODRED.RESPONSAVEL;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_RESP_ID FOR MODRED.SQ_RESP_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PACIENTE FOR MODRED.PACIENTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PACI_NR_RMR FOR MODRED.SQ_PACI_NR_RMR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CONTATO_TELEFONICO FOR MODRED.CONTATO_TELEFONICO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_COTE_ID FOR MODRED.SQ_COTE_ID;

-----Correios------
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."TIPO_LOGRADOURO_CORREIO" FOR "MODRED"."TIPO_LOGRADOURO_CORREIO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."PAIS_CORREIO" FOR "MODRED"."PAIS_CORREIO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."UNIDADE_FEDERATIVA_CORREIO" FOR "MODRED"."UNIDADE_FEDERATIVA_CORREIO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."LOCALIDADE_CORREIO" FOR "MODRED"."LOCALIDADE_CORREIO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."BAIRRO_CORREIO" FOR "MODRED"."BAIRRO_CORREIO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."LOGRADOURO_CORREIO" FOR "MODRED"."LOGRADOURO_CORREIO";