GRANT SELECT ON MODRED.STATUS_PEDIDO_IDM TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.STATUS_PEDIDO_IDM TO RMODRED_WRITE;
GRANT SELECT ON MODRED.PEDIDO_IDM TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PEDIDO_IDM TO RMODRED_WRITE;
GRANT SELECT ON MODRED.PEDIDO_IDM_AUD TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PEDIDO_IDM_AUD TO RMODRED_WRITE;
GRANT SELECT ON MODRED.ARQUIVO_PEDIDO_IDM TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.ARQUIVO_PEDIDO_IDM TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_ARPI_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PEID_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.TIPO_SERVICO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.TIPO_SERVICO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.STATUS_PAGAMENTO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.STATUS_PAGAMENTO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.PAGAMENTO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PAGAMENTO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PAGA_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.PAGAMENTO_AUD TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PAGAMENTO_AUD TO RMODRED_WRITE;
