UPDATE MODRED.RECURSO SET RECU_TX_SIGLA = 'SOLICITAR_PEDIDO_FASE_2_INTERNACIONAL'
WHERE RECU_ID = 94;
DELETE FROM PERMISSAO WHERE RECU_ID = 96 AND PERF_ID = 5;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 96;
COMMIT;

DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 65;
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 66;
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 67;
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 68;
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 69;
DELETE FROM MODRED.TIPO_TAREFA WHERE TITA_ID = 70;
COMMIT;

DELETE FROM MODRED.TIPO_SOLICITACAO WHERE TISO_ID = 5;
DELETE FROM MODRED.TIPO_SOLICITACAO WHERE TISO_ID = 6;
UPDATE MODRED.TIPO_SOLICITACAO SET TISO_TX_DESCRICAO = 'FASE 2'
WHERE  TISO_ID = 1;
UPDATE MODRED.TIPO_SOLICITACAO SET TISO_TX_DESCRICAO = 'FASE 3'
WHERE  TISO_ID = 2;
COMMIT;

ALTER TABLE MODRED.TIPO_SOLICITACAO  
MODIFY (TISO_TX_DESCRICAO VARCHAR2(20 BYTE) );

DROP SEQUENCE MODRED.SQ_ARPI_ID;
DROP INDEX MODRED.IN_FK_ARPI_PEID; 
DROP TABLE MODRED.ARQUIVO_PEDIDO_IDM;
DROP TABLE MODRED.PEDIDO_IDM_AUD;
DROP SEQUENCE MODRED.SQ_PEID_ID;
DROP INDEX MODRED.IN_FK_PEID_STPI;
DROP INDEX MODRED.IN_FK_PEID_SOLI;
DROP TABLE MODRED.PEDIDO_IDM;
DROP TABLE MODRED.STATUS_PEDIDO_IDM;

DELETE FROM "MODRED"."PERMISSAO" WHERE RECU_ID = 97 AND  PERF_ID = 5;
DELETE FROM  "MODRED"."RECURSO" WHERE RECU_ID = 97;
commit;

DELETE FROM "MODRED"."MOTIVO_STATUS_DOADOR" WHERE MOSD_ID  = 9;
DELETE FROM "MODRED"."MOTIVO_STATUS_DOADOR"  WHERE MOSD_ID = 10;

DELETE FROM "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" WHERE MOSD_ID = 9 AND RECU_ID = 97;
DELETE FROM "MODRED"."MOTIVO_STATUS_DOADOR_RECURSO" WHERE MOSD_ID = 10 AND RECU_ID = 97;
commit;

DROP SEQUENCE MODRED.SQ_PAGA_ID;

DROP INDEX MODRED.IN_FK_PAAD_AUDI;
DROP TABLE MODRED.PAGAMENTO_AUD;

DROP INDEX MODRED.IN_FK_PAGA_MATC;
DROP INDEX MODRED.IN_FK_PAGA_REGI;
DROP INDEX MODRED.IN_FK_PAGA_STPA;
DROP INDEX MODRED.IN_FK_PAGA_TISE;

DROP TABLE MODRED.PAGAMENTO;

DROP TABLE MODRED.STATUS_PAGAMENTO;
DROP TABLE MODRED.TIPO_SERVICO;



ALTER TABLE MODRED.PEDIDO_IDM 
DROP COLUMN (PEID_DT_CANCELAMENTO);


ALTER TABLE MODRED.PEDIDO_IDM_AUD 
DROP COLUMN (PEID_DT_CANCELAMENTO);