CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_PEDIDO_IDM FOR MODRED.STATUS_PEDIDO_IDM;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_IDM FOR MODRED.PEDIDO_IDM;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ARQUIVO_PEDIDO_IDM FOR MODRED.ARQUIVO_PEDIDO_IDM;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ARPI_ID FOR MODRED.SQ_ARPI_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PEID_ID FOR MODRED.SQ_PEID_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_SERVICO FOR MODRED.TIPO_SERVICO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_PAGAMENTO FOR MODRED.STATUS_PAGAMENTO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PAGAMENTO FOR MODRED.PAGAMENTO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PAGA_ID FOR MODRED.SQ_PAGA_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PAGAMENTO_AUD FOR MODRED.PAGAMENTO_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_IDM_AUD FOR MODRED.PEDIDO_IDM_AUD;