
ALTER TABLE MODRED.GENOTIPO_DOADOR ADD (GEDO_IN_TIPO_DOADOR NUMBER(1) );
COMMENT ON COLUMN MODRED.GENOTIPO_DOADOR.GEDO_IN_TIPO_DOADOR IS 'Identifica o tipo de doador. 0 - Doador Nacional 1 - Doador Internacional 2 - Cordão Nacional 3 Cordão Internacional.';
UPDATE MODRED.GENOTIPO_DOADOR SET GEDO_IN_TIPO_DOADOR = 0;

ALTER TABLE MODRED.VALOR_GENOTIPO_BUSCA_DOADOR ADD (GEDO_IN_TIPO_DOADOR NUMBER(1) );
COMMENT ON COLUMN MODRED.VALOR_GENOTIPO_BUSCA_DOADOR.GEDO_IN_TIPO_DOADOR IS 'Identifica o tipo de doador. 0 - Doador Nacional 1 - Doador Internacional 2 - Cordão Nacional 3 Cordão Internacional.';
UPDATE MODRED.VALOR_GENOTIPO_BUSCA_DOADOR SET GEDO_IN_TIPO_DOADOR = 0;

ALTER TABLE MODRED.VALOR_GENOTIPO_DOADOR ADD (GEDO_IN_TIPO_DOADOR NUMBER(1) );
COMMENT ON COLUMN MODRED.VALOR_GENOTIPO_DOADOR.GEDO_IN_TIPO_DOADOR IS 'Identifica o tipo de doador. 0 - Doador Nacional 1 - Doador Internacional 2 - Cordão Nacional 3 Cordão Internacional.';
UPDATE MODRED.VALOR_GENOTIPO_DOADOR SET GEDO_IN_TIPO_DOADOR = 0;

ALTER TABLE MODRED.VALOR_GENOTIPO_EXPAND_DOADOR ADD (GEDO_IN_TIPO_DOADOR NUMBER );
COMMENT ON COLUMN MODRED.VALOR_GENOTIPO_EXPAND_DOADOR.GEDO_IN_TIPO_DOADOR IS 'Identifica o tipo de doador. 0 - Doador Nacional 1 - Doador Internacional 2 - Cordão Nacional 3 Cordão Internacional.';
UPDATE MODRED.VALOR_GENOTIPO_EXPAND_DOADOR SET GEDO_IN_TIPO_DOADOR = 0;


ALTER TABLE MODRED.GENOTIPO_DOADOR  MODIFY (GEDO_IN_TIPO_DOADOR NOT NULL);
ALTER TABLE MODRED.VALOR_GENOTIPO_BUSCA_DOADOR  MODIFY (GEDO_IN_TIPO_DOADOR NOT NULL);
ALTER TABLE MODRED.VALOR_GENOTIPO_DOADOR  MODIFY (GEDO_IN_TIPO_DOADOR NOT NULL);
ALTER TABLE MODRED.VALOR_GENOTIPO_EXPAND_DOADOR  MODIFY (GEDO_IN_TIPO_DOADOR NOT NULL);

ALTER TABLE MODRED.VALOR_GENOTIPO_BUSCA_DOADOR RENAME COLUMN GEDO_IN_TIPO_DOADOR TO VGBD_IN_TIPO_DOADOR;
ALTER TABLE MODRED.VALOR_GENOTIPO_DOADOR RENAME COLUMN GEDO_IN_TIPO_DOADOR TO VAGD_IN_TIPO_DOADOR;
ALTER TABLE VALOR_GENOTIPO_EXPAND_DOADOR RENAME COLUMN GEDO_IN_TIPO_DOADOR TO VGED_IN_TIPO_DOADOR;

ALTER TABLE MODRED.DOADOR ADD (DOAD_VL_QUANT_TOTAL_CD34 NUMBER(6) );
ALTER TABLE MODRED.DOADOR ADD (DOAD_VL_QUANT_TOTAL_TCN NUMBER(6) );
COMMENT ON COLUMN MODRED.DOADOR.DOAD_VL_QUANT_TOTAL_CD34 IS 'Quantidade total de  CD34';
COMMENT ON COLUMN MODRED.DOADOR.DOAD_VL_QUANT_TOTAL_TCN IS 'Quantidade total de TCN';
ALTER TABLE MODRED.DOADOR_AUD ADD (DOAD_VL_QUANT_TOTAL_CD34 NUMBER(6) );
ALTER TABLE MODRED.DOADOR_AUD ADD (DOAD_VL_QUANT_TOTAL_TCN NUMBER(6) );

ALTER TABLE MODRED.EXAME 
ADD (DOAD_ID_CORDAO_INTERNACIONAL NUMBER );

ALTER TABLE MODRED.EXAME 
ADD (DOAD_ID_CORDAO_NACIONAL NUMBER );

CREATE INDEX MODRED.IN_FK_EXAM_DOAD_CORDAO_INTERNA ON MODRED.EXAME (DOAD_ID_CORDAO_INTERNACIONAL);

CREATE INDEX MODRED.IN_FK_EXAM_DOAD_CORDAO_NACIONA ON MODRED.EXAME (DOAD_ID_CORDAO_NACIONAL);

ALTER TABLE MODRED.EXAME
ADD CONSTRAINT FK_EXAM_DOAD_CORDAO_INTERNA FOREIGN KEY
(
  DOAD_ID_CORDAO_INTERNACIONAL 
)
REFERENCES MODRED.DOADOR
(
  DOAD_ID 
)
ENABLE;

ALTER TABLE MODRED.EXAME
ADD CONSTRAINT FK_EXAM_DOAD_CORDAO_NACIONA FOREIGN KEY
(
  DOAD_ID_CORDAO_NACIONAL 
)
REFERENCES MODRED.DOADOR
(
  DOAD_ID 
)
ENABLE;

COMMENT ON COLUMN MODRED.EXAME.DOAD_ID_CORDAO_INTERNACIONAL IS 'Chave estrangeira relacionada ao cordão internacional.';
COMMENT ON COLUMN MODRED.EXAME.DOAD_ID_CORDAO_NACIONAL IS 'Chave estrangeira relacionada ao cordão nacional.';

ALTER TABLE MODRED.EXAME_AUD 
ADD (DOAD_ID_CORDAO_INTERNACIONAL NUMBER );

ALTER TABLE MODRED.EXAME_AUD 
ADD (DOAD_ID_CORDAO_NACIONAL NUMBER );


CREATE TABLE MODRED.BANCO_SANGUE_CORDAO 
(
  BASC_ID NUMBER NOT NULL 
, BASC_TX_SIGLA VARCHAR2(4) NOT NULL 
, BASC_TX_NOME VARCHAR2(60) NOT NULL 
, CONSTRAINT PK_BASC PRIMARY KEY 
  (
    BASC_ID 
  )
  ENABLE 
);

COMMENT ON TABLE MODRED.BANCO_SANGUE_CORDAO IS 'Referente aos Bancos de Sangue de Cordão Umbilical.';
COMMENT ON COLUMN MODRED.BANCO_SANGUE_CORDAO.BASC_ID IS 'Identificador único sequencial da tabela.';
COMMENT ON COLUMN MODRED.BANCO_SANGUE_CORDAO.BASC_TX_SIGLA IS 'Sigla do banco de cordão. Será usuado para compor a identificação do cordão.';
COMMENT ON COLUMN MODRED.BANCO_SANGUE_CORDAO.BASC_TX_NOME IS 'Nome do bacno de cordão.';

ALTER TABLE MODRED.DOADOR 
ADD (BASC_ID NUMBER );

ALTER TABLE MODRED.DOADOR 
ADD (DOAD_TX_ID_BANCO_SANGUE_CORDAO VARCHAR2(20) );

CREATE INDEX MODRED.IN_FK_DOAD_BASC ON MODRED.DOADOR (BASC_ID);

ALTER TABLE MODRED.DOADOR
ADD CONSTRAINT FK_DOAD_BASC FOREIGN KEY
(
  BASC_ID 
)
REFERENCES MODRED.BANCO_SANGUE_CORDAO
(
  BASC_ID 
)
ENABLE;

COMMENT ON COLUMN MODRED.DOADOR.BASC_ID IS 'Referência para a tabela banco de sangue de cordão.';
COMMENT ON COLUMN MODRED.DOADOR.DOAD_TX_ID_BANCO_SANGUE_CORDAO IS 'Identificador do cordão nacional no banco de sangue de cordão.';

ALTER TABLE MODRED.DOADOR_AUD 
ADD (BASC_ID NUMBER );

ALTER TABLE MODRED.DOADOR_AUD 
ADD (DOAD_TX_ID_BANCO_SANGUE_CORDAO VARCHAR2(20) );

INSERT INTO BANCO_SANGUE_CORDAO (BASC_ID, BASC_TX_SIGLA, BASC_TX_NOME) VALUES (1, 'BSCA', 'Banco de sangue do agreste');
COMMIT;



--Queiroz adicionando volume 06/07/2018 10:16
ALTER TABLE MODRED.DOADOR ADD (DOAD_VL_VOLUME NUMBER(6) );
COMMENT ON COLUMN MODRED.DOADOR.DOAD_VL_VOLUME IS 'Quantidade em ml de sangue da bolsa';
ALTER TABLE MODRED.DOADOR_AUD ADD (DOAD_VL_VOLUME NUMBER(6) );

-- REFATORANDO RELACIONAMENTO ENTRE PEDIDO WORKUP E COLETA

-- RENOMEANDO A COLUNA QUE INDICA A QUANTIDADE DE ITERAÇÕES ENTRE ANALISTA BUSCA E CT PARA AGENDAR WORKUP.
ALTER TABLE MODRED.PEDIDO_WORKUP RENAME 
COLUMN PEWO_NR_INFO_CORRENTE TO PEWO_NR_TENTATIVAS_AGENDAMENTO;

COMMENT ON COLUMN MODRED.PEDIDO_WORKUP.PEWO_NR_TENTATIVAS_AGENDAMENTO IS 
'Quantidade de tentativas de agendamento junto ao centro de coleta. 
Na prática, representa a quantidade de disponibilidades apresentadas ao centro, cabendo a ele decidir pelas datas ou não, gerando um novo incremento no contador';

-- RENOMEANDO ENUM PRESCRICAO PARA WORKUP E CRIANDO A NOVA ETAPA PARA COLETA
UPDATE MODRED.TIPO_SOLICITACAO SET TISO_TX_DESCRICAO = 'WORKUP' WHERE TISO_ID = 3;

-- REFAZENDO RELACIONAMENTO NO PEDIDO DE COLETA / SAI PEDIDO DE WORKUP ENTRA SOLICITAÇÃO
-- DEIXANDO A MESMA SOLICITAÇÃO PARA COLETA E WORKUP, PARA O HISTÓRICO QUE JÁ EXISTIA NO BANCO.
ALTER TABLE MODRED.PEDIDO_COLETA
ADD SOLI_ID NUMBER;

UPDATE MODRED.PEDIDO_COLETA P
SET P.SOLI_ID = (
SELECT S.SOLI_ID
FROM MODRED.PEDIDO_COLETA PC JOIN MODRED.PEDIDO_WORKUP PW ON(PC.PEWO_ID = PW.PEWO_ID)
JOIN MODRED.SOLICITACAO S ON(S.SOLI_ID = PW.SOLI_ID)
WHERE PC.PECL_ID = P.PECL_ID);
COMMIT;

ALTER TABLE MODRED.PEDIDO_COLETA
MODIFY SOLI_ID NUMBER NOT NULL;

-- REFATORANDO

ALTER TABLE MODRED.DOADOR_AUD ADD (DOAD_VL_VOLUME NUMBER(6) );

ALTER TABLE MODRED.DOADOR  MODIFY (DOAD_VL_PESO NULL);


ALTER TABLE MODRED.PEDIDO_EXAME 
ADD (EXAM_ID_CORDAO_INTERNACIONAL NUMBER );

CREATE INDEX MODRED.IN_FK_PEEX_EXAM_CORDAO_INTER ON MODRED.PEDIDO_EXAME (EXAM_ID_CORDAO_INTERNACIONAL);

ALTER TABLE MODRED.PEDIDO_EXAME
ADD CONSTRAINT FK_PEEX_EXAM_CORDAO_INTER FOREIGN KEY
(
  EXAM_ID_CORDAO_INTERNACIONAL 
)
REFERENCES MODRED.EXAME
(
  EXAM_ID 
)
ENABLE;

COMMENT ON COLUMN MODRED.PEDIDO_EXAME.EXAM_ID_CORDAO_INTERNACIONAL IS 'Referência para o exame do cordão internacional de resultado do pedido';

ALTER TABLE MODRED.PEDIDO_EXAME_AUD 
ADD (EXAM_ID_CORDAO_INTERNACIONAL NUMBER );


ALTER TABLE MODRED.PEDIDO_COLETA 
ADD (PECL_DT_COLETA DATE );

ALTER TABLE MODRED.PEDIDO_COLETA  
MODIFY (PEWO_ID NULL);

COMMENT ON COLUMN MODRED.PEDIDO_COLETA.PECL_DT_COLETA IS 'Data da coleta replicada do pedido de workup ou da prescrição, Depende se o doador é medula ou cordão.';

ALTER TABLE MODRED.PEDIDO_WORKUP_AUD ADD (PEWO_NR_TENTATIVAS_AGENDAMENTO NUMBER );


-- INCLUSÃO DE NOVA FONTE DE CELULA PARA CORDÃO
INSERT INTO "MODRED"."FONTE_CELULAS" (FOCE_ID, FOCE_TX_SIGLA, FOCE_TX_DESCRICAO) VALUES ('4', 'CO', 'CORDAO UMBILICAL');
COMMIT;

-- ALTERANDO O NUMERO DE CASAS DECIMAIS PARA OS VALORES DE COLETA DE CORDAO
UPDATE MODRED.DOADOR
SET DOAD_VL_QUANT_TOTAL_CD34 = NULL, DOAD_VL_QUANT_TOTAL_TCN = NULL, DOAD_VL_VOLUME = NULL;

ALTER TABLE MODRED.DOADOR  
MODIFY (DOAD_VL_QUANT_TOTAL_CD34 NUMBER(6,2) );

ALTER TABLE DOADOR  
MODIFY (DOAD_VL_QUANT_TOTAL_TCN NUMBER(6,2) );

ALTER TABLE DOADOR  
MODIFY (DOAD_VL_VOLUME NUMBER(6,2) );

UPDATE MODRED.DOADOR
SET DOAD_VL_QUANT_TOTAL_CD34 = 7, DOAD_VL_QUANT_TOTAL_TCN = 5
WHERE DOAD_NR_GRID IS NOT NULL;
COMMIT;
