GRANT SELECT ON MODRED.COURIER TO RMODRED_READ;
GRANT SELECT ON "MODRED"."SQ_COUR_ID" TO RMODRED_WRITE;


GRANT SELECT ON "MODRED"."CONTROLE_JOB_BRASILCORD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."CONTROLE_JOB_BRASILCORD" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_COJB_ID" TO RMODRED_WRITE;