ALTER TABLE MODRED.BANCO_SANGUE_CORDAO 
DROP COLUMN BASC_NR_ID_BRASILCORD;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_TOT_LINFOCITOS;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_TOT_MONOCITOS;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_PER_HEMATOCRITOS;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_TOT_PER_HEMA;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_TOT_ANTES;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_TOT_DEPOIS;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_TOT_REAL;

ALTER TABLE MODRED.DOADOR 
DROP COLUMN DOAD_VL_QUANT_TOTAL_TCN_ANTES;

ALTER TABLE DOADOR 
DROP COLUMN DOAD_VL_TOT_PER_HEMATOCRITOS;






ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN DOAD_VL_TOT_LINFOCITOS;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN DOAD_VL_TOT_MONOCITOS;

ALTER TABLE MODRED.DOADOR_AUD 
DROP COLUMN DOAD_VL_PER_HEMATOCRITOS;

ALTER TABLE MODRED.DOADOR_AUD
DROP COLUMN DOAD_VL_TOT_PER_HEMA;

ALTER TABLE MODRED.DOADOR_AUD
DROP COLUMN DOAD_VL_TOT_ANTES;

ALTER TABLE MODRED.DOADOR_AUD
DROP COLUMN DOAD_VL_TOT_DEPOIS;

ALTER TABLE MODRED.DOADOR_AUD
DROP COLUMN DOAD_VL_TOT_REAL;

ALTER TABLE MODRED.DOADOR_AUD
DROP COLUMN DOAD_VL_QUANT_TOTAL_TCN_ANTES;

ALTER TABLE MODRED.DOADOR_AUD
DROP COLUMN DOAD_VL_TOT_PER_HEMATOCRITOS;




DROP TABLE MODRED.CONTROLE_JOB_BRASILCORD;


DELETE FROM "MODRED"."PERFIL" WHERE PERF_ID = '21';
DELETE FROM "MODRED"."USUARIO" WHERE USUA_ID = '22';
COMMIT;


DELETE FROM "MODRED"."USUARIO_PERFIL" WHERE USUA_ID = 21 AND PERF_ID = 21;
COMMIT;