CREATE OR REPLACE SYNONYM MODRED_APLICACAO.COURIER FOR MODRED.COURIER;
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_COUR_ID" FOR "MODRED"."SQ_COUR_ID";

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."CONTROLE_JOB_BRASILCORD" FOR "MODRED"."CONTROLE_JOB_BRASILCORD";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_COJB_ID" FOR "MODRED"."SQ_COJB_ID";
