GRANT SELECT ON "MODRED"."TIPO_CHECKLIST" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."TIPO_CHECKLIST" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."ITENS_CHECKLIST" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."ITENS_CHECKLIST" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."RESPOSTA_CHECKLIST" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."RESPOSTA_CHECKLIST" TO RMODRED_WRITE;


GRANT SELECT ON "MODRED"."SQ_ITEC_ID" TO RMODRED_READ;


-- BUSCA PRELIMINAR
GRANT SELECT ON MODRED.BUSCA_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.BUSCA_PRELIMINAR TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_BUPR_ID TO RMODRED_WRITE;

-- GENOTIPO PRELIMINAR
GRANT SELECT ON MODRED.GENOTIPO_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.GENOTIPO_PRELIMINAR TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_GEPR_ID TO RMODRED_WRITE;

-- GENOTIPO BUSCA PRELIMINAR 
GRANT SELECT ON MODRED.GENOTIPO_BUSCA_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.GENOTIPO_BUSCA_PRELIMINAR TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_GEBP_ID TO RMODRED_WRITE;

-- GENOTIPO EXPANDIDO PRELIMINAR
GRANT SELECT ON MODRED.GENOTIPO_EXPANDIDO_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.GENOTIPO_EXPANDIDO_PRELIMINAR TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_GEEP_ID TO RMODRED_WRITE;

-- MATCH PRELIMINAR
GRANT SELECT ON MODRED.MATCH_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.MATCH_PRELIMINAR TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_MAPR_ID TO RMODRED_WRITE;

-- QUALIFICACAO MATCH PRELIMINAR
GRANT SELECT ON MODRED.QUALIFICACAO_MATCH_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.QUALIFICACAO_MATCH_PRELIMINAR TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_GEBR_ID TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."CONSTANTE_RELATORIO" TO RMODRED_READ;
GRANT UPDATE ON "MODRED"."CONSTANTE_RELATORIO" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."CONSTANTE_RELATORIO_AUD" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."CONSTANTE_RELATORIO_AUD" TO RMODRED_WRITE;


-- BUSCA PRELIMINAR
GRANT SELECT ON MODRED.LOCUS_EXAME_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.LOCUS_EXAME_PRELIMINAR TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_LOEP_ID TO RMODRED_WRITE;GRANT SELECT ON MODRED.SQ_GEBR_ID TO RMODRED_WRITE;

--CATEGORIA CHECKLIST
GRANT SELECT ON MODRED_APLICACAO.CATEGORIA_CHECKLIST TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED_APLICACAO.CATEGORIA_CHECKLIST TO RMODRED_WRITE;

--RESPOSTA CHECKLIST

GRANT SELECT ON MODRED.SQ_RESC_ID TO RMODRED_WRITE;

GRANT EXECUTE ON MODRED.PROC_BUSCA_PRELIMINAR TO RMODRED_READ;
GRANT EXECUTE ON MODRED.PROC_CRIAR_QUAL_MATCH_PRE TO RMODRED_READ;

GRANT SELECT ON MODRED.SQ_QUMP_ID TO RMODRED_WRITE;

