DROP TABLE MODRED.TIPO_CHECKLIST;
DROP TABLE MODRED.ITENS_CHECKLIST;
DROP TABLE MODRED.RESPOSTA_CHECKLIST;

ALTER TABLE MODRED.STATUS_PEDIDO_LOGISTICA  
MODIFY (STPL_TX_DESCRICAO VARCHAR2(20 BYTE) );



DELETE FROM  "MODRED"."STATUS_PEDIDO_LOGISTICA" WHERE STPL_ID = 3;
DELETE FROM  "MODRED"."TIPO_TAREFA" WHERE  TITA_ID = 79;
DELETE FROM  "MODRED"."TIPO_TAREFA" WHERE  TITA_ID = 80 ;

DELETE FROM "MODRED"."TIPO_CHECKLIST" WHERE  = TIPC_ID = 1;
DELETE FROM "MODRED"."TIPO_CHECKLIST" WHERE  = TIPC_ID = 2;
COMMIT;


drop table MODRED_APLICACAO.CATEGORIA_CHECKLIST;


delete from tipo_tarefa where tita_id = 81;
delete from recurso where RECU_ID = 109;
delete from tipo_tarefa where TITA_ID = 82;
delete from "MODRED"."TIPO_TAREFA" where TITA_ID = 83;
commit;


ALTER TABLE MODRED.PEDIDO_LOGISTICA 
drop column PELO_TX_RETIRADA_PAIS;

ALTER TABLE MODRED.PEDIDO_LOGISTICA 
drop column PELO_TX_RETIRADA_ESTADO;

ALTER TABLE MODRED.PEDIDO_LOGISTICA 
drop column PELO_TX_RETIRADA_CIDADE;

ALTER TABLE MODRED.PEDIDO_LOGISTICA 
drop column PELO_TX_RETIRADA_RUA;

ALTER TABLE MODRED.PEDIDO_LOGISTICA 
drop column PELO_TX_TELEFONE;

ALTER TABLE MODRED PEDIDO_TRANSPORTE  
MODIFY (PETR_HR_PREVISTA_RETIRADA NOT NULL);

ALTER TABLE MODRED.PEDIDO_TRANSPORTE  
MODIFY (TRAN_ID NOT NULL);