CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."TIPO_CHECKLIST" FOR "MODRED"."TIPO_CHECKLIST";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."ITENS_CHECKLIST" FOR "MODRED"."ITENS_CHECKLIST";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."RESPOSTA_CHECKLIST" FOR "MODRED"."RESPOSTA_CHECKLIST";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_ITEC_ID" FOR "MODRED"."SQ_ITEC_ID";

-- BUSCA PRELIMINAR
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.BUSCA_PRELIMINAR FOR MODRED.BUSCA_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_BUPR_ID FOR MODRED.SQ_BUPR_ID;

-- GENOTIPO PRELIMINAR
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.GENOTIPO_PRELIMINAR FOR MODRED.GENOTIPO_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_GEPR_ID FOR MODRED.SQ_GEPR_ID;

-- GENOTIPO BUSCA PRELIMINAR
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.GENOTIPO_BUSCA_PRELIMINAR FOR MODRED.GENOTIPO_BUSCA_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_GEBP_ID FOR MODRED.SQ_GEBP_ID;

-- GENOTIPO EXPANDIDO PRELIMINAR
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.GENOTIPO_EXPANDIDO_PRELIMINAR FOR MODRED.GENOTIPO_EXPANDIDO_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_GEBR_ID FOR MODRED.SQ_GEBR_ID;

-- MATCH PRELIMINAR
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.MATCH_PRELIMINAR FOR MODRED.MATCH_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_MAPR_ID FOR MODRED.SQ_MAPR_ID;

-- QUALIFICACAO MATCH PRELIMINAR
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.QUALIFICACAO_MATCH_PRELIMINAR FOR MODRED.QUALIFICACAO_MATCH_PRELIMINAR;

-- CONSTANTE RESLATORIO
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."CONSTANTE_RELATORIO" FOR "MODRED"."CONSTANTE_RELATORIO";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."CONSTANTE_RELATORIO_AUD" FOR "MODRED"."CONSTANTE_RELATORIO_AUD";

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.QUALIFICACAO_MATCH_PRELIMINAR FOR MODRED.QUALIFICACAO_MATCH_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_GEEP_ID FOR MODRED.SQ_GEEP_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_QUMP_ID FOR MODRED.SQ_QUMP_ID;

-- LOCUS_EXAME_PRELIMINAR
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.LOCUS_EXAME_PRELIMINAR FOR MODRED.LOCUS_EXAME_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_LOEP_ID FOR MODRED.SQ_LOEP_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_GEBR_ID FOR MODRED.SQ_GEBR_ID;

--CATEGORIA CHECKLIST
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CATEGORIA_CHECKLIST FOR MODRED.CATEGORIA_CHECKLIST;


CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_RESC_ID FOR MODRED.SQ_RESC_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PROC_BUSCA_PRELIMINAR FOR MODRED.PROC_BUSCA_PRELIMINAR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PROC_CRIAR_QUAL_MATCH_PRE FOR MODRED.PROC_CRIAR_QUAL_MATCH_PRE;
