-- ENDEREÇO DO MÉDICO INSERIDO NO PRÉ CADASTRO
CREATE TABLE MODRED.PRE_CADASTRO_MEDICO_ENDERECO
(
  PCME_ID NUMBER NOT NULL 
, PCME_ID_PAIS NUMBER NOT NULL 
, PCME_TX_CEP VARCHAR2(9) NOT NULL 
, PCME_TX_TIPO_LOGRADOURO VARCHAR2(100) NOT NULL 
, PCME_TX_NOME_LOGRADOURO VARCHAR2(200) NOT NULL 
, PCME_TX_COMPLEMENTO VARCHAR2(255) NOT NULL 
, PCME_TX_BAIRRO VARCHAR2(255) NOT NULL 
, PCME_TX_MUNICIPIO VARCHAR2(255) NOT NULL 
, PCME_TX_SIGLA_UF VARCHAR2(2) NOT NULL 
, PCME_NR_NUMERO NUMBER NOT NULL 
, CONSTRAINT PK_PCME PRIMARY KEY (PCME_ID)
  USING INDEX (
      CREATE UNIQUE INDEX IN_PCME_PK ON MODRED.PRE_CADASTRO_MEDICO_ENDERECO (PCME_ID ASC) 
  )
  ENABLE
);

COMMENT ON TABLE MODRED.PRE_CADASTRO_MEDICO_ENDERECO IS 'Tabela que guarda o endereço defino para oo pré cadastro de médico, onde o mesmo se cadastra e solicita acesso ao Redome e pode ser ou não aprovado.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_ID IS 'Identificação da tabela.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_ID_PAIS IS 'País em que reside o médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_TX_CEP IS 'CEP da residência do médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_TX_TIPO_LOGRADOURO IS 'Tipo do logradouro do médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_TX_COMPLEMENTO IS 'Tipo do logradouro do médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_TX_BAIRRO IS 'Tipo do logradouro do médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_TX_MUNICIPIO IS 'Tipo do logradouro do médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_TX_SIGLA_UF IS 'Tipo do logradouro do médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_ENDERECO.PCME_NR_NUMERO IS 'Tipo do logradouro do médico.';


-- ID SEQUENCE DA PRE CADASTRO MEDICO ENDEREÇO
CREATE SEQUENCE MODRED.SQ_PCME_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;



-- TABELA DE PRÉ CADASTRO DO MEDICO
CREATE TABLE MODRED.PRE_CADASTRO_MEDICO
(
  PRCM_ID NUMBER NOT NULL 
, PRCM_TX_CRM VARCHAR2(13) NOT NULL 
, PRCM_TX_NOME VARCHAR2(255) NOT NULL 
, PRCM_TX_LOGIN VARCHAR2(50) NOT NULL 
, PRCM_TX_SENHA VARCHAR2(255) NOT NULL 
, PRCM_TX_ARQUIVO_CRM VARCHAR2(255) NOT NULL 
, PCME_ID NUMBER NOT NULL
, CONSTRAINT PK_PRCM PRIMARY KEY (PRCM_ID)
  USING INDEX (
      CREATE UNIQUE INDEX IN_PRCM_PK ON MODRED.PRE_CADASTRO_MEDICO (PRCM_ID ASC) 
  )
  ENABLE
);

COMMENT ON TABLE MODRED.PRE_CADASTRO_MEDICO IS 'Tabela que guarda o pré cadastro de médico, onde o mesmo se cadastra e solicita acesso ao Redome e pode ser ou não aprovado.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO.PRCM_ID IS 'Identificação da tabela.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO.PRCM_TX_CRM IS 'CRM do médico pré cadastrado.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO.PRCM_TX_NOME IS 'Nome do médico pré cadastrado.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO.PRCM_TX_LOGIN IS 'Login único sugerido pelo médico no pré cadastro.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO.PRCM_TX_SENHA IS 'Senha cadastrada pelo médico no pré cadastro.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO.PRCM_TX_ARQUIVO_CRM IS 'URL que aponta para o arquivo CRM que o médico informou para validação do cadastro.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO.PCME_ID IS 'ID do endereço informado pelo médico.';

-- ADICIONANDO RELACIONAMENTO COM PRE CADASTRO
ALTER TABLE MODRED.PRE_CADASTRO_MEDICO
ADD CONSTRAINT FK_PRCM_PCME FOREIGN KEY(PCME_ID)
REFERENCES MODRED.PRE_CADASTRO_MEDICO_ENDERECO(PCME_ID)
ENABLE;


-- ID SEQUENCE DA PRE CADASTRO MEDICO
CREATE SEQUENCE MODRED.SQ_PRCM_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;



-- TABELA DE PRÉ CADASTRO DOS TELEFONES DE MEDICO
CREATE TABLE MODRED.PRE_CADASTRO_MEDICO_TELEFONE
(
  PCMT_ID NUMBER NOT NULL 
, PCMT_TX_NOME VARCHAR2(100) 
, PCMT_NR_COD_AREA NUMBER(5) NOT NULL
, PCMT_TX_COMPLEMENTO VARCHAR2(20)
, PCMT_IN_TIPO NUMBER NOT NULL
, PCMT_NR_NUMERO NUMBER NOT NULL
, PCMT_IN_PRINCIPAL NUMBER(1) NOT NULL
, PRCM_ID NUMBER NOT NULL
, CONSTRAINT PK_PCMT PRIMARY KEY (PCMT_ID)
  USING INDEX (
      CREATE UNIQUE INDEX IN_PCMT_PK ON MODRED.PRE_CADASTRO_MEDICO_TELEFONE (PCMT_ID ASC) 
  )
  ENABLE
);

COMMENT ON TABLE MODRED.PRE_CADASTRO_MEDICO_TELEFONE IS 'Tabela que guarda os telefones de contato do médico inseridos no pré cadastro.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PCMT_ID IS 'Identificação da tabela.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PCMT_TX_NOME IS 'Nome do contato do médico pré cadastrado.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PCMT_NR_COD_AREA IS 'Código de área do número informado';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PCMT_TX_COMPLEMENTO IS 'Texto livre utilizado para alguma informação adicional ao contato.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PCMT_IN_TIPO IS 'Tipo do contato, se é Fixo ou Celular.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PCMT_NR_NUMERO IS 'Número do telefonte de contato informado.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PCMT_IN_PRINCIPAL IS 'Indica se o contato é o principal ou não (somente um contato pode ser marcado).';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_TELEFONE.PRCM_ID IS 'ID do pré cadastro do médico.';

-- ADICIONANDO RELACIONAMENTO COM PRE CADASTRO
ALTER TABLE MODRED.PRE_CADASTRO_MEDICO_TELEFONE
ADD CONSTRAINT FK_PRCM_PCMT FOREIGN KEY(PRCM_ID)
REFERENCES MODRED.PRE_CADASTRO_MEDICO(PRCM_ID)
ENABLE;

-- ID SEQUENCE DA PRE CADASTRO EMAILS DO MEDICO
CREATE SEQUENCE MODRED.SQ_PCEM_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;



-- TABELA DE PRÉ CADASTRO DOS TELEFONES DE E-MAILS
CREATE TABLE MODRED.PRE_CADASTRO_MEDICO_EMAIL
(
  PCEM_ID NUMBER NOT NULL 
, PCEM_TX_EMAIL VARCHAR2(100) 
, PCEM_IN_PRINCIPAL NUMBER(1) NOT NULL
, PRCM_ID NUMBER NOT NULL
, CONSTRAINT PK_PCEM PRIMARY KEY (PCEM_ID)
  USING INDEX (
      CREATE UNIQUE INDEX IN_PCEM_PK ON MODRED.PRE_CADASTRO_MEDICO_EMAIL (PCEM_ID ASC) 
  )
  ENABLE
);

COMMENT ON TABLE MODRED.PRE_CADASTRO_MEDICO_EMAIL IS 'Tabela que guarda os e-mails para contato com o médico inseridos no pré cadastro.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_EMAIL.PCEM_ID IS 'Identificação da tabela.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_EMAIL.PCEM_TX_EMAIL IS 'E-mail de contato do médico.';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_EMAIL.PCEM_IN_PRINCIPAL IS 'Indica se o contato é o principal ou não (somente um contato pode ser marcado).';
COMMENT ON COLUMN MODRED.PRE_CADASTRO_MEDICO_EMAIL.PRCM_ID IS 'ID do pré cadastro do médico.';

-- ADICIONANDO RELACIONAMENTO COM PRE CADASTRO
ALTER TABLE MODRED.PRE_CADASTRO_MEDICO_EMAIL
ADD CONSTRAINT FK_PRCM_PCEM FOREIGN KEY(PRCM_ID)
REFERENCES MODRED.PRE_CADASTRO_MEDICO(PRCM_ID)
ENABLE;



-- TABELA DE PRÉ CADASTRO ASSOCIAÇÃO MEDICO E CENTRO AVALIADOR (CENTRO REFERENCIA)
CREATE TABLE MODRED.PRE_CAD_MEDICO_CT_REFERENCIA
(
  PRCM_ID NUMBER NOT NULL 
, CETR_ID NUMBER NOT NULL
, CONSTRAINT PK_PCCR PRIMARY KEY (PRCM_ID, CETR_ID)
  USING INDEX (
      CREATE UNIQUE INDEX IN_PCCR_PK ON MODRED.PRE_CAD_MEDICO_CT_REFERENCIA (PRCM_ID, CETR_ID ASC) 
  )
  ENABLE
);

COMMENT ON TABLE MODRED.PRE_CAD_MEDICO_CT_REFERENCIA IS 'Tabela de relacionamento entre o pré cadastro do médico e os centros de referência que ele atua (centros avaliadores).';
COMMENT ON COLUMN MODRED.PRE_CAD_MEDICO_CT_REFERENCIA.PRCM_ID IS 'Identificação da tabela pré cadastro médico.';
COMMENT ON COLUMN MODRED.PRE_CAD_MEDICO_CT_REFERENCIA.CETR_ID IS 'Identificação da tabela centro transplante.';

-- RELACIONAMENTO COM PRÉ CADASTRO
ALTER TABLE MODRED.PRE_CAD_MEDICO_CT_REFERENCIA
ADD CONSTRAINT FK_PCCR_PRCM FOREIGN KEY(PRCM_ID)
REFERENCES MODRED.PRE_CADASTRO_MEDICO(PRCM_ID)
ENABLE;

-- RELACIONAMENTO COM CENTRO TRANSPLANTE
ALTER TABLE MODRED.PRE_CAD_MEDICO_CT_REFERENCIA
ADD CONSTRAINT FK_PCCR_CETR FOREIGN KEY(CETR_ID)
REFERENCES MODRED.CENTRO_TRANSPLANTE(CETR_ID)
ENABLE;