GRANT UPDATE ON MODRED.CENTRO_TRANSPLANTE TO RMODRED_WRITE;
GRANT INSERT, DELETE ON MODRED.FUNCAO_CENTRO_TRANSPLANTE TO RMODRED_WRITE;

GRANT INSERT ON MODRED.CENTRO_TRANSPLANTE TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."CENTRO_TRANSPLANTE_USUARIO" TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON "MODRED"."CENTRO_TRANSPLANTE_USUARIO" TO RMODRED_WRITE;