INSERT INTO "MODRED"."PERFIL" (PERF_ID, PERF_TX_DESCRICAO, PERF_NR_ENTITY_STATUS) VALUES ('22', 'ANALISTA_LOGISTICA_INTERNACIONAL', '1');
INSERT INTO "MODRED"."USUARIO" (USUA_ID, USUA_TX_NOME, USUA_TX_USERNAME, USUA_TX_PASSWORD, USUA_IN_ATIVO, USUA_NR_ENTITY_STATUS) VALUES ('53', 'ANALISTA LOGÍSTICA INTERNACIONAL', 'ANALISTA_LOGISTICA_INTERNACIONAL', '$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.', '1', '1');
INSERT INTO "MODRED"."USUARIO_PERFIL" (USUA_ID, PERF_ID) VALUES ('53', '22');
commit;

-- PERMISSÃO DE ACESSO AO ANALISTA LOGISTICA INTERNACIONAL PARA ACESSAR A LISTA DE LOGISTICA
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('47', '22', '0');
COMMIT;

-- ATUALIZANDO A DESCRIÇÃO DO RECURSO EFETUAR_LOGISTICA
UPDATE MODRED.RECURSO
SET RECU_TX_DESCRICAO = 'Permite listar as tarefas de logística (workup, coleta e material (nacional e internacional, com e sem aéreo). As logísticas serão exibidas de acordo com o perfil do usuário logado.'
WHERE RECU_ID = 47;
COMMIT;


INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES 
(112, 'MANTER_CENTRO_TRANSPLANTE', 'Permite ao administrador do redome manter o cadastro de centro de transplante');
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES
(19, 112, 0);
COMMIT;
commit;

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES ('84', 'PEDIDO_LOGISTICA_MATERIAL_MEDULA_INTERNACIONAL', '0', '0');
COMMIT;


INSERT INTO "MODRED"."TIPO_PEDIDO_LOGISTICA" (TIPL_ID, TIPL_TX_DESCRICAO) VALUES ('4', 'MEDULA_INTERNACIONAL');
INSERT INTO "MODRED"."TIPO_PEDIDO_LOGISTICA" (TIPL_ID, TIPL_TX_DESCRICAO) VALUES ('5', 'CORDAO_INTERNACIONAL');
commit;

-- CRIANDO RECURSO PARA REALIZACAO DA LOGÍSTICA INTERNACIONAL
INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES ('113', 'EFETUAR_LOGISTICA_INTERNACIONAL', 'Permite ao analista de logística internacional realizar logísticas de workup, doador, material e outros, somente para os pedidos internacionais.');
COMMIT;

-- REMOVENDO ACESSO DO ANALISTA DE LOGÍSTICA INTERNACIONAL A LISTA NACIONAL
-- PERMISSÃO DE ACESSO AO ANALISTA LOGISTICA INTERNACIONAL PARA ACESSAR A LISTA DE LOGISTICA
DELETE FROM "MODRED"."PERMISSAO" 
WHERE RECU_ID = 47 AND PERF_ID = 22;
COMMIT;

-- PERMISSÃO DE ACESSO AO ANALISTA LOGISTICA INTERNACIONAL PARA ACESSAR A LISTA DE LOGISTICA INTERNACIONAL
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('113', '22', '0');
COMMIT;

-- INCLUINDO COLUNA DE ORIGEM DE PEDIDO DE LOGISTICA
ALTER TABLE MODRED.PEDIDO_LOGISTICA
ADD TIPL_IN_ORIGEM VARCHAR2(13);

COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA.TIPL_IN_ORIGEM 
IS 'Define a origem do pedido de logística, se nacional (NACIONAL) ou internacional (INTERNACIONAL).';

-- ATUALIZANDO BASE DE PEDIDOS DE LOGÍSTICA COM O FLAG ORIGEM
-- LOGÍSTICA DE WORKUP
MERGE INTO MODRED.PEDIDO_LOGISTICA PL
USING (SELECT   DISTINCT 
                PW_PL.PELO_ID,
                CASE WHEN D.DOAD_IN_TIPO IN (1, 3) THEN 'INTERNACIONAL' ELSE 'NACIONAL' END AS TIPL_IN_ORIGEM
        FROM DOADOR D JOIN MATCH M ON(D.DOAD_ID = M.DOAD_ID)
        JOIN SOLICITACAO S ON(M.MATC_ID = S.MATC_ID)
        JOIN PEDIDO_WORKUP PW ON(S.SOLI_ID = PW.SOLI_ID)
        JOIN PEDIDO_LOGISTICA PW_PL ON(PW.PEWO_ID = PW_PL.PEWO_ID)) PL_2
ON (PL.PELO_ID = PL_2.PELO_ID)
WHEN MATCHED THEN UPDATE SET PL.TIPL_IN_ORIGEM = PL_2.TIPL_IN_ORIGEM;
COMMIT;

-- LOGÍSICA DE COLETA
MERGE INTO MODRED.PEDIDO_LOGISTICA PL
USING (SELECT   DISTINCT 
                PC_PL.PELO_ID,
                CASE WHEN D.DOAD_IN_TIPO IN (1, 3) THEN 'INTERNACIONAL' ELSE 'NACIONAL' END AS TIPL_IN_ORIGEM
        FROM DOADOR D JOIN MATCH M ON(D.DOAD_ID = M.DOAD_ID)
        JOIN SOLICITACAO S ON(M.MATC_ID = S.MATC_ID)
        JOIN PEDIDO_COLETA PC ON(S.SOLI_ID = PC.SOLI_ID)
        JOIN PEDIDO_LOGISTICA PC_PL ON(PC.PECL_ID = PC_PL.PECL_ID)) PL_2
ON (PL.PELO_ID = PL_2.PELO_ID)
WHEN MATCHED THEN UPDATE SET PL.TIPL_IN_ORIGEM = PL_2.TIPL_IN_ORIGEM;
COMMIT;

-- TORNANDO A ORIGEM DA LOGISTICA COMO OBRIGATÓRIA
ALTER TABLE MODRED.PEDIDO_LOGISTICA
MODIFY TIPL_IN_ORIGEM VARCHAR2(13) NOT NULL;


-- CRIANDO COLUNAS COM DATA E USUÁRIO DE CADASTRO
ALTER TABLE MODRED.BUSCA_PRELIMINAR
ADD BUPR_DT_CADASTRO TIMESTAMP;
COMMENT ON COLUMN MODRED.BUSCA_PRELIMINAR.BUPR_DT_CADASTRO 
IS 'Data em que foi realizada a busca (cadastro do registro).';

ALTER TABLE MODRED.BUSCA_PRELIMINAR
ADD USUA_ID NUMBER;
COMMENT ON COLUMN MODRED.BUSCA_PRELIMINAR.USUA_ID 
IS 'Usuário que realizou a busca (cadastro do registro).';

UPDATE MODRED.BUSCA_PRELIMINAR
SET BUPR_DT_CADASTRO = SYSDATE, USUA_ID = 1;

ALTER TABLE MODRED.BUSCA_PRELIMINAR
MODIFY BUPR_DT_CADASTRO NOT NULL;
ALTER TABLE MODRED.BUSCA_PRELIMINAR
MODIFY USUA_ID NOT NULL;

-- PERMISSÃO DE ACESSO AO HEADER DOADOR PELO ANALISTA LOGISTICA INTERNACIONAL;
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('44', '22', '0');
COMMIT;
MODIFY USUA_ID NOT NULL;MODIFY TIPL_IN_ORIGEM VARCHAR2(13) NOT NULL;

ALTER TABLE PEDIDO_LOGISTICA_AUD 
ADD (TIPL_IN_ORIGEM VARCHAR2(13) );




INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID) VALUES ('44', '21');
commit;

INSERT INTO "MODRED"."PERFIL" (PERF_ID, PERF_TX_DESCRICAO, PERF_NR_ENTITY_STATUS) VALUES ('23', 'SUPERVISOR_BUSCA', '1');
COMMIT;


INSERT INTO "MODRED"."USUARIO" (USUA_ID, USUA_TX_NOME, USUA_TX_USERNAME, USUA_TX_PASSWORD, USUA_IN_ATIVO, USUA_NR_ENTITY_STATUS) VALUES ('54', 'SUPERVISOR_BUSCA', 'SUPERVISOR_BUSCA', '$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.', '1', '1')
COMMIT;


INSERT INTO "MODRED"."USUARIO_PERFIL" (USUA_ID, PERF_ID) VALUES ('54', '23');
COMMIT;


INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES ('114', 'RELACIONAR_ANALISTA_AO_CENTRO', 'Permite o relacionamento de usuário com perfil de analista de busca ao centro avaliador');
commit;


INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('114', '23', '0');
COMMIT;


INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID) VALUES ('44', '21');
COMMIT;

-- INCLUINDO CAMPO QUE CONTERÁ O NOME DO COURIER
ALTER TABLE MODRED.PEDIDO_LOGISTICA
ADD PELO_TX_NOME_COURIER VARCHAR2(255);
COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA.PELO_TX_NOME_COURIER 
IS 'Nome do courier responsável pela retirada do material para implante (somente internacional).';

ALTER TABLE MODRED.PEDIDO_LOGISTICA_AUD
ADD PELO_TX_NOME_COURIER VARCHAR2(255);


-- INCLUINDO CAMPO QUE CONTERÁ O NÚMERO DO PASSAPORTE DO COURIER
ALTER TABLE MODRED.PEDIDO_LOGISTICA
ADD PELO_TX_PASSAPORTE_COURIER VARCHAR2(255);
COMMENT ON COLUMN MODRED.PEDIDO_LOGISTICA.PELO_TX_PASSAPORTE_COURIER 
IS 'Número do passaporte do courier responsável pela retirada do material para implante (somente internacional).';

ALTER TABLE MODRED.PEDIDO_LOGISTICA_AUD
ADD PELO_TX_PASSAPORTE_COURIER VARCHAR2(255);

-- REMOVENDO ACESSO DO MÉDICO E ANALISTA LOGÍSTICA NACIONAL
-- ADICIONANDO ACESSO A RETIRADA DE MATERIAL PARA O ANALISTA DE LOGÍSTICA INTERNACIONAL
DELETE FROM "MODRED"."PERMISSAO" WHERE RECU_ID = 109;
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('109', '22', '0');
COMMIT;

-- CORRIGINDO A CRIAÇÃO DE TAREFA DE RETIRADA/ENTREGA DE MATERIAL INTERNACIONAL PARA O PERFIL CORRETO (ANALISTA LOGISTICA INTERNACIONAL)
UPDATE MODRED.TAREFA
SET PERF_ID_RESPONSAVEL = 22
WHERE TITA_ID IN (81, 82);
COMMIT;

ALTER TABLE MODRED.ENDERECO_CONTATO 
ADD (ENCO_IN_RETIRADA NUMBER DEFAULT 0);

ALTER TABLE MODRED.ENDERECO_CONTATO 
ADD (ENCO_IN_ENTREGA NUMBER DEFAULT 0);

COMMENT ON COLUMN MODRED.ENDERECO_CONTATO.ENCO_IN_RETIRADA IS 'Flag lógico que identifica se o endereço é de retirada para um determinado centro de transplante.';
COMMENT ON COLUMN MODRED.ENDERECO_CONTATO.ENCO_IN_ENTREGA IS 'Flag lógico que identifica se o endereço é de entrega para um determinado centro de transplante.';

ALTER TABLE MODRED.ENDERECO_CONTATO_AUD 
ADD (ENCO_IN_RETIRADA NUMBER DEFAULT 0);

ALTER TABLE MODRED.ENDERECO_CONTATO_AUD 
ADD (ENCO_IN_ENTREGA NUMBER DEFAULT 0);

UPDATE MODRED.ENDERECO_CONTATO SET ENCO_IN_RETIRADA = 0, ENCO_IN_ENTREGA = 0;
UPDATE MODRED.ENDERECO_CONTATO_AUD SET ENCO_IN_RETIRADA = 0, ENCO_IN_ENTREGA = 0;
COMMIT;

INSERT INTO RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES
(115, 'EXCLUIR_ENDERECO_CONTATO_CENTRO_TRANSPLANTE', 'Permite excluir um endereço do centro de transplante');
INSERT INTO RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES
(116, 'EXCLUIR_TELEFONE_CONTATO_CENTRO_TRANSPLANTE', 'Permite excluir um telefone do centro de transplante');
INSERT INTO PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES
(19, 115, 0);
INSERT INTO PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO) VALUES
(19, 116, 0);
COMMIT;

CREATE TABLE MODRED.CENTRO_TRANSPLANTE_USUARIO 
(
  USUA_ID NUMBER NOT NULL 
, CETR_ID NUMBER NOT NULL 
, CONSTRAINT PK_CETU PRIMARY KEY 
  (
    USUA_ID 
  , CETR_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CENTRO_TRANSPLANTE_USUARIO_PK ON CENTRO_TRANSPLANTE_USUARIO (USUA_ID ASC, CETR_ID ASC) 
  )
  ENABLE 
) ;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE_USUARIO
ADD CONSTRAINT FK_CETU_CETR FOREIGN KEY
(
  CETR_ID 
)
REFERENCES CENTRO_TRANSPLANTE
(
  CETR_ID 
)
ENABLE;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE_USUARIO
ADD CONSTRAINT FK_CETU_USU FOREIGN KEY
(
  USUA_ID 
)
REFERENCES USUARIO
(
  USUA_ID 
)
ENABLE;

COMMENT ON TABLE CENTRO_TRANSPLANTE_USUARIO IS 'Tabela de relacionamento entre usuário e centro de transplante para fins de organização de tarefas dos usuários do REDOME.';

COMMENT ON COLUMN CENTRO_TRANSPLANTE_USUARIO.USUA_ID IS 'Identificação do usuário ';

COMMENT ON COLUMN CENTRO_TRANSPLANTE_USUARIO.CETR_ID IS 'Identificação do centro de transplante ';



Insert into MODRED.PERFIL (PERF_ID,PERF_TX_DESCRICAO,PERF_NR_ENTITY_STATUS) values ('23','SUPERVISOR_BUSCA','1');
Insert into MODRED.USUARIO (USUA_ID,USUA_TX_NOME,USUA_TX_USERNAME,USUA_TX_PASSWORD,USUA_IN_ATIVO,USUA_NR_ENTITY_STATUS,TRAN_ID,LABO_ID) values ('54','SUPERVISOR_BUSCA','SUPERVISOR_BUSCA','$2a$11$KMAfznbkZhx9mvESGy3.GewPWbSGQLVTnj5O0m7cIo5NrucDtcXT.','1','1',null,null);
Insert into MODRED.RECURSO (RECU_ID,RECU_TX_SIGLA,RECU_TX_DESCRICAO) values ('114','RELACIONAR_ANALISTA_AO_CENTRO','Permite o relacionamento de usuário com perfil de analista de busca ao centro avaliador');


Insert into "MODRED"."USUARIO_PERFIL" (USUA_ID, PERF_ID) VALUES (54 , 23);
Insert into "MODRED"."PERMISSAO" (RECU_ID, PERF_ID) VALUES (114, 23);

COMMIT;