GRANT SELECT ON "MODRED"."PACIENTE_MISMATCH" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PACIENTE_MISMATCH" TO RMODRED_WRITE;
-- pre cadastro medico endereço
GRANT SELECT ON MODRED.PRE_CADASTRO_MEDICO_ENDERECO TO RMODRED_READ;
GRANT INSERT ON MODRED.PRE_CADASTRO_MEDICO_ENDERECO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PCME_ID TO RMODRED_WRITE;

-- pre cadastro medico
GRANT SELECT ON MODRED.PRE_CADASTRO_MEDICO TO RMODRED_READ;
GRANT INSERT ON MODRED.PRE_CADASTRO_MEDICO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PRCM_ID TO RMODRED_WRITE;


-- pre cadastro medico telefone
GRANT SELECT ON MODRED.PRE_CADASTRO_MEDICO_TELEFONE TO RMODRED_READ;
GRANT INSERT ON MODRED.PRE_CADASTRO_MEDICO_TELEFONE TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PRCM_ID TO RMODRED_WRITE;


-- pre cadastro medico email
GRANT SELECT ON MODRED.PRE_CADASTRO_MEDICO_EMAIL TO RMODRED_READ;
GRANT INSERT ON MODRED.PRE_CADASTRO_MEDICO_EMAIL TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PCEM_ID TO RMODRED_WRITE;


-- tabela associativa: pre cadastro - centro transplante
GRANT SELECT ON MODRED.PRE_CAD_MEDICO_CT_REFERENCIA TO RMODRED_READ;
GRANT INSERT ON MODRED.PRE_CAD_MEDICO_CT_REFERENCIA TO RMODRED_WRITE;



GRANT DELETE ON "MODRED"."PACIENTE_MISMATCH" TO RMODRED_WRITE;

-- CORRIGINDO SINONIMO DE PRE CADASTRO MEDICO TELEFONE
GRANT SELECT ON MODRED.SQ_PCMT_ID TO RMODRED_WRITE;

GRANT INSERT, UPDATE ON "MODRED"."PRE_CADASTRO_MEDICO" TO RMODRED_WRITE;

-- tabela associativa: medico - centro transplante
GRANT SELECT ON MODRED.MEDICO_CT_REFERENCIA TO RMODRED_READ;
GRANT INSERT ON MODRED.MEDICO_CT_REFERENCIA TO RMODRED_WRITE;

-- PERMISSÃO UPDATE PARA AS TABELAS DE PRE CADASTRO MEDICO
GRANT UPDATE ON MODRED.PRE_CADASTRO_MEDICO TO RMODRED_WRITE;
GRANT UPDATE ON MODRED.PRE_CADASTRO_MEDICO_ENDERECO TO RMODRED_WRITE;
GRANT UPDATE ON MODRED.PRE_CADASTRO_MEDICO_TELEFONE TO RMODRED_WRITE;
GRANT UPDATE ON MODRED.PRE_CADASTRO_MEDICO_EMAIL TO RMODRED_WRITE;

-- PERMISSÃO DA GERAÇÃO DE ID DO MEDICO
==== BASE ====
GRANT SELECT ON MODRED.SQ_MEDI_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.ARQUIVO_EVOLUCAO TO RMODRED_READ;
GRANT INSERT, UPDATE  ON MODRED.ARQUIVO_EVOLUCAO TO RMODRED_WRITE;


GRANT SELECT ON MODRED.SQ_AREV_ID TO RMODRED_WRITE;

GRANT DELETE ON MODRED.MEDICO_CT_REFERENCIA TO RMODRED_WRITE;

