-- pre cadastro medico endereço
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PRE_CADASTRO_MEDICO_ENDERECO FOR MODRED.PRE_CADASTRO_MEDICO_ENDERECO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PCME_ID FOR MODRED.SQ_PCME_ID;


-- pre cadastro medico
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PRE_CADASTRO_MEDICO FOR MODRED.PRE_CADASTRO_MEDICO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PRCM_ID FOR MODRED.SQ_PRCM_ID;


-- pre cadastro medico telefone
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PRE_CADASTRO_MEDICO_TELEFONE FOR MODRED.PRE_CADASTRO_MEDICO_TELEFONE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PRCM_ID FOR MODRED.SQ_PRCM_ID;

-- pre cadastro medico email
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PRE_CADASTRO_MEDICO_EMAIL FOR MODRED.PRE_CADASTRO_MEDICO_EMAIL;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PCEM_ID FOR MODRED.SQ_PCEM_ID;

-- tabela associativa: pre cadastro - centro transplante
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PRE_CAD_MEDICO_CT_REFERENCIA FOR MODRED.PRE_CAD_MEDICO_CT_REFERENCIA;


CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PACIENTE_MISMATCH FOR MODRED.PACIENTE_MISMATCH;

-- CORRIGINDO SINONIMO DE PRE CADASTRO MEDICO TELEFONE
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PCMT_ID FOR MODRED.SQ_PCMT_ID;

-- tabela associativa: medico - centro transplante
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.MEDICO_CT_REFERENCIA FOR MODRED.MEDICO_CT_REFERENCIA;

-- SEQUENCE DA TABELA DE MÉDICO
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_MEDI_ID FOR MODRED.SQ_MEDI_ID;

--sinonmo para relacionamento entre evolução e arquivos 
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ARQUIVO_EVOLUCAO FOR MODRED.ARQUIVO_EVOLUCAO;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_AREV_ID FOR MODRED.SQ_AREV_ID;


