GRANT SELECT ON MODRED.PEDIDO_TRANSFERENCIA_CENTRO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PEDIDO_TRANSFERENCIA_CENTRO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PETC_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_CETU_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.CENTRO_TRANSPLANTE_USUARIO TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.CENTRO_TRANSPLANTE_USUARIO TO RMODRED_WRITE;