CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_TRANSFERENCIA_CENTRO FOR MODRED.PEDIDO_TRANSFERENCIA_CENTRO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PETC_ID FOR MODRED.SQ_PETC_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_CETU_ID FOR MODRED.SQ_CETU_ID;