GRANT SELECT ON MODRED.SQ_BASC_ID TO RMODRED_WRITE;
GRANT INSERT, UPDATE ON MODRED.BANCO_SANGUE_CORDAO TO RMODRED_WRITE;

GRANT SELECT ON MODRED.STATUS_AVALIACAO_CAMARA_TEC TO RMODRED_WRITE;
GRANT INSERT, UPDATE ON MODRED.STATUS_AVALIACAO_CAMARA_TEC TO RMODRED_WRITE;

GRANT SELECT ON MODRED.AVALIACAO_CAMARA_TECNICA TO RMODRED_WRITE;
GRANT INSERT, UPDATE ON MODRED.AVALIACAO_CAMARA_TECNICA TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_AVCT_ID TO RMODRED_WRITE;
GRANT INSERT, UPDATE ON MODRED.BANCO_SANGUE_CORDAO TO RMODRED_WRITE;

GRANT SELECT ON MODRED.USUARIO_BANCO_SANGUE_CORDAO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.USUARIO_BANCO_SANGUE_CORDAO TO RMODRED_WRITE;