CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_BASC_ID FOR MODRED.SQ_BASC_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_AVALIACAO_CAMARA_TEC FOR MODRED.STATUS_AVALIACAO_CAMARA_TEC;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.AVALIACAO_CAMARA_TECNICA FOR MODRED.AVALIACAO_CAMARA_TECNICA;

CREATE SYNONYM MODRED_APLICACAO.SQ_AVCT_ID FOR MODRED.SQ_AVCT_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.USUARIO_BANCO_SANGUE_CORDAO FOR MODRED.USUARIO_BANCO_SANGUE_CORDAO;