ALTER TABLE MODRED.CID 
ADD (CID_NR_IDADE_MINIMA NUMBER );

ALTER TABLE CID 
ADD (CID_NR_IDADE_MAXIMA NUMBER );

COMMENT ON COLUMN CID.CID_NR_IDADE_MINIMA IS 'Valor da idade minima para atendimento desta CID';

COMMENT ON COLUMN CID.CID_NR_IDADE_MAXIMA IS 'Valor da idade maxima para atendimento desta CID';

UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C92.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C92.4';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C92.5';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C90.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C91.4';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C92.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C92.4';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C92.5';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C93.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C93.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C93.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C94.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C91.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C83.5';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C92.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D61.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D61.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D61.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D61.3';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D61.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D46.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D46.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D46.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D46.3';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D46.4';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D46.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D80'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D80.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D81.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D81.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D81.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D83'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D83.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D83.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D83.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D83.8';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D83.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D84.8';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D84.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D56'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D56.8';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'D56.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C91.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C90.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C84.4';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C83.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C83.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C85'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C83.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C82.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C85.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C82'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C82.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C82.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C82.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C84'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C84.5';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C82.7';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C85.7';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C81.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C81'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C81.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C81.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C81.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C81.3';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 60	 WHERE CID_TX_CODIGO = 'C81.7';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C90.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C93.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C93.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C93.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C94.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C91.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C83.5';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'C92.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D61.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D61.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D61.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D61.3';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D61.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D46.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D46.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D46.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D46.3';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D46.4';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D46.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D80'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D80.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D81.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D81.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D81.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D83'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D83.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D83.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D83.2';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D83.8';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D83.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D84.8';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D84.9';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D46'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D61'  ;
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D82.0';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D47.1';
UPDATE CID SET CID_NR_IDADE_MINIMA = 0	, CID_NR_IDADE_MAXIMA = 55	 WHERE CID_TX_CODIGO = 'D81.9';
commit;


-- SEQUENCIAL PARA BANCO DE SANGUE
CREATE SEQUENCE MODRED.SQ_BASC_ID INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20 ORDER;


INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES ('86', 'AVALIACAO_CAMARA_TECNICA', '0', '0');
INSERT INTO "MODRED"."PERFIL" (PERF_ID, PERF_TX_DESCRICAO, PERF_NR_ENTITY_STATUS) VALUES ('24', 'AVALIADOR_CAMARA_TECNICA', '1');
INSERT INTO "MODRED"."USUARIO" (USUA_ID, USUA_TX_NOME, USUA_TX_USERNAME, USUA_TX_PASSWORD, USUA_IN_ATIVO, USUA_NR_ENTITY_STATUS, USUA_TX_EMAIL) VALUES ('543', 'AVALIADOR_CAMARA_TECNICA', 'AVALIADOR_CAMARA_TECNICA', '$2a$11$Gr9XfGZu2jZEXhpcpYVo8u.rilUccJa7xX0AXArwhjDGV5Ra4xom6', '1', '1', 'avaliador_camara_tecnica@mail.com');


commit;



CREATE TABLE MODRED.STATUS_AVALIACAO_CAMARA_TEC 
(
  STCT_ID NUMBER NOT NULL 
, STCT_TX_DESCRICAO VARCHAR2(80) NOT NULL 
, CONSTRAINT PK_STCT_ID PRIMARY KEY 
  (
    STCT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_STATUS ON STATUS_AVALIACAO_CAMARA_TEC (STCT_ID ASC) 
  )
  ENABLE 
);

COMMENT ON TABLE  MODRED.STATUS_AVALIACAO_CAMARA_TEC IS 'Tabela com status de avaliações de câmera técnica ';

COMMENT ON COLUMN  MODRED.STATUS_AVALIACAO_CAMARA_TEC.STCT_ID IS 'Chave primária do status da avaliação de camera técnica';

COMMENT ON COLUMN  MODRED.STATUS_AVALIACAO_CAMARA_TEC.STCT_TX_DESCRICAO IS 'Texto dexcritivo do status da avaliação da câmera técnica';




CREATE TABLE MODRED.AVALIACAO_CAMARA_TECNICA 
(
  AVCT_ID NUMBER NOT NULL 
, AVCT_TX_JUSTIFICATIVA VARCHAR2(255 BYTE) 
, PACI_NR_RMR NUMBER NOT NULL 
, STCT_ID NUMBER NOT NULL 
, AVCT_TX_ARQUIVO_RELATORIO VARCHAR2(255 BYTE) 
, CONSTRAINT PK_AVCT PRIMARY KEY 
  (
    AVCT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IN_PK_AVCT ON AVALIACAO_CAMARA_TECNICA (AVCT_ID ASC) 
  )
);

CREATE INDEX IN_FK_AVCT_PACI ON AVALIACAO_CAMARA_TECNICA (PACI_NR_RMR ASC);

CREATE INDEX IN_FK_AVCT_STCT ON AVALIACAO_CAMARA_TECNICA (STCT_ID ASC);

ALTER TABLE AVALIACAO_CAMARA_TECNICA
ADD CONSTRAINT FK_AVCT_PACI FOREIGN KEY
(
  PACI_NR_RMR 
)
REFERENCES PACIENTE
(
  PACI_NR_RMR 
)
ENABLE;

ALTER TABLE AVALIACAO_CAMARA_TECNICA
ADD CONSTRAINT FK_AVCT_STCT FOREIGN KEY
(
  STCT_ID 
)
REFERENCES STATUS_AVALIACAO_CAMARA_TEC
(
  STCT_ID 
)
ENABLE;

COMMENT ON TABLE MODRED.AVALIACAO_CAMARA_TECNICA IS 'Tabela de armazenamento de avaliações de um grupo do REDOME chamado câmera técnica. Este grupo avalia pacientes com diagnósticos com CID''s fora do contemplamento da portaria ou com idade fora do range de atendimento.';

COMMENT ON COLUMN MODRED.AVALIACAO_CAMARA_TECNICA.AVCT_ID IS 'Chave primária de avaliação de câmera técnica';

COMMENT ON COLUMN MODRED.AVALIACAO_CAMARA_TECNICA.AVCT_TX_JUSTIFICATIVA IS 'Texto de justificativa para o resultado da avaliação';

COMMENT ON COLUMN MODRED.AVALIACAO_CAMARA_TECNICA.PACI_NR_RMR IS 'Identificação do paciente que será avaliado';

COMMENT ON COLUMN MODRED.AVALIACAO_CAMARA_TECNICA.STCT_ID IS 'Status da avaliação';

COMMENT ON COLUMN MODRED.AVALIACAO_CAMARA_TECNICA.AVCT_TX_ARQUIVO_RELATORIO IS 'Campo para descrição do caminho do arquivo a ser persistido
';





CREATE SEQUENCE  "MODRED"."SQ_AVCT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

INSERT INTO "MODRED"."STATUS_AVALIACAO_CAMARA_TEC" (STCT_ID, STCT_TX_DESCRICAO) VALUES ('1', 'AGUARDANDO AVALIAÇÃO');
INSERT INTO "MODRED"."STATUS_AVALIACAO_CAMARA_TEC" (STCT_ID, STCT_TX_DESCRICAO) VALUES ('2', 'APROVADO ');
INSERT INTO "MODRED"."STATUS_AVALIACAO_CAMARA_TEC" (STCT_ID, STCT_TX_DESCRICAO) VALUES ('3', 'REPROVADO');
INSERT INTO "MODRED"."STATUS_AVALIACAO_CAMARA_TEC" (STCT_ID, STCT_TX_DESCRICAO) VALUES ('4', 'AGUARDANDO COORD. REDOME');
INSERT INTO "MODRED"."STATUS_AVALIACAO_CAMARA_TEC" (STCT_ID, STCT_TX_DESCRICAO) VALUES ('5', 'AGUARDANDO CAMARA TÉCNICA');

COMMIT;

INSERT INTO "MODRED"."CONFIGURACAO" (CONF_ID, CONF_TX_VALOR) VALUES ('idadeMaximaPacienteTransplante', '65');
==== BASE ====
COMMIT;
-- CRIAÇÃO DA TABELA DE ESPECIALIZAÇÃO PARA USUÁRIO DO BRASILCORD
CREATE TABLE MODRED.USUARIO_BANCO_SANGUE_CORDAO(
    USUA_ID NUMBER NOT NULL,
    BASC_ID NUMBER NOT NULL,
    CONSTRAINT PK_UBSC_ID PRIMARY KEY (BASC_ID) ENABLE
);
COMMENT ON TABLE MODRED.USUARIO_BANCO_SANGUE_CORDAO IS 'Tabela é uma especialização, em cima da tabela de usuário, criada para o BrasilCord.';
COMMENT ON COLUMN MODRED.USUARIO_BANCO_SANGUE_CORDAO.USUA_ID IS 'Além de chave estrangeira, é a chave primária compartilhada com a tabela de usuários.';
COMMENT ON COLUMN MODRED.USUARIO_BANCO_SANGUE_CORDAO.BASC_ID IS 'Chave estrangeira da tabela Banco de Sangue de Cordão.';

ALTER TABLE MODRED.USUARIO_BANCO_SANGUE_CORDAO
ADD CONSTRAINT FK_USUA_UBSC FOREIGN KEY(USUA_ID)
REFERENCES MODRED.USUARIO(USUA_ID)
ENABLE;

ALTER TABLE MODRED.USUARIO_BANCO_SANGUE_CORDAO
ADD CONSTRAINT FK_BASC_UBSC FOREIGN KEY(BASC_ID)
REFERENCES BANCO_SANGUE_CORDAO(BASC_ID)
ENABLE;

INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO)
VALUES (2, 3, 1);
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO)
VALUES (15, 3, 1);
COMMIT;

COMMIT;


INSERT INTO "MODRED"."RECURSO" (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) VALUES ('132', 'AVALIAR_PACIENTE_CAMARA_TECNICA', 'Permite ao avaliador do redome fazer avaliação de câmara técnica');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('132', '24', '0');
INSERT INTO "MODRED"."USUARIO_PERFIL" (USUA_ID, PERF_ID) VALUES ('543', '24');
commit;

ALTER TABLE AVALIACAO_CAMARA_TECNICA po
ADD (AVCT_DT_ATUALIZACAO TIMESTAMP );

COMMENT ON COLUMN AVALIACAO_CAMARA_TECNICA.AVCT_DT_ATUALIZACAO IS 'Campo de data atulização da avaliação
';

INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (133, 'LISTAR_DISPONIBILIDADES', 'Permite ao médico transplantador listar as tarefas para sugerir nova disponibilidade.');
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO)
VALUES (15, 133, 1);
COMMIT;

UPDATE MODRED.PERMISSAO SET PERM_IN_COM_RESTRICAO = 1
WHERE PERF_ID = 15 AND RECU_ID = 106;
COMMIT;


INSERT INTO MODRED.RECURSO (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO) 
VALUES (134, 'CONSULTAR_AVALIAR_RESULTADO_WORKUP', 'Permite ao médico transplantador listar as tarefas para avaliar os resultados de workup.');
INSERT INTO MODRED.PERMISSAO (PERF_ID, RECU_ID, PERM_IN_COM_RESTRICAO)
VALUES (15, 134, 1);
COMMIT;


INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('8', '24', '0');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('4', '24', '0');
INSERT INTO "MODRED"."PERMISSAO" (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO) VALUES ('5', '24', '0');
INSERT INTO "MODRED"."CONFIGURACAO" (CONF_ID, CONF_TX_VALOR) VALUES ('tamanhoArquivoPdfPadraoEmByte', '5242880');
INSERT INTO "MODRED"."CONFIGURACAO" (CONF_ID, CONF_TX_VALOR) VALUES ('extensaoArquivoPdfPadrao', 'application/pdf');
INSERT INTO "MODRED"."CONFIGURACAO" (CONF_ID, CONF_TX_VALOR) VALUES ('quantidadeMaximaArquivosCamaraTecnica', '1');
commit;
