DROP TABLE EVOLUCAO;
DROP TABLE MOTIVO;
DROP TABLE CONDICAO_PACIENTE;
DROP TABLE DIAGNOSTICO;
DROP TABLE ESTAGIO_DOENCA;
DROP TABLE CID;


DROP SYNONYM MODRED_APLICACAO.CID;
DROP SYNONYM MODRED_APLICACAO.ESTAGIO_DOENCA;
DROP SYNONYM MODRED_APLICACAO.MOTIVO;
DROP SYNONYM MODRED_APLICACAO.DIAGNOSTICO;
DROP SYNONYM MODRED_APLICACAO.CONDICAO_PACIENTE;
DROP SYNONYM MODRED_APLICACAO.EVOLUCAO;

DROP SYNONYM MODRED_APLICACAO.SQ_EVOL_ID;
DROP SEQUENCE MODRED.SQ_EVOL_ID;
