CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CID FOR MODRED.CID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ESTAGIO_DOENCA FOR MODRED.ESTAGIO_DOENCA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.MOTIVO FOR MODRED.MOTIVO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DIAGNOSTICO FOR MODRED.DIAGNOSTICO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CONDICAO_PACIENTE FOR MODRED.CONDICAO_PACIENTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.EVOLUCAO FOR MODRED.EVOLUCAO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_EVOL_ID FOR MODRED.SQ_EVOL_ID;
