CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PERFIL_LOG_EVOLUCAO FOR MODRED.PERFIL_LOG_EVOLUCAO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_PACIENTE FOR MODRED.STATUS_PACIENTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_BASC_ID FOR MODRED.SQ_BASC_ID;

CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_HISP_ID" FOR "MODRED"."SQ_HISP_ID";

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.AVALIACAO_NOVA_BUSCA FOR MODRED.AVALIACAO_NOVA_BUSCA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_AVNB_ID FOR MODRED.SQ_AVNB_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.HISTORICO_STATUS_PACIENTE FOR MODRED.HISTORICO_STATUS_PACIENTE;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_HISP_ID FOR MODRED.SQ_HISP_ID;