CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SISTEMA FOR MODRED.SISTEMA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_BUSCA_CHECKLIST FOR MODRED.TIPO_BUSCA_CHECKLIST;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_BUCH_ID FOR MODRED.SQ_BUCH_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SOLICITACAO_REDOMEWEB FOR MODRED.SOLICITACAO_REDOMEWEB;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_SORE_ID FOR MODRED.SQ_SORE_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.BUSCA_CHECKLIST FOR MODRED.BUSCA_CHECKLIST;



CREATE OR REPLACE SYNONYM MODRED_JOB.TIPO_BUSCA_CHECKLIST FOR MODRED.TIPO_BUSCA_CHECKLIST;
CREATE OR REPLACE SYNONYM MODRED_JOB.SQ_BUCH_ID FOR MODRED.SQ_BUCH_ID;
CREATE OR REPLACE SYNONYM MODRED_JOB.BUSCA_CHECKLIST FOR MODRED.BUSCA_CHECKLIST;


CREATE OR REPLACE SYNONYM MODRED_JOB.PEDIDO_EXAME FOR MODRED.PEDIDO_EXAME;



CREATE OR REPLACE SYNONYM MODRED_APLICACAO.BUSCA_CHECKLIST FOR MODRED.BUSCA_CHECKLIST;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ESTABELECIMENTO_IN_REDOME FOR MODRED.ESTABELECIMENTO_IN_REDOME;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ESIR_ID FOR MODRED.SQ_ESIR_ID;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_LABO_ID FOR MODRED.SQ_LABO_ID;
