GRANT SELECT ON MODRED.ARQUIVO_RELAT_INTERNACIONAL TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.ARQUIVO_RELAT_INTERNACIONAL TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."SQ_ARRI_ID" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."SQ_TRAN_ID" TO RMODRED_WRITE;

GRANT INSERT, UPDATE ON "MODRED"."COURIER" TO RMODRED_WRITE;