CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."ARQUIVO_RELAT_INTERNACIONAL" FOR "MODRED"."ARQUIVO_RELAT_INTERNACIONAL";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_ARRI_ID" FOR "MODRED"."SQ_ARRI_ID";
CREATE OR REPLACE SYNONYM "MODRED_APLICACAO"."SQ_TRAN_ID" FOR "MODRED"."SQ_TRAN_ID";