GRANT SELECT ON MODRED.MATCH_DTO TO RMODRED_READ;

GRANT SELECT ON MODRED.VALOR_GENOTIPO_PRELIMINAR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.VALOR_GENOTIPO_PRELIMINAR TO RMODRED_WRITE;

GRANT SELECT ON MODRED.VALOR_GENOTIPO_BUSCA_PRELIMINA TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.VALOR_GENOTIPO_BUSCA_PRELIMINA TO RMODRED_WRITE;

GRANT SELECT ON MODRED.VALOR_GENOTIPO_EXPAND_PRELIMIN TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.VALOR_GENOTIPO_EXPAND_PRELIMIN TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_VABP_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_VAEP_ID TO RMODRED_WRITE;

GRANT SELECT ON MODRED.MATCH_PRELIMINAR_DTO TO RMODRED_READ;

GRANT SELECT ON MODRED.vw_match_preliminar TO RMODRED_READ;
GRANT SELECT ON MODRED.vw_match_preliminar_qualif TO RMODRED_READ;
GRANT SELECT ON MODRED.MUNICIPIO TO RMODRED_READ;

GRANT EXECUTE ON MODRED.PROC_MATCH_PACIENTE TO RMODRED_WRITE;
GRANT EXECUTE ON MODRED.PROC_MATCH_PRELIMINAR TO RMODRED_WRITE;


GRANT SELECT ON MODRED.TIPO_PERMISSIVIDADE TO RMODRED_READ;
GRANT SELECT ON MODRED.GRUPO_PERMISSIVIDADE TO RMODRED_READ;
GRANT SELECT ON MODRED.DPB1_GRUPO_PERMISSIVIDADE TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.DPB1_GRUPO_PERMISSIVIDADE TO RMODRED_WRITE;
GRANT SELECT ON MODRED.DPB1_GRUPO_PERMIS_PACIE_DOADOR TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.DPB1_GRUPO_PERMIS_PACIE_DOADOR TO RMODRED_WRITE;

GRANT SELECT ON MODRED.SQ_DPGP_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_DGPD_ID TO RMODRED_WRITE;

