GRANT SELECT ON "MODRED"."REGISTRO_TIPO_OCORRENCIA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."REGISTRO_TIPO_OCORRENCIA" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_RETO_ID" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."REGISTRO_CONTATO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."REGISTRO_CONTATO" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SQ_REGO_ID" TO RMODRED_READ;

