CREATE OR REPLACE SYNONYM MODRED_APLICACAO.REGISTRO_TIPO_OCORRENCIA FOR MODRED.REGISTRO_TIPO_OCORRENCIA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.REGISTRO_CONTATO FOR MODRED.REGISTRO_CONTATO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_RETO_ID FOR MODRED.SQ_RETO_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_REGO_ID FOR MODRED.SQ_REGO_ID;

DROP SYNONYM "MODRED_APLICACAO"."RESPOSTA_TENTATIVA_CONTATO";
DROP SYNONYM "MODRED_APLICACAO"."SQ_RETC_ID";