GRANT SELECT ON "MODRED"."ANALISE_MEDICA" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."ANALISE_MEDICA" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."EVOLUCAO_DOADOR" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."EVOLUCAO_DOADOR" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."SQ_ANME_ID" TO RMODRED_READ;
GRANT SELECT ON "MODRED"."SQ_EVDO_ID" TO RMODRED_READ;


GRANT SELECT ON "MODRED"."SQ_PECS_ID" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."PEDIDO_CONTATO_SMS" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."PEDIDO_CONTATO_SMS" TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."SQ_SMEN_ID" TO RMODRED_WRITE;
GRANT SELECT ON "MODRED"."SMS_ENVIADO" TO RMODRED_READ;
GRANT INSERT, UPDATE ON "MODRED"."SMS_ENVIADO" TO RMODRED_WRITE;

GRANT SELECT ON MODRED.DOADOR_NAO_CONTACTADO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.DOADOR_NAO_CONTACTADO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_DONC_ID TO RMODRED_WRITE;

GRANT SELECT ON "MODRED"."USUARIO_PERFIL" TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON "MODRED"."USUARIO_PERFIL" TO RMODRED_WRITE;
