CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ANALISE_MEDICA FOR MODRED.ANALISE_MEDICA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.EVOLUCAO_DOADOR FOR MODRED.EVOLUCAO_DOADOR;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_ANME_ID FOR MODRED.SQ_ANME_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_EVDO_ID FOR MODRED.SQ_EVDO_ID;



CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PECS_ID FOR MODRED.SQ_PECS_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PEDIDO_CONTATO_SMS FOR MODRED.PEDIDO_CONTATO_SMS;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_SMEN_ID FOR MODRED.SQ_PECS_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SMS_ENVIADO FOR MODRED.SMS_ENVIADO;


CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DOADOR_NAO_CONTACTADO FOR MODRED.DOADOR_NAO_CONTACTADO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_DONC_ID FOR MODRED.SQ_DONC_ID;