ALTER TABLE MODRED.PACIENTE 
ADD (PACI_NR_WMDA NUMBER );

COMMENT ON COLUMN PACIENTE.PACI_NR_WMDA IS 'Id do wmda quando o paciente é liberado';


INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES ('101', 'ENVIAR_DADOS_WMDA_FOLLOWUP', '1', '0');




CREATE TABLE MODRED.PEDIDO_ENVIO_EMDIS 
(
  PEEE_ID NUMBER NOT NULL 
, PEEE_DT_CRIACAO TIMESTAMP(6) NOT NULL 
, PEEE_DT_ENVIO_EMDIS TIMESTAMP(6) 
, PEEE_TX_NM_ARQUIVO_ENVIO VARCHAR2(250 BYTE) 
, PEEE_DT_RETORNO_EMDIS TIMESTAMP(6) 
, PEEE_TX_NM_ARQUIVO_RETORNO VARCHAR2(20 BYTE) 
, SOLI_ID NUMBER 
, CONSTRAINT PK_PEED PRIMARY KEY 
  (
    PEEE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_PEED ON PEDIDO_ENVIO_EMDIS (PEEE_ID ASC)
  )
);

CREATE INDEX IN_FK_PEED_SOLI ON PEDIDO_ENVIO_EMDIS (SOLI_ID ASC);

ALTER TABLE PEDIDO_ENVIO_EMDIS
ADD CONSTRAINT FK_PEED_SOLI FOREIGN KEY
(
  SOLI_ID 
)
REFERENCES SOLICITACAO
(
  SOLI_ID 
)
ENABLE;

COMMENT ON TABLE PEDIDO_ENVIO_EMDIS IS 'Tabela de controle depdidos realizados ao emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_ID IS 'Identificação do pedido de envio para emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_DT_CRIACAO IS 'Data da criação do pedido emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_DT_ENVIO_EMDIS IS 'Data em que o pedido foi efetivamente enviado para o emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_TX_NM_ARQUIVO_ENVIO IS 'Nome do arquivo de envio do emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_DT_RETORNO_EMDIS IS 'Data de retorno emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_TX_NM_ARQUIVO_RETORNO IS 'Nome do arquivo de retorno do emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.SOLI_ID IS 'id da solicitação de pedido emdis';


CREATE SEQUENCE MODRED.SQ_PEEE_ID INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

INSERT INTO TIPO_SOLICITACAO (TISO_ID, TISO_TX_DESCRICAO) VALUES (7, 'ENVIO PACIENTE EMDIS');
commit;

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES ('102', 'ENVIAR_PACIENTE_PARA_EMDIS_FOLLOWUP', '1', '0');
commit;


insert  into recurso (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO)values(215,'CRIAR_PEDIDO_ENVIO_PACIENTE_EMDIS', 'Cria um novo pedido de envio de paciente para o emdis');
commit;


INSERT INTO PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)VALUES(215,25,0);
INSERT INTO PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)VALUES(215,23,0);
INSERT INTO PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)VALUES(215,5,0);
COMMIT;



