--###############################################################################################################

ALTER TABLE PEDIDO_COLETA ADD (PECL_IN_COLETA_INTERNACIONAL NUMBER(1) DEFAULT 0 );

COMMENT ON COLUMN PEDIDO_COLETA.PECL_IN_COLETA_INTERNACIONAL IS '0- Para coleta de amostra nacional  1-  Para coleta de amostra internacional.';


ALTER TABLE MODRED.PACIENTE 
ADD (PACI_NR_WMDA NUMBER );

COMMENT ON COLUMN PACIENTE.PACI_NR_WMDA IS 'Id do wmda quando o paciente é liberado';


INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES ('101', 'ENVIAR_DADOS_WMDA_FOLLOWUP', '1', '0');




CREATE TABLE MODRED.PEDIDO_ENVIO_EMDIS 
(
  PEEE_ID NUMBER NOT NULL 
, PEEE_DT_CRIACAO TIMESTAMP(6) NOT NULL 
, PEEE_DT_ENVIO_EMDIS TIMESTAMP(6) 
, PEEE_TX_NM_ARQUIVO_ENVIO VARCHAR2(250 BYTE) 
, PEEE_DT_RETORNO_EMDIS TIMESTAMP(6) 
, PEEE_TX_NM_ARQUIVO_RETORNO VARCHAR2(20 BYTE) 
, SOLI_ID NUMBER 
, CONSTRAINT PK_PEED PRIMARY KEY 
  (
    PEEE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_PEED ON PEDIDO_ENVIO_EMDIS (PEEE_ID ASC)
  )
);

CREATE INDEX IN_FK_PEED_SOLI ON PEDIDO_ENVIO_EMDIS (SOLI_ID ASC);

ALTER TABLE PEDIDO_ENVIO_EMDIS
ADD CONSTRAINT FK_PEED_SOLI FOREIGN KEY
(
  SOLI_ID 
)
REFERENCES SOLICITACAO
(
  SOLI_ID 
)
ENABLE;

COMMENT ON TABLE PEDIDO_ENVIO_EMDIS IS 'Tabela de controle depdidos realizados ao emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_ID IS 'Identifica��o do pedido de envio para emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_DT_CRIACAO IS 'Data da cria��o do pedido emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_DT_ENVIO_EMDIS IS 'Data em que o pedido foi efetivamente enviado para o emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_TX_NM_ARQUIVO_ENVIO IS 'Nome do arquivo de envio do emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_DT_RETORNO_EMDIS IS 'Data de retorno emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.PEEE_TX_NM_ARQUIVO_RETORNO IS 'Nome do arquivo de retorno do emdis';

COMMENT ON COLUMN PEDIDO_ENVIO_EMDIS.SOLI_ID IS 'id da solicita��o de pedido emdis';


CREATE SEQUENCE MODRED.SQ_PEEE_ID INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

INSERT INTO TIPO_SOLICITACAO (TISO_ID, TISO_TX_DESCRICAO) VALUES (7, 'ENVIO PACIENTE EMDIS');
commit;

INSERT INTO "MODRED"."TIPO_TAREFA" (TITA_ID, TITA_TX_DESCRICAO, TITA_IN_AUTOMATICA, TARE_IN_SOMENTE_AGRUPADOR) VALUES ('102', 'ENVIAR_PACIENTE_PARA_EMDIS_FOLLOWUP', '1', '0');
commit;


insert  into recurso (RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO)values(215,'CRIAR_PEDIDO_ENVIO_PACIENTE_EMDIS', 'Cria um novo pedido de envio de paciente para o emdis');
commit;


INSERT INTO PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)VALUES(215,25,0);
INSERT INTO PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)VALUES(215,23,0);
INSERT INTO PERMISSAO (RECU_ID, PERF_ID, PERM_IN_COM_RESTRICAO)VALUES(215,5,0);
COMMIT;

INSERT INTO "MODRED"."TIPO_EXAME" (TIEX_ID,TIEX_TX_DESCRICAO) VALUES (6,'Teste Confirmat�rio Somente Swab');  
commit;

INSERT INTO "MODRED"."TIPO_EXAME_LOCUS" (LOCU_ID,TIEX_ID) VALUES ('A','6');  
INSERT INTO "MODRED"."TIPO_EXAME_LOCUS" (LOCU_ID,TIEX_ID) VALUES ('B','6');  
INSERT INTO "MODRED"."TIPO_EXAME_LOCUS" (LOCU_ID,TIEX_ID) VALUES ('C','6');  
INSERT INTO "MODRED"."TIPO_EXAME_LOCUS" (LOCU_ID,TIEX_ID) VALUES ('DQB1','6');  
INSERT INTO "MODRED"."TIPO_EXAME_LOCUS" (LOCU_ID,TIEX_ID) VALUES ('DRB1','6');  
commit;

INSERT INTO USUARIO_PERFIL(perf_id,usua_id) values (5,2321);
commit;

INSERT INTO "MODRED"."TIPO_BUSCA_CHECKLIST" VALUES (10, 'Nova evolu��o cl�nica', 30);
commit;


ALTER TABLE ITEM_INVOICE 

ADD (ITIN_NR_PAGAMENTO NUMBER );

insert into recurso(RECU_ID, RECU_TX_SIGLA, RECU_TX_DESCRICAO)VALUES(218, 'CONCILIAR_PEDIDO_PACIENTE_INVOICE', 'Permite realizar a conciliação de dados de invoice com os pedidos de exame e de amostra');
commit;
insert into permissao(recu_id, perf_id, perm_in_com_restricao) values(218,29,0);
commit;

--##########################################################################################

ALTER TABLE MODRED.CID ADD (CID_TX_SIGLA_CRIR VARCHAR2(10) );
COMMENT ON COLUMN MODRED.CID.CID_TX_SIGLA_CRIR IS 'Sigla de identificação da CID no EMDIS.';

--##########################################################################################

--##########################################################################################

UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'ALL' WHERE CID_TX_CODIGO = 'D76.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'ALL' WHERE CID_TX_CODIGO = 'C91.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'ALL' WHERE CID_TX_CODIGO = 'C91.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'ALL' WHERE CID_TX_CODIGO = 'C91.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'ALL' WHERE CID_TX_CODIGO = 'C91';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C92.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C95.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C95';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C94.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C94.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C93.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C92.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C92.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'D77';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C92.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'AML' WHERE CID_TX_CODIGO = 'C92';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'CML' WHERE CID_TX_CODIGO = 'C92.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'CML' WHERE CID_TX_CODIGO = 'C88';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'CML' WHERE CID_TX_CODIGO = 'D47.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'CML' WHERE CID_TX_CODIGO = 'C95.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HIS' WHERE CID_TX_CODIGO = 'D75';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HIS' WHERE CID_TX_CODIGO = 'C96.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HIS' WHERE CID_TX_CODIGO = 'D76';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HIS' WHERE CID_TX_CODIGO = 'D76.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HL' WHERE CID_TX_CODIGO = 'C81.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HL' WHERE CID_TX_CODIGO = 'C81.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HL' WHERE CID_TX_CODIGO = 'C81.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HL' WHERE CID_TX_CODIGO = 'C81.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HL' WHERE CID_TX_CODIGO = 'C81.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HL' WHERE CID_TX_CODIGO = 'C81.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'HL' WHERE CID_TX_CODIGO = 'C81';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IEA' WHERE CID_TX_CODIGO = 'D56.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IEA' WHERE CID_TX_CODIGO = 'D59.6';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IEA' WHERE CID_TX_CODIGO = 'D60';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IEA' WHERE CID_TX_CODIGO = 'D64.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D89.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D89';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D72';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D72.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D80';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D80.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D80.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D81';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D81.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D81.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D81.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D81.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D82';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D82.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D82.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D82.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D83';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D83.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D83.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D83.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D83.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D83.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D84';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D84.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'D84.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IIS' WHERE CID_TX_CODIGO = 'E70.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IMD' WHERE CID_TX_CODIGO = 'D57';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IMD' WHERE CID_TX_CODIGO = 'E76.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IMD' WHERE CID_TX_CODIGO = 'E75.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IMD' WHERE CID_TX_CODIGO = 'E76.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IMD' WHERE CID_TX_CODIGO = 'E76.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'IPA' WHERE CID_TX_CODIGO = 'D69.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'C90';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'C92.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'C93.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'C93.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'E75.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D56.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'MDS' WHERE CID_TX_CODIGO = 'D46.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'B21.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C85.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C82.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C82.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C82.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C82.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C82.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.6';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C83.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C84';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C84.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C84.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C84.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C85';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C85.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C85.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'NHL' WHERE CID_TX_CODIGO = 'C82';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'D60.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'D75.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'D60.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'D75.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C91.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C91.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C91.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C91.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C91.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C92.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C92.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C93';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C93.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C94';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'E27.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C95.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'M90.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C95.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C96';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'C96.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'D76.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OL' WHERE CID_TX_CODIGO = 'D60.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'C95.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'C88.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'C84.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'B21.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'C74.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'Q81.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'G31.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'D82.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'D81.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'D72.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'D69.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OM' WHERE CID_TX_CODIGO = 'D63';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D69';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D59.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D70';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D71';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'Q82.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D56.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D56.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D56';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'Q06.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'Q78.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D82.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'C94.5';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'E71';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'E71.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'Q81';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D64.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D64.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D64.4';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D64';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'E76.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D57.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OND' WHERE CID_TX_CODIGO = 'D57.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'OTH' WHERE CID_TX_CODIGO = 'E75';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'PCD' WHERE CID_TX_CODIGO = 'C90.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'PCD' WHERE CID_TX_CODIGO = 'C90.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'C94.7';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D57.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D60.1';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D61';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D61.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'E80.0';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D61.2';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D61.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D61.8';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D61.9';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D64.3';
UPDATE MODRED.CID SET CID_TX_SIGLA_CRIR = 'SAA' WHERE CID_TX_CODIGO = 'D61.1';
COMMIT;


--RETIRADA DA COLUNA DE PEDIDO DE EXAME E DE COLETA PARA A INCLUSÃO CORRETA QUE É PARA PAGAMENTO
ALTER TABLE ITEM_INVOICE 
DROP CONSTRAINT FK_ITIN_PECL;

ALTER TABLE ITEM_INVOICE 
DROP CONSTRAINT FK_ITIN_PEEX;

ALTER TABLE ITEM_INVOICE 
DROP COLUMN PEEX_ID;

ALTER TABLE ITEM_INVOICE 
DROP COLUMN PECL_ID;

ALTER TABLE ITEM_INVOICE 
ADD (PAGA_ID NUMBER );

CREATE INDEX IN_FK_ITIN_PAGA ON ITEM_INVOICE (PAGA_ID ASC);

ALTER TABLE ITEM_INVOICE
ADD CONSTRAINT FK_ITIN_PAGA FOREIGN KEY
(
  PAGA_ID 
)
REFERENCES PAGAMENTO
(
  PAGA_ID 
)
ENABLE;

COMMENT ON COLUMN ITEM_INVOICE.PAGA_ID IS 'Identificação do pagamento junto ao redome';
