DROP INDEX MODRED.IN_FK_PACI_MEDI;

ALTER TABLE MODRED.PACIENTE 
DROP CONSTRAINT FK_PACI_MEDI;

ALTER TABLE MODRED.PACIENTE 
DROP COLUMN MEDI_ID_RESPONSAVEL;

DROP SYNONYM MODRED_APLICACAO.MEDICO;
DROP TABLE MODRED.MEDICO;

DROP SYNONYM MODRED_APLICACAO.SQ_MEDI_ID;
DROP SEQUENCE MODRED.SQ_MEDI_ID;

DROP SYNONYM MODRED_APLICACAO.ENDERECO_CONTATO; 