CREATE OR REPLACE SYNONYM MODRED_APLICACAO.MEDICO FOR MODRED.MEDICO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_MEDI_ID FOR MODRED.SQ_MEDI_ID;

-- Adicionando sinonimo para ENDERECO_CONTATO
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ENDERECO_CONTATO FOR MODRED.ENDERECO_CONTATO;