DROP SYNONYM MODRED_APLICACAO.CENTRO_TRANSPLANTE;

DROP INDEX MODRED.IN_FK_PACI_CETR_AVALIADOR;
DROP INDEX MODRED.IN_FK_PACI_CETR_TRANSPLANTADOR;

ALTER TABLE MODRED.PACIENTE 
DROP CONSTRAINT FK_PACI_CETR_AVALIADOR;

ALTER TABLE MODRED.PACIENTE 
DROP CONSTRAINT FK_PACI_CETR_TRANSPLANTADOR;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE 
DROP CONSTRAINT PK_CETR;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE 
RENAME TO CENTRO_AVALIADOR;

COMMENT ON TABLE MODRED.CENTRO_AVALIADOR IS 'Tabela de Centro Avaliador';

ALTER TABLE MODRED.CENTRO_AVALIADOR RENAME COLUMN CETR_ID TO CEAV_ID;

ALTER TABLE MODRED.CENTRO_AVALIADOR RENAME COLUMN CETR_TX_NOME TO CEAV_TX_NOME;

ALTER TABLE MODRED.CENTRO_AVALIADOR RENAME COLUMN CETR_TX_CNPJ TO CEAV_TX_CNPJ;

ALTER TABLE MODRED.CENTRO_AVALIADOR RENAME COLUMN CETR_TX_CNES TO CEAV_TX_CNES;

COMMENT ON COLUMN MODRED.CENTRO_AVALIADOR.CEAV_TX_NOME IS 'Nome do centro avaliador.';

COMMENT ON COLUMN MODRED.CENTRO_AVALIADOR.CEAV_TX_CNPJ IS 'CNPJ do centro avaliador.';

COMMENT ON COLUMN MODRED.CENTRO_AVALIADOR.CEAV_TX_CNES IS 'CNES ao qual está inserido o centro avaliador. (Cadastro Nacional de Estabelecimentos de Saúde).';

ALTER TABLE MODRED.CENTRO_AVALIADOR
ADD CONSTRAINT CEAV_PK PRIMARY KEY 
(
  CEAV_ID 
)
ENABLE;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CENTRO_AVALIADOR FOR MODRED.CENTRO_AVALIADOR;

DROP SYNONYM MODRED_APLICACAO.SQ_CETR_ID;

DROP SEQUENCE MODRED.SQ_CETR_ID;

CREATE SEQUENCE MODRED.SQ_CEAV_ID INCREMENT BY 1 START WITH 35 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_CEAV_ID FOR MODRED.SQ_CEAV_ID;

GRANT SELECT ON MODRED.SQ_CEAV_ID TO RMODRED_WRITE;

ALTER TABLE PACIENTE 
DROP COLUMN CETR_ID_TRANSPLANTADOR;

ALTER TABLE MODRED.PACIENTE 
DROP COLUMN PACI_IN_ACEITA_MISMATCH;

ALTER TABLE MODRED.PACIENTE RENAME COLUMN CETR_ID_AVALIADOR TO CEAV_ID;

COMMENT ON COLUMN MODRED.PACIENTE.CEAV_ID IS 'Referência para a tabela CENTRO_AVALIADOR.';

CREATE INDEX MODRED.IN_FK_PACI_CEAV ON MODRED.PACIENTE (CEAV_ID ASC);

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_CEAV FOREIGN KEY
(
  CEAV_ID
)
REFERENCES CENTRO_AVALIADOR
(
  CEAV_ID 
)
ENABLE;

-- Tipo de Transplante
DROP INDEX MODRED.IN_FK_EVOL_TITR;

ALTER TABLE MODRED.EVOLUCAO
DROP CONSTRAINT FK_EVOL_TITR;

ALTER TABLE MODRED.EVOLUCAO RENAME COLUMN TITR_ID_ANTERIOR TO EVOL_IN_TRANSPLANTADO;

COMMENT ON COLUMN MODRED.EVOLUCAO.EVOL_IN_TRANSPLANTADO IS 'Indica se o paciente já foi transplantado anteriormente';

UPDATE MODRED.EVOLUCAO SET EVOL_IN_TRANSPLANTADO = 0;
COMMIT;

ALTER TABLE MODRED.EVOLUCAO  
MODIFY (EVOL_IN_TRANSPLANTADO NOT NULL);

DROP SYNONYM MODRED_APLICACAO.TIPO_TRANSPLANTE;
DROP TABLE MODRED.TIPO_TRANSPLANTE;

