--Alteração do nome da tabela de CENTRO_AVALIADOR para CENTRO_TRANSPLANTE
DROP SYNONYM MODRED_APLICACAO.CENTRO_AVALIADOR;

DROP INDEX MODRED.IN_FK_PACI_CEAV;

ALTER TABLE MODRED.PACIENTE 
DROP CONSTRAINT FK_PACI_CEAV;

ALTER TABLE MODRED.CENTRO_AVALIADOR 
DROP CONSTRAINT PK_CEAV;

ALTER TABLE MODRED.CENTRO_AVALIADOR 
RENAME TO CENTRO_TRANSPLANTE;

COMMENT ON TABLE MODRED.CENTRO_TRANSPLANTE IS 'Tabela de Centros de Transplantes, Avaliadores e Transplantador.';

ALTER TABLE MODRED.CENTRO_TRANSPLANTE RENAME COLUMN CEAV_ID TO CETR_ID;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE RENAME COLUMN CEAV_TX_NOME TO CETR_TX_NOME;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE RENAME COLUMN CEAV_TX_CNPJ TO CETR_TX_CNPJ;

ALTER TABLE MODRED.CENTRO_TRANSPLANTE RENAME COLUMN CEAV_TX_CNES TO CETR_TX_CNES;

COMMENT ON COLUMN MODRED.CENTRO_TRANSPLANTE.CETR_TX_NOME IS 'Nome do centro de transplante.';

COMMENT ON COLUMN MODRED.CENTRO_TRANSPLANTE.CETR_TX_CNPJ IS 'CNPJ do centro de transplante.';

COMMENT ON COLUMN MODRED.CENTRO_TRANSPLANTE.CETR_TX_CNES IS 'CNES ao qual está inserido o centro de transplante. (Cadastro Nacional de Estabelecimentos de Saúde).';

ALTER TABLE MODRED.CENTRO_TRANSPLANTE
ADD CONSTRAINT PK_CETR PRIMARY KEY 
(
  CETR_ID 
)
ENABLE;

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CENTRO_TRANSPLANTE FOR MODRED.CENTRO_TRANSPLANTE;

DROP SYNONYM MODRED_APLICACAO.SQ_CEAV_ID;

DROP SEQUENCE MODRED.SQ_CEAV_ID;

CREATE SEQUENCE MODRED.SQ_CETR_ID INCREMENT BY 1 START WITH 35 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

ALTER TABLE MODRED.PACIENTE 
ADD (CETR_ID_TRANSPLANTADOR NUMBER );

ALTER TABLE MODRED.PACIENTE 
ADD (PACI_IN_ACEITA_MISMATCH NUMBER(1) );

ALTER TABLE MODRED.PACIENTE RENAME COLUMN CEAV_ID TO CETR_ID_AVALIADOR;

COMMENT ON COLUMN MODRED.PACIENTE.CETR_ID_AVALIADOR IS 'Referência para centro avaliador na tabela CENTRO_TRANSPLANTE.';

COMMENT ON COLUMN MODRED.PACIENTE.CETR_ID_TRANSPLANTADOR IS 'Referência para centro transplantador na tabela CENTRO_TRANSPLANTE.';

COMMENT ON COLUMN MODRED.PACIENTE.PACI_IN_ACEITA_MISMATCH IS 'Define se o médico aceita pelo menos 1 mismatch ex. 5x6';

CREATE INDEX MODRED.IN_FK_PACI_CETR_AVALIADOR ON MODRED.PACIENTE (CETR_ID_AVALIADOR ASC);

CREATE INDEX MODRED.IN_FK_PACI_CETR_TRANSPLANTADOR ON MODRED.PACIENTE (CETR_ID_TRANSPLANTADOR ASC);

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_CETR_AVALIADOR FOREIGN KEY
(
  CETR_ID_AVALIADOR 
)
REFERENCES MODRED.CENTRO_TRANSPLANTE
(
  CETR_ID 
)
ENABLE;

ALTER TABLE MODRED.PACIENTE
ADD CONSTRAINT FK_PACI_CETR_TRANSPLANTADOR FOREIGN KEY
(
  CETR_ID_TRANSPLANTADOR 
)
REFERENCES MODRED.CENTRO_TRANSPLANTE
(
  CETR_ID 
)
ENABLE;

-- Criação da tabela TIPO_TRANSPLANTE
-- Tipo de Transplante
CREATE TABLE MODRED.TIPO_TRANSPLANTE 
(
  TITR_ID NUMBER NOT NULL 
, TITR_TX_DESCRICAO VARCHAR2(30) NOT NULL 
);

COMMENT ON COLUMN MODRED.TIPO_TRANSPLANTE.TITR_ID IS 'Chave primária do tipo de transplante';

COMMENT ON COLUMN MODRED.TIPO_TRANSPLANTE.TITR_TX_DESCRICAO IS 'Descrição do tipo de transplante';

ALTER TABLE MODRED.TIPO_TRANSPLANTE
ADD CONSTRAINT PK_TITR PRIMARY KEY 
(
  TITR_ID 
)
ENABLE;

ALTER TABLE MODRED.EVOLUCAO RENAME COLUMN EVOL_IN_TRANSPLANTADO TO TITR_ID_ANTERIOR;

ALTER TABLE MODRED.EVOLUCAO  
MODIFY (TITR_ID_ANTERIOR NULL);

COMMENT ON COLUMN MODRED.EVOLUCAO.TITR_ID_ANTERIOR IS 'Chave estrangeira para o tipo de transplante indicando qual foi o tipo de transplante anterior';

UPDATE MODRED.EVOLUCAO SET TITR_ID_ANTERIOR = NULL;
COMMIT;

ALTER TABLE MODRED.EVOLUCAO
ADD CONSTRAINT FK_EVOL_TITR FOREIGN KEY
(
  TITR_ID_ANTERIOR 
)
REFERENCES MODRED.TIPO_TRANSPLANTE
(
  TITR_ID 
)
ENABLE;

CREATE INDEX MODRED.IN_FK_EVOL_TITR ON MODRED.EVOLUCAO (TITR_ID_ANTERIOR ASC);

insert into MODRED.TIPO_TRANSPLANTE values (1, 'tipo 1');
insert into MODRED.TIPO_TRANSPLANTE values (2, 'tipo 2');
insert into MODRED.TIPO_TRANSPLANTE values (3, 'tipo 3');
insert into MODRED.TIPO_TRANSPLANTE values (4, 'tipo 4');
COMMIT;

-- A sequence da tabela CENTRO_AVALIADOR foi removida na última sprint.
DROP SYNONYM MODRED_APLICACAO.SQ_CETR_ID;
DROP SEQUENCE MODRED.SQ_CETR_ID;

-- alterando o tipo de transplante para obrigatório
UPDATE MODRED.EVOLUCAO SET TITR_ID_ANTERIOR = 1 WHERE TITR_ID_ANTERIOR IS NULL;

ALTER TABLE MODRED.EVOLUCAO  
MODIFY (TITR_ID_ANTERIOR NOT NULL);
COMMIT;