GRANT SELECT ON MODRED.RASCUNHO TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.RASCUNHO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_RASC_ID TO RMODRED_WRITE;

--------------------------------------------------------
--  Grants Auditoria
--------------------------------------------------------

GRANT SELECT ON MODRED.ENDERECO_CONTATO_AUD TO RMODRED_READ;
GRANT SELECT ON MODRED.CONTATO_TELEFONICO_AUD TO RMODRED_READ;
GRANT SELECT ON MODRED.DIAGNOSTICO_AUD TO RMODRED_READ;
GRANT SELECT ON MODRED.PACIENTE_AUD TO RMODRED_READ;
GRANT SELECT ON MODRED.RESPONSAVEL_AUD TO RMODRED_READ;
GRANT SELECT ON MODRED.AUDITORIA TO RMODRED_READ;

GRANT INSERT ON MODRED.ENDERECO_CONTATO_AUD TO RMODRED_WRITE;
GRANT INSERT ON MODRED.CONTATO_TELEFONICO_AUD TO RMODRED_WRITE;
GRANT INSERT ON MODRED.DIAGNOSTICO_AUD TO RMODRED_WRITE;
GRANT INSERT ON MODRED.PACIENTE_AUD TO RMODRED_WRITE;
GRANT INSERT ON MODRED.RESPONSAVEL_AUD TO RMODRED_WRITE;
GRANT INSERT ON MODRED.AUDITORIA TO RMODRED_WRITE;