CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RASCUNHO FOR MODRED.RASCUNHO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_RASC_ID FOR MODRED.SQ_RASC_ID;

--------------------------------------------------------
--  SYNONYMS Auditoria
--------------------------------------------------------

CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ENDERECO_CONTATO_AUD FOR MODRED.ENDERECO_CONTATO_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.CONTATO_TELEFONICO_AUD FOR MODRED.CONTATO_TELEFONICO_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.DIAGNOSTICO_AUD FOR MODRED.DIAGNOSTICO_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PACIENTE_AUD FOR MODRED.PACIENTE_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESPONSAVEL_AUD FOR MODRED.RESPONSAVEL_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.AUDITORIA FOR MODRED.AUDITORIA;

