GRANT SELECT ON MODRED.RECURSO TO RMODRED_READ;
GRANT SELECT ON MODRED.PERMISSAO TO RMODRED_READ;
GRANT SELECT ON MODRED.AVALIACAO TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.AVALIACAO TO RMODRED_WRITE;
GRANT SELECT ON MODRED.STATUS_PENDENCIA TO RMODRED_READ;
GRANT SELECT ON MODRED.TIPO_PENDENCIA TO RMODRED_READ;
GRANT SELECT ON MODRED.RESPOSTA_PENDENCIA TO RMODRED_READ;
GRANT INSERT ON MODRED.RESPOSTA_PENDENCIA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.ASSOCIA_RESPOSTA_PENDENCIA TO RMODRED_READ;
GRANT INSERT, UPDATE, DELETE ON MODRED.ASSOCIA_RESPOSTA_PENDENCIA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.PENDENCIA TO RMODRED_READ;
GRANT INSERT, UPDATE ON MODRED.PENDENCIA TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_AVAL_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_PEND_ID TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_REPE_ID TO RMODRED_WRITE;

---------------Auditoria-------------------------
GRANT SELECT ON MODRED.AVALIACAO_AUD TO RMODRED_READ;
GRANT INSERT ON MODRED.AVALIACAO_AUD TO RMODRED_WRITE;
GRANT SELECT ON MODRED.PENDENCIA_AUD TO RMODRED_READ;
GRANT INSERT ON MODRED.PENDENCIA_AUD TO RMODRED_WRITE;
GRANT SELECT ON MODRED.SQ_AUDI_ID TO RMODRED_WRITE;