-- Adicionando propriedade Ativo na tabela de USUARIO
ALTER TABLE MODRED.USUARIO 
DROP COLUMN USUA_IN_ATIVO;

-- Criação de tabelas para Controle de Acesso da aplicação
DROP SYNONYM MODRED_APLICACAO.RECURSO;
DROP SYNONYM MODRED_APLICACAO.PERMISSAO;

DROP TABLE MODRED.RECURSO;
DROP TABLE MODRED.PERMISSAO;

DROP SYNONYM MODRED_APLICACAO.AVALIACAO;
DROP SYNONYM MODRED_APLICACAO.SQ_AVAL_ID;
DROP SYNONYM MODRED_APLICACAO.STATUS_PENDENCIA;
DROP SYNONYM MODRED_APLICACAO.PENDENCIA;
DROP SYNONYM MODRED_APLICACAO.SQ_PEND_ID;
DROP SYNONYM MODRED_APLICACAO.TIPO_PENDENCIA;
DROP SYNONYM MODRED_APLICACAO.RESPOSTA_PENDENCIA;
DROP SYNONYM MODRED_APLICACAO.SQ_REPE_ID;
DROP SYNONYM MODRED_APLICACAO.ASSOCIA_RESPOSTA_PENDENCIA;


drop sequence MODRED.SQ_AVAL_ID;
drop sequence MODRED.SQ_PEND_ID;
drop sequence MODRED.SQ_REPE_ID;

drop table MODRED.RESPOSTA_PENDENCIA;
drop table MODRED.ASSOCIA_RESPOSTA_PENDENCIA;
drop table MODRED.PENDENCIA;
drop table MODRED.avaliacao;
drop table MODRED.STATUS_PENDENCIA;
drop table MODRED.TIPO_PENDENCIA;

/* Permissão da identificação para o medico responsável do paciente */
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 8 AND PERF_ID = 1; 
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 8;
COMMIT;

/* remove as permições para o perfil médico avaliador */
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 9 AND PERF_ID = 2;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 10 AND PERF_ID = 2;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 4 AND PERF_ID = 2;
DELETE FROM MODRED.PERMISSAO WHERE RECU_ID = 5 AND PERF_ID = 2;

/* remove o perfil médico avaliador para o usuário 2 */
DELETE FROM MODRED.USUARIO_PERFIL WHERE USUA_ID = 2 AND PERF_ID = 2;

/* remove os recursos  */
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 9;
DELETE FROM MODRED.RECURSO WHERE RECU_ID = 10;

/* remove o perfil Médico avaliador */
DELETE FROM MODRED.PERFIL WHERE PERF_ID = 2;

/* remove o médico avaliador */
DELETE FROM MODRED.MEDICO WHERE MEDI_ID = 2;

/* remove o usuário médico avaliador */
DELETE FROM MODRED.USUARIO WHERE USUA_ID = 2;

COMMIT;

---------------Auditoria-------------------------
drop table MODRED.AVALIACAO_AUD cascade constraints PURGE;
drop table MODRED.PENDENCIA_AUD cascade constraints PURGE;
drop SYNONYM MODRED_APLICACAO.AVALIACAO_AUD cascade constraints PURGE;
drop SYNONYM MODRED_APLICACAO.PENDENCIA_AUD cascade constraints PURGE;
drop sequence "MODRED"."SQ_AUDI_ID";

