CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RECURSO FOR MODRED.RECURSO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PERMISSAO FOR MODRED.PERMISSAO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.AVALIACAO FOR MODRED.AVALIACAO;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_AVAL_ID FOR MODRED.SQ_AVAL_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.STATUS_PENDENCIA FOR MODRED.STATUS_PENDENCIA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PENDENCIA FOR MODRED.PENDENCIA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_PEND_ID FOR MODRED.SQ_PEND_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.TIPO_PENDENCIA FOR MODRED.TIPO_PENDENCIA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.RESPOSTA_PENDENCIA FOR MODRED.RESPOSTA_PENDENCIA;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_REPE_ID FOR MODRED.SQ_REPE_ID;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.ASSOCIA_RESPOSTA_PENDENCIA FOR MODRED.ASSOCIA_RESPOSTA_PENDENCIA;

---------------Auditoria-------------------------
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.AVALIACAO_AUD FOR MODRED.AVALIACAO_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.PENDENCIA_AUD FOR MODRED.PENDENCIA_AUD;
CREATE OR REPLACE SYNONYM MODRED_APLICACAO.SQ_AUDI_ID FOR MODRED.SQ_AUDI_ID;