create tablespace TBL_REDOME
         datafile
         'C:\oraclexe\app\oracle\oradata\XE\tbl_redome.dbf' 
		size 100m autoextend on next 50m maxsize 12000m
         online
         permanent
         extent management local autoallocate
         segment space management auto;
		 

create role RMODRED_READ;
create role RMODRED_WRITE;		
 

-- USER SQL
CREATE USER "MODRED" IDENTIFIED BY "jerico"
DEFAULT TABLESPACE "TBL_REDOME"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "MODRED" QUOTA UNLIMITED ON TBL_REDOME;

-- ROLES
GRANT DBA TO MODRED;

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "MODRED" ;


-- USER SQL
CREATE USER MODRED_APLICACAO IDENTIFIED BY "jerico"  
DEFAULT TABLESPACE "TBL_REDOME"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER MODRED_APLICACAO QUOTA UNLIMITED ON TBL_REDOME;

-- ROLES
GRANT "RMODRED_READ" TO MODRED_APLICACAO ;
GRANT "RMODRED_WRITE" TO MODRED_APLICACAO ;

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "MODRED_APLICACAO" ;

-- ROLLBACK
-- NECESSÁRIO APAGAR O ARQUIVO DA TABLESPACE
--	DROP ROLE RMODRED_WRITE;
--	DROP ROLE RMODRED_READ;
--	DROP USER "MODRED" CASCADE;
--	DROP USER "MODRED_APLICACAO" CASCADE;
--	DROP TABLESPACE TBL_REDOME;

