export const Perfis = {
    MEDICO: 1,
    AVALIADOR :'MEDICO_AVALIADOR',
    MEDICO_REDOME: 13,
    ANALISTA_WORKUP: 9,
    MEDICO_TRANSPLANTADOR: {id: 15, nome: 'MEDICO_TRANSPLANTADOR'},
    CONTROLADOR_LISTA: 16,
    TRANSPORTADORA: 17,
    LABORATORIO:18,
    ANALISTA_BUSCA_REDOME: 'ANALISTA_BUSCA_REDOME',
    CONTATO_SMS: 27,
    ANALISTA_CONTATO: {id: 28, nome: 'ANALISTA_CONTATO'},
    ANALISTA_WORKUP_INTERNACIONAL: 20,
    MEDICO_CENTRO_COLETA: {id: 32, nome: 'MEDICO_CENTRO_COLETA'}
}
