export enum TiposBuscaChecklist {
    NOVA_BUSCA = 1,
    ALTEROU_GENOTIPO = 2,
    RESULTADO_EXAME_SEGUNDA_FASE = 3,
    RESULTADO_EXAME_CT = 4,
    DIALOGO_MEDICO = 6,
    EXAME_SEM_RESULTADO_A_MAIS_DE_30_DIAS = 7,
    DISCREPANCIA_GENOTIPO = 8,
    COBRANCA_LABORATORIO_DIVERGENCIA = 9,
    NOVA_EVOLUCAO_CLINICA = 10
}